### ISSUE TITLE
request: shift + space to move the previous page.

### ISSUE THREAD

**Issue by ChangJoo-Park** [slidevjs/slidev#1]
Hello @antfu ! 

Thank you for making slidev. Can you add a shortcut for the move back like left and up arrow?
slidev already uses space bar to move next slide. So please add `shift + space` to move previous slide.

**Comment by antfu** [comment]
I was doing that with arrow up and down. But yeah, why not, just added.

**Comment by ChangJoo-Park** [comment]
Awesome!
