### ISSUE TITLE
Disable v-click in dev

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1009]
**Is your feature request related to a problem? Please describe.**
In development it's not necessary to click through all items one at a time for v-click or v-clicks, that's usually useful just when presenting. Most of the time it's better to see the final slide.

**Describe the solution you'd like**
`NODE_ENV=development` should disable it. `disableClicks: false` can override it.

**Comment by bru02** [comment]
you could add `?print` to the url as a hacky workaround.

**Comment by antfu** [comment]
I (and quite a few others I believe) use dev mode of presentation, it's definitely not ideal to disable it by default. As stated, you can use `?print` to do so.

**Comment by rightaway** [comment]
@antfu ?print doesnt work with left arrow
