### ISSUE TITLE
pdfDoc.setAuthor

### ISSUE THREAD

**Issue by marshallfWCCI** [slidevjs/slidev#1015]
Currently

```
---
info: 'Some text'
---
```

results in
`pdfDoc.setSubject('Some text')`.

It would be lovely if a frontmatter `author` field were passed to `pdfDoc.setAuthor()`.

**Comment by marshallfWCCI** [comment]
Does this seem to be a reasonable enhancement? It's not high-priority but would be nice.

**Comment by antfu** [comment]
I think adding author and subject indeed makes sense. PR welcome :)

**Comment by marshallfWCCI** [comment]
https://github.com/slidevjs/slidev/pull/1069
https://github.com/slidevjs/docs/pull/132
