### ISSUE TITLE
slidev as a web component

### ISSUE THREAD

**Issue by PhE** [slidevjs/slidev#1028]
Sometimes the presentation is only *a part* of a more general content.
I would like to embed several slidev presentations in an existing vue/nuxt/docus site.

Having a slidev presentation **inside** a page that can play in place along the page content.

Having a zoom / fullscreen toggle.

The slidev component will have a path property pointing to presentation content.
So I could host several distincts presentations in the same site in different pages/sections.

It may be a plugin/layer  to use with vue/nuxt/content.
It may be a *pure web component* allowing the use with any web framework (kind of SPA build in a single web component).

**Comment by antfu** [comment]
Thanks for bringing this up. But sorry I consider this out-of-scope. Slidev would need the dev server integrations to work the best. You may use an iframe with the built SPA to do so I guess.
