### ISSUE TITLE
Images are not displayed in presenter mode

### ISSUE THREAD

**Issue by TechWatching** [slidevjs/slidev#1030]
**Describe the bug**
Images (added in public folder of the project) are not displayed in presenter mode. They work fine when  not in presenter mode.

**To Reproduce**
1. Create a new slidev project
2. Add an image in public folder
3. Add the image in the background (using statement layout for instance  or left-image layout)
4. the image is not displayed in presenter mode

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge Version 114.0.1823.51 (
 - Slidev version: 0.42.4

**Comment by bru02** [comment]
Make sure you prepend the image url with a `/`.

ie.
```md
---
background: /lake.jpg
---

# Welcome to Slidev
```

Also keep in mind image background are only supported on layouts using [`handleBackground`](https://github.com/search?q=repo:slidevjs/themes+handleBackground+language:Vue&type=code&l=Vue).

@antfu Do you think slidev should handle the background property for all layouts automatically? [(at the layout loading level)](https://github.com/slidevjs/slidev/blob/8a7d4e239e307e2a95982d3bfa72377b779843cb/packages/slidev/node/plugins/loaders.ts#L371)

**Comment by TechWatching** [comment]
Oh great thanks, the solution seems so simple now that I know it. I thought it was a bug. Closing the issue
