### ISSUE TITLE
Ability to export to Powerpoint

### ISSUE THREAD

**Issue by trajano** [slidevjs/slidev#1035]
**Is your feature request related to a problem? Please describe.**
We use Teams as our meeting platform which has integration with PowerPoint so we can pass control of the slide deck between people.

**Describe the solution you'd like**
An export to PPTX facility.

**Describe alternatives you've considered**
There is no alternative that works seamlessly with teams and transfer control aside from full screen control.

**Comment by antfu** [comment]
Duplicated https://github.com/slidevjs/slidev/issues/213#issuecomment-853528647
