### ISSUE TITLE
SlideCurrentNo changes during transition

### ISSUE THREAD

**Issue by jgosmann** [slidevjs/slidev#1037]
**Describe the bug**
`<SlideCurrentNo />` can be used to display the current slide number. However, when used together with transitions (e.g.  `transition: slide-left` in the frontmatter of the first slide), both slides that are part of the transition will display the same slide number and it will get updated to the new slide number before the transition. For example, when on slide 1 and advancing do the next slide, the slide number on the first slide will turn into 2 and then we see the transition to slide 2.

More generally, I think that this does not only affect the current page number, but which item is marked as active in `$slidev.nav.tree`. I use that to automatically determine a section number to display. Though, here I could see an argument that his is intended behavior. With `<SlideCurrentNo />` it really seems that the slide number should be tied to the slide the component is used on and not the current slide.

**To Reproduce**
I prepared a pretty minimal reproduction in jgosmann/slidev-slideno-repro. It is pretty much the default template that you get on initial creation of a Slidev presentation. I just replaced all slides with `<SlideCurrentNo />`.

1. Check out the repo.
2. `npm run dev`
3. Flick through the slides and pay attention to the displayed numbers.

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (22F82)
 - Browser: Firefox 114.0.2
 - Slidev version: 0.42.5

**Comment by bru02** [comment]
Could you please elaborate on your use case for `$slidev.nav.tree`?

I think an ideal solution would be to add a property to `$slidev` with the current slide's id, though not sure how to name it since `currentSlideId` already exists.

Plus, an other nice to have feature would be to add a `isActiveSlide` property or similar, to make this [pattern more](https://sli.dev/guide/animations.html#motion:~:text=Or%20control%20the%20element%20life%2Dcycle%20with%20v%2Dif%20to%20have%20fine%2Dgrained%20controls) ergonomic.

**Comment by jgosmann** [comment]
> Could you please elaborate on your use case for $slidev.nav.tree?

Sure, I implemented a layout for a slide that is used between sections in a presentation. It shows the section number and the title of the section.

![019](https://github.com/slidevjs/slidev/assets/850157/fadefb92-c246-44a1-93e6-77ba67ff2980)

While it is possible to set the section number manually, I would like to set it automatically if it hasn't been set explicitly. This would, for example, allow to reorder sections or insert/remove sections without updating all the section numbers.

At the moment I am using essentially the following code to automatically determine and display the section numbers:

```vue
<script setup lang="ts">
import { computed } from 'vue'
const sectionNumber =  computed(() => ($slidev.nav.tree.filter(tocItem => !tocItem.hideInToc).findIndex(tocItem => tocItem.active) + 1).toString())
</script>

<template>
  <div class="slidev-layout section">
    <div class="section-number">{{ sectionNumber }}</div>
    <div class="section-title">
      <slot />
    </div>
  </div>
</template>
```

**Comment by jgosmann** [comment]
I can confirm that this has been fixed for the page number, but I think there is still no solution for the section number that I determine via `$slidev.navtree`, or is there?

**Comment by jgosmann** [comment]
I actually found a solution, though maybe a bit of a hack 🤔 by comparing the `tocItem.path` to the `$page` instead of looking at `active`:
```
const sectionNumber =  computed(() => ($slidev.nav.tree.filter(tocItem => !tocItem.hideInToc).findIndex(tocItem => tocItem.path === $page.value.toString()) + 1).toString())
```

**Comment by c-harding** [comment]
Hi @antfu / @zyyv, I’m just hit this same problem using `$slidev.nav.currentPage`, as well as for accessing the frontmatter and layout. How can I get to the frontmatter of the slide during transition, without it changing mid-transition?

**Comment by c-harding** [comment]
Update: I switched from using `useSlideContext().$slidev.nav.page` to `useSlideContext().$page`, and from `useNav().currentLayout` to `useSlideContext().$frontmatter.layout`, and it seems to be working now
