### ISSUE TITLE
Feature : Add markdown variable for repetitive contents and use components templates

### ISSUE THREAD

**Issue by Erim32** [slidevjs/slidev#1041]
Could you please add a feature to set some variables in markdown slide to be used until change ? 
Could be usefull to set and managed sections or champters headlines without need to insert the varible in every slide headers.
For the moment only global theme config have a global scope.

Usage example :
 ```

COMPONENT : header-chapter
<h1 class="custom-h1">$slidev.vars.chapter</>

```
MARKDOWN :
```

---
var_chapter : concepts : how to ....
---
<header-chapter/>
# slide 4
...
----
----
<header-chapter/>
# Slide N
---

var_chapter : concepts : how to do something else ....
var_another_usage : Custom text
--
----
<header-chapter/>
# Slide N
---



```

**Comment by antfu** [comment]
https://sli.dev/custom/directory-structure.html#components

You can put `.md` file under `/components` folder and import them multiple times.
