### ISSUE TITLE
Presenter: Unable to switch to the next slide. This issue may be caused by caching.

### ISSUE THREAD

**Issue by jinsuichen** [slidevjs/slidev#1044]
**Describe the bug**

When using presenter mode, I utilize the right arrow on my keyboard to navigate to the next page. Initially, the URL reads "http://localhost:3030/presenter/1". Once I press the right arrow, the URL changes to "http://localhost:3030/2". However, the current area still displays page 1, while the next area displays page 3. If I continuously press the right arrow, the URL eventually reads "http://localhost:3030/x", with the current area still showing page 1 and the next area displaying page x+1.

On the other hand, using the button in the lower left corner to switch to the next page works without any issues. Additionally, clearing the browser cache helps resolve the problem.

I vaguely recall encountering an error on the page due to a coding mistake. After making the necessary modifications and restarting vite, the problem with the presenter mode occurred. I am uncertain if the two incidents are related.

**To Reproduce**

This problem occurred randomly and has not recurred since. Sorry :(

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 (22D68)
 - Browser: 114.0.5735.198
 - Slidev version: 0.42.5

**Comment by Camiloruiiz** [comment]
Same issue here, but using incognito seems to solve the problem

**Comment by jinsuichen** [comment]
> Same issue here, but using incognito seems to solve the problem

Yes, this is the same principle as I mentioned about clearing the browser cache

**Comment by jinsuichen** [comment]
A guess, this problem may be caused by the hot start of vite

**Comment by antfu** [comment]
It should be fixed in the latest version
