### ISSUE TITLE
How to disable Integrated Editor? The little audience ruined my ppt and lots of related files...

### ISSUE THREAD

**Issue by 15921483570** [slidevjs/slidev#1048]
I've check all the guides [here](https://sli.dev/guide) and find no switches to cut off this feature...

How to disable it?

ps: I know build may probably solve this problem, but I didn't find a way to set password while hosting build version...

**Comment by 15921483570** [comment]
I found changing this code (/slidev/node_modules/@slidev/client/internals/NavControls.vue, line 121)would work:

```
        <button v-if="__DEV__ && !isPresenter" class="slidev-icon-btn <md:hidden" @click="showEditor = !showEditor">
```

here the logic should be a bug. why an audience instead of a presenter could change all the ppts???

and also, the password could be seen directly so it's dangerous also...

so here I currently change `!isPresenter` to `!isPresenter` or `0` to forbid this smart editor and so the smart students...

**Comment by antfu** [comment]
You can use a password to protect the presenter mode. I won't recommend directly exposing your dev slides to your audience tho, it's better to do with a deployed SPA.

**Comment by 15921483570** [comment]
> You can use a password to protect the presenter mode. I won't recommend directly exposing your dev slides to your audience tho, it's better to do with a deployed SPA.

As I said, SPA seems have no password protection? I didn't find any way.

**Comment by CarsonSlovoka** [comment]
I want to know how to disable the editor. 
It will be great if it is only enabled in the presenter mode.

**Comment by CarsonSlovoka** [comment]
I came up with a solution by directly adding the following code to [styles/index.ts](https://sli.dev/custom/directory-structure.html#style) file. It removes the entire `<nav>` element. 

```ts
const observer = new MutationObserver((mutationsList) => {
  for (const mutation of mutationsList) {
    for (const node of mutation.addedNodes) {
      if (node.classList) {
        if (node.classList.contains("slidev-icon-btn")) {
          
          /* optional: use frontmatter to control
          if (document.title.includes("dev")) {
            observer.disconnect()
            return
          }          
           */
          
          if (!window.location.pathname.startsWith("/presenter")) {
            const navElem = document.querySelector("nav")
            if (navElem) {
              [...document.querySelectorAll(`[class~="slidev-icon-btn"]`)].forEach(e => e.parentElement.remove())
              observer.disconnect()
            }
          }
        }
      }
    }
  }
})
observer.observe(document, {
  childList: true, subtree: true,
})
```

If you also want to hide the drawing tool, you can enable this setting ([frontmatter](https://sli.dev/custom/#frontmatter-configures).`drawings.presenterOnly: true`) so that it only appears in the presenter view.
![image](https://github.com/slidevjs/slidev/assets/17170765/fe91ba9b-a4ce-44cd-bb33-0262aa527e41)

**Comment by 15921483570** [comment]
> I want to know how to disable the editor. It will be great if it is only enabled in the presenter mode.

you can see my comment above: https://github.com/slidevjs/slidev/issues/1048#issuecomment-1626600123

which can only enable the editor in the presenter mode by changing `!isPresenter` to `isPresenter`.
