### ISSUE TITLE
[question][help wanted] there is esno, and why use jiti another node ts runtime ?

### ISSUE THREAD

**Issue by yolio2003** [slidevjs/slidev#105]
https://github.com/antfu/esno esbuild ts node runtime

https://github.com/unjs/jiti Runtime typescript and ESM support for Node.js (CommonJS)

Why do I need to use jiti if I already have esno? I am confused about using these two libraries at the same time.

**Comment by antfu** [comment]
Sorry does it related to this project?

**Comment by yolio2003** [comment]
yes, I'm ask about the tech choice about why use jiti when there is already esno.

**Comment by antfu** [comment]
esno is for developing only, and jiti is used in vite-plugin-windicss to load configure files in the runtime.
