### ISSUE TITLE
Help: Cloudflare Pages HowTo 

### ISSUE THREAD

**Issue by pataquets** [slidevjs/slidev#1055]
I wanted to deploy a slideshow in [Cloudflare Pages](https://pages.cloudflare.com/).
AFAIK, it's a service similar to Vercel.
I can't figure out even where to start.
Thanks.

**Comment by beilunyang** [comment]
It's easy.
1. Authorize the github/gitlab repository to cloudflare pages
2. Set the build options
![1691674735412](https://github.com/slidevjs/slidev/assets/13795713/688ac888-7ffa-4773-b78b-031e76acdb04)
