### ISSUE TITLE
What's written in the Integrated Editor is not persistent but disappears every time toggling the edit button

### ISSUE THREAD

**Issue by shoichiaizawa** [slidevjs/slidev#106]
👇 [UPDATE](https://github.com/slidevjs/slidev/issues/106#issuecomment-840994749): This no longer happens in v0.9.3 👇 

---

Thanks for authoring such a great tool.

I have encountered a phenomenon where what's written in the Integrated Editor disappears every time toggling the edit button (or close it via the top right x button and reopen it with the edit button). It reappears again when transitioning the page back and forth but disappears once toggling the Integrated Editor.

Here is what happened:

![Kapture 2021-05-14 at 12 13 13](https://user-images.githubusercontent.com/1571648/118216135-e046a480-b4ad-11eb-88da-660a9a6fd4dc.gif)

Here are the versions of `node`, `pnpm` and `slidev` that I use:

```bash
❯❯ node -v
v14.17.0

❯❯ pnpm -v
6.3.0

❯❯ npx slidev -v
0.6.11
```

**Comment by shoichiaizawa** [comment]
Realising that the latest version of `slidev` as of 2021-05-14 is [v0.9.3](https://github.com/slidevjs/slidev/releases/tag/v0.9.3) while the version comes with `npm init slidev` is [v0.6.11](https://github.com/slidevjs/slidev/releases/tag/v0.6.11), which is what I used and encountered this phenomenon.

The latest version v0.9.3 no longer has this problem.
It would be great if you could kindly upgrade the version comes with running `npm init slidev` to avoid this confusion for others ;)

I keep this issue awhile; please close this when you get this 🙏

**Comment by antfu** [comment]
It might due to your local cache, the create-slidev package is always up-to-date on npm along with the main package.
