### ISSUE TITLE
Touch gestures hard to use on Tablet

### ISSUE THREAD

**Issue by Jak2k** [slidevjs/slidev#1068]
**Describe the bug**
Touch gestures on a tablet are very hard to trigger.

**To Reproduce**
1. Open a presentation on a tablet.
2. Swipe

**Mobile (please complete the following information):**
 - OS: Android 13 OneUi (Samsung)
 - Browser: Chrome (latest)
 - Slidev version: 0.42.1

**Comment by antfu** [comment]
PR welcome, thanks!
