### ISSUE TITLE
Namespaced Theme installation fails

### ISSUE THREAD

**Issue by JPustkuchen** [slidevjs/slidev#1079]
**Describe the bug**
We've created a custom Slidev Theme (btw. Slidev is sooooo great, thank you so much!!)
https://www.npmjs.com/package/@webksde/slidev-theme-webksde

As you can see, it's prefixed by @webksde namespace at npm. It's a public repo, which is placed at GitLab (not GitHub!)

When using 
```
---
theme: webksde
---
```
and running `npm install ` and `npm run dev` then the question:

> The theme "slidev-theme-webksde" was not found in your project, do you want to install it now?

appears. 

If I enter "**yes**", the following error appears:

> npm ERR! No versions available for slidev-theme-webksde

The error details contain:
```
  shortMessage: 'Command failed with exit code 1: npm i slidev-theme-webksde',
  command: 'npm i slidev-theme-webksde',
  escapedCommand: 'npm i slidev-theme-webksde',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

If I enter "**no**" (using package.json dependency instead), the application aborts and doesn't start.

Adding the dependency to the package.json doen't change anything:
```
  "dependencies": {
    "@slidev/cli": "^0.42.5",
    "@slidev/theme-seriph": "^0.21.3",
    "@webksde/slidev-theme-webksde": "latest"
  }
```
I guess the reason is either, that it's not hosted on GitHub or the @webksde prefix?
Or am I missing something?

Everything else and any other theme works!

**To Reproduce**
See above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Slidev version: 0.42.7

**Comment by JPustkuchen** [comment]
Du I perhaps have to enter the theme name differently, if it is prefixed? Or is there any way to alias the theme?

**Comment by KermanX** [comment]
Hello
I think you can use the full package name as the theme name.

document: https://sli.dev/themes/use.html

![image](https://github.com/slidevjs/slidev/assets/63178754/ef22d590-ce4e-4249-8279-07889f914429)

**Comment by JPustkuchen** [comment]
@KermanX for the records: For my example it would be:

`theme: "@webksde/slidev-theme-webksde"`
right?

**Comment by KermanX** [comment]
I think it is.
