### ISSUE TITLE
No matching export in @unhead/vue

### ISSUE THREAD

**Issue by EverNorif** [slidevjs/slidev#1080]
**Describe the bug**
when using command `slidev slide.md`, there are some errors. One of the errors is : 

```sh
[ERROR] No matching export in "../../../../opt/homebrew/lib/node_modules/@slidev/cli/node_modules/@unhead/vue/dist/index.mjs" for import "useBodyAttrs"
```
There are also some similar errors, like "useHtmlAttrs", "useServerBodyAttrs", "useServerHtmlAttrs", "useServerTagBase", "useServerTagLink", "useServerTagMeta", "useServerTagMetaFlat", "useServerTagNoscript", "useServerTagScript", "useServerTagStyle", "useServerTagTitle", "useServerTitleTemplate", "useTagBase", "useTagLink", "useTagMeta", "useTagMetaFlat", "useTagNoscript", "useTagScript", "useTagStyle", "useTagTitle", "useTitleTemplate".

**To Reproduce**
1. install slidev globally
2. run `slidev slide.md`, and slide.md is an empty file
3. see the errors.

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 
 - Browser: Chrome
 - Slidev version: 0.42.7

**Comment by EverNorif** [comment]
It's probably because @unhead/vue has updated today, and there are breaking changes in this version. 
also see Breaking Changes in [Release v1.3.0 · unjs/unhead](https://github.com/unjs/unhead/releases/tag/v1.3.0).

**Comment by JPustkuchen** [comment]
Works again, thanks!
