### ISSUE TITLE
部署多个ppt时，无法访问

### ISSUE THREAD

**Issue by guofei9987** [slidevjs/slidev#1082]
## 问题描述

使用 `slidev  build` 命令，对两个项目生成2个ppt，目录结构如下：

```
├── slide1
│   ├── 404.html
│   ├── _redirects
│   ├── assets
│   └── index.html
└── slide2
    ├── 404.html
    ├── _redirects
    ├── assets
    └── index.html
```

发布后 `http://localhost:3000/slide1` 和 `http://localhost:3000/slide2` 都可以正常访问。  

但是 `http://localhost:3000/slide1/1` **无法访问**

**Comment by antfu** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

I would honestly recommend a more configurable hosting platform than GitHub Pages for this.
