### ISSUE TITLE
Toc from another file

### ISSUE THREAD

**Issue by naquiroz** [slidevjs/slidev#1089]
**Is your feature request related to a problem? Please describe.**
I use sli.dev for my lectures, and I constantly want to show what I talked about the last lecture. For that I use the TOC from the previous lecture. Since they are different files, what I am doing right now is copying the element from the rendered site, using chrome dev tools.

**Describe the solution you'd like**

I would like that I could do:

```vue
<Toc src="./past_lecture.md" />
```

That way, it would render the TOC from anorther markdown file.

**Describe alternatives you've considered**
I haven't really thought of any other alternative that copying the element from the DOM.

**Comment by KermanX** [comment]
I think this is hard to implement because this requires loading and injecting TOC data in a (new) Vite plugin. And since this isn't a common use case, close this for now. Thanks for your suggestion.
