### ISSUE TITLE
hot reloading not working 

### ISSUE THREAD

**Issue by vim-daniel** [slidevjs/slidev#1092]
**Describe the bug**
When running slidev with latest versions - hot reloading is not working..

in an older version (0.35~) it seems to work

**To Reproduce**
1. Go to https://stackblitz.com/edit/slidev-fqfsw2?file=slides.md
2. Change slides.md
4. page is not updated with the content

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Slidev version: latest (0.42.9)

**Comment by lili21** [comment]
run into the same issue.

**Comment by Wxh16144** [comment]
Same question that's been bothering me.

**Comment by antfu** [comment]
I can confirm it's the case on Stackblitz, but it's working fine on my local machine. Haven't had time to dig deeper, before I work on it, any help on investigating or providing more info are appreciated

**Comment by lili21** [comment]
@antfu I am running on a local machine, it doesn't work. 

macOS Ventura
Chorme
@slidev/cli@0.42.9

**Comment by Wxh16144** [comment]
Provide some information about me to easily reproduce the problem. I don't have time to help with the investigation either

<details><summary>Details</summary>
<p>

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.2.0 - ~/.nvm/versions/node/v16.20.0/bin/pnpm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    Cargo: 1.70.0 - ~/.cargo/bin/cargo
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    Homebrew: 4.1.5 - /opt/homebrew/bin/brew
    pip3: 22.3.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.40.0 - /opt/homebrew/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 7.88.1 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.13 - /usr/local/bin/docker
  IDEs:
    VSCode: 1.81.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.18 - /usr/local/go/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    PHP: 8.2.4 - /opt/homebrew/bin/php
    Python3: 3.11.2 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.70.0 - /Users/wuxh/.cargo/bin/rustc
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 115.0.5790.98
    Safari: 16.5


-----

➜ pnpm list
Legend: production dependency, optional only, dev only

/Users/wuxh/Code/SelfProject/my-talks/components-dev (PRIVATE)

dependencies:
@slidev/cli 0.42.9
@slidev/theme-default 0.21.2
@slidev/theme-seriph 0.21.3

devDependencies:
@iconify-json/logos 1.1.34

</p>
</details>

**Comment by hrmJ** [comment]
I actually do see vite outputting "hot reloaded" in the console, but no changes are actually reflected in the dom

**Comment by antfu** [comment]
Identified that this issue is introduced in the transcendent dependency `@vitejs/plugin-vue@4.3.2`, specifically these two commits:

- https://github.com/vitejs/vite-plugin-vue/pull/232
- https://github.com/vitejs/vite-plugin-vue/pull/236

It's because the Vue plugin now assumes HMR should work on an existing file, while Slidev provides them as virtual modules.

https://github.com/slidevjs/slidev/blob/7f01bade8f931a3e0da37ab46b63ff10c791214f/packages/slidev/node/plugins/loaders.ts#L189-L198

/cc @sxzz Any idea this could be fixed either on Slidev or plugin-vue?

----

A temporary workaround is to pin the version of `@vitejs/plugin-vue` back to `4.3.1` by adding the following lines to your `package.json`

```json
  "resolutions": {
    "@vitejs/plugin-vue": "4.3.1"
  }
```

**Comment by sxzz** [comment]
I'm investigating this
