### ISSUE TITLE
Customize presenter mode

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1095]
Allow us to create a vue template under layouts/_presenter.vue by default that has 3 <slots> for the current, next and notes panels so we can lay them out in any way. And let us provide <style> in that vue template where we can write css to style the generated html only in the notes panel. This will make any customization possible for presenter mode.

https://github.com/slidevjs/slidev/issues/996

**Comment by KermanX** [comment]
Now there are two solutions to achieve this:

- Use [Configure Routers](https://sli.dev/custom/config-routes) to override the route `/presenter:no` to your Vue component.
- Use CSS to override the styles.

**Comment by rightaway** [comment]
@KermanX Where is the default presenter mode component? There's no documentation about how to override the styles or what slots are available.

**Comment by KermanX** [comment]
> @KermanX Where is the default presenter mode component? There's no documentation about how to override the styles or what slots are available.

The default one is at `packages/client/pages/presenter.vue`

About the styles, you can inspect the DOM tree to find where to add/override styles.
