### ISSUE TITLE
Use without web server

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1098]
Build command should have an option so it doesn't need a web server. Pointing browser to index.html on the same device should be enough. You can run it locally like from a mobile device with no web server.

**Comment by antfu** [comment]
Thanks for bringing this up. But sorry, I have no interest in supporting that as it's a requirement inherited from Vite.

**Comment by rightaway** [comment]
@antfu Any workaround? If network is down there is no way to present. And no way to present from a tablet because it can't host local web server.
