### ISSUE TITLE
Export with component

### ISSUE THREAD

**Issue by rightaway** [slidevjs/slidev#1099]
Layout is like this

```
project
  dir
    slide.html
  components
    dir
      CompA.vue
```

slide.html uses `<CompA>text</CompA>` and works in dev mode but in export shows just "text" and doesn't use the component.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by rightaway** [comment]
@antfu Please try with any component. Export doesn't use the component.
