### ISSUE TITLE
Markdown Table with by-row v-click action

### ISSUE THREAD

**Issue by HiroshiMatsumoto** [slidevjs/slidev#1102]
It would be great if there was a functionality for the markdown-table to show one row at a time by v-click.
It can be feasible by writing `<table>` code and placing `v-click` property in `<tr>` tag; I have tested.

Using markdown table construction, `v-click`-ing element by element in table can be done by tagging each element with `<div v-click>` tag.
But I could not find any way to do by-row v-click action.

Just an idea to achieve this, if `<v-click />` tag is inserted in the first column of the header row, every row would show by v-click action.

```
| <v-click />      | emacs | vim            |
| ---------------- | ----- | -------------- |
| startup          | slow  | fast           |
| difficult to use | yes   | yes            |
| keybinds used on | Mac   | Linux-Commands |
| GUI              | yes   | no             |
```

or taging the whole table with `<v-clicks></v-clicks>`

```
<v-clicks>

|                  | emacs | vim            |
| ---------------- | ----- | -------------- |
| startup          | slow  | fast           |
| difficult to use | yes   | yes            |
| keybinds used on | Mac   | Linux-Commands |
| GUI              | yes   | no             |

</v-clicks>
```

Thank you

**Comment by antfu** [comment]
I think it would be possible to do, similar to what we have done with `ul` list: 

https://github.com/slidevjs/slidev/blob/52f967f3525285b28ee598aa03b243356f69cd7e/packages/client/builtin/VClicks.ts#L65-L70

PR welcome if you want to give it a try

**Comment by HiroshiMatsumoto** [comment]
ok, assign me.
I would give it a shot :grinning:

**Comment by adamdehaven** [comment]
Just a note; we'd want to skip over `th`, `tbody`, etc. and likely only apply the `v-click` to each `tr` element

**Comment by bonyuta0204** [comment]
@antfu @HiroshiMatsumoto
I apologize if @HiroshiMatsumoto is already addressing this issue, but I have implemented the feature and submitted a pull request (#1202).

Could you please review the pull request when you have a chance? Thank you.

**Comment by piranna** [comment]
This is fixed in https://github.com/slidevjs/slidev/pull/1202, we can close this.
