### ISSUE TITLE
Custom templates from themes stopped working

### ISSUE THREAD

**Issue by estruyf** [slidevjs/slidev#1110]
**Describe the bug**

I just started a new project and added my `the-unnamed` theme. When I wanted to use the `about-me` layout, it returned an error:

```
Failed to load url /node_modules/@slidev/client/layoutHelper (resolved id: /Users/<project-path>/node_modules/@slidev/client/layoutHelper) in /Users/<project-path>/node_modules/slidev-theme-the-unnamed/layouts/about-me.vue. Does the file exist?
```

I can confirm it exists:

![Xnapper-2023-09-08-14 52 45](https://github.com/slidevjs/slidev/assets/2900833/56268b3f-49de-4091-a18b-e72529d58af4)

**To Reproduce**
1. Create a new project
2. Use the `the-unnamed` theme
3. Add the `about-me` layout:

```markdown
---
layout: about-me
---
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: irrelevant
 - Slidev version: 0.43.1

**Comment by estruyf** [comment]
BTW - opened an older project which used `0.39.0` of Slidev and it returned other errors, but also coming from `@slidev/client`.

```
Failed to load url /node_modules/@slidev/client/constants
```

**Comment by antfu** [comment]
You will need to change the path to `@slidev/client/layoutHelper.ts`. This is because Vite 4 changed the resolving logic and requires explicit extension now.

**Comment by estruyf** [comment]
Thanks, just did an update to the theme, and that fixed it.
