### ISSUE TITLE
CodeMirror editor deletes all other pages of a markdown file when multiple entries are used

### ISSUE THREAD

**Issue by ChewbaccaCookie** [slidevjs/slidev#1111]
**Describe the bug**
If a user uses the CodeMirror editor for editing, and this slide is imported somewhere else, then all other slides, except the currently modified one, are deleted. 

Before:
![image](https://github.com/slidevjs/slidev/assets/15861250/56d28f88-f81c-4ef9-8462-bed18740f04d)

Editing:
![image](https://github.com/slidevjs/slidev/assets/15861250/d24dc07b-9782-42aa-baea-59d674c52c26)

After:
![image](https://github.com/slidevjs/slidev/assets/15861250/611c94b0-b566-4c91-b2d5-d370f0d81f45)

--> Page 1 was deleted.

**To Reproduce**
1. Go to this example: [Stackblitz](https://stackblitz.com/edit/slidev-sn9gy1?file=second-section.md) 
1. Go to page 2 or 3
1. Click on the "Edit file" icon in the bottom left navigation 
1. Edit the content of the page 

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Slidev version: Latest

**Comment by KermanX** [comment]
Cannot reproduce in v0.47.4
