### ISSUE TITLE
feat: Standalone Binary

### ISSUE THREAD

**Issue by Jak2k** [slidevjs/slidev#1118]
**Is your feature request related to a problem? Please describe.**
I know lots of people who would like to use slidev, but can't do it, because setting up node is to complicated for them.

**Describe the solution you'd like**
A standalone binary (powered by bun or deno) that can start a dev server, build and preview a slidev presentation, while fetching the theme from npm and storing it in home directory.

**Describe alternatives you've considered**
Baking the default theme into the binary.

**Comment by antfu** [comment]
Thanks for bringing this up, but sorry I have no interest in supporting it officially (roi is too low). Feel free to experiment as a community solution if you want :)
