### ISSUE TITLE
Fullscreen does not work inside iframe

### ISSUE THREAD

**Issue by jkwchui** [slidevjs/slidev#1122]
When a presentation is embedded in another webpage through an iFrame, the fullscreen (and presenter) features no longer work.  Reveal.js has an "embed mode" that retains the ability for such specified presentations to go fullscreen on `F` keystroke.

This is useful, for example, in making multiple presentations on one page, all of which could be presentable as-is (without opening in new tab).

**Comment by KermanX** [comment]
Cannot reproduce. In the following example fullscreen works:

```html
<iframe src="https://demo.sli.dev/composable-vue/1" allowfullscreen />
```

Did you add the `allowfullscreen` attribute?
