### ISSUE TITLE
`v-motion` broken since v0.10.0 (only dev env)

### ISSUE THREAD

**Issue by johannschopplich** [slidevjs/slidev#113]
Hey there, 

slides including `v-motion` as well as `preload: false` aren't working properly anymore (dev env). The animation is skipped and if navigated a second time to the slide, it won't show anything.

I think https://github.com/slidevjs/slidev/commit/219d9bfeb8abf1ca92a2dcfefb0796339405ace2 breaks something for development. Is the manual chunk really necessary?

Thanks in advance for a fix!

**Comment by antfu** [comment]
Fixed. The line your pointed only applies on build, and does not effects dev. The manual chunk is trying to improve the main entry bundle size, but there are quite a big zone for us to optimize.

**Comment by johannschopplich** [comment]
I see. Thanks for pointing out the difference. 🙂
