### ISSUE TITLE
Add support for delay and animation as params in `v-click` and `v-after`

### ISSUE THREAD

**Issue by george-gca** [slidevjs/slidev#1134]
**Is your feature request related to a problem? Please describe.**
Currently I am trying to display 3 figures with their captions one after another, respecting a specific delay and animation, as shown in #1133. This could be more easily achievable with [v-click](https://sli.dev/guide/animations.html#v-click) and [v-after](https://sli.dev/guide/animations.html#v-after) if they had such parameters.

**Describe the solution you'd like**
It would be nice to add custom delay and animation to [v-click](https://sli.dev/guide/animations.html#v-click) and [v-after](https://sli.dev/guide/animations.html#v-after) in a usage basis, instead of having to use [css directly](https://sli.dev/guide/animations.html#element-transitions). This way I could easily change its behaviors in each instance.

**Describe alternatives you've considered**
Creating numerous css classes per slide as shown in [here](https://sli.dev/guide/animations.html#element-transitions).

**Comment by John98Zakaria** [comment]
The new beta version has transition delays :)

```
<div v-click> hi </div>
<div v-after class="transition delay-300">Delay 1</div>
<div v-after class="transition delay-600">Delay 2</div>
```

Check if that solves the issue for you :)

**Comment by antfu** [comment]
Just for the record - it's always possible in all the versions; it's just a CSS transition delay.
