### ISSUE TITLE
Add to the docs information about paths

### ISSUE THREAD

**Issue by george-gca** [slidevjs/slidev#1137]
As stated by @eric-burel in [here](https://github.com/slidevjs/slidev/issues/932#issuecomment-1522866882_):

> seems "img/foobar" won't work but "/img/foobar" will, the initial slash is needed when building, now works fine both in dev and during build.

I had the same issue and fix, and couldn't find this information anywhere in the docs. I believe this should be stated somewhere.

**Comment by antfu** [comment]
It's mentioned here: https://sli.dev/guide/syntax.html#static-assets

It's rather a limitation of the current virtual module approach. Open to contributions if anyone could find a way to fix it.

**Comment by george-gca** [comment]
Funny though, it states there that static assets should be on the `public/` dir, but in my case I put it in `images/` and it worked.

**Comment by george-gca** [comment]
Moving `images/` to `public/images/` and referencing images starting with `/images/` did the trick. Also just now I found this discussion (#180). Closing this issue.

Thanks for slidev, loving it.
