### ISSUE TITLE
Question: how to implement mindmap in sli.dev

### ISSUE THREAD

**Issue by fjun99** [slidevjs/slidev#1139]
A question.  Currently, mermaid is integrated into sli.dev.

If I would like to integrate mindmap (mindmap.js.org) or other component, how can I do this? 

If someone can give an outline, that would be great. Thanks.

**Comment by george-gca** [comment]
Maybe you could take a look at the [Tweet](https://github.com/slidevjs/slidev/blob/main/packages/client/builtin/Tweet.vue) component, or some other component from this dir.

**Comment by fjun99** [comment]
> Maybe you could take a look at the [Tweet](https://github.com/slidevjs/slidev/blob/main/packages/client/builtin/Tweet.vue) component, or some other component from this dir.

Thank you!

**Comment by twitwi** [comment]
@fjun99 mermaid has a mind map syntax if it fits your need
https://mermaid.js.org/syntax/mindmap.html
