### ISSUE TITLE
Code blocks with maxHeight displace the whole view upwards

### ISSUE THREAD

**Issue by AndreasRoither** [slidevjs/slidev#1140]
**Describe the bug**
When using code blocks with a fixed `{maxHeight:'430px'}` option, the whole page will be displaced upwards. The browser will not show any scrollbars, so you can't scroll the content into view. If no scrollbar is used e.g. `maxHeight` is not used, the issue will not show up.

**Images**

One Page before code block:
<img width="1155" alt="image" src="https://github.com/slidevjs/slidev/assets/9451065/3d8ce3dd-e7f3-4bed-a660-74893e40860b">

Page at code block, notice how the header title is not shown but a blank space with the same color as the slide is shown:
<img width="1155" alt="image" src="https://github.com/slidevjs/slidev/assets/9451065/642dc24e-b04d-47ca-95ca-dc352cd76293">

The picture above shows the same window at the same position. 
If the amount of code lines is reduced, the space at the bottom will be smaller as well:

<img width="1155" alt="image" src="https://github.com/slidevjs/slidev/assets/9451065/0a67eaed-ea60-4c82-8547-807a1a635d3c">

*Edit, add picture with green border for clarification*
<img width="1047" alt="image" src="https://github.com/slidevjs/slidev/assets/9451065/650961c6-88c6-4d2f-b286-0f5cff2f7a4f">

**To Reproduce**

dependencies:
```json
"dependencies": {
    "@slidev/cli": "0.43.6",
    "@slidev/theme-default": "latest",
    "@slidev/theme-seriph": "latest"
  },
  "devDependencies": {
    "@iconify-json/ri": "^1.1.12"
  }
```

Used slides (remove empty space for backtick):
```md
---
layout: default
level: 1
---

# Test

---
layout: default
level: 1
---

# Domain

` ``java {all|1-7|13-29} {maxHeight:'430px', lines:true} 

public class Test {


























}
` ``
```

1. Go to the first empty page (important, as refresh on the page with the issue fixes it until the next code block appears)
2. Transition/click for next page
3. See the error

**Desktop:**
 - OS: Windows 11 Pro Version 10.0.22621 Build 22621
 - Browser: Chrome: 117.0.5938.92, Firefox: 118.0, Edge
 - Slidev version: `0.43.6`

Thanks and let me know if I should update the report with more information :)

**Comment by AndreasRoither** [comment]
Can not reproduce on any other pc

**Comment by jolo-dev** [comment]
I have the same issue. @AndreasRoither is this resolved?

**Comment by AndreasRoither** [comment]
I resolved this by completly cleaning out `node_modules` and reinstalling. I think one of the builder sub dependencies is the issue. As this can be resolved (at least in my case) by just updating all peer dependencies, I decided to close the issue.
