### ISSUE TITLE
UnoCSS @apply in component not working when preceeded with nested styles

### ISSUE THREAD

**Issue by jgosmann** [slidevjs/slidev#1144]
**Describe the bug**

When using UnoCSS and `@apply` after nested styles in a Vue component, the `@apply` styles are not applied. Take the following example component:

```vue
<template>
    <div class="unocss-styled">
        This should have a red background, but doesn't.
    </div>
</template>

<style>
  .unocss-styled {
      div {}  /* Remove this or move it after the @apply, and the @apply works as intended. */

      @apply bg-red-500;
  }
</style>
```

It should render the text with a red background, but it doesn't. When switching to WindiCSS it works as intended. It also works when moving the `div {}` below the `@apply ...` line or when avoiding nesting and declaring the nested div styles like so:

```css
.unocss-styled div { ... }
```

**To Reproduce**
1. Create a Sli.dev presentation.
2. Add the code above as a component.
3. Add the component to the slides.
4. View the slides.

**Desktop (please complete the following information):**
 - OS: macOS Venture 13.6
 - Browser: Firefox 118.0.1
 - Slidev version: 0.43.6

**Comment by KermanX** [comment]
Thanks for your feedback. I think this is the expected behavior of UnoCSS.

**Comment by jgosmann** [comment]
Is this documented anywhere?
