### ISSUE TITLE
Internal server error when using mdi-account-circle Icon

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1148]
**Describe the bug**
using following markdown:
```
<style>
    footer {
        color: #bebebe;
        z-index: 999;
    }
</style>
<!-- <script> doesn't matter if the following been commented out
import SvgIcon from '@jamescoyle/vue-icon'
import { mdiWechat } from '@mdi/js'
</script> -->
<template>
  <footer class="absolute bottom-0 left-5"><br/><small><SlideCurrentNo/>/<SlidesTotal/></small></footer>
  <footer
    v-if="$slidev.nav.currentLayout !== 'cover'"
    class="absolute bottom-0 right-0 p-2 flex items-center"
  >
    <mdi-account-circle />
    <!-- PRESENTED by <mdi-wechat class="c-green-4 ml-1"/> -->
  </footer>
</template>
```
will cause error:

```
7:11:30 PM [vite] Internal server error: Icon `mdi/account-circle` not found
      at generateComponent (/usr/local/lib/node_modules/@slidev/cli/node_modules/unplugin-icons/dist/chunk-ACYGWCJ6.cjs:337:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.load (/usr/local/lib/node_modules/@slidev/cli/node_modules/unplugin-icons/dist/chunk-ACYGWCJ6.cjs:394:20)
      at async Object.load (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44316:32)
      at async loadAndTransform (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:54943:24)
      at async viteTransformMiddleware (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32)

```
**Desktop (please complete the following information):**
 - OS: macos m1, node is v18.14.0
 - Browser: firefox
 - Slidev version: 0.43.6

**Comment by KermanX** [comment]
Cannot reproduce on `slidev0.47.5`, `node20.9.0`, `Windows11`, `Edge121`.

If the error still happens, please reopen this issue.

**Comment by ani-per** [comment]
> Cannot reproduce on `slidev0.47.5`, `node20.9.0`, `Windows11`, `Edge121`.
> 
> If the error still happens, please reopen this issue.

This occurred to me as well when I created a new custom theme (it's not limited to just `mdi-account-circle`). It's because the `mdi` portion of `@iconify` is not installed by default; see [`client/package.json`](https://github.com/slidevjs/slidev/blob/fc9dd0e8dd819876f4ffa07495c0ddd12f20d9e0/packages/client/package.json#L32), which includes `@iconify/(carbon,ph,svg-spinners)` but not `mdi`.

Is there a reason it's left out, even though [the docs recommend it](https://sli.dev/guide/syntax#icons)? This seems like an accidental miss.

**Comment by KermanX** [comment]
> Is there a reason it's left out, even though [the docs recommend it](https://sli.dev/guide/syntax#icons)? This seems like an accidental miss.

I personally think it is not installed by default because the package could be too large if we include all the icon packs listed in the docs. I've once confirmed with Antfu that the icon packs not used in `@slidev/client` are not installed by default, so the docs was updated then.
