### ISSUE TITLE
View transition not working with Presenter mode

### ISSUE THREAD

**Issue by sapphi-red** [slidevjs/slidev#1160]
**Describe the bug**
View Transition is not shown in presenter mode. It works with play mode.

It seems this `from.meta`/`to.meta` doesn't return the value of the slide if it's in presenter mode.
https://github.com/Jannchie/slidev/blob/dad957728e5d73b5926cb8635ae03228baca52eb/packages/client/composables/useViewTransition.ts#L14

refs #1100 #1101

**To Reproduce**
1. Open https://stackblitz.com/edit/slidev-xaqvhc?file=slides.md
2. Open it with play mode and check that view transition works
4. Switch to presenter mode and check that it doesn't work

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 118.0.5993.89
 - Slidev version: 0.43.7

**Comment by cmplank** [comment]
I'm seeing the same issue on Ubuntu with slidev 0.43.8.
