### ISSUE TITLE
Create mutli-col slides

### ISSUE THREAD

**Issue by COD1995** [slidevjs/slidev#1161]
Is there a way to create multi-cols slides? Right now there are only two-cols.

**Comment by TechWatching** [comment]
You can easily do that by creating your own layout. You can look at the coder for the two-cols layout and copy it to creat your own three-cols layout.

**Comment by twitwi** [comment]
if your number of columns varies a lot (and/or you prefer not to have a dedicated layout), you can write directly in the slides, as in:

```md

## TEST COLS

<div class=" w-full h-full grid grid-cols-3">
  <div>c1</div>
  <div>

  ### some markdown

  - use empty lines after div to allow markdown parsing
  - it rocks
  
  </div>
  <div>c3</div>
</div>
```

**Comment by COD1995** [comment]
Thanks
