### ISSUE TITLE
How to set a page's background-image?

### ISSUE THREAD

**Issue by hezhongfeng** [slidevjs/slidev#1162]
the `background: '/cover.jpeg'` just work for first page. Now I want to set second page's background,how to set?use style?

```
---
background: '/01.png'
transition: slide-left
---

# firstpage

firstpage

---
background: '/01.png'
transition: slide-left
---

# second page

second page

<style>
h1 {
  color: red;
}

</style>

```
<img width="1025" alt="image" src="https://github.com/slidevjs/slidev/assets/12163050/51e7a285-c69b-48b9-a8bb-461f319dac6c">
<img width="1045" alt="image" src="https://github.com/slidevjs/slidev/assets/12163050/3d87946f-8be9-406f-8a5c-bf87ee8aebb7">

**Comment by hezhongfeng** [comment]
demo

https://github.com/hezhongfeng/interaction

**Comment by hezhongfeng** [comment]
I find a way

```
<style>
.slidev-layout{
  padding: 0;
  background-image: url("/cover.jpeg");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
</style>
```

**Comment by aeudes** [comment]
A bit late, but I think you can also use layout, have you try :
```
---
layout: image
image: '/cover.jpeg'
---
```

**Comment by hezhongfeng** [comment]
@aeudes yes, it's not what I want.
