### ISSUE TITLE
`--remote` argument doesn't work with build

### ISSUE THREAD

**Issue by clairesunstudio** [slidevjs/slidev#1165]
## Description

`slidev --remote=[my_pw]` works for me locally. However, I'm getting `Unknown argument: remote` when I pass the argument to the build command. I expect `slidev build --remote=[my_pw]` to work so I can protect the presenter mode when I host my slides.

**Comment by antfu** [comment]
`--remote` is a dev only option, and would not work in build as the build is a SPA and there would be no server.
