### ISSUE TITLE
Presentation mode does not work with minimized / non-visible tab

### ISSUE THREAD

**Issue by GeeWee** [slidevjs/slidev#1169]
**Describe the bug**

When presenting I would like to share the non-presenter view e.g. on Teams, while having the presenter view visible on my screen. I only have one screen.

However, the synchronization between presenter -> viewing window only seems to happen if the viewing window is partially visible. If the window is completely covered by the presenter view (aka in the background) or minimized, the synchronization does not happen until the window becomes visible again.

I am not sure if this is something that can be fixed by `slidev` or if this is browsers saving energy by postponing all work if the window is not visible.

**To Reproduce**
1. Open up a slide-deck
2. Create two windows, one with presenter mode and one without
3. Share the view window on Teams, and view from another PC
4. Minimize the view window on the presenting PC
5. Click forward in Presenter mode
6. Notice the teams window is not updated
7. Maximize the view window
8. See the transition to the correct slide happen, and the shared teams window update

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: tested in Firefox & Chrome
 - Slidev version: 0.43.12

**Comment by KermanX** [comment]
Close this because it seems that this can't be solved by fixing Slidev.
