### ISSUE TITLE
Unable to import stuff from @slidev/types

### ISSUE THREAD

**Issue by DanielGiljam** [slidevjs/slidev#1175]
**Describe the bug**
When you try to import e.g. `defineAppSetup` from @slidev/types you get a TS error saying there's no such exported error (TS2305). This is because [index.d.ts](https://github.com/slidevjs/slidev/blob/main/packages/types/index.d.ts) in @slidev/types has an export statement which fails to resolve in the built package:

```ts
export * from "./dist/index.d";
```

In the built package there is dist/index.d.mts, but the export statement above cannot resolve that. I suspect it tries to find dist/index.d.ts, which does not exist.

- Slidev version: 0.43.13

**Comment by openscript** [comment]
The same happens for `defineShikiSetup`.

**Comment by openscript** [comment]
`0.43.15` still breaks our build: https://github.com/openscript-ch/slidev-theme/actions/runs/6854211222/job/18636653482?pr=31
