### ISSUE TITLE
Slidev published into vercel don't show camera view and recording

### ISSUE THREAD

**Issue by filiafobico** [slidevjs/slidev#1179]
**Describe the bug**
Slidev published into vercel don't show camera view and recording

localhost 
![image](https://github.com/slidevjs/slidev/assets/13921642/2026c71b-83e3-4afc-b28e-b53e98ff98b2)

vercel
![image](https://github.com/slidevjs/slidev/assets/13921642/5fa2d52d-1dc5-4d9f-ba94-9ffa30dd6710)

**To Reproduce**
1. Install slidev
3. Publish into vercel
5. Notice that this button does not appear

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Firefox Snap for Ubuntu 118.0.2
 - Slidev version: 0.43.13

**Comment by antfu** [comment]
It's disabled in production by default, add this in the frontmatter:

```md
---
record: true
---
```

https://sli.dev/custom/#frontmatter-configures
