### ISSUE TITLE
two-cols-header layout is broken in latest release

### ISSUE THREAD

**Issue by adamdehaven** [slidevjs/slidev#1185]
**Describe the bug**

Merging this PR broke the `two-cols-header` layout: https://github.com/slidevjs/slidev/pull/1114

**To Reproduce**
1. Add a page with the layout
2. make sure you have 2 columns of slot content
3. everything displays in a single column

**Comment by TechWatching** [comment]
I have the same problem, I did not upgrade to latest version to avoid that issue.

**Comment by antfu** [comment]
Should be fixed in v0.44
