### ISSUE TITLE
[question]does slidev support mobile? or are there any themes for mobile divices?

### ISSUE THREAD

**Issue by keosu** [slidevjs/slidev#119]

**Comment by antfu** [comment]
Currently, no. You can browse slides in mobile without problems, but in the near feature, we are don't have a plan on supporting vertical layouts if that's what you mean. Thanks.

**Comment by keosu** [comment]
Thanks for reply. Yes, I am looking for a vertical layout support.

**Comment by antfu** [comment]
Currently, the aspect ratio is hard coded, https://github.com/slidevjs/slidev/blob/1807ef2eb0136d38e74ce026ef0cf87324af0c37/packages/client/constants.ts#L1-L1

Maybe you can clone it down, can change it locally to see if it works well on vertical layout. If so, we might consider make it configureable.

**Comment by keosu** [comment]
I

> Currently, the aspect ratio is hard coded,
> 
> https://github.com/slidevjs/slidev/blob/1807ef2eb0136d38e74ce026ef0cf87324af0c37/packages/client/constants.ts#L1-L1
> 
> Maybe you can clone it down, and change it locally to see if it works well on vertical layout. If so, we might consider make it configureable.

I tried a simple demo, it works, thanks!

**Comment by antfu** [comment]
Now in v0.13.0

```md
---
aspectRatio: 16/9
---
```
