### ISSUE TITLE
v-clicks not working in combination with custom components and <slot>

### ISSUE THREAD

**Issue by patrickpichler** [slidevjs/slidev#1190]
**Describe the bug**
`<v-clicks>` is not working when used in a custom component and passed children via `<slot>`. It simply shows
all the children, but you cannot click through it.

**To Reproduce**
1. Clone https://github.com/patrickpichler/slidev-components-sample/
2. Checkout commit `297962cd93be5f119164d26416cc5d9331fcfdfc`
3. Run `npx slidev`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox + Chrome
 - Slidev version: 0.43.15

**Comment by twitwi** [comment]
self-note (to detect slots, if nothing better):
`(listTags.includes(i.type as string) || typeof i.type === 'symbol')`
`(listTags.includes(defaults[0].type as string) || typeof defaults[0].type === 'symbol')`
