### ISSUE TITLE
Proposals: include code snippet from external source file

### ISSUE THREAD

**Issue by tryfinally** [slidevjs/slidev#1193]
Usually to make sure the code on the slide is correct you need to compile and test it.
Then you copy it into the slide.
But code can change. Now you need to copy & paste it again.
It would be nice to just include the required lines from the external source file automatically without copy/paste.

````
``` cpp [./src/list.hpp: 10 | 20] {all | 10 | 14-16}

```
````

will read lines 10 to 20 from /src/list.hpp file and display that as a snippet.

Alternative:
Use a component:
```html
<SourceCode file="./src/list.hpp" from="10" to="20"  anim="all | 10 | 14-16" />
```

**Comment by tryfinally** [comment]
### Workaround

use a marker inside code block to specify source file:

````
```cpp {all|1|4-6} {lines:true}
@@@: demo.cpp
```
````

I wrote a pre-parser extension to look for the marker  and replace it with content of the source code file.
Now edit the demo.cpp and restart slidev.

**Comment by piranna** [comment]
For code, a marker in the code block is fine, but I would like to have also the option to include slides from another deck (a ref in a slide frontmatter is ok) or raw content (a component is fine here)

**Comment by KermanX** [comment]
I've opened a PR for it: #1222
