### ISSUE TITLE
Export using Firefox (or any browser engine Playwright supports)

### ISSUE THREAD

**Issue by yheuhtozr** [slidevjs/slidev#1195]
**Is your feature request related to a problem? Please describe.**
I usually present my slides with Firefox because of some i18n-related typography things Chrome does not support, but it is not an option for `slidev export`; exported PDF has unwanted layout.

**Describe the solution you'd like**
Since Playwright is shipped with multiple engines, is it possible to have an option to choose which one to render?

**Comment by antfu** [comment]
PR welcome :)

**Comment by KermanX** [comment]
Closing this, as pointed out by https://github.com/slidevjs/slidev/pull/1196#issuecomment-1979681462
