### ISSUE TITLE
Empty animation step when first v-click is a number

### ISSUE THREAD

**Issue by twitwi** [slidevjs/slidev#1198]
Example, the goal being to show the gifs at step 2 (but the two v-clicks add two empty steps)

```md
<img src="/amazing.gif" v-click="2" />
<img src="/amazing.gif" v-click="2" />

<v-clicks>

- a
- b (and the gif)
- c

</v-clicks>
```

**Comment by twitwi** [comment]
Thanks for the workaround.

There have been a few questions (discord, issues) where the answer was to set `clicks:` manually.
I feel it is not the "least surprise" implementation we can have.
If I specify a v-click number, I'd expect it should be taken out of the default sequence (or by construction we are making a no-op step).
Similarly, I would expect to not require the explicit clicks:3 here as it can be derived automatically (as the max between the number of sequential clicks and the max value appearing in v-click).

I'll close it for now.

**Comment by 0phoff** [comment]
> If I specify a v-click number, I'd expect it should be taken out of the default sequence (or by construction we are making a no-op step).

While I understand your point of view, I believe this is a matter of semantics.
Both points of view have their pros and cons, so there is no real right or wrong answer IMO.

---

> Similarly, I would expect to not require the explicit clicks:3 here as it can be derived automatically (as the max between the number of sequential clicks and the max value appearing in v-click).

This is indeed an issue in the current codebase.
If you want, you can take a look and try to fix this issue. :innocent:
