### ISSUE TITLE
Maybe we could provide a method to build executable output without node environment

### ISSUE THREAD

**Issue by DevilTea** [slidevjs/slidev#12]
First of all, sorry for my poor english.

As title, I made a [tool](https://github.com/DevilTea/serve-something) to provide this feature!

I've test to packed the demo slides spa into executable outputs for macos-x64 and win-x64

```bash
# Assume the current path is in the slidev repo's root
# With dependency 'serve-something' installed (assume that we installed as a global dependency)

# Execute the command (Checkout the serve-something repo for the options' detail)
$ serve-something ./demo/dist --spa --build --targets node14-macos-x64,node14-win-x64

# There would be a folder named as 'executable-outputs' by default, and the executable outputs would finally be inside the folder!
```

It works just fine, but the disadvantage is that the output size may be over 4X MB because of the packed node runtime.

I think this could be an option for build into spa, it might be a convenient  way for using anywhere!

I would like to have a discussion with everyone who loves this awesome project!

**Comment by DevilTea** [comment]
Also, the tool provide programmatic usage too!

**Comment by antfu** [comment]
I am not sure if I get the use cases to pack slides into an executable file. To me, the best way of sharing slides are either a plain PDF file or just a link to your slides. Can you maybe explain a bit more? Thanks

**Comment by DevilTea** [comment]
I agree the point that you said when the case is to share the slides. 
I think the feature of packing slides into an executable file is aim to provide the convenient for presentation. 
The case is that I love the web SPA could bring us lots of powerful features that traditional slides applications can't do when I am presenting. 
But actually sometimes I face problems like bad network environment, only able to use the field provided computer .etc. 
To deal with these problems, I made the above tool for myself to prepare a plan B that all I need is a USB storage and make sure the computer has installed a modern browser, and the SPA's resources would be served from local.

**Comment by antfu** [comment]
Yeah, maybe that's a good point. However I still think this is rather a rare use case. And since we already assumed our users are developers, they should be able to find the solutions for their particular needs (just like you did!). Thanks for bring this up, I think it's good as it also provided the info for ppl who faced similar problems to find your package and solution. Closing.
