### ISSUE TITLE
Multiple entries features corrupts markdown file specified in `src:` when editing in browser

### ISSUE THREAD

**Issue by oripka** [slidevjs/slidev#1204]
I use the [multiple entries feature](https://sli.dev/guide/syntax.html#diagrams) and noticed that editing slides in the browser that are not in the main markdown file get corrupted. When typing slidev reloads and the markdown file gets corrupted.

Here a [reproduction](https://stackblitz.com/edit/slidev-zyvuyq?file=slides.md,subslide.md,README.md) and video of the issue 

https://github.com/slidevjs/slidev/assets/227032/d5d8bd11-adf6-489f-9599-655093d16b81

**Comment by KermanX** [comment]
Duplicate of #1111
