### ISSUE TITLE
Black background when exporting to PDF

### ISSUE THREAD

**Issue by piranna** [slidevjs/slidev#1207]
**Describe the bug**
I'm using `shibainu` theme, and when exporting to PDF both with the `download` frontmatter option or with `slidev export` command, generated PDF slides have a black background instead of the theme colorful ones. I think it can be related with the fact they are SVG images, so they should be rasterized to PNG images with the actual slides resolution first and use them instead. Rendering on web works properly.

**To Reproduce**
1. Create a new sli.dev with `shibainu` theme
2. Generate PDF with `slidev export`
3. Open the generated PDF
4. See the black background instead of the colorful one

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 23.10
 - Browser: Chrome 119
 - Slidev version: 0.44.0

**Comment by piranna** [comment]
`bricks` theme has the same problem, polygons are shown, but background is not rendered since it's a SVG image, showing it a white background.

**Comment by piranna** [comment]
Still happening in version 0.46.1.

**Comment by AlbertBrand** [comment]
Try the following:

Open `node_modules/@slidev/cli/dist/export-WYWYD5MK.mjs` (this is for 0.46.3).
Find:
```
  const browser = await chromium.launch({
    executablePath
  });
```
(in the function `exportSlides`)

Change to:
```
  const browser = await chromium.launch({
    executablePath,
    headless: false,
  });
```

Then look for:
```
    await page.waitForLoadState("networkidle");
```

And add the following line after it:
```
    await page.waitForLoadState("networkidle");
    await page.pause();
```

Now run export. Playwright will run in headed mode and pause on the first page. You can use the Inspector panel to figure out which CSS is causing issues. 

I've seen an issue with page height, I needed to add:
```
.slidev-page {
  @apply h-full;
}
```
to my theme `layout.css` to make SVG size correctly.

**Comment by longshihui** [comment]
same problem, Does this issue have a corresponding pull request?
