### ISSUE TITLE
`<v-click>` component not working

### ISSUE THREAD

**Issue by piranna** [slidevjs/slidev#1214]
**Describe the bug**
Using the [`<v-click>` components](https://sli.dev/guide/animations.html#v-click) is a no-op, but using the `v-click` directive does.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.10
 - Browser: Chrome 120
 - Slidev version: 0.45.0

**Comment by xsjcTony** [comment]
Seems you need to manually define `clicks` in the frontmatter, component usage may not set it automatically.

**Comment by piranna** [comment]
> Seems you need to manually define `clicks` in the frontmatter

Not fully understand this... Isn't `clicks` just a helper to don't need to wrap each element in a list with `<v-click>`? I just only want to show on click some elements, and left others visible since start, I don't have a list...

**Comment by george-gca** [comment]
Can you provide an example to understand the problem?

**Comment by piranna** [comment]
> Can you provide an example to help understand the problem?

```md
---
layout: default-3
---

### Ambit (2/2)

Big companies could have enough resources to dedicate a research team to develop
their own in-house media streaming scalability solutions

<v-click>
...but they could be interested in Mafalda SFU as a way to save time and money,
and get a shorter time-to-market with a more robust solution
</v-click>
<v-click>
or also they could be interested in acquiring the technology, intellectual
property and the team behind it.
</v-click>
```

This slide directly shows me the content insde the `<v-click>` tags, clicks are not endoresed and markdown is not rendered. If I replace them with `<div v-click>`, content is properly shown after clicks, but still markdown is shown raw (not rendered as HTML).

**Comment by oripka** [comment]
Newline between click tags?

**Comment by piranna** [comment]
> Newline between click tags?

Yes, I have newlines, because content that I want to shown and hide is multiline :-)

**Comment by oripka** [comment]
I meant like this

```
---
layout: default-3
---

### Ambit (2/2)

Big companies could have enough resources to dedicate a research team to develop
their own in-house media streaming scalability solutions

<v-click>

...but they could be interested in Mafalda SFU as a way to save time and money,
and get a shorter time-to-market with a more robust solution

</v-click>

<v-click>

or also they could be interested in acquiring the technology, intellectual
property and the team behind it.

</v-click>

```

**Comment by piranna** [comment]
> I meant like this

Ok, with whitelines between the tags and the markdown code, it works properly, including the Markdown rendering instead of being shown as raw text... I think it's a bug in the way is detected the content of the `<v-click>` tags.

**Comment by george-gca** [comment]
I believe this kind of information (with empty lines between the tags and the contents) should be in the docs close to the tags example.

**Comment by piranna** [comment]
> I believe this kind of information (with empty lines between the tags and the contents) should be in the docs close to the tags example.

Yes, but I truly believe that's a bug that should be fixed and allow to use the `<v-click>` tags without whitespaces, and that they could be used for example to show and hide inline content mid-sentence.
