### ISSUE TITLE
Markdown inside components or directives is not rendered

### ISSUE THREAD

**Issue by piranna** [slidevjs/slidev#1215]
**Describe the bug**
When having a component or html fragment, its content is showed verbatin, without rendering the markdown syntax.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.10
 - Browser: Chrome 120
 - Slidev version: 0.45.0

**Comment by John98Zakaria** [comment]
You need to put the fragment at the start of the line and an empty space between the divs

if you add a tab it breaks

```
<div>

$2^{128}+2^{64}+2^{0}$

</div>
```

**Comment by piranna** [comment]
> You need to put the fragment at the start of the line and an empty space between the divs

Why are these limitations?

**Comment by John98Zakaria** [comment]
@piranna This is the place where the markdown gets parsed, you can see every function and the regex that matches each of the building blocks of slidev, so if you want better recognition you need a better regex that would match even if it is not at the beginning of the line

https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/plugins/markdown.ts#L128

**Comment by piranna** [comment]
Maybe I'm missing something, but that code seems only to parse code blocks, not content of html fragments...

**Comment by antfu** [comment]
This is how markdown works, otherwise it's ambiguous to tell if the content inside HTML should be interop or not.
