### ISSUE TITLE
Images gallery

### ISSUE THREAD

**Issue by piranna** [slidevjs/slidev#1230]
**Is your feature request related to a problem? Please describe.**

If I put multiple images in queue, I can't control to put them in a row with an homogeneous distribution.

**Describe the solution you'd like**

An easy to use way (maybe a custom widget?) where I can set several images (a list?) and they are distribute equally centered in a row, or multiple ones if there's no space.

**Describe alternatives you've considered**

Create a HTML table with border zero width, or using flex layout, or allow to have absolute (relative?) position of images in a slide.

**Comment by ayanamists** [comment]
Maybe [photoswpie](https://photoswipe.com/) is worth trying. You can directly embedding in your html code, or define a vue component to wrap it. See [Slidev Doc](https://sli.dev/custom/directory-structure.html#components)

**Comment by piranna** [comment]
> Maybe [photoswpie](https://photoswipe.com/) is worth trying. You can directly embedding in your html code, or define a vue component to wrap it. See [Slidev Doc](https://sli.dev/custom/directory-structure.html#components)

It looks nice, thank you :-)
