### ISSUE TITLE
How can I support video player?

### ISSUE THREAD

**Issue by lance-loong** [slidevjs/slidev#124]
I need play the video,The video format is mov,how can i support video player in slidev?

**Comment by johannschopplich** [comment]
You have to convert the video to `mp4` for example — you may use an encoder like [Handbrake](https://handbrake.fr/).

Then, just add an HTML5 video tag to your slide:

```
html<video controls>
  <source src="/mov/lance-loong.mp4" type="video/mp4">
</video>
```

**Comment by lance-loong** [comment]
Think for you. You are right.

**Comment by baggiponte** [comment]
Can it work with a youtube link? (e.g. [this](https://youtube.com/clip/UgkxaPDJaKOB7IfbwkuNA1e-wWLwvd5Orknx))

**Comment by Fanisting** [comment]
> Can it work with a youtube link? (e.g. [this](https://youtube.com/clip/UgkxaPDJaKOB7IfbwkuNA1e-wWLwvd5Orknx))

@baggiponte Just copy the sharing link in the YouTube page into your md file. It is a bunch of html code which help you to create a new windows in the slides.

**Comment by CarsonSlovoka** [comment]
I have created a component: [vtt.vue](https://gist.github.com/CarsonSlovoka/f6768b3289a90b53c0d6ef4e96e37515/revisions#diff-fd083d0b0425d5443700935e44976adf2c0155719f1b64cc62a40e78ba0abedfR1-R123) that allows you to add webVTT subtitles, making it much easier for you.

![image](https://github.com/slidevjs/slidev/assets/17170765/68864a37-006b-41eb-8f13-2f5067362b4f)
