### ISSUE TITLE
export blank pdf

### ISSUE THREAD

**Issue by jneless** [slidevjs/slidev#1240]
**Describe the bug**
init slidev@0.42.9, without any more actions
but the export PDF is blank.

**To Reproduce**
1. npm init slidev@0.42.9
2. slidev export

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Browser: Edge
 - Slidev version: 0.42.11( yes, the version by npx slidev@42.9 is v0.42.11, instead of 42.9)

**Comment by innovatingdev** [comment]
Have the same issue with `slidev export` => empty pdf with a size of about 800 bytes.

For me it worked by running `slidev build --download`, which generated a working pdf in `./dist`.

**Comment by jneless** [comment]
> Have the same issue with `slidev export` => empty pdf with a size of about 800 bytes.
> 
> For me it worked by running `slidev build --download`, which generated a working pdf in `./dist`.

thank you very much!
it do works.

However, I can NOT bear Slidev eternal bug anymore and turn back to PPT.
Yes, I could understand it is a community project, but it seems no one is charging for the testing and bug, even the init and demo processes.
