### ISSUE TITLE
error in installation with Slidev version and playwright-chromium

### ISSUE THREAD

**Issue by jneless** [slidevjs/slidev#1241]
**Describe the bug**

run 'npx create-slidev' and shell indicate the version is v0.46.1
when I export PDF, shell shows the version v0.42.8 (global), two version are different

the shell ask me to install the playwright-chromiu

so that I run the `npm i -D playwright-chromium` by suggestion, and the installation succeeded.

I tried to run `slidev export`, it ask me to install playwright-chromiu, again.

there are two bugs in pdf export.

**To Reproduce**
1.  run 'npx create-slidev',  the shell indicate the [Slidev Creator v0.46.1]
2. select the agent npm
3. run 'slidev export', the shell shows [Slidev v0.42.8 (global)]
4. error, needs install it via `npm i -D playwright-chromium`
5. run `npm i -D playwright-chromium`
6. re do the  'slidev export'
7. error, needs install it via `npm i -D playwright-chromium`, AGAIN

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1, Apple M1
 - Browser: Edge
 - Slidev version: v0.46.1 or v0.42.8 (global), I am NOT sure.

**Comment by KermanX** [comment]
It seems that this has been fixed by 03a522006fea49588a646b36810a53a3ca7d6b88.
