### ISSUE TITLE
Twitter widgets.js is still included in index.html when writing `<Tweet/>` within a code block

### ISSUE THREAD

**Issue by yspjack** [slidevjs/slidev#1244]
**Describe the bug**
When you write `<Tweet/>` within a code block in your slides, the twitter widget js is still included in `index.html`

**To Reproduce**
1. Create the slidev Project, replace `slides.md` with the following:
```markdown
---
theme: default
class: text-center
highlighter: shikiji
lineNumbers: false
info: |
  ## Slidev Starter Template
  Presentation slides for developers.

  Learn more at [Sli.dev](https://sli.dev)
drawings:
  persist: false
transition: slide-left
title: Welcome to Slidev
mdc: true
---
Code block `<Tweet/>`
```
2. Run `npx slidev build`
3. Go to 'dist/index.html'
4. See the error: `platform.twitter.com/widgets.js` is found in index.html

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Slidev version: v0.46.1

**Comment by KermanX** [comment]
Personally, I think this is a very rare edge use case and it's not quite worth it to perform this possible optimization. Close this for now.
