### ISSUE TITLE
Highlighting two blocks of code in the same time doesn't work

### ISSUE THREAD

**Issue by xaviermignot** [slidevjs/slidev#1246]
**Describe the bug**
I can't make the `{at:0}` feature work when highlighting lines of code blocks. I have tried to use the solution of [this discussion](https://github.com/slidevjs/slidev/discussions/431#discussioncomment-2625444) to highlight the lines of two blocks of code at the same time but it doesn't work (highlighting is done in sequence as if the `{at:0}` was ignored).  

**To Reproduce**
1. Initialize a new presentation with `npm init slidev`. Replace the content of the `slides.md` with this (remove the `\` before the ` ``` `):
```
\```js{all|1|2|all}
const a = "Highlight me first!"
const b = "then me!"
\```

\```js{all|1|2|all} {at:0}
const thisVarChanged = "Highlight me first!"
const eyo = "then me!"
\```

---

\```js{all|1|2|all}
const a = "Highlight me first!"
const b = "then me!"
\```

<v-clicks at="0">

* one
* two
* three

</v-clicks>

---

# Last slide
```
3. Launch locally and open the slides in your browser
4. You should see two errors:
  - On the first slide, the code blocks are highlighted in sequence (the `{at:0}` of the second block is ignored)
  - On the second slide, the `at="0"` of the `v-clicks` works fine: the lines appear when the code lines are highlighted. But you'll notice that 3 other clicks are required to go to the last slides. I'm wondering if it's related so I include this in the issue report.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 (Under WSL with Windows 11)
 - Browser: Edge 120.0.2210.121
 - Slidev version: v0.46.1

Many thanks for your help (and for building an awesome product) !

**Comment by xaviermignot** [comment]
Some additional information: I have tried to reproduce the issue using Stackblitz, and got a different behavior:
- The lines on the first slide were highlighted in the same time (as expected) !
- 3 more clicks were needed to go to the second slide
- For the second slide, the behavior was the same as described in the issue description

Then I have noticed the version used by Stackblitz: `v0.35.4`... After a `npm update` to bump to `v0.46.1`, the behavior was the same as described in the issue description for both slides.  
So something has probably changed regarding this feature between those versions 🤔

**Comment by xaviermignot** [comment]
For anyone having the same issue, let met share this workaround:
- Stick to `v0.45.0`
- Limit the number of clicks on the slide using the `clicks` property in the frontmatter (as explained [here](https://sli.dev/guide/animations.html#custom-clicks-count)).

With these two steps I don't have the issue anymore.

**Comment by asm0dey** [comment]
For me, the workaround works too, but it's ugly. Especially given the fact that in docs, the scenario of two synchronized code blocks is highlighted as a main scenario.

**Comment by John98Zakaria** [comment]
I decided to invest some time into the issue
Here are the 2 problems 

1. The documented syntax broke in commit as the regex that detects latex blocks changed in https://github.com/slidevjs/slidev/commit/80be226b201f68f67af8e82d3594558a50c29251#diff-345d7ee55c0f3c8202375b28cf816e5fdf5f246d760624b86ed2e6f22c1510f1R192

Now you the should not add a space between the highlighting lines blocks and {at}

'''

```js{all|1|2|all}{at:0}
const thisVarChanged = "Highlight me first!"
const eyo = "then me!"
```

'''

**Comment by John98Zakaria** [comment]
I fixed the docs such that no-one would hang at the issue again for now

https://github.com/slidevjs/docs/pull/159
