### ISSUE TITLE
Prettier plugin/parser

### ISSUE THREAD

**Issue by antfu** [slidevjs/slidev#1261]
Introduce a Prettier plugin to format Slidev's extension well

Related https://github.com/slidevjs/slidev/issues/854

**Comment by KermanX** [comment]
I wrote one in https://github.com/KermanX/prettier-plugin-slidev.

TODO:

- [ ] formal unit tests
- [ ] some small bugs (some haven't been found yet)

**Comment by KermanX** [comment]
@antfu I think https://github.com/KermanX/prettier-plugin-slidev is ready for a release. How can the repository be transferred to the `slidev` organization? (I can't do it myself because I don't have write permission)?

**Comment by antfu** [comment]
Looks promising! Just invited to join the team!

Up to you if want to transfer the repo to this org, or want to migrate it inside this monorepo :)

**Comment by KermanX** [comment]
I have transferred it to https://github.com/slidevjs/prettier-plugin, and published it as `prettier-plugin-slidev@1.0.0`. (Invited @antfu to the package)

**Comment by antfu** [comment]
Awesome, thanks! Check your Discord btw :P
