### ISSUE TITLE
Ability to control the quality of the png export

### ISSUE THREAD

**Issue by juanrgon** [slidevjs/slidev#1263]
**Is your feature request related to a problem? Please describe.**

Frustrated that I can't control the quality of the pngs that are exported when running:

```
npx slidev export --format png
```

**Describe the solution you'd like**

I would like to be able to control the quality via a feature flag of some sort

**Comment by antfu** [comment]
I think we could have an option to change the resolutions on exporting. PR welcome if someone wants to work on it

**Comment by KermanX** [comment]
According to https://playwright.dev/docs/api/class-page#page-screenshot-option-quality, exporting in PNG format does not support the `quality` option (JPEG is OK):

<img width="450" alt="image" src="https://github.com/slidevjs/slidev/assets/63178754/910abed2-75d5-4946-812e-f333ac56cec9">

Perhaps what @juanrgon needs is a feature to zoom in to make the exported image clearer.

**Comment by KermanX** [comment]
I think 1eaf92a (PR #1274) is what this issue requests. Close this for now.
