### ISSUE TITLE
Basic accessibility like keyboard navigation (on the public facing slides)

### ISSUE THREAD

**Issue by BogdanCerovac** [slidevjs/slidev#1280]
**Describe the bug**
Currently only mouse reveals buttons in the (bottom) navigation, if user wants to use keyboard buttons remain hidden.

**To Reproduce**
Use the tab key to reach the buttons in the public facing slides, check where the focus is (in the code, you can use `document.activeElement` in the browser developer tools console

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (also Edge and Firefox, it is crossbrowser issue)
 - Slidev version: 0.47.4
 
 **Possible fix**
 I will have to dig into code to verify this, but it seems that tailwind focus-within (https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-classes) could be used to set opacity to 100 (current classes used are `opacity-0 hover:opacity-100 opacity-100`).

**Comment by Goketech** [comment]
@KermanX I made a pr to fix this issue
https://github.com/slidevjs/slidev/pull/1857
