### ISSUE TITLE
Add support for making charts

### ISSUE THREAD

**Issue by rolisz** [slidevjs/slidev#129]
Something like https://github.com/highcharts/highcharts-vue can be used, but it would be nice if it were built in to slidev.

**Comment by antfu** [comment]
Not sure, but probably no. Making charts is kinda a visual and opinionated things, and might also depends on your data's format, or specific professional fields to make different charts. There are many chart libraries with different strength and trade-offs, and I don't think we have one that covers all the use cases. Meanwhile, it's fairly easy to install one on the user side. That said, it might not be a good idea to have one built-in. Thanks for bringing this up.

**Comment by crazyn2** [comment]
how to install one on the user side
