### ISSUE TITLE
Can't use regular clicks on temporal form fields in slides

### ISSUE THREAD

**Issue by tdd** [slidevjs/slidev#1292]
**Describe the bug**

Temporal form input fields (e.g. `input type="date"`) suffer from some wider-scope click interception or something, so clicks on their right-hand icons, that are supposed to trigger their picker UI, are ineffective. (On OSX for instance you'd have to Option+Down to get their picker UI.)

Also, when the picker UI is open by keyboard and we click anywhere in the slide, it triggers a fast-forward navigation to the end of the deck! And later attempts to go back are foiled, the fast-forward continues!

**To Reproduce**
1. Go to https://tdd.github.io/confoo-html/10
2. Click on any of the fields' right-hand icons
3. See there is no opening behavior
4. Open it by keyboard (e.g. OSX: Option+Down)
5. Click anywhere in the slide outside the picker
6. See the fast-forward to end

**Desktop (please complete the following information):**
 - OS: OSX Sonoma 14.3
 - Browser: Brave 1.62.162 / Chrome 121
 - Slidev version: 0.48.0-beta.0

**Comment by tdd** [comment]
Hey @KermanX, thanks for looking into this.

I'm not so sure about your lead, though.

Clicks seem to work fine for most of my other demos in these slides, like focusing fields, clicking buttons, etc. The issues you mention seem to relate to widespread click banning? That'd prevent any kind of click within my slides, wouldn't it?

I only have an issue with date/time-related inputs' right-hand icons, that are supposed to trigger the dropdown.

**Comment by tdd** [comment]
Hey @KermanX your MDN Playground repro is great, it matches my experience, but I still don't understand how that lets clicks through for other bits of my UI, such as the fields themselves, buttons, etc. Odd.

**Comment by KermanX** [comment]
It seems that this has been fixed via 4cf8d6ec6cce53065821d3c662e8f07b8f6cfc1f in #1330
