### ISSUE TITLE
Emojis are rendered in black-only on PDF export. Presentation and PNG Export produces correct result.

### ISSUE THREAD

**Issue by lmu-babelo** [slidevjs/slidev#1296]
# Describe the bug:
The emojis on slide 2 of the example slides get rendered incorrectly on PDF export. The same happens for custom slides with emojis. Only their silhouette gets rendered in all black. The correct result is obtained when rendering to PNG or in the presentation mode in the browser.

As it is a common use case, to provide lecture or presentation slides as PDF to participants, this issue is quite severe and hinders adapting slidev instead of Powerpoint or Latex Beamer for lectures and presentations.

# PDF export of example slide 2 (incorrect):
![Screenshot from 2024-02-14 13-32-58](https://github.com/slidevjs/slidev/assets/134196837/72838c2e-b512-4772-8854-ff3773c1f597)
# PNG export of example slide 2 (correct):
![002](https://github.com/slidevjs/slidev/assets/134196837/cd11d533-8190-458c-b9f4-b981ab285306)

# Suggestion for a possible way to fix:
As the emojis work on PNG export, a fix could be to 
- export each emoji with the method used in PNG export and 
- embed the exported emoji as image in the PDF instead of as character.

Then the export can circumvent the malfunction of the PDF export method regarding emojis as character.

# To Reproduce:
1. create new slidev project with "npm init slidev" (I have chosen yarn as package manager)
2. export slide with "yarn export"
3. open 2nd example slide in the exported PDF

# Desktop (please complete the following information):
 - OS: Ubuntu 22.04.
 - Browser: Mozilla Firefox 122.0.1
 - Slidev version: 0.47.4
 - playwright-chromium: 1.41.2
 - theme @slidev/theme-seriph
 - css engine unocss

**Comment by KermanX** [comment]
Cannot reproduce on Windows.

Could you upload the exported PDF? It seems that this is a bug with your PDF viewer, according https://askubuntu.com/questions/1279100/emoji-disappear-when-i-print-export-to-pdf-or-download-a-pdf-after-update-to-2

**Comment by lmu-babelo** [comment]
Yes, could be that the issue is with the Ubuntu default PDF Viewer.
Here is the export:
[slides-export.pdf](https://github.com/slidevjs/slidev/files/14281331/slides-export.pdf)

**Comment by KermanX** [comment]
This PDF looks fine on my computer:
<img width="216" alt="image" src="https://github.com/slidevjs/slidev/assets/63178754/adcc5d17-a57e-4de1-889f-5cf16853034f">

Thanks for your report.
