### ISSUE TITLE
Attribute Inheritance at layout components cause problems

### ISSUE THREAD

**Issue by KermanX** [slidevjs/slidev#1303]
### Current Behavior

Currently, all the frontmatter is passed as props to the layout component via `v-bind="frontmatter"`:

https://github.com/slidevjs/slidev/blob/81b28c2edb12b80d186796be8565e94344b00ab1/packages/slidev/node/plugins/loaders.ts#L496

This is problematic, because the props not defined in the layout component are considered attributes, and are automatically added to the slide's root element. For example, the first slide of the demo is rendered to:
![image](https://github.com/slidevjs/slidev/assets/63178754/2b9a05a0-1bdc-4611-8270-893de2522bc1)
Most of the unwanted attributes are effectless, but some cause unwanted behavior, like `title` in the above example.

Besides, some attributes match UnoCSS classes, for example, `scale="1"`, which means `transform: scale(0.01)`😭

### Expected Behavior

Among the entries of the frontmatter, only `class`, `style`, `id` and defined props should be passed to the layout component.

### Unsuccessful Solutions

1. `defineOption({ inheritAttrs: true })`
  It is hard to add this line to all the layout components, and this will also prevent `class` from fallthroughing to the root element.

2. change `v-bind="frontmatter"` into `:frontmatter="frontmatter"`
  This will break existing layout components.

3. change `v-bind="frontmatter"` into `v-bind="pickProps(InjectedLayout, frontmatter)"`
    ```ts
    function pickProps(component, frontmatter) {
      return objectPick(frontmatter, [...component.DEFINED_PROPS, 'class', 'style'])
    }
    ```
    But there seems to be no `component.DEFINED_PROPS`.

**Comment by antfu** [comment]
I think we could have a hard-coded blocklist of attributes remove from props, and always pass extra `:frontmatter="frontmatter"` for full meta info.
