### ISSUE TITLE
`disabled: true` removes slides at the end of a presentation

### ISSUE THREAD

**Issue by openscript** [slidevjs/slidev#1310]
**Describe the bug**

`disabled: true` in a slides frontmatter removes slides at the end of the presentation and also breaks hot reload.

[Kooha-2024-02-19-21-19-34.webm](https://github.com/slidevjs/slidev/assets/1105080/9c758ac4-0298-4eab-844b-529306f01eee)

**To Reproduce**
1. Clone https://github.com/openscript/slidev-reproduction
2. Run with `pnpm dev`

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser: Firefox 122 (but it happens in other browsers as well) 
 - Slidev version: 0.47.5

**Comment by KermanX** [comment]
I think this has been fixed in `v0.48.0-beta.3` via #1305

**Comment by openscript** [comment]
You are right!
Unfortunately I ran into other bugs with the beta, that code blocks are visible before the necessary click happens. Should I open a new issue for this or is this already in progress?

Thank you so much for your efforts! :)

**Comment by KermanX** [comment]
I think you can open a new issue about the code blocks
