### ISSUE TITLE
Feature: animations to code-blocks

### ISSUE THREAD

**Issue by kharann** [slidevjs/slidev#132]
This isn't really an "essential" feature, but i think that animations in the style of [code-surfer](https://github.com/pomber/code-surfer) would be really cool.

It has some cool features such as split-view with highlighting lines between two code-blocks at the same time with each step and some nice animations with fade-in, fade-out and code-lines sliding in and out. 

Also the full page-view of a code-block with a description box which changes per step is also kinda cool to have.

Great project by the way! It looks super clean :)

**Comment by antfu** [comment]
That's interesting. Thanks for sharing. Shame it's on react, but if anyone interested in make a Vue port, I am happy to have it included! Thanks
