### ISSUE TITLE
Icons not found

### ISSUE THREAD

**Issue by carlogarro** [slidevjs/slidev#1323]
**Describe the bug**
I am trying to add icons to my slides, but it is not working. I am using the component as in the guide:
`<uim-rocket class="text-3xl text-orange-400 animate-ping" />`

And the next error appears:
`Internal server error: Icon 'uim/rocket' not found`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox 
 - Slidev version: v0.48.0-beta.5

**Comment by KermanX** [comment]
Install  `npm i @iconify-json/uim` manually can fix this.

**Comment by KermanX** [comment]
Docs updated
