### ISSUE TITLE
After migration, failed to load markdown-it-admon plugin

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1325]
**Describe the bug**
I use markdown-it-admon plugin to render admonitions like this:

```
!!! tip
    this is a tip
```

will be rendered like:

<img width="389" alt="图片" src="https://github.com/slidevjs/slidev/assets/7206696/02961b5b-a582-492e-90f0-7af4bb4f8d33">

this has been worked at slidev v0.42.11. After upgrade slidev to 0.48.beta, I'll got errors like "  throw Error('Dynamic require of "' + x + '" is not supported');"

**To Reproduce**
1. install brand new slidev by `npm init slidev@latest`
2. install markdown-it-admon by `npm i markdown-it-admon`
3. put the following configure under project root, to load markdown-it-admon:
```
// vite.config.ts
```
4. edit slides.md as the following:
```
---
theme: seriph
class: text-center
title: Welcome to Slidev
---

!!! tip
    This is a admonition
```
5. start serving by `npx slidev slides.md`, it will reports:
```
added 1 package in 2m
(base) aaron:slidev aaronyang$ npx slidev slides.md 
file:///Users/aaronyang/workspace/test/slidev/vite.config.ts.timestamp-1708566464370-0876d122192b4.mjs:6
  throw Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "markdown-it-admon" is not supported
    at file:///Users/aaronyang/workspace/test/slidev/vite.config.ts.timestamp-1708566464370-0876d122192b4.mjs:6:9
    at Object.markdownItSetup (file:///Users/aaronyang/workspace/test/slidev/vite.config.ts.timestamp-1708566464370-0876d122192b4.mjs:30:16)
    at Object.markdownItSetup (file:///Users/aaronyang/workspace/test/slidev/node_modules/@slidev/cli/dist/chunk-U44GKKNH.mjs:3975:35)
    at createMarkdown (file:///Users/aaronyang/workspace/test/slidev/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js:144:17)
    at unpluginFactory (file:///Users/aaronyang/workspace/test/slidev/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js:314:25)
    at file:///Users/aaronyang/workspace/test/slidev/node_modules/unplugin/dist/index.mjs:1571:32
    at createMarkdownPlugin (file:///Users/aaronyang/workspace/test/slidev/node_modules/@slidev/cli/dist/chunk-U44GKKNH.mjs:3950:10)
    at async ViteSlidevPlugin (file:///Users/aaronyang/workspace/test/slidev/node_modules/@slidev/cli/dist/chunk-U44GKKNH.mjs:4230:26)
    at async createServer (file:///Users/aaronyang/workspace/test/slidev/node_modules/@slidev/cli/dist/chunk-CV7O37IO.mjs:41:11)
    at async initServer (file:///Users/aaronyang/workspace/test/slidev/node_modules/@slidev/cli/dist/cli.mjs:105:16)
```

I understand this may caused by so-called cjs to ems transition, but I don't understand how to workaround this, and markdown-it-admon has been released years ago, seems not maintained anymore.

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Slidev version:

**Comment by KermanX** [comment]
Could you provide the full `vite.config.ts`?

**Comment by zillionare** [comment]
sorry, forgot to paste the content of vite config.

Attached pls find workable example, both 0.48 and 0.42 included. 
[Archive.zip](https://github.com/slidevjs/slidev/files/14370967/Archive.zip)

node_modules are stripped.

when you run npx slidev slides under 0.42 folder, you'll got:

<img width="623" alt="图片" src="https://github.com/slidevjs/slidev/assets/7206696/a39a1626-e304-40f4-ae7d-90dd272fe729">

run same cmd under 0.48 folder, you'll got:

![图片](https://github.com/slidevjs/slidev/assets/7206696/6e75a864-6c44-49d1-bb22-6ffc60eca8be)

sorry for not providing reproducible sample project at very first time. I'm so unfamiliar with web tech stack.
And thanks for handling this case!

**Comment by KermanX** [comment]
1. Use ESM import statement to import the plugin:

```
// vite.config.ts

import MdItAdmon from 'markdown-it-admon';

...

        markdown: {
            /* markdown-it options */
            markdownItSetup(md) {
                /* custom markdown-it plugins */
                md.use(MdItAdmon);
            }
        }
```

2.  Add `/styles/index.ts` with the following content:

```ts
import "markdown-it-admon/styles/admonition.css"
```

**Comment by zillionare** [comment]
Verified.

I didn't know that I can use any name to carry what export from markdown-it-admon before. That's why I'm stuck. 

Thanks again for working on my special case.
