### ISSUE TITLE
support notes navigation

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1333]
**Is your feature request related to a problem? Please describe.**
在讲课中，notes常常会很长。基本上每一个动作(click)，都会对应一大段讲解。如果动作过多，notes太长，在后面的click执行后，有时候会出现一时之间找不到对应的notes的情况。

尽管可以把一个包含多个动作的slide分解为多个slide，从而缓解这种定位问题，但是，也有很多情况，把这些动作组织在一个页面更合适。

**Describe the solution you'd like**
我通常在notes中，插入 html标题来区分每个动作对应的notes。幸运的是，slidev也支持markdown标记。所以，我常常这样写：

```
<v-clicks>
## problem 1
## problem 2
</v-clicks>

<!--
这节课我们将介绍...

## click1 problem1
解决问题的关键，是找到关键的问题...

## click2 problem2
我们继续
-->

这样在每个click点击后，我会通过导航栏上的clicks，来迅速找到notes中对因的click (因为是html header, 所以字体也大一些）。

需要的功能是，如果notes部分存在CLICK1开头的html header标签，则根据当前的clicks=?，自动滚动该标签到notes窗口的顶部（或者可视窗口）。
```
**Describe alternatives you've considered**
如果这个功能不符合slidev的roadmap，能否简单告我们自己该如何实现？谢谢！

**Comment by antfu** [comment]
That's a good idea! I found it would be useful to myself as well - I will see what we can do to support that
