### ISSUE TITLE
Sli.dev and twoslash cause strange behavior

### ISSUE THREAD

**Issue by kravetsone** [slidevjs/slidev#1349]
**Describe the bug**
When I use twoslash, they statically appear on 1 slide as shown in the screenshot below.... (tested on my custom and default theme)
[Presentation repo](https://github.com/kravetsone/kravetsone/tree/main/presentations/Elysia)

![image](https://github.com/slidevjs/slidev/assets/57632712/a5f9f9a5-0922-4a8a-a024-03029ef7a254)

![image](https://github.com/slidevjs/slidev/assets/57632712/0ccde2d8-f579-4295-b7eb-990f7bc2ce20)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: 122.0.6261.69
 - Slidev version: ^0.47.5

**Comment by antfu** [comment]
Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

**Comment by kravetsone** [comment]
> Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

https://stackblitz.com/edit/slidev-btd8ya?file=slides.md


❯ npm list
slidev-btd8ya@ /home/projects/slidev-btd8ya
+-- @slidev/cli@0.48.0-beta.19
+-- @slidev/theme-default@0.25.0
`-- @slidev/theme-seriph@0.25.0

**Comment by kravetsone** [comment]
> Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

any updates?

**Comment by kravetsone** [comment]
> Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

By the way, your presentations are very cool! Don't you share their source code?

**Comment by kovsu** [comment]
@kravetsone 👉 [here](https://github.com/antfu/talks)

**Comment by kravetsone** [comment]
> Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

 twoslash turned white on beta.... By the way, everything is in place when exporting to PDF

![image](https://github.com/slidevjs/slidev/assets/57632712/d640e456-834d-402b-a4e2-89ff0f00139e)
![image](https://github.com/slidevjs/slidev/assets/57632712/b323b804-a11e-4b5b-8b67-2bfed664ea51)

**Comment by kravetsone** [comment]
> Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

Can you fix it today? It's important to me)

**Comment by KermanX** [comment]
> Can you fix it today? It's important to me)

I will try to fix this later. But it seems a little bit hard.

**Comment by kravetsone** [comment]
> > Can you fix it today? It's important to me)
> 
> I will try to fix this later. But it seems a little bit hard.

Thank you! Slidev is awesome...

**Comment by KermanX** [comment]
I spent 1 hour on this but made no actual progress. However, there is a workaround which hides all the popovers when the current slide has no popover:

1. add the following to your `<root>/styles.css`:

```css
.v-popper__popper.v-popper--theme-twoslash {
  display: none;
}
```

2. add the following to your `<root>/components/ShowTwoslash.vue`:

```vue
<script setup>
import { computed } from 'vue'
import { useStyleTag } from '@vueuse/core'

useStyleTag(computed(() => $page.value === $slidev.nav.currentPage ? `
.v-popper__popper.v-popper--theme-twoslash {
  display: block !important;
}` : ''))
</script>

<template>
  <div/>
</template>
```

3. if you want to enable twoslash popovers on a slide, add the following to that slide:

```md
<ShowTwoslash />
```

**Comment by kravetsone** [comment]
> I spent 1 hour on this but made no actual progress. (It's really hard!) However, there is a workaround that can hide all the popovers when the current slide doesn't need them.
> 
> 1. add the following to your `<root>/styles.css`:
> 
> ```css
> .v-popper__popper.v-popper--theme-twoslash {
>   display: none;
> }
> ```
> 
> 2. add the following to your `<root>/components/ShowTwoslash.vue`:
> 
> ```
> <script setup>
> import { computed } from 'vue'
> import { useStyleTag } from '@vueuse/core'
> 
> useStyleTag(computed(() =>
>   ['slide', 'presenter'].includes($renderContext.value) && $page.value === $slidev.nav.currentPage ? `
> .v-popper__popper.v-popper--theme-twoslash {
>   display: block !important;
> }` : ''))
> </script>
> 
> <template>
>   <div />
> </template>
> ```
> 
> 3. if you want to enable Twoslash popovers on a specific slide, add the following code to that slide:
> 
> ```
> <ShowTwoslash />
> ```


It hides these elements on other slides but they are still on the edge))

well, I'll wait! Thanks for the work!
