### ISSUE TITLE
Error going from overview page to slide page

### ISSUE THREAD

**Issue by kamuiiiii** [slidevjs/slidev#1360]
**Describe the bug**

**To Reproduce**
1. Go to '/overview' page
2. Click on slide or 'Play in new tab'
3. It always redirect to page '/1'

**Comment by KermanX** [comment]
Cannot reproduce on the demo slide. Could you help provide a minimal reproduction? thanks a lot

**Comment by kamuiiiii** [comment]
Cannot be reproduced in codesanbox
