### ISSUE TITLE
Images from the image-left / image-right are not getting bundled for static hosting

### ISSUE THREAD

**Issue by alexandruradovici** [slidevjs/slidev#1361]
**Describe the bug**
When using the `imag-left` or `image-right` layout, the image specified in the `image` parameter is not bundled for static hosting and is not exported to pdf. There is no error displayed (by the build system) if the image filename or path is wrong (it points to a file that does not exists).

**To Reproduce**
1. Write a slide using the `image-right` template.
2. Copy a file named `image.png` into a folder called `images` that is in the current slide's folder.
3. Use the image for the `image` tag: `image: /images/image.png`.
4. Build for static hosting
5. The image is not copied and is not displayed.

The image is displayed is displayed in development mode.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox or Chrome
 - Slidev version: 0.48.0-beta.2

**Comment by KermanX** [comment]
As a workaround, you can use [the public directory](https://sli.dev/custom/directory-structure#public) here:

Store the image in `/public/images/image.png` folder, and set `image: /images/image.png` in the frontmatter.

**Comment by antoniomtz** [comment]
the workaround worked for me

**Comment by yedidyar-ni** [comment]
also worked for me.
Thanks!

**Comment by vorburger** [comment]
This also affects `layout: image`, e.g. something like this:

```
---
layout: image
image: images/wordcloud.svg
----
```

I had initially worked (hacked) around this [using a `ln -s ../images/ dist/images`](https://github.com/vorburger/LearningMachineLearning/commit/20bbefdc2de39e7ce5210a94f773c22fb8e86b3d); but moving `image/*` into a new created `public/` is a better solution.

Perhaps the default MD generated by `npm init slidev@latest` could illustrate this and include a `public/image/example.png` kind of illustration?
