### ISSUE TITLE
Support for dynamic aspect ratio

### ISSUE THREAD

**Issue by stackoverfloweth** [slidevjs/slidev#1366]
When I first understood what slidev was, one of the things I thought was the most excited is the idea that I could host my presentation and present it on any device. 

In the starter example, and when I start a new project, the aspect ratio seems locked at 16:9

I'm still very new to slidev, so my attempts to resolve this myself are limited, I tried adjusting scale and I tried setting `canvasWidth` to 100vw.

**Comment by antfu** [comment]
https://github.com/slidevjs/slidev/blob/95660c04baee2e1ae5d43e9963e09082e6405259/packages/types/src/config.ts#L106-L119

**Comment by stackoverfloweth** [comment]
> https://github.com/slidevjs/slidev/blob/95660c04baee2e1ae5d43e9963e09082e6405259/packages/types/src/config.ts#L106-L119

@antfu thanks for the quick reply.  I see that this verifies the default behavior I am seeing but I'm not seeing how I can use that to solve the feature request of a "dynamic" experience like what we'd expect from a responsive webpage where height/width is whatever the browser is and it doesn't add the black bars around the content.

**Comment by antfu** [comment]
I don't really sure the use case of "dynamic" aspect ratio. As it's kinda of defeating the purpose of having slides, that will make the layout breaks on different devices. In that case you might directly use a web page then?

**Comment by stackoverfloweth** [comment]
> I don't really sure the use case of "dynamic" aspect ratio. As it's kinda of defeating the purpose of having slides, that will make the layout breaks on different devices. In that case you might directly use a web page then?

Fair enough. I think using a web page isn't a good solution since I lose the ease of building and all the other great features of slidev. Do you think it would be a difficult change for me to remove the aspect ratio contraints with css? Or perhaps if I fork the repo?

**Comment by antfu** [comment]
Since it's not hard, I added a3fdfc8 so that you can override the value of `import { slideAspect } from '@slidev/client/env.ts'` at runtime to change it - that said, I would personally not recommend doing that so use as your own risk.

**Comment by CJohnDesign** [comment]
I'm interested in making it mobile responsive. Just leaving a comment in case anyone else is interested.

**Comment by man-trackunit** [comment]
I come from the (much simpler) AI Presenter app but am starting to grow out of it. It works so well to have responsive slides though—So I for sure thought Slidev would work the same. Didn't even consider the possibility that it wouldn't 😅
Any ways. Lovely to use in general but also wanted to flag that I too think it would be _great_ with dynamic aspect ratio.
