### ISSUE TITLE
Cannot access '_rawRoutes' before initialization

### ISSUE THREAD

**Issue by pdcxs** [slidevjs/slidev#137]
I use windows 10, npm 7.13.0, yarn 1.22.10, when I run the default project, browser gives out the following error and shows a blank page:
```
Uncaught ReferenceError: Cannot access '_rawRoutes' before initialization
    at routes.ts:6
```

**Comment by antfu** [comment]
Can't reproduce on my side, can you share a minimal reproduction? Thanks

**Comment by pdcxs** [comment]
> Can't reproduce on my side, can you share a minimal reproduction? Thanks

1） npm init slidev

Need to install the following packages:
  create-slidev
Ok to proceed? (y) y
...
Project name: test,
...
Choose the agent: yarn
yarn install v1.22.10
...

2) after execute the previous command, browser automatically open and shows a blank page.

**Comment by antfu** [comment]
What's your slidev version? Tried `npm init slidev@latest`?

**Comment by pdcxs** [comment]
> What's your slidev version? Tried `npm init slidev@latest`?

I tried `npm init slidev@latest`, but unluckily, it still doesn't work. The version of slidev is `v0.11.2`

**Comment by pdcxs** [comment]
I tried use slidev on WSL2, Ubuntu. It finally works. But on windows, it still cannot work. Sadly.

**Comment by antfu** [comment]
I don't have Windows PC to testing on this, help wanted. Thanks!

**Comment by antfu** [comment]
Just tested out on Windows with the Command Prompts, it works fine for me.
