### ISSUE TITLE
Add Guide To Use `mhchem` Katex Extension In Documentation. 

### ISSUE THREAD

**Issue by Craneplayz** [slidevjs/slidev#1371]
**Is your feature request related to a problem? Please describe.**
`mhchem` is a commonly used extension in Katex, and I think it should be beneficial to notion how to use it in Slidev

**Describe the solution you'd like**
Add a new file called `vite.config.ts` and add the following code snippet. 

```ts
import 'katex/contrib/mhchem'

export default {}
```
Taken from: https://github.com/slidevjs/slidev/issues/928#issuecomment-1571929838

**Comment by John98Zakaria** [comment]
Can you give me a example chemical equation, and I'll happy create a docs pr

**Comment by Craneplayz** [comment]
> Can you give me an example for a chemical equation, and I'll happly create a docs pr

$$
\delta_{B4} x + \delta_{B3}(1-x) = \delta_{\sum B}
$$

Sure, here's one about boric acid equilibrium using `mhchem`

**Comment by John98Zakaria** [comment]
@Craneplayz Can you read it and tell me if it is missing anything you want mentioned ?
https://github.com/slidevjs/slidev/pull/1400
