### ISSUE TITLE
RFC: Built-in Python Code runner

### ISSUE THREAD

**Issue by John98Zakaria** [slidevjs/slidev#1405]
Python is in the fortunate position that it is available in the browser thanks to https://github.com/pyscript/pyscript.

I am open to adding it as a custom coderunner to slidev, if the idea is greenlit :)

**Comment by antfu** [comment]
Thank you for bringing this up. That's the reason we bring up the custom code runner setup - which would allow you to provide your own runner. We don't want to introduce too many dependencies for a feature that the majority of the Slidev users might not need. In addition, even for Python users, the behaviour misalignment between cpython and pyscript might not be desired - I think it's better to have users to implement that. If needed, an community maintained addon or so might make it easier.
