### ISSUE TITLE
`view-transition` regression

### ISSUE THREAD

**Issue by QuentinRoy** [slidevjs/slidev#1408]
**Describe the bug**

view-transition triggers additional clicks (often 1, sometimes more) since slidev v0.48.x

**To Reproduce**
1. Startup a new project
```sh
pnpm create slidev
```
2. Replace `slides.md` with the following

```md
---
theme: default
mdc: true
---

# Intro

---
transition: view-transition
mdc: true
---


# Slide 1
Test

[Some element]{ .view-transition-test }

---
mdc: true
---

# Slide 2
Test

Some other element

[Some element]{ .view-transition-test }
```

Notice that the transition from Slide 1 to Slide 2 now requires two steps, the first one triggering a fade out then fade in again of Slide 1. This wasn't the case in Slidev 0.46.

https://github.com/slidevjs/slidev/assets/728801/8cb42700-f831-4485-a970-0f47ab07c311

**Desktop (please complete the following information):**

- OS: macOS 14.3.1 
- Browser: Arc and Chrome (other browsers don't support view-transition)
- Slidev version: 0.48.1

**Comment by KermanX** [comment]
As a workaround, you can add `transition: view-transition` to the headmatter (the first slide's frontmatter).

**Comment by QuentinRoy** [comment]
@KermanX I do not think it is that simple. I have tried in a project of mine, and I still got the "blink" effect on a slide, and another one ended up looping on itself indefinitely. I haven't really be able to isolate what causes it, but I'll try to provide a minimal reproducible example when I find some time.

**Comment by KermanX** [comment]
> @KermanX I do not think it is that simple. I have tried in a project of mine, and I still got the "blink" effect on a slide, and another one ended up looping on itself indefinitely. I haven't really be able to isolate what causes it, but I'll try to provide a minimal reproducible example when I find some time.

I agree with you. The finished part of #1411 may has fixed these navigation problems.
