### ISSUE TITLE
In included example slides, slide 10 with Mermaid diagrams doesn't work: "An error occurred on this slide"

### ISSUE THREAD

**Issue by janroden** [slidevjs/slidev#1409]
**Describe the bug**

For the included example slides, slide 10 with the Mermaid diagrams doesn't show the content of the slide, but instead an error "An error occurred on this slide. Check the terminal for more information."

But the terminal doesn't show an error.

The other slides of the example slide deck work as expected.

Same behavior in both Firefox and Chrome.

When I remove the mermaid code blocks in the Markdown for slide 10, its content shows up in the browser and the error is gone.

**To Reproduce**

1. Install Slidev globally with `npm i -g @slidev/cli`
2. When prompted, choose to create example file and add the seriph theme
3. Run `npx slidev`
4. In browser, open `http://localhost:3030/`
5. Observe how all slides show up as expected, except for slide 10 with the Mermaid diagrams, which shows the error instead of the slide content (see above)

**Desktop:**

- OS: Linux (Kernel: 5.10.0-28-amd64 [5.10.209-2] x86_64 bits; Distro: MX-21.3_x64 Wildflower October 20  202; base: Debian GNU/Linux 11 (bullseye))
- Browser: Firefox 123.0.1 (64-bit) (but also happens the same in Chrome 122.0.6261.111 (Official Build) (64-bit))
- Slidev version: v0.48.1 (global)

**Comment by KermanX** [comment]
It seems that the way Slidev includes dependency into `optimizeDeps` (for example, `@slidev/cli > @slidev/client > lz-string`) not working when installed globally.

**Comment by kamuiiiii** [comment]
https://vitejs.dev/config/server-options.html#server-fs-strict
Setting server `strict:false` seems to solve this problem

**Comment by jxpeng98** [comment]
After update to `0.48.2`, I still have the same issue with mermaid.

Here are the outputs:
```
Failed to resolve dependency: @slidev/cli > @slidev/client > @iconify-json/svg-spinners, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > @shikijs/monaco, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > @slidev/rough-notation, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > @typescript/ata, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > shiki-magic-move, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > shiki-magic-move/vue, present in 'optimizeDeps.include'
```

<img width="579" alt="image" src="https://github.com/slidevjs/slidev/assets/83734772/c1f10731-1ade-4ee7-b1f1-95525b83380f">
