### ISSUE TITLE
Exported pdf with magic-move md blocks only shows the first version of the code

### ISSUE THREAD

**Issue by QuentinRoy** [slidevjs/slidev#1422]
**Describe the bug**
When using shiki magic, the exported pdf will only show the initial version of the code (without click) while other animations are usually exported on the last click.

**To Reproduce**

1. Run
```sh
pnpm create slidev test
cd test
pnpm upgrade --latest  # pnpm create slidev doesn't use latest slidev version
pnpm add -D playwright-chromium
```
3. Replace `slides.md` with:

`````md
---
highlighter: shiki

layout: default
---

````md magic-move
```js
const person = {};
```

```js
const person = {
  name: "John",
  age: 30,
  city: "New York",
};
```
````
`````

4. `pnpm export`

[slides-export.pdf](https://github.com/slidevjs/slidev/files/14584753/slides-export.pdf)

I would have expected the result to be the following:

[slides-export.pdf](https://github.com/slidevjs/slidev/files/14584771/slides-export.pdf)

**Desktop (please complete the following information):**

- OS: mac OS 14.3.1
- Browser: NA
- Slidev version: 0.48.2

**Comment by KermanX** [comment]
It seems that the clicks system works fine. But `ShikiMagicMovePrecompiled` doesn't reflect the current step index in the print mode because of some unknown reason.

**Comment by azat-io** [comment]
I have the same problem.

Slidev v0.50.0-beta.5
playwright-chromium v1.49.0

I use this command:

```
slidev export --with-clicks --wait 5000 --dark
```

Shiki Magic Move:

```
dependencies:
@slidev/cli 0.50.0-beta.5
├─┬ @slidev/client 0.50.0-beta.5
│ └── shiki-magic-move 0.5.0
└── shiki-magic-move 0.5.0
```

**Comment by nfogh** [comment]
Same here:
slidev export --with-clicks --dark

I did some triaging:

0.50.0-beta.10 faulty
0.49.29 faulty
0.49.21 faulty
0.49.17 faulty
0.49.15 faulty
0.49.14 couldnt install with npm
0.49.13 faulty (blank slides)
0.49.12 faulty (blank slides)
0.49.11 good
0.48.9 good (but no color highlighting)

Seems something happened between 0.49.11 and 0.49.15 that caused this.

**Comment by azat-io** [comment]
@antfu Could you reopen this issue?
