### ISSUE TITLE
Official local video support (`SlidevVideo`?)

### ISSUE THREAD

**Issue by QuentinRoy** [slidevjs/slidev#1423]
**Is your feature request related to a problem? Please describe.**

I found myself often using the `SlideVideo` component because I'd rather self host my videos rather than relying on youtube. I noticed however this component is not documented. Is it on purpose? 

When including videos into slides (using 

**Describe the solution you'd like**
I'd love official local video support. `SlidevVideo` seems to (almost) perfectly meet my needs.

**Comment by antfu** [comment]
It's more like a missing docs, PR welcome if you are interested in helping to write some docs for it

**Comment by QuentinRoy** [comment]
I added it on my todo list. However I'm not likely to be able to do it soon :-(.
