### ISSUE TITLE
Feature request: Taking questions through a dedicated website

### ISSUE THREAD

**Issue by UnlimitedCookies** [slidevjs/slidev#143]
This might be too much to ask for, but it would be awesome to have the ability to accept questions via a simple website with a form, similar to how Google Slides implemented this. There would be a QR code and link to this website in the presentation slide. The presenter then should be able to select certain questions to display.

**Comment by UnlimitedCookies** [comment]
That would a possibility, but I don't know of any service yet that would provide this functionality. It could also be a built-in functionality, which would just use the same web server as the presentation does. This would for example work if you self-host slidev on a public facing web server or in case there ever will be a hosted slidev (similar to google docs). [If the viewers are in the same local network this could also work]
(Even though it might not always be a good idea to expose the presentation server, so that others can try to interfere with it / get it to crash)

**Comment by antfu** [comment]
It's better to not expose your dev server to the open web. And this sounds like a pretty user side thing, I'd prefer to not included built-in to keep Slidev simple, especially it's hard to find a good solutions handling most of the cases.

So, still, a public services with iframe might be a better option to me, as well as the separations of concerns. If there it's an good service for that, maybe could be a good chance for you to make one? If so, I am happy to have section in docs recommending to integrate with those services for this features.

Thanks for bringing this up. Close for now.
