### ISSUE TITLE
Failed to install slidev globally on MacOS

### ISSUE THREAD

**Issue by gvariable** [slidevjs/slidev#1440]
**Describe the bug**
I encountered an issue while attempting to install Slidev globally using npm. Despite having npm (version 10.5.0) installed via Homebrew, along with Node.js (version 21.7.1), the installation process for Slidev failed.

**To Reproduce**
1. `brew install npm`
2. `npm i -g @slidev/cli`
3. Then conflict occurs
<img width="808" alt="image" src="https://github.com/slidevjs/slidev/assets/57946012/280c94fc-a01b-4783-935f-c978d0c1eadc">
4. `npx slidev`
<img width="1478" alt="image" src="https://github.com/slidevjs/slidev/assets/57946012/8f74c3b6-d123-4b70-9b20-cca3dc592d87">

**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.1.1
- Browser: Safari
- Slidev version: 0.48.3
- Node version: 21.7.1
- Npm version: 10.5.0

**Comment by KermanX** [comment]
The waring in the installation is expected and not harmful. The error is a bug, also the same as #1409

**Comment by gvariable** [comment]
Oh, I see. Thank you for the swift response.
