### ISSUE TITLE
Unmet peer dependencies, @typescript/ata 0.9.4 x typescript@^4.4.4: found 5.4.2

### ISSUE THREAD

**Issue by Innei** [slidevjs/slidev#1447]
**Describe the bug**

pnpm enables `strict-peer-dependencies` in the latest version, and `@typescript/ata 0.9.4` peers `typescript@^4.4.4`, but `slidev/client`'s typescript version is 5.4.2. so the start template installs deps via pnpm, will get a error.

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @slidev/cli 0.48.3
  └─┬ @slidev/client 0.48.3
    └─┬ @typescript/ata 0.9.4
      └── ✕ unmet peer typescript@^4.4.4: found 5.4.2

hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to a .npmrc file at the root of your project.
```

**To Reproduce**

1. pnpm create slidev@latest
2. use pnpm to install

**To Fix**

1. add `.npmrc` and set `strict-peer-dependencies=false` in the starter template.
2. or, fix the peer deps version

**Desktop (please complete the following information):**

- OS: NA
- Browser: NA
- Slidev version: NA

**Comment by antfu** [comment]
https://github.com/slidevjs/slidev/pull/1448#issuecomment-2008727969

**Comment by KermanX** [comment]
`strict-peer-dependencies` is enabled by default since `pnpm v7` (https://github.com/pnpm/pnpm/pull/4427), but re-disabled in `v7.3.15` (https://github.com/pnpm/pnpm/pull/5499). So updating pnpm to a version larger than `v7.3.15` can fix this.

**Comment by Innei** [comment]
```
pnpm -v
8.15.4
```

My pnpm version is 8.x

**Comment by KermanX** [comment]
tested on pnpm v8.15.1 and v8.15.4 and laetst(v8.15.5), all no error happens
