### ISSUE TITLE
Ability to control scale/font size of code blocks on a global level

### ISSUE THREAD

**Issue by todor-a** [slidevjs/slidev#1449]
**Is your feature request related to a problem? Please describe.**
I was giving out a presentation and received a pretty valid feedback that people in the back couldn't see the code examples.

**Describe the solution you'd like**
A way to control the scale/font size of text inside code blocks.

**Describe alternatives you've considered**
An alternative solution was found [here](https://github.com/slidevjs/slidev/discussions/1443#discussioncomment-8849108).

**Comment by antfu** [comment]
You can override the CSS selector or CSS variables - it's web - you have all the freedom you need :)

**Comment by KermanX** [comment]
The solution was discussed at https://github.com/slidevjs/slidev/discussions/1443. The remaining problem is that we have to use `children:h-15 !children:text-2xl` to control the style, instead of `h-15 !text-2xl`. At first, I thought we could just apply the classes to the inner `pre` of the code block, but it seems to be not a perfect idea because then we can't control the outer `div`'s style.

**Comment by todor-a** [comment]
> You can override the CSS selector or CSS variables - it's web - you have all the freedom you need :)

Absolutely agree. Just thought providing a convenient way to do it globally might be useful?

P.S. I tried zooming in the browser but that did not work either 🤔

**Comment by antfu** [comment]
https://github.com/slidevjs/slidev/blob/5480829fdb2a8b8fa1820713a1d5cec364db72bd/packages/client/styles/vars.css#L6-L7

You can overrides CSS vars with these, isn't that convenient enough?

**Comment by todor-a** [comment]
Looked all over and couldn't find that. Thanks, it is convenient enough. :)

**Comment by antfu** [comment]
We could definitely improve the docs tho :)

**Comment by todor-a** [comment]
I would love to contribute.

**Comment by GarreltMock** [comment]
Thanks for this information. This worked pretty well.
Is it also possible to use this in the Monaco Editor {monaco-run}?

**Comment by Giuseppe499** [comment]
> [slidev/packages/client/styles/vars.css](https://github.com/slidevjs/slidev/blob/5480829fdb2a8b8fa1820713a1d5cec364db72bd/packages/client/styles/vars.css#L6-L7)
> 
> Lines 6 to 7 in [5480829](/slidevjs/slidev/commit/5480829fdb2a8b8fa1820713a1d5cec364db72bd)
>  --slidev-code-font-size: 12px; 
>  --slidev-code-line-height: 18px; 
> 
> You can overrides CSS vars with these, isn't that convenient enough?

Can you explain to me how can I override the  ` --slidev-code-font-size: 12px; `  variable only for one slide?

I tried to use the "Slide Scope Styles" feature as follows

```html
<style>
.slidev-code {
  --slidev-code-font-size: 50px; 
  --slidev-code-line-height: 70px;
  font-size: var(--slidev-code-font-size) !important;
  line-height: var(--slidev-code-line-height) !important;
}
</style>
```

but it did not work.
