### ISSUE TITLE
Add `startClicksCount` to frontmatter options

### ISSUE THREAD

**Issue by kravetsone** [slidevjs/slidev#1452]
**Is your feature request related to a problem? Please describe.**
This is convenient for reused slides with clickable components

Useful for combination with [multiple-entries](https://sli.dev/guide/syntax#multiple-entries) and
[custom-total-clicks-count](https://sli.dev/guide/animations#custom-total-clicks-count)

Usage example:

```yaml
---
src: ./slide-with-clicks.md
clicks: 4
---

---
src: ./another-slide.md
---

---
src: ./slide-with-clicks.md
clicks: 10
startClicksCount: 5
---

---
src: ./another-slide.md
---
```

**Describe the solution you'd like**
Add `startClicksCount` to frontmatter options

**Describe alternatives you've considered**
Idk

**Comment by antfu** [comment]
That's an interesting usage - I don't mind to have it if it's not technically hard. Maybe name it `clicksStart` that could be visually grouped together with `clicks`?

**Comment by kravetsone** [comment]
> That's an interesting usage - I don't mind to have it if it's not technically hard. Maybe name it `clicksStart` that could be visually grouped together with `clicks`?

It's a good name! Does anyone want to do this? I'm just not sure I'm that good at figuring out how to do it) Especially since I don't have much time

I am preparing my first talk and slidev helps me a lot! I want to continue using it)

You are amazing!

**Comment by kravetsone** [comment]
> That's an interesting usage - I don't mind to have it if it's not technically hard. Maybe name it `clicksStart` that could be visually grouped together with `clicks`?

It's a good name! Does anyone want to do this? I'm just not sure I'm that good at figuring out how to do it) Especially since I don't have much time

I am preparing my first talk and slidev helps me a lot! I want to continue using it)

You are amazing!

**Comment by kravetsone** [comment]
> That's an interesting usage - I don't mind to have it if it's not technically hard. Maybe name it `clicksStart` that could be visually grouped together with `clicks`?

it is posible to implement this without frontmatter options?
like workaround
