### ISSUE TITLE
Support "incremental" builds?

### ISSUE THREAD

**Issue by aytey** [slidevjs/slidev#1465]
## Is your feature request related to a problem? Please describe.

My background is as a software engineer who also moonlights (among other things) as a build engineer. Part of the build engineer work is making sure what I work on has a "no-op" builds.

A no-op build means: if you don't change any input, no work needs to be done.

I just did (roughly) the following:

```
npm init slidev@latest
npx slidev build
npx slidev build
```

and the second build _still took 48.98s_ even though none of the inputs (including the slides themselves!) had changed.

## Describe the solution you'd like

Looking at the output of my second (which should have been a no-op) build, I can see that `slidev` did this:

```
vite v5.2.6 building for production...
✓ 1602 modules transformed.
```

It seems like these are artefacts that do not change "run to run", so why does `slidev` regenerate them every time I do a build?

Probably the only thing that does change is `dist/assets/slidev/2-LRp7ZWwo.js` (which is where `slides.md` go), so if all that was regenerated was `dist/assets/slidev/2-LRp7ZWwo.js`, that's probably quite a saving.

## Describe alternatives you've considered

Use `marp` with a `Makefile` with explicitly-specified dependencies 😬

**Comment by aytey** [comment]
> This is not in the responsibilities of Slidev, you can use tools like Makefile or nx to cache the command based on input/output, but what slidev build does is to build the file.
>

Sorry, maybe my point wasn't clear: I don't think a user _can_ do this from the outside.

Let's say I have a rule that depends between `index.html` and `slides.md`, and I change `slides.md`: `slidev build` here builds "1602 modules", when all it should be doing is re-generating `dist/assets/slidev/2-LRp7ZWwo.js`.

Is there some way I can setup `slidev` such that it only builds `dist/assets/slidev/2-LRp7ZWwo.js` and not the rest of the assets?

**Comment by antfu** [comment]
>  all it should be doing is re-generating dist/assets/slidev/2-LRp7ZWwo.js.

It's way easier said than done.

I already made clear that the ROI is not worth it - if you really want that feature, how about giving it a try and sending a PR?

**Comment by aytey** [comment]
> It's way easier said than done.

Sure, I wasn't trivialising it.

> I already made clear that the ROI is not worth it - if you really want that feature, how about giving it a try and sending a PR?

`slidev` isn't actually a fit for my needs; I was raising this issue to point a place where the UX when using this tool could be dramatically improved.

I think I should have replied to this:

> Given that Slidev is not something you run very frequently

Actually, _it is_. I typically write some slides, build them, view them, and edit the markdown again. Viewing the rendered output gives my brain a second chance to go "is this what I mean?".

I use the build process to quickly iterate between markdown and output to make sure stuff is going in the right direction. If the iteration takes 50 seconds to generate some output, that that "quickly iterate" falls apart. I know I am definitely not the only person to do this (very much the same was when you're writing LaTeX -> you build the PDF to check what you've written).

Maybe I am just a very weird use-case for `slidev`.

**Comment by antfu** [comment]
I am confused, why don't you use the dev mode?

**Comment by aytey** [comment]
> I am confused, why don't you use the dev mode?

Err, because I didn't know it existed? 🙈 

I read the documentation here: https://sli.dev/guide/ and was like "oh, I need a HTML file, I guess I need to run `slidev build`".

Is the suggested workflow that I should use `npx slidev` (no `build`)? Does this automatically refresh when I save the input `.md`?

**Comment by antfu** [comment]
It does not even refresh, but hot updates (which happens instantly)

So, I hope you enjoy the 50s -> 50ms improvement then :)

**Comment by aytey** [comment]
> So, I hope you enjoy the 50s -> 50ms improvement then :)

Ah, not much to complain about there then 😄 

Okay, maybe this case should be: "can we make https://sli.dev/guide/ clearer about the correct way to use `npx slidev`"? Apologies if I missed this, but I did *genuinely* try to read the docs to know how to use `slidev`!

**Comment by antfu** [comment]
Isn't https://sli.dev/guide/#command-line-interface clear?

**Comment by aytey** [comment]
> Isn't https://sli.dev/guide/#command-line-interface clear? What do you suggest to improve?

Maybe it should say something like:

```
After running `npx slidev`, a hot-reloadable web server is running; editing
your input markdown will cause the content to be automatically regenerated and
displayed.

`slidev build` and `slidev export` are for export formats, and not typically
used while editing or showing presentations. For these use-cases, typically you
would use `npx slidev` for a quickly iterating on slide content.
```

Basically, as a first time user who is trying to go from "nothing" to "something", I have no idea what `"dev": "slidev", // start dev server` means.

I'm currently a `marp` user and so the whole idea of generating a static HTML or PDF is what was natural to me; running a "development server" wasn't something that was obvious (now I understand how `slidev` works it is, but the first time I tried it, it wasn't).

**Comment by yhatt** [comment]
Slidev is actually designed for developers (especially for web developers) as indicated by the concept "Presentation Slides for Developers". JavaScript developers are familar with running the local web server while developing, so it may not too difficult to figure out this meaning for them.

Marp is not designed with a specific expert in mind, so it's design is intentionally simple: Just convert Markdown into a single HTML file.

**Comment by aytey** [comment]
> JavaScript developers are familar with running the local web server while developing, so it may not too difficult to figure out this meaning for them.
>

I write Python and C++ in my day job ... and I just wanted something nice to write slides in Markdown.

For me, I didn't "get" that `slidev` wanted to launch a server and hot-reload like it does (until I made this issue 😄); I don't think the docs make it clear that's the expected workflow (if you're not a web developer).
