### ISSUE TITLE
In shiki-magic-move code block display line number

### ISSUE THREAD

**Issue by n3taway** [slidevjs/slidev#1470]
**Is your feature request related to a problem? Please describe.**
in Frontmatter Configures setting  `lineNumbers: true`, but shiki-magic-move code block No line number

**Describe the solution you'd like**
shiki-magic-move code block can display line numbers

**Describe alternatives you've considered**

**Comment by KermanX** [comment]
It seems that Shiki Magic Move doesn't support line numbers yet.

**Comment by manniL** [comment]
it should via `options.lineNumbers` 🤔
