### ISSUE TITLE
Keyboard shortcut to go back to previous slide or click.

### ISSUE THREAD

**Issue by pixiedevpraveen** [slidevjs/slidev#1473]
**Is your feature request related to a problem? Please describe.**
when we click outside of slide it registered it as click and move to next slide or click. And it also register right (secondary) click as a click to go next.

**Describe the solution you'd like**
I want a keyboard shortcut to go back to previous slide or click (search param) when click outside of slide with "shift" or "ctrl" or "alt". And if possible a config toggle button to use right (secondary) click as a click or as to go back to previous click or slide.

**Comment by KermanX** [comment]
Thanks for your advice. Clicking the left part of the outside of slide will go to the previous slide or click.

**Comment by pixiedevpraveen** [comment]
Can we use right(secondary) click to open  "Show slide overview".

**Comment by KermanX** [comment]
I agree with you. Also, adding a context menu can also be friendly to touch-only desktop devices like computers on the blackboard.

**Comment by KermanX** [comment]
I've opened #1475 after being inspired by this issue.

But I suddenly find I may have misunderstood what you were saying. I think arrow keys are enough to navigate between slides using a keyboard.

**Comment by KermanX** [comment]
I think this need has been implemented by #1475 (maybe in a different way).
