### ISSUE TITLE
globally installed  0.48.8 seems breaking mermaid

### ISSUE THREAD

**Issue by fjun99** [slidevjs/slidev#1479]
local install is correct. 

**Describe the bug**
Mermaid error when slidev is globally installed. 

page displays:   An error occurred on this slide. Check the terminal for more information.

console error : 

slides:294 Failed to load slide 17: SyntaxError: The requested module '/@fs/usr/local/lib/node_modules/@slidev/cli/node_modules/lz-string/libs/lz-string.js?v=d46b41fe' does not provide an export named 'default' (at mermaid.ts?v=d46b41fe:2:8)
﻿
- OS: macOS
- Browser: chrome 
- Slidev version: 0.48.8

I uninstall completely  and reinstall again, and the issue remains there.

by the way, there are many warning and failing warning in current version when globally installed, how to fix this? 

Failed to resolve dependency: @slidev/cli > @slidev/client > @antfu/utils, present in 'optimizeDeps.include'
Failed to resolve dependency: @slidev/cli > @slidev/client > @iconify-json/carbon, present in 'optimizeDeps.include'
...

**Comment by KermanX** [comment]
There seem to be many bugs when using Slidev via global installation. Hopefully, we can fix these in the future, but currently we can use the local installation as a workaround.

Also, this issue is duplicated with #1409.

**Comment by fjun99** [comment]
> There seem to be many bugs when using Slidev via global installation. Hopefully, we can fix these in the future, but currently we can use the local installation as a workaround.
> 
> Also, this issue is duplicated with #1409.

thanks!
