### ISSUE TITLE
Typo in documentation section "Composable Usage" (discussing `useSlideContext` and `useNav`)

### ISSUE THREAD

**Issue by ani-per** [slidevjs/slidev#1483]
https://github.com/slidevjs/slidev/blob/a0585db866ad299f238c024b40df013cba540c57/docs/custom/vue-context.md?plain=1#L120-L129

Based on my debugging, I believe that `useSlidevContext` should actually be `useSlideContext`:

```vue
<script setup>
import { useDarkMode, useNav, useSlideContext } from '@slidev/client'

const { $slidev } = useSlideContext()
const { currentSlideRoute } = useNav()
const { isDark } = useDarkMode()
// ...
</script>
```

**Comment by antfu** [comment]
Nice spot, do you want to send a quick PR?

**Comment by ani-per** [comment]
I've sent #1484, which also adds a brief section about importing a type. This is my first PR so hopefully it's all good!

**Comment by antfu** [comment]
Part of #1489 already
