### ISSUE TITLE
Embedding image(s) in a custom layout results in an unnecessary warning about the `public` folder

### ISSUE THREAD

**Issue by ani-per** [slidevjs/slidev#1488]
I created a custom layout `cover.vue`. To add an image to the layout, I used an `<img>` tag. Since the layout is stored in the `layouts` folder, I need to reference `../public/img/` for the image filepath instead of `./img` (like one would in a Slidev Markdown file).

However, this results in a (well-intentioned) warning about referencing the `public` folder that prints for each slide. Ideally, this warning would only apply to Slidev Markdown files.

---

Example custom `cover` layout:

```vue
<template>
  <div class="slidev-layout cover" :style="style">
    <div class="my-auto w-full">
      <div style="display: flex; flex-direction: row; gap: 4px; margin-bottom: 1.15rem; height: 40px;">
        <img src="../public/img/logos/PSU_Engineering.png" alt="PSU Mark">
        <img src="../public/img/logos/PSU_Aero.png" alt="PSU Mark">
      </div>
      <div style="display: flex; flex-direction: row; margin-top: 1.15rem; height: 40px">
        <img src="../public/img/logos/PURL.png" alt="PSU Mark">
      </div>
  </div>
</template>
```

Results in these warnings:

```console
Files in the public directory are served at the root path.
Instead of /public/img/logos/PSU_Engineering.png, use /img/logos/PSU_Engineering.png.
Files in the public directory are served at the root path.
Instead of /public/img/logos/PSU_Aero.png, use /img/logos/PSU_Aero.png.
Files in the public directory are served at the root path.
Instead of /public/img/logos/PURL.png, use /img/logos/PURL.png.
```

---

This issue is platform-agnostic, but:

- OS: Windows 11
- Browser: Brave, Firefox, Edge
- Slidev version: 0.48.8

**Comment by KermanX** [comment]
The usage of the `public` folder is:

```md
<img src="/abc.png">
```

Wherever the Markdown or Vue file is.

**Comment by ani-per** [comment]
> The usage of the `public` folder is:
> 
> ```
> <img src="/abc.png">
> ```
> 
> Wherever the Markdown or Vue file is.

I see my issue now, thanks - I had missed the note about the leading slash in the docs, and had tried using "./", instead of "/".

**Comment by ani-per** [comment]
Suggested a clarification for this in #1489 to prevent others from making the same mistake.
