### ISSUE TITLE
monaco - run : how to import 

### ISSUE THREAD

**Issue by yandok** [slidevjs/slidev#1499]
Hello, 

I've started from the template via `npm init slidev@latest`.

I'm trying to use a rxjs example in monaco-runner. I've added rxjs to the dependencies in package.json.

```typescript {monaco-run}
import { from } from 'rxjs';

const source = from([1, 2, 3, 4, 5]);
```

I'm getting the error: ERROR: SyntaxError: Cannot use import statement outside a module

Do you have any hints how I can use rxjs library in the monaco runner with slidev?

Thanks & Regards

Klaus

**Comment by KermanX** [comment]
We haven't supported the import statement yet. As a workaround, you can use the following code.

```ts
const {from} = await import("CDN to rxjs");
```

The CDN can be found on https://esm.sh

**Comment by yandok** [comment]
thanks a lot!

**Comment by KermanX** [comment]
#1502 has been merged, and it will be possible to import local packages in the next release.
