### ISSUE TITLE
RFC: Custom UI layouts

### ISSUE THREAD

**Issue by KermanX** [slidevjs/slidev#1509]
One of Slidev's main features is to be hackable. It would be useful if UIs, especially the presenter's view (#1095), could be configured by users.

Also, `global-top` and `global-bottom` can be one of these UIs. (Related to #1492)

We may need a new folder like `pages` to store these UIs. For example, users can create a `pages/presenter.vue` of a component receiving the `#thisSlide`, `#previewNext`, `#note`, and `#editor` slots.

> edit: I am working on this now

**Comment by antfu** [comment]
Sure, slot approach sounds good!

**Comment by KermanX** [comment]
Closed this as this is not really useful. A workaround could be using custom routes.
