### ISSUE TITLE
Can't export a larger presentation – timeout exceeded

### ISSUE THREAD

**Issue by gy-mate** [slidevjs/slidev#1514]
**Describe the bug**
I can't export a presentation (which is quite large) because slidev hits the timeout—even when it's several minutes long.

**To reproduce**

1. Clone [this](https://github.com/gy-mate/kalauz) repo
2. `git checkout dev_main`
3. `git checkout 64e6767e`
4. `cd presentation`
5. `slidev export --timeout 380000`
6. The command exits with the following error:
```
  ●■▲
  Slidev  v0.49.0-beta.1 (global)

  theme       @slidev/theme-apple-basic
  css engine  unocss
  entry       /Users/gymate1/Desktop/drop/python/kalauz/presentation/slides.md
  ■ rendering...page.goto: Timeout 380000ms exceeded.
Call log:
  - navigating to "http://localhost:12445/print?print=true", waiting until "networkidle"

    at go (/opt/homebrew/lib/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:156:16)
    at genPagePdfOnePiece (/opt/homebrew/lib/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:278:11)
    at genPagePdf (/opt/homebrew/lib/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:330:46)
    at exportSlides (/opt/homebrew/lib/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:383:11)
    at async Object.handler (/opt/homebrew/lib/node_modules/@slidev/cli/dist/cli.mjs:422:22) {
  name: 'TimeoutError'
}
```

**Desktop**
- OS: macOS `14.4.1`
- Browser: N/A
- Slidev version: `0.49.0-beta.1` (global)

**Comment by KermanX** [comment]
Try going to http://localhost:3030/print?print and use the browser to print the slides?

**Comment by gy-mate** [comment]
@KermanX Thank you, that works! :) It's a good workaround, but unfortunately I can't reduce the margins to zero due to the printing limitations of the system.

**Comment by KermanX** [comment]
If you use edge, there is a “more settings" panel, where you can set "margin" to 0

**Comment by gy-mate** [comment]
@KermanX Thanks for the tip, but unfortunately Chrome and Edge [both render the presentations with the wrong font](https://github.com/slidevjs/slidev/issues/1497#issuecomment-2049411669).
