### ISSUE TITLE
Remote control doesn't work

### ISSUE THREAD

**Issue by gy-mate** [slidevjs/slidev#1519]
**Describe the bug**
I can open remote control and step between slides, but it doesn't sync any slide changes to the desktop browser.

**To reproduce**

1. Clone [this](https://github.com/gy-mate/kalauz) repo
2. `git checkout dev_main`
3. `git chekout 34ddf0cc`
4. `cd presentation`
5. `npx slidev --remote`
6. Open the presentation in any of the desktop browsers below
7. Open the remote control in any of the mobile browsers below

**Devices**
- Safari `17.4.1` / Chrome `123.0.6312.124` on macOS `14.4.1`
- Safari `17.4.1` / Chrome `123.0.6312.52` on iOS `17.4.1`
- Slidev version: `0.49.0-beta.1` (global)

**Comment by KermanX** [comment]
I think only the navigations made in the presenter mode will be synced to the other devices.

**Comment by gy-mate** [comment]
Oh, I see, my bad!
