### ISSUE TITLE
layout image-left image-right images are not shown when deployed to github-pages

### ISSUE THREAD

**Issue by draptik** [slidevjs/slidev#1520]
When deploying the presentation to github-pages, all images referenced by "layout: image-left" or "layout: image-right" are missing.
Running the application locally: All is fine.

![image](https://github.com/slidevjs/slidev/assets/313058/a4a76f43-3a8f-4016-b6af-50b1c35c5c53)

```md

---
layout: image-left
image: /images/machine4.jpg
---

# Legacy-Context

- Domain
- Tech-Stack(s)
- Architecture
```

A few slides later you can see that the book cover is displayed correctly:

```md
# Find a "Seam"

- What is a Seam? 👉 M. Feathers "Working Effectively with Legacy Code"

<img
  class="absolute bottom-20 left-10 h-70"
  src="/images/feathers-legacy-code.jpg"
/>
```

Any ideas what I might be doing wrong?

- OS: Windows11, Arch Linux
- Browser: Firefox, Chrome
- Slidev version: 0.48.8

**Comment by KermanX** [comment]
Moving images to [the public folder](https://sli.dev/custom/directory-structure#public) can solve this. I think the docs should be clearer about this.

**Comment by draptik** [comment]
@KermanX thanks for the quick feedback!

The images where already in the public folder, but there was a missing trailing slash in my github workflow yaml file.
Layer-8 problem.... sorry for the noise
