### ISSUE TITLE
Static relative folder host no longer working

### ISSUE THREAD

**Issue by cookednoodles** [slidevjs/slidev#1525]
**Describe the bug**
We host generated slidev presentations in a subfolder : /app/xxxxxx/index.html
These are generated using : npm run build -- --base ./

This used to work with version 0.46.0

Since upgrading to 0.48 the page isn't loaded and the console starts with : 
No match found for location with path "/app/xxxx/index.html"

**To reproduce**
Build any project using : npm run build -- --base ./
host this in a static sufolder.

**Comment by KermanX** [comment]
Hmmm, what's the usage of `--base ./`? I think `--base /` is the default and correct one.

**Comment by cookednoodles** [comment]
If you run a build and then host it in a subfolder such as /aa/bb/index.html

* with a base of /, The first slide is at /1, so the vue rooter is trying to match /aa/bb/1 (won't work)
* with a base of ./ The first slide is at /aa/bb/index.html/1 (used to work)

**Comment by KermanX** [comment]
> If you run a build and then host it in a subfolder such as /aa/bb/index.html
> 
> * with a base of /, The first slide is at /1, so the vue rooter is trying to match /aa/bb/1 (won't work)
> * with a base of ./ The first slide is at /aa/bb/index.html/1 (used to work)

What if `--base /aa/bb/` ?

**Comment by KermanX** [comment]
Now `/aa/bb/index.html` will go to the first slide.
