### ISSUE TITLE
SPA's css building seems to be broken after upgrading to `v0.13.1`, page became very tiny.

### ISSUE THREAD

**Issue by dizys** [slidevjs/slidev#153]
**Describe the bug**

My project contains only `slides.md`(the default slides created by `@slidev/cli`) and dependency `@slidev/cli` and the default theme, nothing else. After upgrading slidev to the latest `v0.13.1`., the dev mode still works fine. The SPA building process, however, would suddenly output very long css ignoring warning, and the output page's css styles seem to be broken, the whole page became very tiny and disordered.

Building warning:

<img width="1510" alt="Screen Shot 2021-05-22 at 10 05 15 AM" src="https://user-images.githubusercontent.com/23469706/119211574-84030680-bae5-11eb-90ee-2aed1b5a3a05.png">

SPA demo:

<img width="1668" alt="Screen Shot 2021-05-22 at 10 09 52 AM" src="https://user-images.githubusercontent.com/23469706/119211633-f5db5000-bae5-11eb-9ec7-3ee5de53c7f5.png">

**To Reproduce**

Matter of fact, the init project created by `@slidev/cli` has this problem now.

1. `yarn init slidev` to create a new slidev project
2. `yarn build`
3. Deploy `dist` folder and you'll see.

**Desktop:**
 - OS: macOS Big Sur 11.3.1
 - Browser: Chrome 90
 - Slidev version: `v0.13.1`

**Comment by prd-y-nguyen** [comment]
I'm facing the same bug at `0.19.3`, why isn't it fixed?
