### ISSUE TITLE
Slides are not loaded properly in presenter mode

### ISSUE THREAD

**Issue by gy-mate** [slidevjs/slidev#1533]
**Describe the bug**
The presentation is displayed correctly in play mode:
<img width="600" alt="Screenshot 2024-04-15 at 10 53 36" src="https://github.com/slidevjs/slidev/assets/13014176/cd4f6f6b-3c18-4a42-8a1d-0760f9d2e4a0">

But no images are loaded in presenter mode. Some texts are also not loaded.
<img width="600" alt="Screenshot 2024-04-15 at 10 53 54" src="https://github.com/slidevjs/slidev/assets/13014176/e1d5ca95-9a19-478f-b0ce-8e4aec8d0132">

**To reproduce**

1. Clone [this](https://github.com/gy-mate/kalauz) repo
2. `git checkout dev_main`
3. `git chekout 85166735`
4. `cd presentation`
5. `npx slidev`

**Desktop**
- OS: macOS `14.4.1`
- Browser: Safari `17.4.1` or Chrome `123.0.6312.124`
- Slidev version: `0.49.0-beta.2` (global; the presentation uses `theme-apple-basic`)

**Comment by KermanX** [comment]
I think the problem is that `image: './MAV_1_felujitas.jpeg'` should be `image: '/MAV_1_felujitas.jpeg'`

**Comment by gy-mate** [comment]
I see, thanks! It works that way.
