### ISSUE TITLE
Animation on homepage of sli.dev errors

### ISSUE THREAD

**Issue by bux** [slidevjs/slidev#1537]
**Describe the bug**
The animation showcasing slidev on the homepage of sli.dev errors after the heading is complete

**To Reproduce**

1. Go to https://sli.dev
2. Observe the animation
3. See the error

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Slidev version: n/a

**Comment by KermanX** [comment]
![image](https://github.com/slidevjs/slidev/assets/63178754/9f9c39b4-b152-44b0-af94-c9bd1e5a710d)

https://deploy-preview-1444--slidev.netlify.app/ has this bug, but

https://deploy-preview-1439--slidev.netlify.app/ is correct.

This is quite strange.

**Comment by huiliangShen** [comment]
it's because typeit last version throw error!
