### ISSUE TITLE
Mustache Syntax is always interpreted

### ISSUE THREAD

**Issue by antfu** [slidevjs/slidev#1540]
#524 seems to reoccur, I guess probably related to the MagicString rewrite

**Comment by KermanX** [comment]
Also related: Magic String always replace text against the original text, which causes external snippets to no work with other features. For example:

```md
<<<./external.ts {monaco-run}
```

The monaco-run transformer works on the original text, instead of the text transformed by the snippets transformer

**Comment by antfu** [comment]
I made https://github.com/antfu/magic-string-stack for that :)
