### ISSUE TITLE
`.pdf` websites embedded with `layout: iframe` are unstable in Safari

### ISSUE THREAD

**Issue by gy-mate** [slidevjs/slidev#1541]
**Describe the bug**

If I open a slide with a website embedded by `layout: iframe` and click on a link on that site that points to a `.pdf` file...
- two-finger scrolling doesn't work for a few seconds
- it only recognizes clicks and scrolling in the blue box (the controls are also in the wrong place):
  <img width="600" alt="Screenshot 2024-04-16 at 23 25 49" src="https://github.com/slidevjs/slidev/assets/13014176/f56074ba-8cad-4860-bbd6-870f5c1583f4">
- using the scrollbar is unstable—it often gets stuck in a position while scrolling:
  - [example](https://github.com/slidevjs/slidev/assets/13014176/8498422d-acc3-484a-bd0a-56da8dd74862)
  - [live example](https://www.youtube.com/live/vkPkjzaun4o?si=duXNaV-4V1Q6T6Jo&t=4484)

**To reproduce**

1. Clone [this](https://github.com/gy-mate/kalauz) repo
4. `git checkout dev_main`
5. `git checkout 586fa61b`
6. `cd presentation`
7. `npx slidev`
8. Go to slide 10
9. Click on _Adony_

**Desktop**

- OS: macOS `14.4.1`
- Browser: Safari `17.4.1` (it works fine in Microsoft Edge `123.0.2420.81` and Chrome `123.0.6312.124`)
- Slidev version: `v0.49.0-beta.3` (global)

**Comment by KermanX** [comment]
I think we can't fix this by editing Slidev's source code. Feel free to reopen this issue if a possible solution is found.

**Comment by gy-mate** [comment]
You're right, this seems like a Safari bug.
