### ISSUE TITLE
Built results misses some unocss styles.

### ISSUE THREAD

**Issue by mosuzi** [slidevjs/slidev#1554]
**Describe the bug**
Built results missed some unocss styles.

**To Reproduce**
Please follow this repo: https://github.com/mosuzi/vue3-slidev.

Run`pnpm dev`:
![image](https://github.com/slidevjs/slidev/assets/43341701/0f7df0a8-e2bc-418d-9f79-efa61abcee2e)

But run `pnpm build`
![image](https://github.com/slidevjs/slidev/assets/43341701/159aa3bd-47af-4f53-87d3-c43a38890885)

See, the position of the github icon is different because of some unocss styles missing.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome 123.0.6312.122
- Slidev version: 0.49.0-beta.4

**Comment by KermanX** [comment]
The problem is that `md` is not included in your `uno.config.ts`:

```ts
  content: {
    pipeline: {
      include: [/\.(css|postcss|sass|scss|less|stylus|styl)($|\?)/, /\.(vue|ts|md)/]
//                                                                            ^^^ Add this
    }
  }
```

**Comment by mosuzi** [comment]
Thanks a lot!!!
