### ISSUE TITLE
Feat: v-switch

### ISSUE THREAD

**Issue by xiaodong2008** [slidevjs/slidev#1561]
For switching some scope's content, `v-switch` is a better solution than `v-click`

Demo: https://stackblitz.com/edit/fastjs-playground-xxjngd?file=src%2Fmain.ts

**Comment by KermanX** [comment]
Thanks for the idea. I agree that it would be very useful.

In my opinion, we can have a `<v-switch>` component for this:

```md
<v-switch at="{start click of the first element, default is '+1', refer to VClicks component}">
  <template #1>
    Show at start. Hide at start+1.
  </template>
  <template #2-3>
    Show at start+1. Hide at start+3.
  </template>
</v-switch>
```

**Comment by xiaodong2008** [comment]
That's cool! I will take on this.
