### ISSUE TITLE
Feature Request: Simplify adjustments of specific element style via Markdown instead of editing the code or using shell.

### ISSUE THREAD

**Issue by BingoKingo** [slidevjs/slidev#159]
I love this peoject, and I hope it will be more convenient. There, I have some ideas or needs:
1. Import font using @font-face, import css and js, define icon in theme configuration field easily, like: **More Prior to Default Style and Theme**

```
---
fontFace: ‘./name.woff’, ‘./name2.woff’
font: ‘name’
css: ‘./name.css’, ‘./name2.less’
js: ‘./name.js’, ‘./name2.js’
theme: ‘default’
icon: ‘name.ico’
---
```

2. Recommend Page Transitions like Concave, Convex, Fade, Zoom, Cube, Coverflow, and more.

```
---
transition: ‘coverflow’
---
```

3. Support the slide aspectRatio of 16/9, 4/3, 9/16 adjustments via control bar.
4. Support element animation like Morph (the simplest svg animation), Fade (as default).
5. Click the blankspace of slide (More than the black empty area up and down) to switch to next page.
6. Export to html with dist files (single file better) and browse them anywhere.

**Comment by antfu** [comment]
Thanks for the suggestions. But please read the docs first next time.

1. https://sli.dev/custom/directory-structure.html
2. Current planned, but not yet https://sli.dev/guide/animations.html#pages-transitions
3. You can with the frontmatter, and no plan to add UI for that. https://sli.dev/custom/#frontmatter-configures
4. https://sli.dev/guide/animations.html#element-transitions
5. What's "blankspace"? If you mean "Spacebar", does it support alreay?
6. https://sli.dev/guide/exporting.html#single-page-application-spa
