### ISSUE TITLE
markdown-it plugins running twice?

### ISSUE THREAD

**Issue by gureckis** [slidevjs/slidev#1592]
**Describe the bug**
It seems that markdown-it plugins are being run more than once to the same slide.  For instance, I tried using the `markdown-it-footnote` plugin.  It works ok but inserts the footnote material twice at the bottom of the slide.  I reported a similar behavior in #1579 which i attributed to the editor but might also be the same issue?

**To Reproduce**

1. install `markdown-it-footnote`
2. add it to your `vite-config.mjs`:
```js
import { defineConfig } from 'vite'
import footnote from 'markdown-it-footnote'

export default defineConfig({
  slidev: {
    vue: {
      /* vue options */
    },
    markdown: {
      /* markdown-it options */
      markdownItSetup(md) {
        /* custom markdown-it plugins */
        md.use(footnote)
      },
    },
    /* options for other plugins */
  },
})
```
4. made a slide with a footnote

```
---
layout: default
---

# Hello

- Here is a bullet^[here is a foonote]
```

5. Results

<img width="1254" alt="Screenshot 2024-05-14 at 12 25 30 PM" src="https://github.com/slidevjs/slidev/assets/1457760/bfa3970c-2652-414d-a360-cf3da9f469e7">

**Desktop (please complete the following information):**

- OS:
- Browser:
- Slidev version: v0.49.0-beta.6 
- Markdown-it-footnote version: 4.0.0

**Comment by antfu** [comment]
Wait... probably because we have `markdown-it-footnote` already builtin?

**Comment by gureckis** [comment]
doh 😳!!  yes confirmed, that was the issue.
