### ISSUE TITLE
slidev build --watch no work

### ISSUE THREAD

**Issue by YIngChenIt** [slidevjs/slidev#1597]
**Describe the bug**
The slidev build --watch command is not working as expected. It only performs a single build operation and does not continue to watch for changes and rebuild.

**Desktop (please complete the following information):**

- Slidev version: 0.49.2

**Comment by KermanX** [comment]
Reproduced.

Could you please tell us why you need to build the slides in watch mode? Run the `slidev` command itself will start a dev server.

**Comment by YIngChenIt** [comment]
> 轉載。
> 
> 您能否告訴我們為什麼需要在觀看模式下建立投影片？運行`slidev`命令本身會啟動一個開發伺服器，它可以反映原始程式碼的變化，甚至不需要刷新瀏覽器頁面。

![image](https://github.com/slidevjs/slidev/assets/53081460/d278da2c-8507-4185-b441-bd3e819db878)
I saw this usage in the documentation.

**Comment by KermanX** [comment]
Yes, and this is not working😓. And since we have the dev server, this option is almost useless, so we are planning to remove it. Want to know why you want to use this option?

**Comment by YIngChenIt** [comment]
> Yes, and this is not working😓. But since we have the dev server, this option is almost useless, so we are planning to remove it. Want to know why you want to use this option?
> 
> 中文版：这个功能坏了，但是因为可以直接运行`slidev`命令启动开发服务器，所以我觉得这个功能其实没有实际用处。想问一下您为什么需要这个功能

Thank you for your response. I have found another way to achieve this, so I am closing this issue.
