### ISSUE TITLE
LaTeX Support

### ISSUE THREAD

**Issue by Immortalin** [slidevjs/slidev#16]
LaTeX support will make writing math equations easier.

**Comment by antfu** [comment]
Sure, any library recommended?

**Comment by Immortalin** [comment]
I think MathJax and KaTeX are the main big ones.

**Comment by Immortalin** [comment]
@antfu that was really fast 🥳.

**Comment by faroit** [comment]
@antfu is there a way to use the Math renderer from HTML instead of markdown?

**Comment by haoyun** [comment]
Possible to add also MathJax Support?
* https://www.npmjs.com/package/markdown-it-mathjax3
