### ISSUE TITLE
Bug on slide 5 of the demo deck `yarn create slidev`

### ISSUE THREAD

**Issue by jaanli** [slidevjs/slidev#1614]
**Describe the bug**
On slide 5 of the demo deck, from `yarn create slidev`, there is an error:

<img width="822" alt="image" src="https://github.com/slidevjs/slidev/assets/5317244/5abc2186-c7db-4277-b045-2bc66854eeb5">

**To Reproduce**

1. `yarn create slidev`
2. open the presentation
3. go to slide 5 to see the bug

**Desktop (please complete the following information):**

- OS: macos
- Browser: firefox
- Slidev version: latest

Thank you for an awesome library!

**Comment by KermanX** [comment]
This is expected demonstration of Twoslash's ability to show a type error.

**Comment by jaanli** [comment]
Sounds good, thank you @KermanX - in that case, there is a bug in the Twoslash system: I cannot scroll on the error message to see the full thing.

Is that expected behavior? Is the error message able to be resized? 

(I need to display errors in my presentation too!)

**Comment by KermanX** [comment]
Cannot reproduce on my machine: 
![image](https://github.com/slidevjs/slidev/assets/63178754/9f9cd6c6-2f3c-4406-9256-8bd482f93871)
