### ISSUE TITLE
GitHub Actions deployment fails from fresh install

### ISSUE THREAD

**Issue by jaanli** [slidevjs/slidev#1623]
**Describe the bug**
Error when following https://sli.dev/guide/hosting

**To Reproduce**

1. Run `yarn create slidev`
2. Create new GitHub repo and push
3. Follow https://sli.dev/guide/hosting for GitHub Pages
4. See the error: https://github.com/onefact/talks.onefact.org/actions/runs/9275248524/job/25519492154

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Slidev version: latest

Any ideas how to debug?

**Comment by KermanX** [comment]
How about removing package-lock.json and re-create it, as the instructions in the error message.

btw, if you mean to deploy your slides to https://talks.onefact.org/, the --base option should be /. Not sure if the current base option is intentional.
