### ISSUE TITLE
Issue with MDC inline components

### ISSUE THREAD

**Issue by rwnobrega** [slidevjs/slidev#1625]
**Describe the bug**

Apparently, no _bold_, _italics_, or _link_ markdown can appear **after** an [MDC inline component](https://sli.dev/guide/syntax#mdc-syntax). Inline _code_ markdown is fine.

**To Reproduce**

Remark: I used the [`Counter.vue`](https://github.com/slidevjs/slidev/blob/main/demo/starter/components/Counter.vue) sample component in the example below, but the same behavior was observed with other components.

1. Start a new slidev project.

1. Write the following into `slides.md`:

   ```md
   ---
   title: Test
   mdc: true
   ---

   <!-- Works: -->

   Test **bold** :counter test

   Test _italic_ :counter test

   Test [link](https://example.com) :counter test

   Test :counter test `code` test

   <!-- Renders incorrectly: -->

   Test :counter test [link](https://example.com)

   <!-- Error: -->

   Test :counter test **bold**

   Test :counter test _italic_
   ```

1. Run `npm run dev`

1. Check the terminal:

   ```text
   1:39:50 PM [vite] Internal server error: inline rule didn't increment state.pos
     Plugin: unplugin-vue-markdown
     ...
   ```

**Desktop:**

- OS: Fedora Linux 40
- Browser: Firefox 126.0
- Slidev version: 0.49.5

**Comment by KermanX** [comment]
The error thrown here is (almost) the same as https://github.com/antfu/markdown-it-mdc/issues/10.
