### ISSUE TITLE
run build and get the wrong background images path

### ISSUE THREAD

**Issue by lfire** [slidevjs/slidev#1627]
**Describe the bug**
![image](https://github.com/slidevjs/slidev/assets/2528719/8963f243-c778-4d2d-8654-4231d43329f5)

**To Reproduce**

1. put the bg images in `/public` path
2. config the slide theme and background like 
```
theme: seriph
background: /public/bg/_966fd0c7-591b-499e-b472-5cdfad5eed4d.jpeg
```
3. config the npm script build `slidev build ai.md --out ./docs`
4. run build
5. get the error path like the image desc

**Desktop (please complete the following information):**

- OS: MAC
- Browser:
- Slidev version: latest 0.49.5

**Comment by KermanX** [comment]
The frontmatter should be like:

```md
background: /bg/_966fd0c7-591b-499e-b472-5cdfad5eed4d.jpeg
```

(No `/public` prefix)

**Comment by lfire** [comment]
@KermanX 
![image](https://github.com/slidevjs/slidev/assets/2528719/02c74598-8a06-441c-a411-2722d5036393)
when I work with multi entry in a repo, how can I set the backgroud path? 
If I config the backgroud like `/bg/****`, the resource will be error path. 
![image](https://github.com/slidevjs/slidev/assets/2528719/1db26ab8-9d90-4e07-a9c2-e387698186e4)

**Comment by KermanX** [comment]
I don't know why the dist looks like this. Please send a minimal reproduction.

**Comment by lfire** [comment]
> I don't know why the dist looks like this. Please send a minimal reproduction.

Thx, I have resolved the problem by a shell. https://github.com/lfire/slidev-share/blob/main/build.sh
