### ISSUE TITLE
Slide navigation is not working with hash router

### ISSUE THREAD

**Issue by rwnobrega** [slidevjs/slidev#1637]
**Describe the bug**

Slide navigation (next/previous slide) is broken in **hash** router mode. Same behavior both in Firefox and Chromium.

**To Reproduce**

1. Add `routerMode: hash` to the frontmatter.

1. Try navigating the slides (right arrow, left arrow, space, mouse). It does not work.

**Desktop:**

- OS: Fedora Linux 40
- Browsers: Firefox 126.0, Chromium 125.0.6422.112.
- Slidev version: 0.49.7

**Comment by lfire** [comment]
the same problem.
