### ISSUE TITLE
Install the theme were failed

### ISSUE THREAD

**Issue by LogicLord-Liu** [slidevjs/slidev#1653]
**Describe the bug**
Why did the theme installation fail and show this picture?

![](https://img-blog.csdnimg.cn/direct/7ec16d4c48bf4b1da0edf1c2732ef94e.png)

What's that meaning?

Please Help me

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: chrome
- Slidev version: v0.49.9

**Comment by KermanX** [comment]
I think the `theme` option in your slide's headmatter is wrong. It should be

```md
---
theme: apple
---
```

**Comment by LogicLord-Liu** [comment]
Sorry, it is still wrong.

![](https://img-blog.csdnimg.cn/direct/71f994317c444c8497522391d8ad3c40.png)

But when i install 'seriph' ,it's right. That's why?

![](https://img-blog.csdnimg.cn/direct/fe3bbe61183e43fba4b4a80495a1e0c6.png)

**Comment by KermanX** [comment]
Hmmm, the slide name is case-sensitive

**Comment by LogicLord-Liu** [comment]
Oh, it's right now.

Does that mean it can only be recognized when using lowercase?

And another question: Why the theme were installed and already run it,but it still doesn't load the theme in Google Chrome.
**Is that the network issue?**

**Comment by LogicLord-Liu** [comment]
Thanks for your responses to my questions
