### ISSUE TITLE
vscode/vscodium : Request for improved documentation for the “Slidev for VS code” extension.

### ISSUE THREAD

**Issue by kosenhitatchi** [slidevjs/slidev#1654]
Good afternoon.
Thanks for this wonderful project.

-- **Is your feature request related to a problem? Please describe.** -- 

I'm running [vscodium 1.84.2](https://vscodium.com/) (VScode FLOSS version) and I'm facing some issue to properly install the _[Slidev for VS code](https://marketplace.visualstudio.com/items?itemName=antfu.slidev)_ extension. 

Since 10/05/2024 the [initial extension's repo](https://github.com/slidevjs/slidev-vscode) got archived and the extension code got integrated within [slidev main repo](https://github.com/slidevjs/slidev/tree/main/packages/vscode).

That said the [documentation ](https://sli.dev/guide/editors) to correctly install and use the extension is lacking information. 

-- **Describe the solution you'd like** -- 

Please update the documentation to correctly install and use the _[Slidev for VS code](https://marketplace.visualstudio.com/items?itemName=antfu.slidev)_ extension.

Thanks a lot 😄

**Comment by KermanX** [comment]
You are right. The documentation is not complete.

About the installation of the extension, what's the problem you are facing? Simply install it from the marketplace and it will work.

**Comment by kosenhitatchi** [comment]
> You are right. The documentation is not complete.
> 
> About the installation of the extension, what's the problem you are facing? Simply install it from the marketplace and it will work.

Hi @KermanX ,
Thanks for your lightning fast feedback.

Well, the Vscode extension panel find the extension (_v0.3.3_ in the editor at the time of writing) and ..seems.. to install it.
That said, it doesn't seem that the slidev custom channel got enabled as shown below (img for the offical doc). 
I've probably missed a step but the doc lacks information on this.

![116809994-cc2caa00-ab73-11eb-879f-60585747c3c9](https://github.com/slidevjs/slidev/assets/11291599/7276e4b8-9a63-4c7f-8b79-fc11ad1f26a7)

Best
