### ISSUE TITLE
Some questions about Slidev--Theme and load it in browser

### ISSUE THREAD

**Issue by LogicLord-Liu** [slidevjs/slidev#1655]
Dear Developer, Hello.

I have some questions about slidev.
* Does that mean the theme can only be recognized when using lowercase?
* Why the theme were installed, but it doesn't load the theme in Google Chrome? It that the network issue?

And thanks for your previous replies to my questions

**Comment by KermanX** [comment]
The themes are NPM packages. All the NPM package names are lower-cased.

About the "theme doesn't loaded issue", please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.

Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by LogicLord-Liu** [comment]
Thinks for your replies to my questions.
