### ISSUE TITLE
Title not working - $slidev.configs.title is not parsing

### ISSUE THREAD

**Issue by AdamFiser** [slidevjs/slidev#1656]
**Describe the bug**
When using {{ $slidev.configs.title }} in the MD file, the title is not displayed.

It appears in embedded files (src: '../../pages/index.md') and directly in md.

It shows up in the latest 0.49.10, and was functional in the previous tested 0.48.9.

The other slidev.config tags are also functional.

I think it's caused by #1621

**To Reproduce**

1. Go to slides.md
2. Use the source: 
```
---
#== Slide Info
...
title: "My title"
titleTemplate: "PRF %s by Me"
src: '../../pages/index.md' # no impact - it manifests itself in embedded and directly 
...
---
# {{ $slidev.configs.title }}
```
4. run presentation and in slide is shown `{{ $slidev.configs.title }}` instead `My title`

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Slidev version: latest (0.49.10)

**Comment by KermanX** [comment]
I can't reproduce the problem when running the following slides:

```md
---
title: "My title"
titleTemplate: "PRF %s by Me"
---

# {{ $slidev.configs.title }}
```

Did I miss something?

**Comment by AdamFiser** [comment]
You can check my repo https://github.com/OA-PVA2-Syllabus/pva2_prednasky or if you are interested in, i can prepare new one for testing purposes.
