### ISSUE TITLE
Can't create multiple slides

### ISSUE THREAD

**Issue by jaanli** [slidevjs/slidev#1658]
**Describe the bug**
Tried adding multiple slide decks to talks.onefact.org (https://github.com/onefact/talks.onefact.org).

**To Reproduce**

1. Go to https://github.com/onefact/talks.onefact.org/blob/main/pages/multiple-entries.md - and verify that this text appears
2. Try it locally: `slidev --open pages/multiple-entries.md` and verify that it opens in your browser
3. Go to talks.onefact.org/pages/multiple-entries
4. See the error: it goes back to the first page :(

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome latest
- Slidev version: latest via `yarn upgrade-interactive --latest`

Open to any help in debugging this! Thank you on behalf of @onefact :)

**Comment by jaanli** [comment]
Related from @jonathanlukas: https://github.com/jonathanlukas/slidev-setup-sample

**Comment by KermanX** [comment]
Do you run `slidev build pages/multiple-entries.md --out ./dist/pages/multiple-entries/ --base /pages/multiple-entries/`?

**Comment by KermanX** [comment]
This is temporarily closed because more information is required.
