### ISSUE TITLE
an error occurs when exporting slides with more than 2 pages on wsl

### ISSUE THREAD

**Issue by TardyPurcell** [slidevjs/slidev#166]
**Describe the bug**
an error occurs when exporting slides with more than 2 pages on wsl.

**To Reproduce**
1. `npm init slidev@latest`
2. leave the project name as it is
3. install and start it now
4. choose npm as the agent
5. `^C`
6. `cd slidev`
7. `npx slidev export`
8. see error
    ![image](https://user-images.githubusercontent.com/39642409/119263440-a134f380-bc11-11eb-8e4d-2ed24b075bd0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 focal(on the Windows Subsystem for Linux)  
 - Browser: Microsoft Edge 90.0.818.66
 - Slidev version: 0.13.10
 - Node version: 14.17.0
 - Npm version: 6.14.13

**Comment by hannoeru** [comment]
Failed in WSL version 1, but works in WSL version 2, can you upgrade your environment?

**Comment by TardyPurcell** [comment]
Thanks a lot. It worked after upgrade.
