### ISSUE TITLE
`slidev build` is exposing local directory paths

### ISSUE THREAD

**Issue by rwnobrega** [slidevjs/slidev#1669]
**Describe the bug**

The files generated by [`slidev build`](https://sli.dev/guide/hosting#build-single-page-applications-spa) are unnecessarily exposing local directory paths.

**To reproduce**

1. Create a new Slidev project.
1. Run `npm run build`.
1. Open, for example, `dist/index.html` and `dist/assets/slidev/Arrow-[hash].js`.
1. Check that your local directory (e.g., `/home/user/...`) is indeed there.

To get the full list of offending files, you may run

```sh
grep "/home/" dist/ -r -l
```

**Desktop:**

- OS: Fedora Linux 40
- Browser: Firefox 127.0.
- Slidev version: 0.49.10

**Comment by KermanX** [comment]
It seems that `process.env.NODE_ENV` is still `"development"` when running `slidev build`

**Comment by rwnobrega** [comment]
Thank you for your work on this!

As of version `0.49.11`, most files are now free from local directory paths. However, the following files still expose local paths:

```
dist/assets/index-[hash].js
dist/index.html
dist/404.html
```

Additionally, as a side effect of the patch, some filenames now have unusual suffixes before the hash, which did not appear before. For example:

```
Arrow.vue_vue_type_script_setup_true_lang-[hash].js
```

instead of just:

```
Arrow-[hash].js
```

**Comment by KermanX** [comment]
@rwnobrega Thank you for noticing these! Opened #1690 to track these issues.
