### ISSUE TITLE
Build a subset of pages

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [slidevjs/slidev#167]
Is it planned in the future to be able build a subset of the pages in slides.md, e.g.: pages 0 - 20, etc?

This would be really nice

**Comment by antfu** [comment]
You can use frontmatter to disable pages you want to hide

```md
# Page 1

---
disabled: true
---

# Page 2
```

Will result in Page 1 only.

Or if you mean exporting to PDF or PNG, you can already to that by

```bash
slidev export --range 1-10,14,15
```

**Comment by mariomurrent-softwaresolutions** [comment]
Oh, well then I must have overread this .. sorry :(
And thx for the fast answer
