### ISSUE TITLE
Bullet points remain unfaded when using `[click]`s

### ISSUE THREAD

**Issue by gy-mate** [slidevjs/slidev#1680]
**Describe the bug**

A minor issue: when using `[click]`s in notes with (nested) bullet points, the bullet points of faded list elements that have one or more `[click]`s remain unfaded.
<img width="300" alt="Screenshot 2024-06-18 at 00 16 48" src="https://github.com/slidevjs/slidev/assets/13014176/57bb83d7-8ccf-415f-82ac-7445dedc95da">

**To reproduce**

1. Run my presentation

    ```bash
    git clone https://github.com/gy-mate/kalauz
    cd kalauz/presentation
    git checkout ef1967e5
    npx slidev
    ```

2. Open http://localhost:3030/presenter/18?clicks=1

**Desktop**

- OS: macOS `14.5`
- Browser: Safari `17.5` (same in the latest Chrome)
- Slidev version: `0.49.10` (global)

**Comment by gy-mate** [comment]
@KermanX Thank you for your work!

I'd like to add that I would expect all bullet points of faded list elements to be also faded. Like the second bullet point in the picture of the issue description. Now (version `0.49.12`) it looks like this:
<img width="300" alt="Screenshot 2024-06-28 at 23 53 26" src="https://github.com/slidevjs/slidev/assets/13014176/76f4d25b-6624-44dc-9294-3c88d3a915f2">

And if you move to http://localhost:3030/presenter/18?clicks=6 I would also expect the circled bullet points to be faded:
<img width="300" alt="Screenshot 2024-06-28 at 23 55 15" src="https://github.com/slidevjs/slidev/assets/13014176/7ecf977f-dceb-44f3-8f78-fa47983566d2">

What do you think about this?

**Comment by gy-mate** [comment]
Also, sometimes the list element that should be highlighted is not highlighted at all. If you go to http://localhost:3030/presenter/18?clicks=2 the list element _"tul ritkak a merovonati bejarasok"_ should be highlighted but it isn't:
<img width="300" alt="Screenshot 2024-06-29 at 00 06 07" src="https://github.com/slidevjs/slidev/assets/13014176/1335e1fc-d718-47c5-8ce9-e969657a0e65">

**Comment by KermanX** [comment]
@gy-mate The `[click]` markers should be put before the content like this:

```md
<!--
Content before the first click

[click] This will be highlighted after the first click

Also highlighted after the first click.

[click] This will be highlighted after the second click

[click:3] Last click (skip two clicks)
-->
```

Then the current behavior will be reasonable - The bullet points unfade when there is sone content in this `<li>` unfade.

**Comment by gy-mate** [comment]
@KermanX I see, thank you for the explanation! I've opened a PR to include these in the docs.
