### ISSUE TITLE
电脑没有科学上网的话, 页面打不开

### ISSUE THREAD

**Issue by webliving** [slidevjs/slidev#169]
**Describe the bug**
默认加载的google , twitter 脚本怎么去除? 电脑没有科学上网的话, 页面打不开

**To Reproduce**
1. npm run dev
2. 打开网页

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser: chrme
 - Slidev version: 0.13.8

**Comment by webliving** [comment]
还有个问题, 为什么dev时, 总可能会让风扇转啊 😺

**Comment by webliving** [comment]
slides.md 中的Tweet 这个组件删除, 就会报错, 打不开了呢?

**Comment by antfu** [comment]
Twitter 的脚本只有在 使用了 <Tweet/> 组件的时候引入，删掉就行了。主题里可能会用到 Google Fonts，但是应该不影响使用。需要修改的话可以把主题弹出。

后面的两个问题缺少上下文，没办法回答。

**Comment by webliving** [comment]
> Twitter 的脚本只有在 使用了 组件的时候引入，删掉就行了。主题里可能会用到 Google Fonts，但是应该不影响使用。需要修改的话可以把主题弹出。
> 
> 后面的两个问题缺少上下文，没办法回答。

嗯, 是删除了. 有些伙伴没有整翻墙. 其它两个问题, 也没太仔细看具体什么原因. 再发现什么细节再说吧. 感谢. 👍

**Comment by zillionare** [comment]
就是google fonts的原因
