### ISSUE TITLE
Run slidev template failed

### ISSUE THREAD

**Issue by HelloAny** [slidevjs/slidev#1696]
**Describe the bug**
I meet some compiling errors when i run `pnpm create slidev` and run `pnpm dev`.
<img width="800" alt="image" src="https://github.com/slidevjs/slidev/assets/44696899/a04e1f57-36d5-4575-8216-c4cb9a92077b">

When I removed the `vue-template-complier` package in the `pnpm-lock.json` file, these errors disappeared and it worked fine.
<img width="590" alt="Code 2024-06-23 14 16 44" src="https://github.com/slidevjs/slidev/assets/44696899/7a1be648-08c6-41ce-8ccd-d6f3e1e68e4b">
<img width="617" alt="Code 2024-06-23 14 16 00" src="https://github.com/slidevjs/slidev/assets/44696899/5c126b64-f7a7-4db7-8088-92b6184e23ac">

**To Reproduce**

1. Run `pnpm create slidev`
2. Run `pnpm dev`

**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.2.1(M1)
- Browser: Chrome 125.0.6422.78(ARM64)
- Slidev version: 0.49.11
- pnpm version: 9.1.2
- node version: 18.20.3

**Comment by KermanX** [comment]
Sorry, I can't reproduce this on my machine. I think some upstream packages caused this error.

**Comment by HelloAny** [comment]
I tried again, and it works now. 😂
