### ISSUE TITLE
Showcase image should be clickable?

### ISSUE THREAD

**Issue by gokulkrishh** [slidevjs/slidev#17]
To open the showcase, it took me a few seconds to understand i have to click the showcase icon which is not very obvious. perhaps make the entire showcase image clickable?

<img width="811" alt="Screenshot_2021-05-06_at_8_47_43_AM" src="https://user-images.githubusercontent.com/2944237/117237268-32e9e600-ae48-11eb-9bdd-63f05c506a68.png">

**Comment by antfu** [comment]
Yeah, good point, mind open a PR for it? Thanks

**Comment by gokulkrishh** [comment]
@antfu Why not 😁. Will send you one in sometime.

**Comment by gokulkrishh** [comment]
@antfu Also can you update the readme with **how to setup in local** or **contribution** guide perhaps?

**Comment by antfu** [comment]
Sure thing

**Comment by gokulkrishh** [comment]
Fixed in #19 We can close it.
