### ISSUE TITLE
Impossible to record current tab where the presentation is shown

### ISSUE THREAD

**Issue by thomascenni** [slidevjs/slidev#1703]
**Describe the bug**
When trying to record the presentation, only other tabs are shown according to the following image:

![image](https://github.com/slidevjs/slidev/assets/33039107/17c2c16c-2841-44cf-9483-51ad37091f61)

**To Reproduce**
Click on the Slidev icon to record your screen.

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Chrome Version 126.0.6478.63 (Official Build) (64-bit)
- Slidev version: v0.49.11

**Comment by fdtl01** [comment]
Hello,
     Have you solved this issue? I also have the same problem.

**Comment by thomascenni** [comment]
> Hello, Have you solved this issue? I also have the same problem.

Hi, no I didn't solve the issue.
