### ISSUE TITLE
static assets not processed by vite when referenced in the frontmatter of the image-left/image-right default layouts

### ISSUE THREAD

**Issue by gureckis** [slidevjs/slidev#1707]
**Describe the bug**

When building slides that reference static image assets in the front matter (e.g., image-left) the asset is not copied into the final build folder by vite.

**Minimal reproduction**

1. create a starter project
2. create a folder assets/ with photo.png inside
3. Include a slide with the following front matter

```
---
layout: image-left
image: assets/photo.png
class: mycoolclass
---
```

4. Things display ok in dev mode
5. build the project using `slidev build`
6. photo.png is not copied into assets folder of the dist/ folder  
However, the rendered HTML does reference this file:

```
<div class="w-full h-full" style="color: white; background-image: url("assets/photo.png"); background-repeat: no-repeat; background-position: center center; background-size: cover;"></div>
```

I expected that all references static content would be processed by vite and moved into the assets folder.

**Environment**

- Slidev version: 0.49.12
- Browser: ARC
- OS: Mac Sonoma 14.5

**Comment by gureckis** [comment]
nevermind, this is probably a use case for `public/` folder

**Comment by arialdomartini** [comment]
It's still a bit confusing that not having the background file in `public`, `npm run dev` renders it as a background image, while `slidev build` would not.

**Comment by KermanX** [comment]
> It's still a bit confusing that not having the background file in `public`, `npm run dev` renders it as a background image, while `slidev build` would not.

This is one of the most complained points of Vite🥲
