### ISSUE TITLE
generated project name is incorrect when I use sequence

### ISSUE THREAD

**Issue by skanehira** [slidevjs/slidev#171]
**Describe the bug**
When input project name, then if I use sequence (like `C-w` to delete default word), generated directory name is incorrect.
If I input `<C-u>test`, then `\u{15}test` is generated.

**To Reproduce**
1. `yarn create slidev`
2. When input project name, at first input `C-w`, continue input the name.

**Desktop (please complete the following information):**
 - OS: M1 Mac Big Sur
 - Browser: Sidekick
 - Slidev version: v0.13.10

**Comment by antfu** [comment]
Sorry what is `C-w`?

**Comment by skanehira** [comment]
It's `Ctrl + w`
In the terminal, we can enter `Ctrl + w` to delete words.

**Comment by antfu** [comment]
Not sure, maybe create an issue to https://github.com/terkelg/prompts instead?
