### ISSUE TITLE
[unocss] Entry module not found. Did you add `import 'uno.css'` in your main entry?

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1719]
**Describe the bug**

I'm developing a slidev theme: https://github.com/zillionare/slidev-theme-rich
Everything works ok when checked by `npm run dev`. However, if I try to build it, unocss warning happens:

```
[plugin:unocss:global:build:bundle] [plugin unocss:global:build:bundle] [unocss] Entry module not found. Did you add `import 'uno.css'` in your main entry? (x2)
```

And the final result is broken.

![图片](https://github.com/slidevjs/slidev/assets/7206696/58fc1473-69a1-4871-9684-bc33edc15ca2)

**Minimal reproduction**

1. checkout https://github.com/zillionare/slidev-theme-rich
2. run `npm run dev`, check the output, everything is ok.
3. run `npm run build`, the above warning appears and the webpage is broken.

**Environment**

- Slidev version: 0.49.12
- Browser: Firefox
- OS: Macos M1

---
More screenshots:

the right one(dev mode):

![图片](https://github.com/slidevjs/slidev/assets/7206696/81c206c8-7648-4504-a504-9f527626d0ad)

the bad one(build mode)

![图片](https://github.com/slidevjs/slidev/assets/7206696/16125fb8-2ac2-4da1-acd9-48cad0849ffe)

It's my first theme, so maybe I'm asking dumb questions, thanks if you can help.

**Comment by KermanX** [comment]
I think removing the UnoCSS plugin in your vite.config.ts can solve this. Slidev has imported that plugin internally.

**Comment by zillionare** [comment]
Verified and many thanks!
