### ISSUE TITLE
Using onSlideEnter() causes error in existing slide deck

### ISSUE THREAD

**Issue by gureckis** [slidevjs/slidev#1723]
**Describe the bug**

I have a slide presentation which has loads a custom component in one of my slidse.  This component is simple test just for debugging:

```js
<script setup>
import { onSlideEnter } from '@slidev/client'

onSlideEnter(() => {
  console.log('start scrolling')
})

</script>

<template>
  <div><slot></slot></div>
</template>
```

which is to say a component that doesn't do much.

I reference it in my slides.md

```
<TestComponent><h1>My content</h1></TestComponent>
```

This results in an error on the console that looks like this

<img width="1392" alt="image" src="https://github.com/slidevjs/slidev/assets/1457760/e997b32a-e799-40bf-8d70-87af91d0cdcf">

And the slide containing this component will not display.  It might be unreleated but this seems to also causes any Monaco formatted code sections to not load correctly.

Commenting out the `onSlideEnter( () => { console.log('start scrolling') }` makes things work again.

**Environment**

- Slidev version: 0.49.13
- Browser: ARC
- OS: Mac 14.5

**Comment by KermanX** [comment]
Sorry, I can't reproduce this on my machine. Does this still happen after restarting the Slidev server?

**Comment by gureckis** [comment]
i'm not sure i had a local theme that was behaving weird for some other reason.  i think it seems to have gone away now.
