### ISSUE TITLE
Single binary for windows

### ISSUE THREAD

**Issue by yodatak** [slidevjs/slidev#1726]
**Is your feature request related to a problem? Please describe.**
When i'm at work i got no permission to install and no admin right, i would love to have a single binary or user only installation of slidev

**Describe the solution you'd like**
Single binary to run my slides

**Describe alternatives you've considered**
unzip a nodejs windows binary and run some commands

**Comment by KermanX** [comment]
Try this: https://sli.dev/new. Only your browser is required

**Comment by antfu** [comment]
We are not interested in doing that due to the maintenance cost. We'll leave this to community solutions if someone wants to work on that. Thanks for bringing this up.
