### ISSUE TITLE
Slide appears in bottom right corner

### ISSUE THREAD

**Issue by bgschiller** [slidevjs/slidev#173]
**Describe the bug**
Slides appear in the bottom right corner after a refresh. If I click either of the `scale` options, they are back where they belong. I can also fix by clearing localstorage. With either fix, the issue re-appears after a couple of refreshes.

**To Reproduce**
1. `npm init slidev@latest`, install and start now, npm. Browser will open to `localhost:3030` automatically.
2. Refresh the page. Observe that the slides are now in the bottom right corner.

video demo: https://user-images.githubusercontent.com/2491257/119438940-241f8200-bcd6-11eb-8e4b-49fa599a6e31.mp4

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome Version 90.0.4430.93 (Official Build) (x86_64)
 - Slidev version: v0.13.10

**Comment by dizys** [comment]
I've also notices this, working on a fix.
