### ISSUE TITLE
lineNumbers options is not working when using Code Snippets

### ISSUE THREAD

**Issue by nana4gonta** [slidevjs/slidev#1754]
**Describe the bug**

The `lineNumbers: true` option displays line numbers in code blocks, 
but line numbers are not displayed when imported as Code Snippets.

**Minimal reproduction**

1. Create Project: `npm init slidev@latest`
2. Open `slides.md`, and add the option `lineNumbers: true` 
3. Run `npm run dev`
4. Open: http://localhost:3030/5
5. See that line numbers are not displayed in Code Snippets

https://stackblitz.com/edit/github-fc4pne?file=slides.md

**Environment**

- Slidev version: 0.49.16
- Browser: 126.0.6478.127（Official Build） （arm64）
- OS: macOS Sonoma 14.5

**Comment by nana4gonta** [comment]
**workaround**

If you specify the line numbers to highlight (e.g. `{1-100}`) and set `{lines:true}`, the line numbers will be displayed.
But if you don't specify the line numbers to highlight, they will not be displayed.

```md
Any Text...

<!-- display line numbers -->
<<< @snippets/something-code.ts {1-100}{lines: true}

<!-- not display line numbers -->
<<< @snippets/something-code.ts {lines: true}

Any Text...
```

**Comment by KermanX** [comment]
This is an expected behavior. The first `{}` will always be regarded as line highlighting.

A more elegant way is:

```md
<<< @snippets/something-code.ts {*}{lines: true}
```

**Comment by nana4gonta** [comment]
@KermanX 
I **only presented a workaround**, the original problem has not been solved.
**The problem of line numbers not being displayed in Code Snippets has not been resolved, even though `lineNumbers: true` is set.**

See Minimal reproduction properly.
And See stackblitz
https://stackblitz.com/edit/github-fc4pne?file=slides.md
