### ISSUE TITLE
Black screen after upgrade of slidev version

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [slidevjs/slidev#177]
**Describe the bug**
install the latest cli 

**To Reproduce**
1. nom run dev
2. open browser
3. the following error occurs

```
[Vue warn]: Invalid prop: type check failed for prop "scale". Expected Number with value NaN, got String with value "null". 
  at <SlideContainer class="w-full h-full" style= {background: "var(--slidev-slide-container-background, black)"} width=undefined  ... > 
  at <Play onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< {} > > 
  at <RouterView> 
  at <App>
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Slidev version: 0.13.10

**Comment by dizys** [comment]
This warn is related to #173

**Comment by mariomurrent-softwaresolutions** [comment]
Ah okay, thx ... so your slides also look like mine on the screenshot?

<img width="2044" alt="image" src="https://user-images.githubusercontent.com/5072806/119449985-9c686080-bd33-11eb-907a-f1b7770e3506.png">

**Comment by dizys** [comment]
Yeah, the same. I believe this is fixed by the PR, waiting for @antfu to take a look.

**Comment by mariomurrent-softwaresolutions** [comment]
What I actually don't unterstand, why this is also not working in version 0.10.5 - I downgraded to the version I was using before, but still the issue.

Anyway, waiting for your fix - thx :)

**Comment by dizys** [comment]
Great, v0.13.11 has been release. Upgrade to it and see if the problem has been resolved.
