### ISSUE TITLE
请问如何使用本地的图片资源呢？

### ISSUE THREAD

**Issue by 7ynstar** [slidevjs/slidev#178]
如题，系统环境 `Windows 10`，在 `Slidev` 中使用到本地的图片资源，尝试过 `markdown` 语法和 `Vue` 语法感觉都不能显示出来，文档中也没有看到相关的说明，请问应该如何操作呢？

**Comment by antfu** [comment]
https://cn.sli.dev/custom/directory-structure.html#public
