### ISSUE TITLE
shadows under some particular elements when exporting as pdf

### ISSUE THREAD

**Issue by zillionare** [slidevjs/slidev#1784]
**Describe the bug**

when I exported it as pdf, some elements has shadows under itself.

![image](https://github.com/user-attachments/assets/27634ea8-f2b4-4d02-baa4-8565704a2535)

the web page works as expected:

![image](https://github.com/user-attachments/assets/e80da4a8-c588-499f-b81a-cdadfcb7ec9c)

If I view this PDF on my phone, the display is normal.

**Minimal reproduction**

the layout.css:

```
:root {
    --slidev-theme-primary: #404040;
    /* --slidev-theme-secondary: #E60000; */
    --slidev-theme-secondary: #606060;
    --slidev-background-color: #fcfcfc;
    font-family: ZhuqueFangsong, sans-serif !important;

    .abs {
        position: absolute;
    }

}

.slidev-layout {
    text-justify: inter-character;
    text-align: justify;
    @apply h-full text-left text-$slidev-theme-primary;

    p+h2,
    ul+h2,
    table+h2 {
        @apply mt-10;
    }

    h1 {
        font-size: 6.3vw;
        color: var(--slidev-theme-secondary);
        margin: 9vw 0;
        line-height: 8vw;
        ;
    }


    h2 {
        text-align: left;
        font-size: 4.5vw;
        font-weight: 500;
        margin: 6.4vw 0vw;
        padding: 0.5vw 1vw;
        /* counter-increment: section; */
    }
}
```

omitted the rest since h2 already causes the problem.

**Environment**

- Slidev version: 0.49.16
- Browser: firefox, but no related
- OS: macos

**Comment by KermanX** [comment]
I think this can't be fixed by editing Slidev's code.

There is some chance that changing a PDF viewer will fix this.

**Comment by zillionare** [comment]
Verified it's PDF viewer. When viewing in firefox, it all looks well.

I'll try workaround here:

https://github.com/slidevjs/slidev/issues/1236

Thanks @KermanX
