### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by susmitpy** [slidevjs/slidev#1790]
**Describe the bug**

npm init slidev@latest
npm run build
Gives error

**Environment**

- Slidev version:  both 0.49.23, 0.49.24
- Browser: Error during build, running on dev
- OS: Mac OS M2

If you are using Slidev globally (i.e. `npx slidev` or `npm i -g slidev`), please try to reproduce the issue in a local project (i.e. `npm create slidev@latest`).

Error
  Slidev  v0.49.23

  theme       @slidev/theme-seriph
  css engine  unocss
  entry       /Users/susmitvengurlekar/projects/slidev/slides.md
vite v5.3.5 building for production...

<--- Last few GCs --->

[43860:0x158008000]    16820 ms: Mark-Compact 2030.2 (2083.1) -> 2023.4 (2080.2) MB, 334.62 / 0.00 ms  (average mu = 0.359, current mu = 0.242) allocation failure; scavenge might not succeed
[43860:0x158008000]    17223 ms: Mark-Compact 2031.2 (2087.9) -> 2025.6 (2098.3) MB, 396.79 / 0.00 ms  (average mu = 0.210, current mu = 0.018) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100b6cbf4 node::Abort() [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 2: 0x100b6cddc node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 3: 0x100cf0da8 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 4: 0x100ec56e8 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 5: 0x100ec41c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 6: 0x100eba9dc v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 7: 0x100ebb23c v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 8: 0x100e9fb04 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
 9: 0x100e938ec v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
10: 0x10103af18 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3>>::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
11: 0x10103ad94 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3>>::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
12: 0x10103b68c v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3>>::AddImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
13: 0x101039f74 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3>>::Add(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
14: 0x101100634 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
15: 0x1011799d4 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin, v8::internal::EnforceDefineSemantics) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
16: 0x101178464 v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
17: 0x10128ee44 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
18: 0x10128fe88 v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
19: 0x1015e4c44 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
20: 0x10786cf78
21: 0x10786f29c
22: 0x1015fcb3c Builtins_ArrayForEach [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
23: 0x10155c3e4 Builtins_InterpreterEntryTrampoline [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
24: 0x10155c3e4 Builtins_InterpreterEntryTrampoline [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
25: 0x10155c3e4 Builtins_InterpreterEntryTrampoline [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
26: 0x101593210 Builtins_AsyncFunctionAwaitResolveClosure [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
27: 0x101640fb8 Builtins_PromiseFulfillReactionJob [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
28: 0x101582b94 Builtins_RunMicrotasks [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
29: 0x10155a3f4 Builtins_JSRunMicrotasksEntry [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
30: 0x100e329f0 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
31: 0x100e32edc v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
32: 0x100e330b8 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
33: 0x100e5a284 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
34: 0x100e5aa20 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
35: 0x100a9cc64 node::InternalCallbackScope::Close() [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
36: 0x100a9c77c node::CallbackScope::~CallbackScope() [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
37: 0x100b3c174 (anonymous namespace)::uvimpl::Work::AfterThreadPoolWork(int) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
38: 0x100b3c568 node::ThreadPoolWork::ScheduleWork()::'lambda'(uv_work_s*, int)::operator()(uv_work_s*, int) const [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
39: 0x101538b64 uv__work_done [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
40: 0x10153c5b4 uv__async_io [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
41: 0x10154e68c uv__io_poll [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
42: 0x10153cb78 uv_run [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
43: 0x100a9d754 node::SpinEventLoopInternal(node::Environment*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
44: 0x100bac8d8 node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
45: 0x100bac674 node::NodeMainInstance::Run() [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
46: 0x100b37030 node::Start(int, char**) [/Users/susmitvengurlekar/.nvm/versions/node/v20.10.0/bin/node]
47: 0x18655e0e0 start [/usr/lib/dyld]

**Comment by KermanX** [comment]
Please try `NODE_OPTIONS=--max-old-space-size=8192 npm run build` to increase the max heap size

**Comment by susmitpy** [comment]
Working, Thanks !
