### ISSUE TITLE
Add Mermaid Zenuml Support

### ISSUE THREAD

**Issue by HenryZhang-ZHY** [slidevjs/slidev#1795]
**Describe the solution you'd like**
Mermaid can render sequence diagrams with [ZenUML](https://zenuml.com/).

**Comment by HenryZhang-ZHY** [comment]
https://mermaid.js.org/syntax/zenuml.html

**Comment by KermanX** [comment]
It is possible to register the ZenUML renderer for Mermaid via ['./setup/mermaid.ts'](https://sli.dev/custom/config-mermaid).
