### ISSUE TITLE
monaco-diff NOT working as expected

### ISSUE THREAD

**Issue by huyxvd** [slidevjs/slidev#1806]
**Describe the bug**

monaco-diff not working as expected

**Minimal reproduction**

in the slide put the code like this

```ts {monaco-diff}
console.log('Original text')
~~~
console.log('Modified text')
```

[reproduction with stackblitz](https://stackblitz.com/edit/github-7mje4q?file=slides.md)

![image](https://github.com/user-attachments/assets/093915ef-2a64-4b70-ad34-6466216cf349)

**Comment by KermanX** [comment]
A workaround is using the `height` prop:

````md
```ts {monaco-diff}{height:'60px'}
console.log('Original text')
~~~
console.log('Modified text')
```
````
