### ISSUE TITLE
HMR always leads to crashes

### ISSUE THREAD

**Issue by Wxh16144** [slidevjs/slidev#1821]
**Describe the bug**

Check the screenshot. Every time I modify the md file, it always crashes after saving.

**Minimal reproduction**

4. See the error

You can use https://sli.dev/new to create a new project to reproduce the issue.

**Environment**

- Slidev version: 0.49.25
- Browser: chrome latest
- OS: macos14

If you are using Slidev globally (i.e. `npx slidev` or `npm i -g slidev`), please try to reproduce the issue in a local project (i.e. `npm create slidev@latest`).

<img width="765" alt="image" src="https://github.com/user-attachments/assets/d49098a1-3ce2-4b50-9648-ef146b9f83f3">

**Comment by KermanX** [comment]
Sorry for this inconvenience. This has been fixed in the latest version.

**Comment by Wxh16144** [comment]
Good job 🎉
