### ISSUE TITLE
Chromium based browsers crash without warning

### ISSUE THREAD

**Issue by ChrisLaRocque** [slidevjs/slidev#1826]
**Describe the bug**

When running a Slidev presentation in a chromium-based browser (I tried Arc and Chrome), the browser will close without warning after an indeterminate amount of time. When restarting Arc I get the "Arc quit unexpectedly" error with the ability to report, but Chrome provides no error. Safari appears to be working.

**Minimal reproduction**

1. Create a new Slidev project
2. Run `slidev --open`
3. Wait until the browser crashes (thus far hasn't taken longer than 20 minutes)

**Environment**

- Slidev version: 0.49.26
- Browser: Chrome Version 127.0.6533.120 (Official Build) (arm64)
- OS: Mac OSX 14.5

**Comment by KermanX** [comment]
This seems to be a serious problem. However, I can't reproduce this on my Windows machine😭

I also think this is an upstream problem. Could you help check this by switching to the old dependencies via the `overrides` field in `package.json`?

**Comment by twitwi** [comment]
in the other issue reverting to 0.49.24 seems to be a workaround (using `"0.49.25",` , without any `^`, in package.json)

**Comment by ras0q** [comment]
Not sure if this is benefical, but I override vueuse (`@vueuse/core`, `@vueuse/math`) versions from v11 to v10 and it seems stable after 30 minutes of startup.

```json
// I'm using pnpm
{
  "pnpm": {
    "overrides": {
      "@vueuse/core": "10.11.1",
      "@vueuse/math": "10.11.1"
    }
  },
  "packageManager": "pnpm@9.7.1+sha512.faf344af2d6ca65c4c5c8c2224ea77a81a5e8859cbc4e06b1511ddce2f0151512431dd19e6aff31f2c6a8f5f2aced9bd2273e1fed7dd4de1868984059d2c4247"
}
```

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/f4543081-3106-45cd-a21e-2c903ce7b65c">

**Comment by KermanX** [comment]
> Not sure if this is benefical, but I override vueuse (`@vueuse/core`, `@vueuse/math`) versions from v11 to v10 and it seems stable after 30 minutes of startup.
> 
> relevant commit: [9a1e824](https://github.com/slidevjs/slidev/commit/9a1e824eb78827f9a3a68029a809dd989ecd6a75)

Thanks a lot for the information!

Does the issue still happen after setting `wakeLock: false` in headmatter?

**Comment by KermanX** [comment]
A new version released. Hopefully, everything will be fine now.

> Never use async inside `watchEffect`, especially when the async function is a DOM API 😭

**Comment by KermanX** [comment]
> Just out of curiosity, could you provide more details on why calling the localStorage API in `watchEffect` is not recommended?

I checked the code again and found that the async DOM API (in this issue, `avigator.wakeLock.request`), is not the cause.

Usually, we are not afraid of updating a `ref` inside `watchEffect`. For example, `watchEffect(() => { a.value++ })` will only run once when `a` is changed.

Even if there is an infinite loop like [this example](https://play.vuejs.org/#eNp9Uc9PwjAU/leaXoBIhkRPOEjUcNCDGvXYSylvMOzapn0FkmX/u28bg5kYbq/fj/b7+kr+6Fyyj8BnPA3K5w5ZAIxuIUxeOOuRlewgUW2XWQYKWcUybws2IMvgoafxkP3hhBFGWROQSTav2eHtqENWPUSY3u3D4YjNF6wUhjGZ7KWOQNJVO91MhamuOU46cpy8nSOdtM2oEx0QCqclAp0YS7fTRVlSxqpKJzT3sNUFSyc9Ex9zDFQkyzfJLlhDP9c8L7iyhcs1+HeHORUVfNYGqzmptT28Nhj6COMOV1tQP//gu3CsMcE/PATwexD8zKH0G8CWXn69wZHmM1nYddSkvkJ+QrA61hlb2VM0a4rd0zVpX5rd5mbzHZZHBBO6UnXQWlk1esFp389Xql/i3iX3jY/Wwqtfu/jQ6g==), the "Maximum recursive updates exceeded" error will be thrown by Vue - and then we can fix this immediately.

However, the infinite loop won't be detected after an async operation.

```ts
import { watchEffect, ref } from 'vue'

const a = ref(0)

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
}

async function f() {
  a.value++
  await sleep(0)
  a.value++
}

const enabled = ref(true)

watchEffect(() => {
  if (!enabled.value)
    return
  console.log('run')
  f()
})
```


This is not quite unexpected - Vue can't know the context after `await sleep(0)`. However, when `f` is provided by a 3rd-party library, it becomes hard to notice when writing the code.

**Comment by schauppi** [comment]
It´s working again with v0.49.27. Thx for the fast fix! :-)

**Comment by schauppi** [comment]
> It´s working again with v0.49.27. Thx for the fast fix! :-)

Update: I used it for an hour now and the same bug again.

**Comment by KermanX** [comment]
> Update: I used it for an hour now and the same bug again.

I can't reproduce in the new version 🤔

**Comment by twitwi** [comment]
I cannot reproduce either with 0.49.27 (I haven't tried for 30 minutes but it originally crashed right away)

**Comment by schauppi** [comment]
The problem continues even with version 0.49.27. I'm not sure why, but it worked for about 45 minutes before it stopped again, even after restarting the system.

**Comment by KermanX** [comment]
> The problem continues even with version 0.49.27. I'm not sure why, but it worked for about 45 minutes before it stopped again, even after restarting the system.

Does the workaround in https://github.com/slidevjs/slidev/issues/1826#issuecomment-2299198069 still useful, and can you confirm the version you're running?

**Comment by Boshen** [comment]
My chrome kept crashing after 5 minutes for the past two days while trying to record for my Vite conf talk 🥲 

<img width="395" alt="image" src="https://github.com/user-attachments/assets/42a949ce-ae75-4053-abe0-249ebab36b5d">


I'm on version `0.49.29`, used QuickTime Player for screen recording with slide'v builtin camera mode (so heavy CPU and memory usage).

My final successful attempt was `wakeLock: false`.

There may be a correlation with lock screen time as well ...

<img width="706" alt="image" src="https://github.com/user-attachments/assets/1829d527-8284-4322-9b53-00d5f68ce4a8">

---

I'm happy to help and triage further if you can tell me what to look for. I don't want the next person to have Chrome crashing 😅
