### ISSUE TITLE
将slidev嵌入网页

### ISSUE THREAD

**Issue by zhang-yunqi** [slidevjs/slidev#1834]
我希望能有一个便捷的方式能将slidev嵌入到博客网页中，在学校我常常有使用slidev做演示文稿的需求，但是学校不能带电脑在加上我的博客和我的演示文稿几乎是一一对应的，所以我十分希望可以有一个方便快捷的方式将slidev嵌入自己的网页中。再不济也希望可以在服务器部署以个便于管理多个slidev的面板，单个slidev就要占用一个端口有些太麻烦，而且还有每次重新部署。如果可以用面板来管理就好了

**Comment by KermanX** [comment]
编译成静态网页（参考 https://cn.sli.dev/guide/hosting），再部署到博客里，用iframe嵌入，是否可以？
