### ISSUE TITLE
Personal export for themes?

### ISSUE THREAD

**Issue by HamzaMoiyadi** [slidevjs/slidev#184]
Hi, 
I've created more or less my own theme by using `npm init slidev-theme`, 

I was wondering if there's a way I can use the theme in other repositories without publishing my theme on npm?

**Comment by antfu** [comment]
You can have them in the a common folder

```
/
  /A
  /B
  /my-theme
```

And then for `/A/slides.md`

```md
---
theme: ../my-theme
---
```
