### ISSUE TITLE
feat: Edit in Presenter mode

### ISSUE THREAD

**Issue by Decipher** [slidevjs/slidev#185]
**Is your feature request related to a problem? Please describe.**
Edit mode is available in display mode but not in presenter mode.
If you are doing a live presentation, it would be nice to be able to edit in the presenter view, and also preview the edit before the change appears.

**Describe the solution you'd like**
Enable edit mode on Presenter.
Add Presenter preview.
Add ability to edit the next slide before it's displayed.

**Describe alternatives you've considered**

**Comment by ASaiAnudeep** [comment]
To add more.. 

- Ability to edit code on the current slide on a live presentation from presenters mode.
- Ability to run the code on the current slide and display the results on the live presentation would be great.
