### ISSUE TITLE
Leading whitespace in code blocks breaks all subsequent highlighted codeblocks

### ISSUE THREAD

**Issue by EmNudge** [slidevjs/slidev#1867]
**Describe the bug**

If you have a leading white space in a codeblock, it will break the parser such that having subsequent **highlighted** codeblocks will crash the current slide.

<img width="629" alt="image" src="https://github.com/user-attachments/assets/28757460-b443-4f25-b0e4-8317d7605528">

This is an issue for assembly which often has leading whitespace. This is also where I encountered this problem.

**Minimal reproduction**

https://stackblitz.com/edit/github-sspw9v?file=slides.md=

````
block 1

```
 test
```

block 2

```js
const val = 42
```
````

**Environment**

- Slidev version: 0.49.29
- Browser: Chrome
- OS: MacOS

**Comment by zillionare** [comment]
Thanks for the report! I also encountered same exception this afternoon, but slightly different cause.

```python

print("hello world")
```

the leading blank line will cause same issue. Thanks to the report, provide me a clue.

**Comment by KermanX** [comment]
I am sorry for the late reply.

@EmNudge I've opened https://github.com/slidevjs/slidev/pull/1909 to allow leading whitespace in code blocks.

@zillionare In my opinion the leading empty lines are invalid. Because Slidev wraps code blocks before passing the code to the Markdown parser, we may not be able to handle them correctly.

**Comment by zillionare** [comment]
@KermanX 

Thank you for the answering my question. 

Although my example may not be syntactically correct, I believe many others might also be confused about the formatting requirements here. So, it would be helpful to keep this as a record.

It would be even better if there could be a section in the documentation or discussions dedicated to recording these invalid cases that people often make mistakes with.
