### ISSUE TITLE
Cannot find package 'vue-template-compiler'

### ISSUE THREAD

**Issue by cander0815** [slidevjs/slidev#1871]
Hello everyone, I tried to create a project using the command `npm init slidev@latest`. After running `npm install`, when I executed `npm run dev`, I encountered an error in the console:

`[vite] Pre-transform error: Cannot find package 'vue-template-compiler' imported from dir/slidev/node_modules/local-pkg/dist/index.mjs.`

 How should I go about solving this error?

If you need further assistance or more details about the error, feel free to ask.

Slidev： v0.49.29
nodejs: v20.11.0
os:      darwin arm64 m1

**Comment by nourakhy** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by cander0815** [comment]
I've already resolved the issue. To specify the required Vue version for icons, which is Vue 3 in this case, you can create a `vite.config.ts` file with the following code:

```
import { defineConfig } from 'vite'
export default defineConfig({
  slidev: {
    icons: {
      compiler: 'vue3'
    }
  },
})
```

**Comment by AlanQtten** [comment]
I have this issue at 0.50.0，I don't think this is `completed` @cander0815 maybe you can reopen it?

**Comment by liangmiQwQ** [comment]
I totally agree with @AlanQtten, I wonder that why the others don't meet the same question with us, if we all meet the problem i think I can make a pr to solve it
