### ISSUE TITLE
Cannot run slidev after npm initialization

### ISSUE THREAD

**Issue by christian-nils** [slidevjs/slidev#188]
(Please note that this "bug" is probably a misconfiguration on my side. I would appreciate some help to identify it.)

**Describe the bug**
Running `npm run dev` does not work, it fails to resolve entry for package `fs`. This error shows up since slidev@0.13.0. I have tried using nodejs v14 and v16. Same issue so it might not be related to https://github.com/slidevjs/slidev/issues/10.

Link to the pastebin of the error: https://pastebin.com/NDHnzp6B

**To Reproduce**
1. `npm init slidev`
2. Use the default options to generate the repository

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: N/A
 - Slidev version: > 0.13.0

**Comment by antfu** [comment]
Can't repro on my side. Does it work on v0.12.2?

**Comment by christian-nils** [comment]
Hi @antfu,

It did work on v0.12.2, but now I have an issue related to the function "loadTheme" that cannot be found (https://pastebin.com/e3vsLGp5).

For > 0.13.0, note that if I use `npm run build` and then `npx serve ./dist`, I do not get any issues.

I reinstalled nodejs/npm from scratch. But I still have the same issue.

Anyway, this issue seems to be only for me. Feel free to close the issue, I will continue to search the web and see if I can find the reason.

Thanks

**Comment by antfu** [comment]
> "loadTheme" that cannot be found

You will need to downgrade the theme, this is the theme using the new API

**Comment by christian-nils** [comment]
Yes, correct. Downgrading the theme works. So I can run slidev@0.12.2 now!

But I cannot understand why it does not work with higher versions.

**Comment by antfu** [comment]
So error occurs on 0.13.0 but not 0.12.2 right? Then I will try to find out why with then changes between them

**Comment by christian-nils** [comment]
Yeah, exactly, the problem starts with 0.13.0.

**Comment by christian-nils** [comment]
Ok, I found the issue. And I am ashamed. I had installed the `fs` package (for some reasons) and by removing it, I do not get any issue. So I can open Slidev@0.14.1 now. 

Thanks for your help @antfu, and sorry for the time wasted on this misconfiguration. Have a great day.
