### ISSUE TITLE
Scoped style with > selector causes error

### ISSUE THREAD

**Issue by lucascool12** [slidevjs/slidev#1888]
**Describe the bug**

Creating a slide with a style element using the `>` selector (e.g. `p > a`) causes an error.

**Minimal reproduction**

1. Go to https://sli.dev/new
2. Add the following to a slide:
```html
<style>
p > a {}
</style>
```
3. See the error
<details>
<summary> The error </summary>

```
[plugin:vite:vue] Tags with side effect (<script> and <style>) are ignored in client component templates.
```

</details>

**Environment**

- Slidev version: 0.49.29
- Browser: Firefox 118.0.1
- OS: Linux

**Comment by KermanX** [comment]
Looks like an upstream bug... The transformation logic in Slidev is correct.
