### ISSUE TITLE
`htmlAttrs.lang` seems not to be honored

### ISSUE THREAD

**Issue by porteneuve** [slidevjs/slidev#1894]
**Describe the bug**

Regardless of the `lang` setting I put inside the `htmlAttrs` setting object at the top of the first slide's frontmatter, the rendered layout, both dev and build, hardcodes `en`.

**Minimal reproduction**

1. Create a `slides.md`
2. Add the following in its frontmatter
3. Run the dev mode or build the output
4. Check out the `<html lang="en">` tag at the top of the `index.html`

**Environment**

- Slidev version: `@slidev/cli` 0.49.29
- Browser: any
- OS: OSX Sonoma 14.7

**Comment by KermanX** [comment]
Currently, the html attrs are dynamically loaded. That's why `lang` is left unchanged in the built `index.html`

**Comment by porteneuve** [comment]
I see! Indeed the DOM has the right value, so vocalization should work alright. Thanks!
