### ISSUE TITLE
VSCode Extension: cursor location move on save

### ISSUE THREAD

**Issue by fonnesbeck** [slidevjs/slidev#1907]
**Describe the bug**

After saving changes to a presentation with the extension activated, the cursor moves to a random/arbitrary location in the file. No matter where you place the cursor, saving the file always returns the cursor to this location, making using the extension somewhat disorienting. The location changes from time to time, for reasons I cannot determine.

**Minimal reproduction**

1. Make changes to `slides.md`
2. Save changes
3. Observe new cursor location unrelated to change

**Environment**

- Slidev version: v0.50.0-beta.4
- Browser: Chrome
- OS: Fedora 40

If you are using Slidev globally (i.e. `npx slidev` or `npm i -g slidev`), please try to reproduce the issue in a local project (i.e. `npm create slidev@latest`).

**Comment by KermanX** [comment]
I am afraid that I can't reproduce this problem. Could you disable all other extensions, and check the `editor.formatOnSave` setting and the formatter you're using?

**Comment by fonnesbeck** [comment]
Here's a screen capture of what's happening. After I type, I save using `ctrl-S` and you can see it jump to an arbitrary location. I do not have `formatOnSave` turned on.

https://github.com/user-attachments/assets/b5a4acb2-f038-4d95-9f49-0dbceddc939e
