### ISSUE TITLE
Support for unscaled iframes

### ISSUE THREAD

**Issue by tschaub** [slidevjs/slidev#1920]
**Is your feature request related to a problem? Please describe.**
The built-in `iframe` layout accepts a `scale` prop. I assumed that I could set this to 1 to embed an iframe without scaling. However, resizing the page shows that the iframe content is still scaled.

**Describe the solution you'd like**
I'd like to be able to embed an iframe without scaling.

**Describe alternatives you've considered**
I've created a custom `iframe-unscaled.vue` layout to reverse the scaling that is applied to slide content:
```html
<script setup lang="ts">
const props = defineProps<{
  url: string
}>();

const unscaledSize = 'calc(100% * var(--slidev-slide-scale))';
const unscaledTransform = 'scale(calc(1 / var(--slidev-slide-scale)))';
</script>

<template>
  <div class="h-full w-full">
    <div relative :style="{ width: unscaledSize, height: unscaledSize }">
      <iframe
        id="frame" class="w-full h-full"
        :src="url"
        :style="{ transform: unscaledTransform, transformOrigin: 'top left' }"
      />
    </div>
  </div>
</template>
```

I'm uncertain if making use of the `--slidev-slide-scale` CSS variable should be avoided. Ideally, I could pass a prop to the existing `iframe` layout to avoid scaling.

Here is an example that demonstrates the scaling of the current `iframe` layout: https://stackblitz.com/edit/slidev-iframe-unscaled?file=slides.md,layouts%2Fiframe-unscaled.vue (the preview needs to be opened in a dedicated tab for the iframes to load).

**Comment by antfu** [comment]
The scale is applied to the slide container, which is the parent of your iframe element, so it can be unscaled, unfortunately. The way I see it is indeed your approach to scale it back. And feel free to use `--slidev-slide-scale`, it's exposed for that purpose. (and maybe, just maybe,  you can even force override `--slidev-slide-scale` to 1 or something, but we can't promise the UI would keep working, which is on your responsibility if you go with that approach.)

**Comment by tschaub** [comment]
Thanks for the reply. Having an `iframe-unscaled` layout using the technique above is working well for me, so I'll close this.
