### ISSUE TITLE
Layout end is stuck in dark theme

### ISSUE THREAD

**Issue by Chadys** [slidevjs/slidev#1938]
**Describe the bug**

When you use a "layout: end" on a slide, that slide will be black, no matter if light or dark theme is selected.

This is because in `packages/client/layouts/end.vue` we explicitely set the classes `text-white bg-black`, which are not added to any other layout.

**Minimal reproduction**

1. Just add `layout: end` to any slide in https://sli.dev/new
2. That slide will become black

**Environment**

- Slidev version: v0.50.0-beta.5
- Browser: Firefox (bug is also seen in export result)
- OS: Mac OSX Sonoma 14.5

**Comment by KermanX** [comment]
I think this is intentional. In Microsoft PowerPoint, in presenting mode, after the last slide, the screen will also become black.
