### ISSUE TITLE
CORS error when using GitLab Pages without unique domain

### ISSUE THREAD

**Issue by irishismyname** [slidevjs/slidev#1941]
**Describe the bug**
If you use GitLab pages WITHOUT unique domains

![image](https://github.com/user-attachments/assets/9f18c531-8d1f-42c9-98bb-53bae501657b)

 your browser will report a bunch of CORS errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gitlab.com/oauth/authorize?client_id=<redacted>&redirect_uri=https://projects.gitlab.io/auth&response_type=code&state=<redacted>&scope=api. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302.
```

**Minimal reproduction**

1. Create a new project using `npm init slidev@latest`
2. Add a `.gitlab-ci.yml` file like [this](https://gitlab.com/ryans-tests/slidev-test/-/blob/f0f47815a720a51ca8658df99a5d97096c7d5afe/.gitlab-ci.yml).
3. Modify `package.json` to build to the `public/` folder instead of `dist/` like [this](https://gitlab.com/ryans-tests/slidev-test/-/commit/f0f47815a720a51ca8658df99a5d97096c7d5afe#7030d0b2f71b999ff89a343de08c414af32fc93a).
4. Turn off `Use unique domain` under Deploy -> Pages in GitLab.
5. Push all that to GitLab.
6. Go to the published page after the `pages:deploy` job finishes like this: https://ryans-tests.gitlab.io/slidev-test/

**Environment**

- Slidev version: 0.50.0-beta.5
- Browser: Firefox 128.4.0esr, Chrome 130.0.6723.117, Brave
- OS: Windows 10

**Comment by irishismyname** [comment]
For anyone else who comes across this problem:

you must set the [base path](https://sli.dev/guide/hosting#base) properly to resolve this.

**Comment by Nxt3** [comment]
For Vite users, I needed to add `base: './'` to my `vite.config.js`.
