### ISSUE TITLE
Best practice: how to add presentation custom info accessible in any component

### ISSUE THREAD

**Issue by christian-nils** [slidevjs/slidev#195]
Hi,

Is there a way to add some custom information related to the presentation in the markdown's headmatter and then access it in components?

I would like to create a footer component that would be added to all slides and it should display the author name added in the headmatter. I am thinking about other use cases, so I guess I would like to know if there is a generic way to add any type of info that can then be accessed in components. Is the key `themeConfig` what I am after? If yes, how can I access it in the component?

Thanks in advance ! :)

//CN

**Comment by antfu** [comment]
In v0.16.0, you can access the first frontmatter via `$slidev.configs` and `$slidev.themeConfigs` for `themeConfig` in Vue context.

**Comment by christian-nils** [comment]
Fantastic! Thanks @antfu !
