### ISSUE TITLE
bug: `pnpm run build` for slidev take a long time 

### ISSUE THREAD

**Issue by Zheaoli** [slidevjs/slidev#1956]
**Describe the bug**

```text
╰─ pnpm run build     

> pycon-china-2024@ build /home/manjusaka/Documents/projects/pycon-china-2024
> slidev build



  ●■▲
  Slidev  v0.50.0-beta.7 

  theme       @slidev/theme-seriph
  css engine  unocss
  entry       /home/manjusaka/Documents/projects/pycon-china-2024/slides.md
vite v5.4.11 building for production...

```

The command stop here for more than 10mins

**Minimal reproduction**

1. run `pnpm run build`

You can use https://sli.dev/new to create a new project to reproduce the issue.

**Environment**

- Slidev version:  v0.50.0-beta.7 
- Browser:  Chrome 
- OS: Linux 

If you are using Slidev globally (i.e. `npx slidev` or `npm i -g slidev`), please try to reproduce the issue in a local project (i.e. `npm create slidev@latest`).

Here is the this repo https://github.com/Zheaoli/pycon-china-2024

**Comment by KermanX** [comment]
This seems like a Rollup bug similar to https://github.com/rollup/rollup/issues/5734. A possible workaround is adding the following to your `package.json`, then run `npm i`:

```json
  "resolutions": {
    "rollup": "4.27.3"
  },
```

**Comment by Zheaoli** [comment]
Thanks for the tips! it's work!
