### ISSUE TITLE
How to enable content selection?

### ISSUE THREAD

**Issue by madlogos** [slidevjs/slidev#196]
**Is your feature request related to a problem? Please describe.**
Now it seems impossible to select and copy contents directly from the slides unless exporting it to a pdf or SPA. But I currently keep failing to export PDFs or SPAs for timeout errors reported elsewhere. I think text selection is pretty reasonable requirements for presentation slides. 

**Describe the solution you'd like**
I expect there is some solution to enable content selection.

**Describe alternatives you've considered**
I noticed the code in the line 62, /node_modules/@slidev/client/internals/SlideContainer.vue has `@apply ... select-no`. But even if I changed it to `select-text` or `select-all`, I still cannot select and copy the contents.

**Comment by dizys** [comment]
Texts are unselectable by default for many presentation apps like PowerPoint, Keynote.

In Slidev, one solution to make part of your text to be selectable is to use markdown code syntax (enclosing it in backticks), like this `selectable in Slidev`.

Or,

~~~
```
Code blocks are selectable by default, too.
```
~~~

**Comment by antfu** [comment]
Think maybe we can have an option for that.

**Comment by naquiroz** [comment]
This is not working anymore
