### ISSUE TITLE
VSCode Autoformat Breaks Metadata

### ISSUE THREAD

**Issue by titouandk** [slidevjs/slidev#1981]
I use VSCode and Prettier to format files on save.

The following markdown code:

```
---
src: ./pages/imported-slides.md
hide: false
---
```

...is transformed into:

```
---

src: ./pages/imported-slides.md
hide: false

---
```

This leads to the code being parsed as a new slide, instead of metadata.

**Comment by KermanX** [comment]
You can use our prettier plugin: https://sli.dev/features/prettier-plugin, or use tour vscode extension to format the code.

**Comment by titouandk** [comment]
Thank you!
