### ISSUE TITLE
All paragraphs in a slide don't have the same color

### ISSUE THREAD

**Issue by Bktero** [slidevjs/slidev#205]
**Describe the bug**

All paragraphs in a slide don't have the same color.

**To Reproduce**

`slides.md`:

```markdown
---
layout: default
---
# Slide 1

All paragraphs should have the same colors.

---
layout: default
---
# Slide 2

All paragraphs should have

the same colors.
```

Slide 1:

<img width="300" alt="slide1" src="https://user-images.githubusercontent.com/1047370/120224665-2a68ad80-c244-11eb-841c-e44dbe2e3469.png">

Slide 2:

<img width="204" alt="slide2" src="https://user-images.githubusercontent.com/1047370/120224669-2c327100-c244-11eb-922f-fc0b0c527b43.png">

Both lines should have the same style and hence the same colors.

If this is the expected behavior, then I think it is quite not natural for the default theme.

**Desktop (please complete the following information):**
- OS: Windows 10
- NodeJS: 14.17.0
- Browser: Chrome 90.0.4430.212

`package.json`:

```json
{
  "private": true,
  "scripts": {
    "dev": "slidev --open",
    "build": "slidev build",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.16.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
  },
  "name": "slidev"
}
```

**Comment by antfu** [comment]
Yes, this is by design. The first `p` is treated as subheader. https://github.com/antfu/themes/blob/63a9dc971c3c7e4207d32832e534ddc1063328e1/packages/theme-default/styles/layouts.css#L9-L11

You can eject the theme and modify it to fit you need. https://sli.dev/themes/use.html#eject-theme

**Comment by Bktero** [comment]
Seems a weird choice to me but OK :)

The level of subheading is unclear to me. Indeed, the 4 followings slides are different:

```
---
layout: default
---
# Slide 1

This is a sub header

This is the first real paragraph

---
layout: default
---
# Slide 2

## This is a sub header

This is the first real paragraph

---
layout: default
---
# Slide 3

### This is a sub header

This is the first real paragraph

---
layout: default
---
# Slide 4

#### This is a sub header

This is the first real paragraph
```

<img width="781" alt="slidev_headers" src="https://user-images.githubusercontent.com/1047370/120227551-a9acb000-c249-11eb-8fd9-46bc4440d5eb.png">

**Comment by jpambrun** [comment]
This looks really silly, even broken, by default. Broken enough that I spend time looking for open issues. You should reconsider..

**Comment by iliocatallo** [comment]
Hi,

A workaround is to introduce an empty sub header, as in:

```
# Title
##

Text
```

But I agree it would be better to treat all `p`s consistently.
