### ISSUE TITLE
Unexpected numbers of slides when two "src:" are used in a row.

### ISSUE THREAD

**Issue by Bktero** [slidevjs/slidev#206]
**Describe the bug**

If I have two sub *.md files are try to include thel with 2 "src:" commands in a row, I get more slides that expected.

**To Reproduce**

`slides.md`:

```markdown
---
src: sub/page1.md
---

This is ignored.

---

---
src: sub/page2.md
---

This is ignored.

---
```

Files `sub/page1.md` and `sub/page2.md` are from https://github.com/slidevjs/slidev/tree/main/test/fixtures/markdown/subs.

Expected behavior:

- There are 2 slides in the presentation

Observed behavior:

- There are 4 slides in the presentation

<img width="852" alt="slidev_src" src="https://user-images.githubusercontent.com/1047370/120225556-bd561780-c245-11eb-8b10-6fefa19b2f81.png">

** Additional comments***

I guess the problem is in fact when a slide with "src:" is followed by a slide with front matter block. Indeed, the following `slides.md` behaves weirdly:

```markdown
---
src: sub/page1.md
---

This is ignored.

---

---
layout: cover
---

This is ignored.

---
```

**Desktop (please complete the following information):**
- OS: Windows 10
- NodeJS: 14.17.0
- Browser: Chrome 90.0.4430.212

`package.json`:

```json
{
  "private": true,
  "scripts": {
    "dev": "slidev --open",
    "build": "slidev build",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.16.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
  },
  "name": "slidev"
}
```

**Comment by Bktero** [comment]
Maybe there are too many `---` in my file, as this one renders properly:

```
---
src: sub/page1.md
---

This is ignored.

---
src: sub/page2.md
---

This is ignored.
```

**Comment by antfu** [comment]
Meaning this?

```md
---
src: sub/page1.md
---

This is ignored.

---
src: sub/page2.md
---

This is ignored.
```

**Comment by Bktero** [comment]
Yes.

I have runned into weird behaviors with src today. Not sure how to reproduce them to understand if I don't use them correctly or if there are buggy.

I close this ticket for the moment, sorry for the noise ;)
