### ISSUE TITLE
LaTeX not supported in HTML divs

### ISSUE THREAD

**Issue by Ahacad** [slidevjs/slidev#207]
**Describe the bug**
When wrapping contents inside HTML divs or similar tags, LaTeX rendering no longer works.

**To Reproduce**
1. Create a new slidev project
2. Create a new page, with structures like:
```
# Title

<div>
$a + b = c$
</div>
```
3. Dollar signs will be rendered, and no LaTeX output

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome 90
 - Slidev version: 0.16.0

**Expected Solution:**

I need the divs to implement customized styles, so LaTeX needs to be rendered inside of them, I would like to know how.

**Comment by antfu** [comment]
Tried?

```md
<div>

$a + b = c$

</div>
```

**Comment by Ahacad** [comment]
Thanks, works like a charm.
