### ISSUE TITLE
upgrade mermaid

### ISSUE THREAD

**Issue by ameinhardt** [slidevjs/slidev#211]
**Is your feature request related to a problem? Please describe.**
gantt.sectionFontSize doesn't work for me in mermaid = 8.5.0

**Describe the solution you'd like**
Allow newer minor version of mermaid, e.g.  ^8.10.1

**Describe alternatives you've considered**
using a combination of setup/mermaid.ts and !important style rules

**Comment by antfu** [comment]
Currently we are having some issue with the integration of mermaid greater than v8.5. If you want, maybe you can give it a try and I am more than happy to review the PR. Thanks

**Comment by christian-nils** [comment]
But you cannot use `gantt.sectionFontSize` because the types for mermaid are outdated, or?

Can't you just use this in your stylesheet instead?

```css
.mermaid .sectionTitle > tspan {
  @apply text-sm;
}
```

**Comment by ameinhardt** [comment]
the mermaid css is scoped and thus its theme takes precedence. It's possible to use `theme: 'null'` in mermaid config and link a custom mermaid style in slidev theme, though.
