### ISSUE TITLE
Export presentation to other formats than PDF

### ISSUE THREAD

**Issue by christian-nils** [slidevjs/slidev#213]
Hi!

I am just wondering if we could extend the list of export formats. PDF is great, but some of my colleagues are used to have PPTX. I checked around and it seems that MARP can export MD to different extensions.

I do not know how hard it would be to add some formats to the Sli.dev export. I guess I could use [MARP-CLI](https://github.com/marp-team/marp-cli) otherwise. What do you think?

Thanks,

Greetings,

CN

**Comment by antfu** [comment]
Maybe you can try with this lib https://github.com/gitbrent/PptxGenJS or some other tools to convert PDF to PPTX. But honestly, I would not recommend it as you will lost most of the awesome parts of Slidev for example animations, components and interactivities. That said, giving the support for pptx is quite complex to handle correctly and kinda little to gain from my point of view, we are not likely to have built-in support for that. Thanks for bringing this up.

**Comment by christian-nils** [comment]
Yep, I understand! If it were only me, I wouldn't care much about PPTX ;) Thanks for your input! Have a great day.

/CN
