### ISSUE TITLE
named slots don't work

### ISSUE THREAD

**Issue by ksnyde** [slidevjs/slidev#215]
## Description

I want to have columnar based flow on certain pages, I had hoped to be able to just add a layout with the default slot and a named slot (aka, "right"). I can add the layout and the slide renders with this theme:

![image](https://user-images.githubusercontent.com/980757/120586747-ebc02800-c3e8-11eb-8a5c-2a5c0a4b7a2d.png)

But as soon as I put in the named slot content into the slide it crashes:

```md
<template #right>
    Content on the right
</template>
```

Although I prefer the `#right` shorthand syntax I recognize that this could cause issue with Markdown parsing as it's non-standard syntax but the full syntax `v-slot:right` produces the same results.

The resultant error message is:

> [vite] Internal server error: Cannot read property 'line' of undefined
 > Plugin: vite:vue
 > File: /@slidev/slides/2.md

## Preferred Solution

I just want to be able to leverage the power of named slots in _layouts_ using normal Vue syntax. Because this is probably a pretty common need/desire for presentations, it might be supplemented by use of some Markdown shortcuts such as:

```md
::left

Content on the left

::right

Content on the right
```

any opportunity to keep Markdown free of HTML bracket tags to me is a nice improvement so the above syntax seems cooler than having to use formal slot syntax but this is more icing on the cake. The key issue right now is only being able to target one part of the page. Yes, markdown has "table support" but this is very limited for most/many slot based designs.

**Comment by ksnyde** [comment]
Note: don't think there's anything wrong with my layout file but just for context it is defined as:

```vue
<template>
  <div class="slidev-layout two-columns w-full h-full grid grid-cols-2">
    <div class="slidev-layout default" :class="props.class">
      <slot />
    </div>
    <div class="slidev-layout default" :class="props.class">
      <slot name="right">
        To add content to right column use the template slot named `right`.
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from "vue";

const props = defineProps({
  class: {
    type: String,
  },
  /** the width of the right column */
  width: {
    type: String,
  },
});
</script>
```

**Comment by antfu** [comment]
I like the slot sugar, great idea! Wanna give it a try to make a PR?

(tho I am still not sure how should we extend the markdown syntax properly, but so far it looks good to me!

**Comment by antfu** [comment]
Emm, I will do this now. Thanks for bringing this up!

**Comment by antfu** [comment]
Supported in v0.18.0, with this style:

```md
::default::

Content on the left

::right::

Content on the right
```

`::default::` is optional

**Comment by ksnyde** [comment]
Awesome! Woke up this morning and this is not only done in a basic sense but also with the syntactic sugar _and_ a built in layout! Great stuff and thanks.
