### ISSUE TITLE
`v-click`, `v-after`, and `v-click-hide`

### ISSUE THREAD

**Issue by ksnyde** [slidevjs/slidev#217]
## Description

I find the description of `v-link` fine and intuitive but after that it goes down hill pretty quickly and there are no examples to go in the docs or the test skeleton you get when you create. I did try to use `v-after` but must admit it still made no sense to me.

More fundamentally I think there is an attempt to treat click transitions as a 2-state problem when in fact it is at a minimum a 3 state problem. The states are:

> Note: I am ignoring the _initial_ state when a user first enters the slide; this might be considered too but it probably better left as a "non-click block" and therefore not a part of scope of this feature request directly

0. [ unclicked ] The click blocks which are not yet "in scope" (which typically means _not yet visible_)
1.  [ current ] The most recent "click" block
2.  [ clicked ] The click blocks which have been brought into scope but are not the "current" item

Currently state **clicked** and **current** are represented by CSS classes but not the **clicked** state. I believe it is _very_ desirable to distinguish between **current** and **clicked** for two key reasons:

1.  **Focus:** Presenters often want to "dim" prior clicked states so that the focus of the audience can be maintained 
2. **Space Management:** sometimes you just want the prior blocks to "disappear"; the advantage being that you can reclaim the vertical space

### Preamble
As I am currently a bit unclear on the intent of `v-after` and `v-click-hide`, I may be missing features that this solution does not provide but my goal is to reduce the primitives down to just one: `v-click`.

### Proposed changes to `v-click`

1. Allow for indexation with property on `v-click`:

    ```html
    <v-click index="1" />
    ```

    Allows you to state the step count in which the given block will be brought into scope. This is intended to work with the functionality exposed in `<v-clicks>` but for a single block element instead of a list.

2. Provide `hide` boolean flag:

    ```html
    <v-click hide />
    ```

    Inverts the behavior of the block. Instead of starting out hidden, it starts out visible but then becomes hidden when clicked.

3. Provide `after` class prop:

    ```html
    <v-click after="text-gray-300" />
    ```

    Provides an alternate way of styling the different click states that matches up well with WindiCSS's super powers while at the same time providing a shorthand for styling at the _per block_ level (this can often be desirable)

4. Provide `current` and `before` class props:

    ```html
    <v-click before="opacity-10" current="opacity-100" after="opacity-50" />
    ```

    Kind of self-explanatory at this point. I called out `after` first because I think it would end up being the most used but all three could be very useful.

> Note: the **before**, **after**, and **current** props proposed here are intended to be _additive_ to the CSS classes below

### CSS to _state_ mapping

| State        |       CSS Class(es)                             |     with `hide`           | 
| ---------  | ------------------------                  | ---------------        |
| unclicked | slidev-vclick-hidden                         | slidev-vclick-target |
| current     |  slidev-vclick-target slidev-vclick-current | slidev-vclick-hidden slidev-vclick-current |
| clicked     |  slidev-vclick-target slidev-vclick-prior     | slidev-vclick-hidden slidev-vclick-prior

## In Closing

I think this would add a lot of intuitive and powerful features to **Slidev** and I'd hesitantly consider creating a PR for it but having just started looking at the code and much of the mechanics of how meta props within "clicks" works remains opaque. I would need some pointers to really tackle this (and I'm desperately poor in time currently). That is _not_ me saying I wouldn't be willing to consider the PR ... just that I have limitations at the moment which I can't ignore.

**Comment by jkomyno** [comment]
Hey @antfu, this seems a very interesting proposal. Have you had time to read this?

**Comment by antfu** [comment]
Sounds good, open for PR.

> 1. `<v-click index="1" />`

Meaning this one https://sli.dev/guide/animations.html#ordering? You can do `<v-click at="1" />` already

> I would need some pointers

This is actually a bit tricky, basically, this functionality it powered by [`v-click` directive](https://github.com/slidevjs/slidev/blob/1e40ca8015e1d3e1ac07ca1f5d04edbd61c2b006/packages/client/modules/directives.ts), using the `inject` to access the shared context. `<v-click/>` and `<v-clicks/>` are [component wrappers](https://github.com/slidevjs/slidev/blob/14b8509f6206aaf23a27da287225a82017bbd7e1/packages/client/builtin/VClicks.ts) of `v-click` directive.

**Comment by WingLim** [comment]
I think the `unclicked` state should have `slidev-vclick-target` class too.
It is use for css selector to find the `v-click` element.
So, the pr I make doesn't remove it, just add `slidev-vclick-prior` and `slidev-vclick-current`

**Comment by WingLim** [comment]
With #277 merged, now we have `slidev-vclick-prior` and `slidev-vclick-current` class state.

And `hide` prop can be used in `<v-click>` and `<v-clicks>`.

**Comment by antfu** [comment]
I think #277 already covered most of the cases, closing now and feel free to bring up in another thread if you think anything is missing. Thanks.
