### ISSUE TITLE
notebook cell element

### ISSUE THREAD

**Issue by Roger-luo** [slidevjs/slidev#219]
Hi, first I have to say this is a very nice work! thanks for making this.

In most of the developer presentations, I believe it happens that one needs to demonstrate some code,
which is a cool feature for jupyter notebooks with [revealjs](https://revealjs.com/) via the [RISE plugin](https://rise.readthedocs.io/en/stable/).
This makes demonstrating a piece of code reactively a lot easier, so that one do not need to copy the code inside the slide to a terminal REPL window
manually. So I believe it would be nice if slidev could have this.

However, the RISE plugin has a very limited layout one could choose and do not have other nice features slidev has.

I'm thus thinking if there could be a slidev component that allows one to insert a notebook cell anywhere they like, e.g
for the compiled HTML element there could be a class of cell denote which `div` is the cell,

```html
<div class="notebook-cell"></div>
```

this `div` should save the output produced by excuting the inner code cell.
and for markdown syntax, it could be a special code block like how monaco works

    ```js {cell}
    const count = ref(1)
    const plusOne = computed(() => count.value + 1)
    
    console.log(plusOne.value) // 2
    
    plusOne.value++ // error
    ```

potentially this could connect to a jupyter notebook kernel, or just run on its own communication
kernel and in the export mode, we can save the results as HTMLs and force the cell to be converted
to a static code block.

I know there might be some related work done in the Julia-based notebook Pluto: https://github.com/fonsp/Pluto.jl
but it's less general for other languages since it doesn't aim to support other languages, and does not focus on writing
slides.

**Comment by manniL** [comment]
I agree that some way of running code would be a nice addition. It doesn't necessarily have to be "as complex" as a Jupyter Notebook cell. A simple "run" button as seen on [https://javascript.info/string#getting-a-substring](javascript.info) for example would be sufficient IMO.
