### ISSUE TITLE
HMR failed after change slides.md

### ISSUE THREAD

**Issue by ChenLuoi** [slidevjs/slidev#221]
**Describe the bug**
I start a new project use "npm init slidev@latest" , and change nothing. I just start to developing use "npm run dev".
Every times I change the slides.md，a new page open in the browser instead of HMR.
Downgrade to 0.18.1, HMR is ok.

**To Reproduce**
1. start a new project user "npm init slidev@latest" and npm i
2. Run "npm run dev"
2. open a page in the browser automatically
3. change some text in the slides.md
4. a new page open in the browser, and the console show the log: "restarting on config change"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 91.0.4472.77
 - Slidev version: 0.19.5

**Comment by Ahacad** [comment]
Same problem, slidev v0.19.5, OS: Arch Linux 5.12.8, Browser: Chrome 90

**Comment by antfu** [comment]
Should be fixed in 0.19.6, wrong closing number in the commit 😅
