### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by TutoDS** [slidevjs/slidev#229]
I create a **Sli.dev** project with yarn, and when I open my screen are blank

In console I not have any error. I'm using a macOs.
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/18479474/121076088-d6e9e880-c78a-11eb-91ce-4a57f0f27589.png">

**Comment by ali-commits** [comment]
Same problem with me. I tried creating slidev with npm but I have black page. it was working very will yesterday.
I am running Manjaro linux and brave browser.

**Comment by TutoDS** [comment]
> Same problem with me. I tried creating slidev with npm but I have black page. it was working very will yesterday.
> I am running Manjaro linux and brave browser.

I already try Brave, Safari, Firefox, Google Chrome and Edge.
Noting work...

**Comment by Proteusiq** [comment]
As Pythonista, we thought our nodejs world was terrible as we could not get to work. I am happy to here that I am not alone. Is any previous versions still working?

**Comment by TutoDS** [comment]
> As Pythonista, we thought our nodejs world was terrible as we could not get it to work. I am happy to here that I am not alone. Is any previous versions still working?
> 
> Tried on Ubuntu 20.04, Windows 10, Windows 10 WSL(Ubuntu 18.04): all give black screen.

Yea, already try generate a bunch of projects, all give a blank screen

**Comment by vecerek** [comment]
@Proteusiq the same result here, tried on a MacOS; I also tried an older version (0.18.1) in hope that a severe bug was introduced just recently but it did not change the result. I did not dare trying an even earlier release 😅

**Comment by jonasclaes** [comment]
I can confirm this issue as well. Running on Pop! OS 20.10, Node installed through NVM (Node Version Manager).

**Comment by Darth-Knoppix** [comment]
Got the same with, tried editing the `slides.md` and hot reloading worked as expected and shows the presentation.

Using Node: v14.16.0 on MacOS, testing with Chrome 91.0.4472.77

**Comment by TutoDS** [comment]
> Got the same thing but, tried editing the `slides.md` and hot reloading worked as expected and shows the presentation.
> 
> Using Node: v14.16.0 on MacOS, testing with Chrome 91.0.4472.77

For me the hot reloading not working

**Comment by TutoDS** [comment]
Sometimes I receive this error: 
`<project>/node_modules/@slidev/client/internals/Goto.vue has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.`

**Comment by vecerek** [comment]
Adding a `height: 100%` to the `#slide-container` element shows the content.

**Comment by sugatoray** [comment]
I don't know, but could this be related to what I mentioned in this discussion? https://github.com/slidevjs/slidev/discussions/231

**Comment by TutoDS** [comment]
> Adding a `height: 100%` CSS rule to the `#slide-container` element shows the content.

Now appears `node_modules/@slidev/client/internals/SelectList.vue has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.`

**Comment by antfu** [comment]
Some dependencies issues, can you try with v0.16.9 to see if it's fixed? Thanks

**Comment by TutoDS** [comment]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/18479474/121125533-9b006300-c81e-11eb-8cde-28b3baa4452a.png">

And this vite error? Any solution?

**Comment by TutoDS** [comment]
@antfu  after change to 0.16.1 (not appears to me 0.16.9) the animations and highlighting not working

```
---
layout: image-right
image: https://source.unsplash.com/collection/94734566/1920x1080
---

# Code

Use code snippets and get the highlighting directly!

```ts {2,3|all}
function add(
  a: Ref<number> | number,
  b: Ref<number> | number
) {
  return computed(() => unref(a) + unref(b))
}
```

<arrow v-click="3" x1="400" y1="420" x2="230" y2="330" color="#564" width="3" arrowSize="1" />
```

this is my code, and animations not run and not highlight the code

**Comment by antfu** [comment]
It's due to Vue 3.1, which I haven't find the way to fix it. Downgraded to fixed v3.0.x in v0.16.9

**Comment by TutoDS** [comment]
> It's due to Vue 3.1, which I haven't find the way to fix it. Downgraded to fixed v3.0.x in v0.16.9

<img width="490" alt="image" src="https://user-images.githubusercontent.com/18479474/121130201-faae3c80-c825-11eb-9462-5d449603c596.png">
 But in versions of slidev not appear 0.16.9 only 0.16.1 and 0.17.0

**Comment by antfu** [comment]
Ah, sorry I mean v0.16.8

**Comment by Proteusiq** [comment]
@vecerek, that works. Is it possible to make the changes permanent?

**Comment by vecerek** [comment]
@Proteusiq not as far as I can tell. It would require a fix in the project and a new release. The CSS rule should persist across the pagination through the slides, though. So as long as you set the rule before presenting, it should be alright. Refreshing the page would override it, though.
