### ISSUE TITLE
Markdown-it customization

### ISSUE THREAD

**Issue by m4dz** [slidevjs/slidev#234]
Hi there,

**Is your feature request related to a problem? Please describe.**
I want to add the `"breaks": true` rule to markdown-it, but can't find a proper way to customize the configuration. Am I missing something?

I found https://github.com/slidevjs/slidev/blob/e165df0889e030225a2ff065f8d2c8f7006ef0c2/packages/slidev/node/plugins/markdown.ts#L84 but it seems that `mdOptions` are directly herited from the cli call, and be passed at this point.

**Describe the solution you'd like**
In case we can't easily customize markdown-it, and as it's a preset built-in plugin, I suggest we rely on a dedicated file: `setup/mardown-it.ts`  (i.e. like `setup/windicss.ts`) that allow to add custom configuration to makrdown-it, like plugins to use or custom setup in options.

Thanks!

**Comment by antfu** [comment]
Yeah, we could have it. Open for PR, thanks

**Comment by antfu** [comment]
https://sli.dev/custom/config-vite.html#configure-internal-plugins

**Comment by m4dz** [comment]
Woo-hoo, awesome ✨! Thanks 🙏
