### ISSUE TITLE
能否支持多个md文件？

### ISSUE THREAD

**Issue by mxchenxiaodong** [slidevjs/slidev#235]
文档中说：”Slidev 会读取位于项目根目录的 slides.md 文件“.

请问是否表示一个 Slidev 项目中不能支持多个md文件转换成对应的多个样式文档？
或者可以支持？能够给点思路？

**Comment by antfu** [comment]
https://cn.sli.dev/guide/syntax.html#multiple-entries

**Comment by alexwanng** [comment]
同样关注这个问题， 不支持多个文件意味着每次都要新建一个项目， 太傻了。

**Comment by alexwanng** [comment]
> > 可以支持多个 ppt 嘛， 举个例子： 下面有 slide1.md, slide2.md，slide3.md
> > 开发(或发布后)访问： http://localhost:3000/#/slide1/1 http://localhost:3000/#/slide2/1 http://localhost:3000/#/slide3/1
> 
> 貌似不行。可能我没发现~ 目前我的做法是：
> 
> * npx slidev build 'markdowns/learn_ruby.md' --base="learn_ruby" --out='docs/learn_ruby‘
> * npx slidev build 'markdowns/learn_rails.md' --base="learn_rails" --out='docs/learn_rails'
> * npx slidev build 'markdowns/learn_vue/doc.md' --base="learn_vue" --out='docs/learn_vue'
> * ...
> 
> 在同一slidev项目里，指定不同的md文件。 然后部署后，都是访问docs里面的文件。


同样关注这个问题， 不支持多个文件意味着每次都要新建一个项目， 太傻了。
