### ISSUE TITLE
Hello, when can Plantuml be supported？

### ISSUE THREAD

**Issue by jaxon-hub** [slidevjs/slidev#236]
When I was using SLIDEV, I wanted to insert PLANTUML to make some flowcharts, but found it was not supported.
Hope you can support Plantuml, thank you

**Comment by antfu** [comment]
We already have Mermaid https://sli.dev/guide/syntax.html#diagrams, isn't it enough for your cases?

**Comment by tonyho** [comment]
> We already have Mermaid https://sli.dev/guide/syntax.html#diagrams, isn't it enough for your cases?

The plantuml is much powerfull than the mermaid. Still hoping the slidev can support the PlantUML.

**Comment by antfu** [comment]
Note PlantUML is written in Java, while Slidev is using JavaScript and Node. I guess this might be still possible to integrate on server side, but I will left it to the community as we don't want to force ppl to have Java env in order to use Slidev. Closing for now.

**Comment by tonyho** [comment]
> Note PlantUML is written in Java, while Slidev is using JavaScript and Node. I guess this might be still possible to integrate on server side, but I will left it to the community as we don't want to force ppl to have Java env in order to use Slidev. Closing for now.

The plantUML has a public server, which can be used without Java env.

Just a tips, may be useful, we can refer some Pandoc plantuml fiters, which would generate the UML png then convert the markdown to PDF with latex backend engines.
