### ISSUE TITLE
feat: Video templates

### ISSUE THREAD

**Issue by Decipher** [slidevjs/slidev#238]
**Is your feature request related to a problem? Please describe.**
It's easy to fullscreen and 50/50 with images, but not videos, which would be a useful feature for remote conferences.

**Describe the solution you'd like**
Add fullscreen and 50/50 video/iframe layouts.

**Describe alternatives you've considered**
Using `full` and doing the code myself.

**Comment by antfu** [comment]
> Using full and doing the code myself.

Which I think, would be the best way to handle all the use cases, otherwise, maybe we can discuss with a proposal PR, thanks

**Comment by Decipher** [comment]
I actually couldn't use `full` to do it, as it doesn't seem the `h-full w-full` are passing through correctly, but I did eject the theme and create some layouts.

I'll likely followup with a PR for some youtube layouts and some iframe layouts.
