### ISSUE TITLE
howto achieve same layout for different resolutions?

### ISSUE THREAD

**Issue by draptik** [slidevjs/slidev#242]
**Describe the bug**
When displaying slides the layout is different depending on the screen resolution. I'm not sure if this is a bug. If it's not a bug: what would be the recommended best-practice to deal with this situation?

**To Reproduce**
1. Create a new folder
2. `npm init slidev@latest`
3. Replace `slides.md` with minimal example (sse below)
4. Repeat on machine with different screen resolution

Screenshot with resolution 3840x2160:

![slidev-4k-3840x2160](https://user-images.githubusercontent.com/313058/121423283-613f7180-c970-11eb-94e6-ba426d096800.png)

Screenshot with resolution 1920x1080:

![slidev-non-4k-1920x1080](https://user-images.githubusercontent.com/313058/121423336-6ef4f700-c970-11eb-9e95-a82dbb533e28.png)

Minimal `slides.md` file:

```markdown
---
theme: default
layout: default
---

# This is a long title, but it's on a single line with 4k

There are 13 bullet points

- foo01
- foo02
- foo03
- foo04
- foo05
- foo06
- foo07
- foo08
- foo09
- foo10
- foo11
- foo12
- foo13
```

**Desktop**
 - OS: Arch Linux x86_64
 - Browser: Chromium Version 91.0.4472.77 (Official Build) Arch Linux (64-bit)
 - Slidev version: 0.20.1

**Comment by antfu** [comment]
Do they have different DPI? It's weird as this shouldn't happened - which is also work fine to me

**Comment by draptik** [comment]
@antfu yes, they have different dpis.
What is the best format for providing further debug infos?

**Comment by antfu** [comment]
I can't reproduce on macOS when changing the dpi. Maybe you can pull down the source and try to debug out, pointer here:
https://github.com/slidevjs/slidev/blob/62de84836a0d28b596a45199a0191a74bc95a556/packages/client/internals/SlideContainer.vue#L35-L48

**Comment by draptik** [comment]
sorry, I'm not a frontend developer, but I would like to help: can you give me a step-by-step on how to debug?

**Comment by antfu** [comment]
Install Node.js v16, cd into the project.

```bash
npm i -g pnpm

pnpm i

pnpm run dev
```

New terminal

```bash
pnpm run demo:dev
```

Modify the source you should be able to see the changes automatically in your browser

**Comment by draptik** [comment]
2 questions: 
- is Node.js 15.x also ok?
- is `pnpm` required?

**Comment by antfu** [comment]
Node v15 is unstable releases, better to use **even** version number whenever possible.

Yes, pnpm is required.

**Comment by draptik** [comment]
OK, I'll have to get back to you tomorrow (haven't heard of pnpm: sounds like another package wrapper...)

**Comment by draptik** [comment]
Sorry, I currently can't install the sources using `pnpm`. Cannot link binary 'jest' of 'jest-cli' to 'xxx': binary of 'jest' is already linked.
Feel free to close the ticket. I'll get back to you once I have more time to investigate. Sorry for the noise.

**Comment by antfu** [comment]
> Cannot link binary 'jest' of 'jest-cli' to 'xxx': binary of 'jest' is already linked.

That's just a warning, you can just ignore it.

I don't mind to keep this open if anyone faced same problem and want to have a look

**Comment by 97-109-107** [comment]
I am able to reproduce this; what data should I share to help resolve this?
