### ISSUE TITLE
Suggestion: Allow changing slides by clicking on the slide

### ISSUE THREAD

**Issue by yannxaver** [slidevjs/slidev#246]
**Is your feature request related to a problem? Please describe.**

I cannot change slides by clicking / tapping on the right or left side of the slide.
This becomes especially annoying on mobile where you have to swipe to change a slide.

**Describe the solution you'd like**

Tap on the left side of the slide: Previous slide.
Tap on the right side of the slide: Next slide.

That's the way the Kindle reader handles it and it works quite well.

**Describe alternatives you've considered**

The small menu in the bottom left is not a good alternative in my opinion because it is a lot less convenient to use. (especially on mobile again).

**Comment by antfu** [comment]
This is by design, as Slidev is not like other slides maker, we could have interactive components inside slides, which could be troublesome if we have the feature you described. Btw, the black area outside of the slide content do have this feature tho.

If you really need it, you can do that in your layout with https://sli.dev/custom/vue-context.html

```html
<template>
  <div @click="$slidev.nav.next()">
    <slot/>
  </div>
</template>
```

**Comment by yannxaver** [comment]
> we could have interactive components inside slides, which could be troublesome if we have the feature you described

What would these troubles be exactly? 
Wouldn't it be fine as long as we call `event.stopPropagation()` for all click events that occur in components inside the slides?

**Comment by antfu** [comment]
> for all click events

As you mentioned, this could be one of the troubles if you forget to do that (or force ppl to add this). I'd think this introduces more problems than it's trying to solve, especially you can already do that on user land.
