### ISSUE TITLE
Suggestion: Multiple presentations from one repository

### ISSUE THREAD

**Issue by yannxaver** [slidevjs/slidev#248]
**Is your feature request related to a problem? Please describe.**

If I didn't miss anything the current mapping is:
One repository --> One presentation

**Describe the solution you'd like**

Ideally I'd like to have a single repository that is hosted under e.g. `slides.domain.com` and that contains all of my presentations mapped to `slides.domain.com/{topic}/presentation1`, `slides.domain.com/{topic}/presentation2`, based on the folder structure of my repository (think 'file-based routing')

Benefits:
- Less repositories to manage
- Less manual mapping of repositories to URLs
- Easily share slides, layouts, etc. between presentations

**Describe alternatives you've considered**

If I'm not mistaken, I currently would have to create a new repository for each presentation and then map them manually to the desired URL.

**Comment by antfu** [comment]
https://sli.dev/guide/exporting.html#base-path

https://github.com/antfu/talks/blob/master/2021-04-29/src/package.json#L6

**Comment by yannxaver** [comment]
I think we misunderstood each other. :)

I'm aware of the solution that you linked to (manually mapping presentations to paths). With this solution each of the presentations is a separate slidev project though with its own `package.json`, `components` folder etc.

My suggestion was to have one slidev project folder with only one `package.json`, `components` folder etc. which can then host multiple presentations (via `file-based routing`).

- root
  - package.json
  - components
    - componentA
    - componentB
  - presentations
    - presentationA
      - Slides.md
    - presentationB
      - Slides.md

When you deploy this to `sub.domain.com`, you could then access the presentations via `sub.domain.com/presentationA` and `sub.domain.com/presentationB`. 

IMO this would make it a lot more convenient to create multiple presentations, share components between them, deploy them etc.

**Comment by theboi** [comment]
Hi, any updates on this? It will be really great if multiple presentations in a single repo is implemented!

**Comment by mariomurrent-softwaresolutions** [comment]
> https://sli.dev/guide/exporting.html#base-path
> 
> https://github.com/antfu/talks/blob/master/2021-04-29/src/package.json#L6

--base ist not working. If I use --base it says unknown argument and if I use --base=... it does not work

**Comment by joe733** [comment]
Hi,

I've stumbled upon this issue as my use-case demands it. Here's the gist. 

I've a songbook. Currently 1 song = 1 presentation = 1 slidev repository/project. I would like to have songs on separate markdown files within the same project. #317 proposes this feature. Additionally I'd like to create an index presentation with song numbers linking to the respective songs.

```yaml
# Speculated directory structure
.
├── components
├── netlify.toml
├── node_modules
├── package.json
├── package-lock.json
├── presentations
    └── 01_index
        └── slides.md
    └── 02_song01
        └── slides.md
    └── 03_song02
        └── slides.md
    └ ...
├── README.md
├── slides.md # could be used as index slide also ...
└── vercel.json


# URL examples
# first slide in first presentation
http:://localhost:3000/01_index/1

# fifth slide in second presentation
http:://localhost:3000/02_song01/2

# second slide in third presentation
http:://localhost:3000/03_song02/2
```

So if possible please re-open this issue.

**Comment by bigpopakap** [comment]
🙏 I would love to see this feature built in with first-party support as well!
