### ISSUE TITLE
Question: Would it make sense to decouple layouts from themes? 

### ISSUE THREAD

**Issue by yannxaver** [slidevjs/slidev#250]
**Is your feature request related to a problem? Please describe.**

Currently, themes include layouts. 
That leads to a certain degree of 'theme-lock-in' because `themeB` might not support the same layouts as `themeA`.

Also: When you look at many of the custom layouts that community themes have created they are basically rehashes of already existing layouts - just named differently. So `image-left` layout becomes `presenter` layout but structurally it's pretty much the same.

**Describe the solution you'd like**

I see two possible solutions for this:

1. Decouple layouts entirely from themes. So basically layouts are defined by slidev and themes should only be concerned about their implementation.

--> Pretty strict solution that could also limit creativity in the community

2. Define a set of 'default layouts' and ask community themes to at least implement those - plus any additional ones they want to implement

You could then group community themes into two categories:
A: Implements all default layouts
B: Does not implement all default layouts

That would give me the security as a user that as long as I stick to themes from group A I can switch between them effortlessly because they all implement the same set of 'default layouts'.

**Comment by antfu** [comment]
I think this is totally up to how theme authors want to implement. Indeed they can provide `layout-less` theme as they want. The layout resolution is `local > theme > default` which means theme can partially overrides default layouts while keep the others as-is. If you want layouts to be interchangeable across themes, use the ones available in the default layouts would always get you resolved.

That said, I would still recommend to have local layouts, or even eject the theme if you want to have the full controls over things.

> Define a set of 'default layouts'

We already do.

> Ask community themes

We could have a note in the guide, but I don't think it's make sense to make it "required". As they could contribute to the global styles to change how the layout looks like but leave the implementation to the default ones.
