### ISSUE TITLE
highlight code feature for PDF

### ISSUE THREAD

**Issue by HerbertHe** [slidevjs/slidev#251]
**Is your feature request related to a problem? Please describe.**

I found that the slidev provided some features but not worked in PDF.

for example

````markdown
```ts {all|1}
const a = "Hello, World!"
console.log(a)
```
````

When run as SPA, it was controlled by `clicks` step by step and run well. But exported as PDF file, it seems that lose this feature...

**Describe the solution you'd like**

I thought the new pages could be generated for this feature when exported.

**Comment by antfu** [comment]
Clicks is disabled in PDF export by default. And yeah, probably we could add this feature to export pages for every clicks.

**Comment by antfu** [comment]
https://github.com/slidevjs/slidev/pull/269
