### ISSUE TITLE
PROXY | Problems in secure network environments 

### ISSUE THREAD

**Issue by deleonio** [slidevjs/slidev#258]
External Sources like the favicon, could not be loaded in secure network environments.

![image](https://user-images.githubusercontent.com/6279703/122158039-3d969280-ce6c-11eb-812c-ba797bdaed50.png)

```bash
npm run dev
npm run build # or
```

https://github.com/slidevjs/slidev/blob/8cce79a382ab8ad3ca26958ab68b52e07da4b410/packages/client/index.html#L6

**It would be better, all assets are included in the npm package.**

Another example ...

![image](https://user-images.githubusercontent.com/6279703/122157887-f3151600-ce6b-11eb-8977-855c4eefae2b.png)

**Comment by antfu** [comment]
What do you mean secure network environments?

> It would be better, all assets are included in the npm package.

Yes we could, but I am not sure if we want to make since complicated. Since it's just a webpage in a browser, there is no reason you can't use web resources.

**Comment by deleonio** [comment]
Both are attracted to vite and cannot be built. Because the network restrictions do not allow everything.

**Comment by deleonio** [comment]
If it were only assets, then am I with you?

**Comment by antfu** [comment]
The remoteAssets is now disabled by default from v0.24
