### ISSUE TITLE
Enable to Modify Title Suffix

### ISSUE THREAD

**Issue by iwgx** [slidevjs/slidev#263]
Hi, in my slides, looks like we have kind of `titleTemplate` so it become `%s - Slidev`. How to update that titleTemplate? I want to change word "Slidev" to my name.

![Screenshot 2021-06-19 082902](https://user-images.githubusercontent.com/20817629/122627249-75097700-d0d8-11eb-8a94-5611b197b08f.png)

I have tried modify index.html, unfortunately it's not works
```html
<head>
  <title>SEO Essentials - Ilham Wahabi</title>
</head>
```

Thank you for developing Slidev!

**Comment by antfu** [comment]
Sounds reasonable, open for PR. Thanks.
