### ISSUE TITLE
Highlight feature for elements other than code

### ISSUE THREAD

**Issue by ngaurav** [slidevjs/slidev#266]
**Is your feature request related to a problem? Please describe.**
Yes I'm trying to use slidev for step by step solutions to math problems. I thought I could highlight steps like I could highlight code.

**Describe the solution you'd like**
The curly braces syntax for highlight row numbers should be allowed for Katex blocks. E.g.
$$ {2-3|all}
\begin{array}{c}
\nabla \cdot \vec{\mathbf{B}} & = 0
\end{array}
$$

**Describe alternatives you've considered**
None

**Comment by MountNoperest** [comment]
I second this, this would be an amazing feature.

**Comment by EkaanshArora** [comment]
This was added in #1105, I think we can close this issue.
