### ISSUE TITLE
Specify clicks for code highlighting

### ISSUE THREAD

**Issue by XiNiHa** [slidevjs/slidev#267]
Unlike `v-click="n"` or `<v-clicks at="n">`, code highlighting has no way to assign a specific click number to start the animation (at least I see no way to do this on docs). I want this feature to sync the code animation with list animation, placed parallelly using the `two-cols` layout.

**Describe the solution you'd like**
Feature to assign the starting click count (or specific clicks for each step) of the animation is needed. Something like this:

```md
```ts {all(click=2)|2|1(click=5)|all}
function hello(name: string) {
  console.log(name)
}
```

**Comment by antfu** [comment]
~~~md
<div class="grid grid-cols-2 gap-x-4">

```html {all|3,7,8,12,13,17|4-6|8-12|13-17|all} {at:0}
<script>
export default {
  data() {
    return {
      dark: false
    }
  },
  computed: {
    light() {
      return !this.dark
    }
  },
  methods: {
    toggleDark() {
      this.dark = !this.dark
    }
  }
}
</script>
```

```html {all|5,16|6,10|7,11|12-14|all} {at:0}
<script>
import { ref, computed } from 'vue'

export default {
  setup() {
    const dark = ref(false)
    const light = computed(() => !dark.value)

    return {
      dark,
      light,
      toggleDark() {
        dark.value = !dark.value
      }
    }
  }
}
</script>
```
~~~

Yeah, the docs are missing this. Would be appreciated if you want to make a PR for it. Thanks.
