### ISSUE TITLE
Building does not produce a GitPage-ready build 

### ISSUE THREAD

**Issue by why-not-try-calmer** [slidevjs/slidev#268]
**Describe the bug**
There seems to be two separate bugs but the likely cause is probably the same so I am lumping them together.

Bug 1: Server a slidev build yields a blank page (Error 404)

Bug 2: Trying to manually fix the build by prepending `.` to all assset references fixes Bug 1 but fails to get the anchored pictures rendered.

**To Reproduce**
1. Installed with `npm install @slidev/cli @slidev/theme-default`
2. Made some slides, linking images sitting in root directly.
3. Checked with `npm run dev` (all images render correctly)
4. Built with `npx slidev build`
5. Served `dist` locally with `python -m http.server ...` (all images render correctly)
5. Renamed `dist` to `docs` served via the GitPages features of my GitHub repository (main branch). Admired a blank page from the GitPage. Then prepended `.` to all assets links (from `/asset...` to `./asset...`). Pushed, waited, reloaded. Web app renders but all image links are broken.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed 20210618
 - Browser: Brave 1.25.73
 - Slidev version: 0.19.9

**Comment by dizys** [comment]
Please use CLI option `base` to help build your SPA with the correct base paths.

For example, for GitHub Pages, usually it's:

```bash
$ npx slidev build --base /my-repo-name/
```

**Comment by why-not-try-calmer** [comment]
@dizys Thanks, I will convert my Issue to a Pull Request
