### ISSUE TITLE
MDX Support?

### ISSUE THREAD

**Issue by karlhorky** [slidevjs/slidev#273]
**Is your feature request related to a problem? Please describe.**

When I create slide decks, I often want to have interactive elements, sometimes those which are already built in React / JSX. With MDX, I can consume those components or build new ones.

Looks like slidev is doing really well for velocity, something that cannot be said for alternatives like `mdx-deck`

**Describe the solution you'd like**

Support for MDX for authoring slide decks

**Describe alternatives you've considered**

Continue using other MDX slide deck options

**Comment by antfu** [comment]
Slidev is powered by Vue with Vue powered MD, which means you can use HTML elements and Vue components inside the md directly. Currently, we have no plan to support React / JSX / MDX officially.
