### ISSUE TITLE
SVG export for mermaid.js diagrams

### ISSUE THREAD

**Issue by christian-nils** [slidevjs/slidev#275]
Hello,

**Describe the solution you'd like**
I would like to add an option "exportable: true" (or such) in the mermaid markdown markup so an icon is present on the MermaidJS diagram. If I click on this export button I can save the diagram only as SVG (together with the current styling).

**Note**
I will try to implement it, but not sure I can do it in the short term.

Cheers,

CN

**Comment by antfu** [comment]
Maybe this could be done on the userland with a Vue component wrapper

**Comment by christian-nils** [comment]
Absolutely. I just thought that it could be useful and more handy to have an option on the markdown markup directly (but maybe you could do that in the user land as well?). 

Feel free to close this issue! :) 

Have a great day
