### ISSUE TITLE
windicss styles haven't been exported to dist by default

### ISSUE THREAD

**Issue by HerbertHe** [slidevjs/slidev#278]
![image](https://user-images.githubusercontent.com/30955264/122938969-c7cb8300-d3a5-11eb-9171-10a5763f1ce9.png)

**Describe the bug**
As you can see, when I exported the `dist`, I found the windicss styles had not been exported to the css bundle by default.

Maybe it caused by class name detection?

**To Reproduce**
1. initial project
2. add some HTML code with windicss utilities in `slides.md`
3. slidev build

**Desktop (please complete the following information):**
 - OS: Win10 Home Edition
 - Browser: Edge / Chrome
 - Slidev version: `v0.21.0`

**Comment by antfu** [comment]
Works fine on my side, can you try with `DEBUG=vite-plugin-windicss:scan:* slidev build`?

**Comment by HerbertHe** [comment]
The debug info showed that everything is ok, but I found that lost some utilities. like `windicss layer utilities`

**Comment by antfu** [comment]
Does any previous version work for you?

**Comment by amarriner** [comment]
I'm experiencing this, too, in v0.21.0. If I build in windows I'm missing that CSS. However, if I build against the same source in WSL, it works fine.

**Comment by antfu** [comment]
Maybe try with v0.21.1

**Comment by amarriner** [comment]
I was able to reproduce in v.0.21.1, sorry. Like I said, I can get around it for now by doing everything in WSL so not the end of the world. Thanks, great tool!

**Comment by antfu** [comment]
Might be a Windows related bug, will try to debug later when I have access to a PC.

**Comment by antfu** [comment]
Close due to inactive
