### ISSUE TITLE
Dark background overlay on cover slides not showing in pdf export, making some text almost unreadable

### ISSUE THREAD

**Issue by Adwirawien** [slidevjs/slidev#279]
**Describe the bug**
Dark background overlay on cover slides not showing in pdf export, making some text almost unreadable

**To Reproduce**
1. Use a bright background image with cover text
2. (tested for default theme) slidev export
3. Look at the difference between the browser version and the pdf

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari
 - Slidev version: 0.20.x

**Comment by tears330** [comment]
Duplicate of #80 
Just try `yarn export --dark`, it will export the pdf that use dark theme

**Comment by Adwirawien** [comment]
That wasn't really what I meant. However, I guess it was some kind of bug with the pdf viewer which appearently lead to the overlaying gradient to not be displayed ¯\_(ツ)_/¯

**Comment by Adwirawien** [comment]
Couldn't spot it again right now, so it seems to have resolved itself. Thank you anyway! 🙌
