### ISSUE TITLE
SPA asset-path

### ISSUE THREAD

**Issue by 6c756b** [slidevjs/slidev#28]
The SPA points to the assets-folder in the root dir.
href="/assets/..."
I think a relative path would be much better

**Comment by antfu** [comment]
This is the output of Vite. And I think using absolute if safer as you can't actually be sure which route will the component been used. As long as the base is resolved correct, I don't see it's an issue.

What's the problem you have facing?

**Comment by 6c756b** [comment]
actually I have no problem atm with this. Was just testing your great work.

But when I host the SPA somewhere in a subfolder of my filesystem like example.com/bla/bla/index.html the asset-folder has to be at example.com/assets/ .. in my opinion it would be better to have it in exmaple.com/bla/bla/assets/

**Comment by antfu** [comment]
`slidev build --base /bla/bla/`

The demo https://slidev.antfu.me/demo/starter is using exactly that.

**Comment by antfu** [comment]
Yeah, good idea, thanks
