### ISSUE TITLE
can't export video in pdf.

### ISSUE THREAD

**Issue by lance-loong** [slidevjs/slidev#281]
**Describe the bug**
can't export video in pdf.

**To Reproduce**
1. insert video in ppt `<iframe width="560" height="315" src="https://www.youtube.com/embed/8KavBpfLLtY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
2. export pdf
3. pdf only show image

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Slidev version:v0.20.4

**Comment by antfu** [comment]
Sorry I don't think you can have iframe in PDF. The SPA export might fit better to your needs.

**Comment by naquiroz** [comment]
Hi, whenever whenever you try to deploy to vercel, with a youtube video, it fails because of the print.
