### ISSUE TITLE
The code appears in the note panel

### ISSUE THREAD

**Issue by margo13131** [slidevjs/slidev#282]
The part of code move to in the NOTE panel  from SLIDE panel after  writing note on the second page and reloading this page. 

**On the first page: Expected result = Actual result** 

Steps to reproduce the  behavior:
1. Open   "Slidev"
2. Go to second page  
3. Click on the "Editor" button 
4. Click on the "Note" button 
5. Write a note                                           
6. Refresh the page
7. Click on the "Note" button 
8. **Actual result is empty Note panel
    Expected result is a note for slide**

9 Click on the note area
10. See the error: **part of code on the note area**

 - OS: Windows 10
 - Browser: Chrome
 - Slidev version: 0.21.0
 
  ![Screenshot 2021-06-23 094520](https://user-images.githubusercontent.com/55614989/123149646-54ae2500-d416-11eb-986f-e6563aa53895.png)

**Comment by antfu** [comment]
What's your code? Can't reproduce with the starter template.

**Comment by margo13131** [comment]
Hi. I didn't write code. it was UI testing.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by margo13131** [comment]
Do you need video reproduction?

**Comment by margo13131** [comment]
I have sent a reproduction steps and attached a screenshot. Is something
wrong with the file?

**Comment by antfu** [comment]
I'd prefer code reproduction, ideally a git repo. Thanks

**Comment by margo13131** [comment]
Could you explain what do you mean?

**Comment by margo13131** [comment]
Advice how can I do what you need.
