### ISSUE TITLE
SPA showing error

### ISSUE THREAD

**Issue by dingiso** [slidevjs/slidev#283]
**Describe the bug**
When I use slidev build to build a SPA , I upload it on my server but it seems not right in the website. It's all right in my Win10 computer offline with localhost:3030 . the website is as following 
![image](https://user-images.githubusercontent.com/43989619/123438480-4ec96700-d603-11eb-9000-525d5f122020.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Slidev version: 0.19.5

**Comment by antfu** [comment]
Please upgrade to the latest version and try out
