### ISSUE TITLE
CodeMirror is not defined

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [slidevjs/slidev#284]
**Describe the bug**
After upgrading to the newest slidev version I'm getting the following error:

placeholder.js?v=f557482b:10 Uncaught (in promise) ReferenceError: CodeMirror is not defined
    at placeholder.js?v=f557482b:10
    at placeholder.js?v=f557482b:11

**To Reproduce**
1. Upgraded to the latest slidev version
2. Rund command nem run dev --entry mymarkdown.md
3. Open browser
4. See the above error on some slides

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Slidev version: 0.21.3

**Comment by antfu** [comment]
Might be some cache issue, can you try to do a clean install and try again?

**Comment by mariomurrent-softwaresolutions** [comment]
I already tried this, but this also did not work

**Comment by mariomurrent-softwaresolutions** [comment]
@antfu It seems like these are all issues on my side - ill close this one for now ... If there is anything which I think could be on your side, ill let you know
