### ISSUE TITLE
Multi slides in sub slide when using multiple entry

### ISSUE THREAD

**Issue by malcolm-kee** [slidevjs/slidev#291]
**Is your feature request related to a problem? Please describe.**
When using multiple entry features, the sub page can only include single slide.

E.g. in subpage:

```md
# Slide 1

---

# Slide 2

---
``` 

The output will treat the `---` separator as horizontal line instead of new slide.

The reason why I want to split a subpage into multiple slide is because I would like to organize my slide by section, where each section is its own file.

**Describe the solution you'd like**
We can split the subslide into multiple slides as well by using `---`.

**Describe alternatives you've considered**
Having to create a new file for each slide, while still working, is not so useful as we replace the problem of having a file that is too large to the problem of having too many files.

**Comment by lajunta** [comment]
I have the same question. How to solve it?

**Comment by SunflowerAries** [comment]
seems people have disscussed related features in #53 , and most people may think one layer is sufficient. but to give a talk, especially full of matrix, usally have > 1000 LOCs in the main md. So a multi-layer, I mean rendering a subpage into multi-slides are more convienient.

**Comment by antfu** [comment]
Yeah, I think that makes sense. Currently I don't have much bandwidth to work on it, but contributions are welcome before I managed to work on it. Thanks

**Comment by Ahacad** [comment]
I don't know exactly how multiple entry works now, but a simple copy many files together might work? Maybe some macro can achieve this effect.
