### ISSUE TITLE
Build failed when installing slidev in globally

### ISSUE THREAD

**Issue by mrchi** [slidevjs/slidev#292]
**Describe the bug**
If you install slidev globally, when build SPA by running command `slidev build xxx`, there is an error raised
![image](https://user-images.githubusercontent.com/16170578/124001053-cbdf4c80-da06-11eb-9fc0-4b3fef35a8c2.png)

But if you install slidev in project, and build by running command `npx slidev build xxx`, it works fine.

**To Reproduce**
1. Install slidev globally, `npm i -g @slidev/cli`
2. Create a `slides.md`
3. Build it by running `slidev build slides.md`

**Desktop (please complete the following information):**
 - OS: alpine
 - Browser: 
 - Slidev version: 0.22.1

**Comment by Zenahr** [comment]
Apart from your specific build error this should be part of the `Getting Started` docs section for sure.

**Comment by antfu** [comment]
I think it's already fixed in the latest version. Please try to upgrade.
