### ISSUE TITLE
Custom index.html not working

### ISSUE THREAD

**Issue by dipunj** [slidevjs/slidev#294]
**Describe the bug**
The docs suggest that to modify the exported index.html, create a index.html file in the project root and supply the head tags etc. and the exported index.html will the default tags add to it.

**To Reproduce**
1. run `yarn dev` in a sli.dev project
1. create an index.html file in the root of a slidev scaffolded project
2. add the following to the index.html file:
```html
<!-- ./index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Custom Title</title>
</head>

<body>
	<div id="app"></div>
</body>

</html>
```
3. start the slidev dev server by `yarn dev`
4. Open the browser and go to the localhost:3030 (or whatever port slidev is running)
5. See the error (title is still slidev-slidev)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Slidev version:
     "@slidev/cli": "^0.22.1",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*",

**Comment by antfu** [comment]
Title is controlled by the runtime via [`@vueuse/head`](https://github.com/vueuse/head), while you can use `title` field of the frontmatter to customize it.
https://sli.dev/custom/#frontmatter-configures

**Comment by dipunj** [comment]
Okay. Thank solves my problem. Can we please also update the docs to fix it there? Thanks
