### ISSUE TITLE
Relative img imports

### ISSUE THREAD

**Issue by Minipada** [slidevjs/slidev#298]
**Is your feature request related to a problem? Please describe.**
I would like to be able to do this. At the moment, it does not seem doable:
```
    <img src="../images/brisa_circle.png">
    <img src="images/brisa_circle.png">
```

**Describe the solution you'd like**
Not sure how this should be done.

**Describe alternatives you've considered**
Hosting the image online but not so practical for long term...

**Comment by Ahacad** [comment]
try `/images/brisa_circle.png`

**Comment by antfu** [comment]
See https://sli.dev/guide/syntax.html#static-assets

**Comment by Minipada** [comment]
Relative imports (../) doesn't work. But anyway, closing the issue probably means you don't plan on handling this.

**Comment by antfu** [comment]
Pages files are served via virtual modules, where relative import does not make sense to vite. While we could rewrite the path in the code to make it work, as the absolute path works perfectly fine, I personally don't feel it's worth to do (as it can bring may false-positive cases). If you absolutely need it, feel free to make a PR and I am happy to review it. Thanks
