### ISSUE TITLE
install global error

### ISSUE THREAD

**Issue by Croie** [slidevjs/slidev#303]
**Describe the bug**
\[\033[38;5;203m\]\u\[\033[38;05;38m\]$(__git_ps1)\[\033[0;34m\] \W
$ \[\033[0m\]npm i -g @slidev/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roie/.npm/_logs/2021-07-11T15_52_34_859Z-debug.log

**Desktop (please complete the following information):**
 - OS: MacOs catalina 10.15.7
 - Browser: Google
 - Slidev version:latest

**Comment by antfu** [comment]
This is not Slidev's error, you will need to have a user install of npm, or use `sudo` to install globally (take your own risk).

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by Croie** [comment]
thanks, i will try
