### ISSUE TITLE
colorSchema types

### ISSUE THREAD

**Issue by superwf** [slidevjs/slidev#305]
https://github.com/slidevjs/slidev/blob/78cbc5cfc40c3f27b9f88bf2e2c2570716ad1052/packages/types/src/types.ts#L150

https://github.com/slidevjs/slidev/blob/78cbc5cfc40c3f27b9f88bf2e2c2570716ad1052/packages/types/src/types.ts#L32

May these two colorSchema use same type ?

**Comment by antfu** [comment]
They are in different contexts, the difference is expected.
