### ISSUE TITLE
inline codes are rendered without hiding backticks

### ISSUE THREAD

**Issue by sammyne** [slidevjs/slidev#307]
**Describe the bug**
Slidev renders  inline codes without hiding backticks.

**To Reproduce**
I've made a [repository](https://github.com/sammyne/slidev-bugs-report) to reproduce this problem.

Failed rendering goes as

![ugly-inline-codes](https://user-images.githubusercontent.com/16666661/125412990-004b9558-0389-4f7f-b0eb-daae86763cd9.png)

where `<Tweet />` and `<Youtube />` render without hiding the backticks '\`'.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome 91.0.4472.114 (Official Build) (x86_64)
 - Slidev version: 0.22.4

**Comment by yjl9903** [comment]
https://github.com/slidevjs/slidev/issues/208#issuecomment-851874432

**Comment by yuuuxt** [comment]
IMAO: Such a style should be removed from **default** style. I guess most users prefer hidden backticks instead of explicit. (I was about to report "bug" as well)

**Comment by hlship** [comment]
+1 - visible backticks is just wrong

**Comment by hlship** [comment]
Is there a workaround for this, as in, exactly what to put into project's `style.css` to disable this?

**Comment by yuuuxt** [comment]
- open `./node_modules/@slidev/theme-<you-use>/styles/prism.css`, 
- scroll down to bottom, and delete code mentioned in [#208 (comment)](https://github.com/slidevjs/slidev/issues/208#issuecomment-851874432),
- save file, and restart `slidev`.

**Comment by hlship** [comment]
Is that recommended?  That change won't be persisted in Git history, and may be overwritten by npm or yarn, AFAIK (I don't do front end work generally).

**Comment by hlship** [comment]
I'm more likely to copy the theme locally and make the changes there, but I'd rather use the existing them and _patch_ this small part of it.  It's just that CSS tends to be additive, and here I want to subtract something.

**Comment by yuuuxt** [comment]
Yes that's true.
But for me, I create one repo for all `slidev` markdown files, so that's the quickest way for me to get it working. If I re-install packages, I just redo this manual patch. It may not happen more than twice a year, so for me I don't want to dig deeper here.
