### ISSUE TITLE
Import static asset

### ISSUE THREAD

**Issue by FedericoTartarini** [slidevjs/slidev#308]
**Describe the bug**
Fail to import static image when I am using slidev installed globally.

**To Reproduce**
1. Install slidev globally with `npm i -g @slidev/cli`
2. Create a folder called presentation and cd into the project
3. Create a folder called `images` and add any image called `image.jpg`
4. Create a file called `slides.md` and enter the following code.
5. Run using `npx slidev`
6. And I get the following error
7. I do not get the error if I use `npm init slidev`
```
---
layout: default
---
# Title
<img src="./images/intro.jpg">
```
![image](https://user-images.githubusercontent.com/40018640/125569772-99adeb8c-c105-4172-9742-75664d99cd1a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera and Chrome
 - Slidev version: 0.22.4

**Comment by zwwtj2014** [comment]
https://sli.dev/guide/syntax.html#static-assets

put assets into the public folder and reference them with leading slash is worked well.

`<img src="/pic.png" class="m-40 h-40 rounded shadow" />`

**Comment by FedericoTartarini** [comment]
Hi thank you so much for your quick response but unfortunately, it is not working. I am using the following command to start the local server `npx slidev`. I can see the slides and the text but not the image.

My directory tree is:
```
C:\USERS\....\DESKTOP\TEST
│   slides.md
│
└───public
        smile.png
```

My slides.md file contains the following code:
```
# title

test

---

# Slide one

test image

<img src="/smile.png" class="m-40 h-40 rounded shadow" />
```

Below the image, I have been using. I also tested to see if it was working with a .jpg and another .png image. I have also tried with the following command `![Local Image](/smile.png)` but also this one does not work. If on the other hand I use the command `yarn create slidev` then I put the image in `./public/` then it works. The downside of that is that each presentation folder is massive ~500MB since it contains all the node_modules. 
![smile](https://user-images.githubusercontent.com/40018640/125717148-91996d3b-d0f5-403a-8888-76be4c2614c0.png)
