### ISSUE TITLE
monaco.editor.setTheme not works

### ISSUE THREAD

**Issue by diveDylan** [slidevjs/slidev#309]
```ts
// monaco.ts
import { defineMonacoSetup } from '@slidev/types'

export default defineMonacoSetup(async (monaco) => {
  // 使用 `monaco` 配置
  monaco.editor.setTheme('vs-dark')
})
```

```md
--js{monaco}

some code here

---


```
expect to see the dark theme, but not.
Reproduce: copy the code, run the slidev

 - OS: Big Sur 11.4
 - Browser: Chrome91.0
 - Slidev version: "@slidev/cli": "^0.20.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"

**Comment by antfu** [comment]
It's controlled by Slidev based on the dark/light theme. However I missed it and hard-coded the theme. Now with v0.22.5, you can do this:

```ts
import { defineMonacoSetup } from '@slidev/types'

export default defineMonacoSetup(() => {
  return {
    theme: {
      dark: 'vs-dark',
      light: 'vs',
    },
  }
})
```
