### ISSUE TITLE
Line number in code block 

### ISSUE THREAD

**Issue by mathieutu** [slidevjs/slidev#310]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for this cool project!

When explaining pieces of code to an audience it's really useful to be able to tell them that "you can find xxx at line number yyy", and for them it's easier for asking question.

It would also be useful to have the line numbers for click highlighting (I count lines all the day to know which one is what)

**Describe the solution you'd like**
As usual, a simple column at the beginning of the block.

**Describe alternatives you've considered**
😶

Thanks!

I have no time for this right now, but I could try a PR to add it!

**Comment by antfu** [comment]
Happy to have it, PR welcome!

(Prism seem to easier to do, I don't mind to have the features only available on one highlighter first, so you don't need to take the task too big. For Shiki, https://github.com/shikijs/shiki/issues/3

**Comment by mathieutu** [comment]
Hi, 
I'm currently using Shiki, so I've put in #311 something basic I've quickly made on my own project, based on https://github.com/shikijs/shiki/issues/3#issuecomment-830564854.

**Comment by antfu** [comment]
#311

**Comment by fr0zn** [comment]
Would it be possible to provide a way to set the initial line number for each code block and allow line highlighting based on the new numbers?
