### ISSUE TITLE
Could not open slides.md in the editor.

### ISSUE THREAD

**Issue by KermanX** [slidevjs/slidev#312]
**Describe the bug**
Could not open slides.md in the editor.

**To Reproduce**
1. Go to 'http://localhost:3030/presenter/1'
2. Click on '![image](https://user-images.githubusercontent.com/63178754/126107996-55a0e6e2-a90f-41af-b183-d48eae6f6823.png)'
3. See the error

**Desktop (please complete the following information):**
 - OS:Win10
 - Browser:msedge
 - Slidev version:0.22.5

**Comment by antfu** [comment]
What error?

**Comment by KermanX** [comment]
Output `Could not open slides.md in the editor.` in console
