### ISSUE TITLE
Do we have Lazer pointer or colored pens in presentation?

### ISSUE THREAD

**Issue by WANG-lp** [slidevjs/slidev#320]
**Describe the solution you'd like**
I wonder do we have Lazer pointer or colored pens when in the presentation?

It will be better if we can write sth with either Lazer pointer or colored pens on the page during the presentation.

Thanks.

**Comment by antfu** [comment]
Think we could embed some libraries that does that. Any recommendations?

**Comment by xam1311** [comment]
Hi,
Found some example in reveal.js
https://github.com/caiofcm/plugin-revealjs-mouse-pointer
https://github.com/djsutherland/reveal.js-notes-pointer

**Comment by antfu** [comment]
I am working on it.

**Comment by antfu** [comment]
https://twitter.com/Slidevjs/status/1437261881928867841

**Comment by Sparkenstein** [comment]
Hey was looking for this exact same feature, 

Can I suggest one improvement on top of it? the colored pen works well, but drawing stays on your presentation.

a laser pointer that fades away after 1 or 2 seconds would be really cool. laser pointer helps to just highlight the things like in an architecture diagram. with pen we have to press Ctrl-z after drawing every highlight.

**Comment by Sparkenstein** [comment]
No plans for this one? I can work on it if it's easy I can make a PR if you point me to right direction
