### ISSUE TITLE
deploy in vercel got problem

### ISSUE THREAD

**Issue by pomeloneo** [slidevjs/slidev#322]
**Describe the bug**
I have encountered a problem
I'm trying to deploy a slidev project in vercel
When the script executes to **slidev build** it gets stuck
I don't know if it's my configuration or a bug
Hope to get help 
thanks

**Desktop (please complete the following information):**
 - Slidev version: ^0.22.7

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by pomeloneo** [comment]
https://github.com/pomeloneo/vue3-ppt
Use this repository to deploy on vercel
All are configured by default

**Comment by pomeloneo** [comment]
https://vercel.com/pomeloneo/vue3-ppt/35nzkjSwzETXQUeWTePc89UaK7U1
I don't know if this link will work for you

**Comment by pomeloneo** [comment]
It works fine today
It should be a problem with vercel
Thanks for the reply

**Comment by quanscheng** [comment]
我也在vercel构建时候遇到相同的问题 
如果直接构建, 默认选择的是 `other`
解决方式: 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/68772719/187711476-c31a57de-4cad-436d-8d1e-b80d9ad06130.png">

最后感谢 antfu 在开源中的无私奉献. 希望能解决此类问题
