### ISSUE TITLE
HTML comments in Layout code are breaking navigation

### ISSUE THREAD

**Issue by mrwwalmsley** [slidevjs/slidev#328]
**Describe the bug**
HTML comments in the `dynamic-image` of the light icons theme was causing that slide to remain visible even when navigating to the next slide.

**To Reproduce**
1. Use the `light-icons` theme
2. Create a slide with the `layout: dynamic-image` and `left: false`
3. Create another slide after the dynamic-image layout.
4. You can't navigate to the second slide.

**Workaround**

1. Copy the dynamic-image.vue into your local layouts folder.
2. Remove the HTML comments on line 3 and line 42
3. Now navigation works correctly!

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Slidev version:  @slidev/cli: 0.22.7

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by tonai** [comment]
This seems more an issue related to the `light-icons` theme
