### ISSUE TITLE
UI draw nothing because of error

### ISSUE THREAD

**Issue by q82184828** [slidevjs/slidev#330]
**Describe the bug**
when i install slidev in manual way and run npx slidev, can't see anything in ui.

npm install @slidev/cli @slidev/theme-default
npx slidev

my nodejs version is 14.17.5

here is my install message:
![image](https://user-images.githubusercontent.com/26521260/129669875-2254be38-a271-4104-ad05-c1da9c4cf318.png)
here is ui error:
![image](https://user-images.githubusercontent.com/26521260/129670064-6a6d8fcd-172d-4fe7-be27-736c7e716418.png)

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome 76.0.3809.87
 - Slidev version: 0.22.7

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by mariomurrent-softwaresolutions** [comment]
@q82184828 Well but there is not even an error: Can you please also show the error when you run slidev? You just put the error from the npm install here ...

**Comment by antfu** [comment]
Close due to inactive
