### ISSUE TITLE
mermaid journey parse error

### ISSUE THREAD

**Issue by Innei** [slidevjs/slidev#332]
**Describe the bug**

```mermaid
journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
```
parse error, 
![image](https://user-images.githubusercontent.com/41265413/129871337-bf6698d7-a1e2-4282-9bcb-0dff944e620e.png)

This is sample code copy from mermaid site, and it worked in mermaid live edit, see below:
https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiam91cm5leVxuICAgIHRpdGxlIE15IHdvcmtpbmcgZGF5XG4gICAgc2VjdGlvbiBHbyB0byB3b3JrXG4gICAgICBNYWtlIHRlYTogNTogTWVcbiAgICAgIEdvIHVwc3RhaXJzOiAzOiBNZVxuICAgICAgRG8gd29yazogMTogTWUsIENhdFxuICAgIHNlY3Rpb24gR28gaG9tZVxuICAgICAgR28gZG93bnN0YWlyczogNTogTWVcbiAgICAgIFNpdCBkb3duOiA1OiBNZSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9

**To Reproduce**
https://github.com/Innei/slidev-mermaid-reproduction

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Browser: Chrome 92
 - Slidev version: 0.22.7

**Comment by antfu** [comment]
Should be fixed in 0.23
