### ISSUE TITLE
Image position incorrect in pdf

### ISSUE THREAD

**Issue by duskmoon314** [slidevjs/slidev#333]
**Describe the bug**
I tried to export a pdf. In my slides, I used image like this:

```md
---

# Title

Description

<img src="public/image.png"/>

<style>
img {
  height: 100%
}
</style>

---
```

Because the image is too high, I use style to force it in the screen

Then I used `npm run export` to export a pdf.

what I got:

![image](https://user-images.githubusercontent.com/20477228/129879637-c0af7098-1001-4adb-bbf3-4bef3c32ce46.png)

What I expect (in the browser):

![image](https://user-images.githubusercontent.com/20477228/129879793-6748bde8-8981-46db-9b31-6afb2777e9bf.png)

**To Reproduce**
1. Use `npm init slidev` to create a repo
2. `npm i -D playwright-chromium`
3. Insert Image like above
4. `npm run export`

**Desktop (please complete the following information):**
 - OS: Windows 10 (Windows_NT x64 10.0.19043)
 - Browser: Edge 92.0.902.73
 - Slidev version:
   ```
   "playwright-chromium": "^1.14.0"
   "@slidev/cli": "^0.22.7"
   "@slidev/theme-default": "*"
   "@slidev/theme-seriph": "*"
   ```

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by pepijnolivier** [comment]
Hi @antfu and thanks for this awesome project.

I have this bug as well. It's quite easy to reproduce.
Using the last version `0.27.10`

---

You can use add this as a slide to the `slides.md` to reproduce
It is reproducible just with a new project, with the default settings (seriph font, etc)

```
---
# Bug Reproduction
Subtitle

  ![Remote Image](https://www.christies.com/img/LotImages/2021/NYR/2021_NYR_20447_0001_001(beeple_everydays_the_first_5000_days034733).jpg)
```

It looks okay in the browser (with `yarn start`) but in the PDF it is exactly as mentioned by @duskmoon314 

Seems like a positioning bug or something ?

Thanks again for the work on slidev, it is awesome.

**Comment by bambalamm** [comment]
I ran into this as well. It happens whenever this happens:  
![reason](https://user-images.githubusercontent.com/22509035/158038317-97e35d44-7c3b-4b81-bf65-fb3935b3cd57.png)  

The image gets stretched/scaled to fill the space and the image flows over in the Y direction. Two factors play a role:  
1) Image height  and/or CSS height are a high value.  
2) Image aspect ratio is smaller than the aspect ratio of the white area it has to fill (= area under the subtitle).  

PDF exports:  

Small image, small aspect ratio (1:1)  **works**:   
![small_image](https://user-images.githubusercontent.com/22509035/158038836-31db30dd-1f53-469a-8239-1f04bdd90ce2.png)

Large image, small aspect ratio (1:1) **fails**:   
![large_image](https://user-images.githubusercontent.com/22509035/158038721-edf7f16c-f58d-414b-b585-dd306369bcab.png)  

Large image, large aspect ratio (2:5) **works**:   
![good_scale](https://user-images.githubusercontent.com/22509035/158039046-781d28b8-82f0-4f72-ab8b-e7e6bf507b8e.png)  

Small image, small aspect ratio (1:1), high CSS height **fails**:   
![css_height](https://user-images.githubusercontent.com/22509035/158038937-c3134ea6-f221-4f9a-9eec-b3e069c00b56.png)

Large image, small aspect ratio (1:1), moderate CSS height **works**:   
![css_medium](https://user-images.githubusercontent.com/22509035/158039119-ede50c48-cb7a-4a5d-9585-212e3e519b3d.png)

Hope this info might help anyone else that struggles with this issue.

**Comment by imyelo** [comment]
Having the same problem.
It looks like playwright-chromium is laying out `<img />` unexceptionally with slidev.

For those who encountered this issue too, wrapping the image with an absolute positioned `<div />` can avoid it, like:

```
- <img class="w-200" src="..." />
+ <div class="w-200 h-full">
+  <img class="absolute w-200" src="..." />
+ </div>
```

**Comment by duskmoon314** [comment]
Thanks @tonai
