### ISSUE TITLE
Custom default layout not applying

### ISSUE THREAD

**Issue by antfu** [slidevjs/slidev#334]
### Discussed in https://github.com/slidevjs/slidev/discussions/331

<div type='discussions-op-text'>

<sup>Originally posted by **kecrily** August 18, 2021</sup>
I tried creating `default.vue` in the theme's `layouts` directory, but it still doesn't work when I don't specify `layout: default`.

According to #141, there should be nothing wrong with my way, but it's not taking effect, and I'm not sure if the method has changed in the meantime, or if this is a bug.

## Additional Information

I used the theme creation tool written in the documentation

```bash
pnpm init slidev-theme
```

This is dependencies written in `package.json`.

```json
"dependencies": {
  "@slidev/types": "^0.22.7",
  "codemirror-theme-vars": "^0.1.1",
  "prism-theme-vars": "^0.2.2",
  "theme-vitesse": "^0.1.12"
},
"devDependencies": {
  "@slidev/cli": "^0.22.7"
}
```</div>

**Comment by kecrily** [comment]
After I read the code, I found out that this is a feature and not a bug.

https://github.com/slidevjs/slidev/blob/4f498c04d0c03bd54957a0031139d3d70de9ee56/packages/slidev/node/plugins/loaders.ts#L286

Should we consider providing the option to include overriding the first page in `default.vue`?

**Comment by antfu** [comment]
Ah, yes that's by design. About the option, explicit set `layout: default` is already an option right?
