### ISSUE TITLE
Support Videos

### ISSUE THREAD

**Issue by jolo-dev** [slidevjs/slidev#339]
**Is your feature request related to a problem? Please describe.**
It would be nice to intergrate videos from Youtube or Vimeo.

**Describe the solution you'd like**
I am quite new to sli.dev but a Component in the `.md`- File could implement the video.

```md

# My Video

<Youtube src="https:youtube.com/12345">
```

Furthermore, we could make use of the Youtube-Player API and also add more properties like `fullscreen="true"` or similar.

Here are some examples:
https://webslides.tv/demos/portfolios#slide=74
https://jolo-dev.github.io/pyberlin-2020-serverless-presentation/#slide=9

**Comment by antfu** [comment]
We do have `<Youtube/>` component built-in already https://github.com/slidevjs/slidev/tree/main/packages/client/builtin

Meanwhile, as our markdown supports full HTML syntaxes, you can always use `<video/>` or `<iframe/>` tag to embedded any videos or even web pages you want.
