### ISSUE TITLE
`create-slides` version number mismatch

### ISSUE THREAD

**Issue by nico-bachner** [slidevjs/slidev#34]
In the `create-slidev` source code, the version is `"version": "0.5.0"` and that value seems to be referenced in the setup script:

```js
const { version } = require('./package.json')

...

console.log(`${bold('  Slidev') + dim(' Creator')}  ${blue(`v${version}`)}`)
```

However, the version number when running `npm init slidev` is `v0.1.6`:

<img width="569" alt="create-slidev" src="https://user-images.githubusercontent.com/45149421/117532791-a70fbf80-afe9-11eb-8d90-2ff51217cc1c.png">

**Comment by antfu** [comment]
Em, I don't know how to solve that. It's more like a local npm cache. Try `npm init slidev@latest`

**Comment by nico-bachner** [comment]
Yeah that did the trick.

Never seen that before.
