### ISSUE TITLE
[question] How can we embed it into existing vue app?

### ISSUE THREAD

**Issue by jd-0001** [slidevjs/slidev#344]
Hi,

Can I embed it in an existing vue app like vuepress docs?

**Comment by antfu** [comment]
Yes, I think so. Any obstacles?

**Comment by jd-0001** [comment]
I don't see guide for embedding in [export](https://sli.dev/guide/exporting.html#pdf) page

Can you please provide link for correct guide?

**Comment by antfu** [comment]
It isn't designed to be embed in another app, giving it rely heavily on custom toolings. You can generate the build in a subroute to be host with your app, or work with iframe.
