### ISSUE TITLE
Playwright update needed on Netlify

### ISSUE THREAD

**Issue by kissu** [slidevjs/slidev#345]
**Describe the bug**
Playwright needs an update on Netlify with elevated rights

**To Reproduce**
- get the latest version of sli.dev	
- following the [hosting guide](https://sli.dev/guide/hosting.html#netlify)
- face the errors

I have to mention that I've successfully built it previously but today the deploy is not good anymore. Those are the errors that I got.

![image](https://user-images.githubusercontent.com/5133074/133618264-887c68f8-1a56-47df-b766-665af0ca150f.png)
---
![image](https://user-images.githubusercontent.com/5133074/133618614-3f880ee5-d1e4-4498-af9d-1ad58eec72a9.png)

I've reached the second screenshot with the following
```
[build]
  publish = "dist"
  command = "npx playwright install && npx playwright install-deps && yarn build"
```

But I cannot run `sudo` on Netlify, hence the second part is not totally fine I guess.

<details>
  <summary>Here is the whole stacktrace with just the npm run build command as shown here: https://sli.dev/guide/hosting.html#netlify</summary>

2:48:50 PM: Build ready to start
2:48:52 PM: build-image version: fa439ad1ab9393b2c0d449d8d7c033927683f4b0
2:48:52 PM: build-image tag: v4.3.0
2:48:52 PM: buildbot version: d34b57a8e2866c6521420792f076bdf372efc56f
2:48:52 PM: Fetching cached dependencies
2:48:53 PM: Starting to download cache of 354.8MB
2:49:00 PM: Finished downloading cache in 7.307695347s
2:49:00 PM: Starting to extract cache
2:49:10 PM: Finished extracting cache in 10.068979212s
2:49:10 PM: Finished fetching cache in 17.507244489s
2:49:10 PM: Starting to prepare the repo for build
2:49:10 PM: Preparing Git Reference refs/heads/master
2:49:11 PM: Parsing package.json dependencies
2:49:11 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm run build' versus 'yarn build' in the Netlify UI
2:49:11 PM: Starting build script
2:49:11 PM: Installing dependencies
2:49:11 PM: Python version set to 2.7
2:49:12 PM: Started restoring cached node version
2:49:14 PM: Finished restoring cached node version
2:49:14 PM: v14.17.6 is already installed.
2:49:15 PM: Now using node v14.17.6 (npm v6.14.15)
2:49:15 PM: Started restoring cached build plugins
2:49:15 PM: Finished restoring cached build plugins
2:49:15 PM: Attempting ruby version 2.7.2, read from environment
2:49:16 PM: Using ruby version 2.7.2
2:49:17 PM: Using PHP version 8.0
2:49:17 PM: Started restoring cached yarn cache
2:49:20 PM: Finished restoring cached yarn cache
2:49:20 PM: No yarn workspaces detected
2:49:20 PM: Started restoring cached node modules
2:49:20 PM: Finished restoring cached node modules
2:49:20 PM: Installing NPM modules using Yarn version 1.22.10
2:49:21 PM: yarn install v1.22.10
2:49:21 PM: [1/4] Resolving packages...
2:49:21 PM: success Already up-to-date.
2:49:21 PM: Done in 0.35s.
2:49:21 PM: NPM modules installed using Yarn
2:49:22 PM: Started restoring cached go cache
2:49:22 PM: Finished restoring cached go cache
2:49:22 PM: go version go1.16.5 linux/amd64
2:49:22 PM: go version go1.16.5 linux/amd64
2:49:22 PM: Installing missing commands
2:49:22 PM: Verify run directory
2:49:23 PM: ​
2:49:23 PM: ────────────────────────────────────────────────────────────────
2:49:23 PM:   Netlify Build                                                 
2:49:23 PM: ────────────────────────────────────────────────────────────────
2:49:23 PM: ​
2:49:23 PM: ❯ Version
2:49:23 PM:   @netlify/build 18.10.0
2:49:23 PM: ​
2:49:23 PM: ❯ Flags
2:49:23 PM:   baseRelDir: true
2:49:23 PM:   buildId: 61433d324cb16100076fa8e1
2:49:23 PM:   deployId: 61433d324cb16100076fa8e3
2:49:23 PM: ​
2:49:23 PM: ❯ Current directory
2:49:23 PM:   /opt/build/repo
2:49:23 PM: ​
2:49:23 PM: ❯ Config file
2:49:23 PM:   /opt/build/repo/netlify.toml
2:49:23 PM: ​
2:49:23 PM: ❯ Context
2:49:23 PM:   production
2:49:23 PM: ​
2:49:23 PM: ────────────────────────────────────────────────────────────────
2:49:23 PM:   1. build.command from netlify.toml                            
2:49:23 PM: ────────────────────────────────────────────────────────────────
2:49:23 PM: ​
2:49:23 PM: $ npm run build
2:49:24 PM: > conf-nuxtnation-2021@ build /opt/build/repo
2:49:24 PM: > slidev build
2:49:24 PM:   ●■▲
2:49:24 PM:   Slidev  v0.23.0
2:49:24 PM:   theme   @slidev/theme-seriph
2:49:24 PM:   entry   /opt/build/repo/slides.md
2:49:26 PM: vite v2.5.7 building for production...
2:49:26 PM: transforming...
2:49:37 PM: ✓ 255 modules transformed.
2:49:39 PM: rendering chunks...
2:50:07 PM: dist/assets/8b9eb19119592679c97707c257d88026.a02f38e2.png   59.08 KiB
2:50:07 PM: dist/assets/nuxt_logo.6a7ff90d.svg                          0.60 KiB
2:50:07 PM: dist/assets/poor_effort.6cc30f81.png                        59.93 KiB
2:50:07 PM: dist/assets/e58260c608c6b561fe83014c7cea6b0e.02ca51aa.png   72.94 KiB
2:50:07 PM: dist/assets/logo-title-horizontal.96c3c915.png              119.68 KiB
2:50:07 PM: dist/assets/2088e2bbdbe2490545f19ad7736380a1.fbb3b07c.png   267.53 KiB
2:50:07 PM: dist/assets/63efc529c06aba10c5e1cb302edadb0a.2496976c.png   310.00 KiB
2:50:07 PM: dist/assets/logo.b72bde5d.png                               92.11 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Bold.acee258c.woff2           6.77 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Bold.5ed7c1a3.woff2               11.08 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Regular.ada73fb2.woff2        6.75 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Regular.79bb8158.woff2            11.04 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Bold.eecd8e98.woff2             11.89 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Italic.fba87080.woff2           11.68 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Regular.9729a729.woff2          10.13 KiB
2:50:07 PM: dist/assets/KaTeX_Script-Regular.15c00a11.woff2             9.39 KiB
2:50:07 PM: dist/assets/KaTeX_Size2-Regular.5e2769eb.woff2              5.07 KiB
2:50:07 PM: dist/assets/KaTeX_Size1-Regular.c77c185d.woff2              5.29 KiB
2:50:07 PM: dist/assets/KaTeX_Size4-Regular.80aca689.woff2              4.77 KiB
2:50:07 PM: dist/assets/KaTeX_Typewriter-Regular.e96429b2.woff2         13.23 KiB
2:50:07 PM: dist/assets/KaTeX_AMS-Regular.34c2ce38.woff2                27.43 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Bold.0bc8b973.woff2                  24.74 KiB
2:50:07 PM: dist/assets/KaTeX_Main-BoldItalic.20912b1a.woff2            16.36 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Italic.d98644df.woff2                16.58 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Regular.0b23765e.woff2               25.64 KiB
2:50:07 PM: dist/assets/KaTeX_Math-BoldItalic.6e612a33.woff2            16.08 KiB
2:50:07 PM: dist/assets/KaTeX_Math-Italic.23099f26.woff2                16.06 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Bold.0ec62f03.woff            7.52 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Bold.00eb32ff.woff                12.97 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Regular.70a90ebd.woff         7.47 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Regular.25359a5c.woff             12.89 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Bold.85b2801f.woff              14.06 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Italic.2f4e4b91.woff            13.77 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Regular.658e9a9b.woff           12.01 KiB
2:50:07 PM: dist/assets/KaTeX_Script-Regular.ac656332.woff              10.33 KiB
2:50:07 PM: dist/assets/KaTeX_Size2-Regular.cf3ac857.woff               6.04 KiB
2:50:07 PM: dist/assets/KaTeX_Size1-Regular.5a63009d.woff               6.33 KiB
2:50:07 PM: dist/assets/KaTeX_Size3-Regular.8f82ae40.woff               4.31 KiB
2:50:07 PM: dist/assets/KaTeX_Size4-Regular.6660bc95.woff               5.83 KiB
2:50:07 PM: dist/assets/KaTeX_Typewriter-Regular.19971701.woff          15.64 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Bold.da61b0be.woff                   29.20 KiB
2:50:07 PM: dist/assets/KaTeX_Main-BoldItalic.e0e34b8b.woff             18.95 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Italic.912e161e.woff                 19.20 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Regular.ac0d2690.woff                30.04 KiB
2:50:07 PM: dist/assets/KaTeX_Math-BoldItalic.585a5c0b.woff             18.22 KiB
2:50:07 PM: dist/assets/KaTeX_Math-Italic.44f6b52f.woff                 18.30 KiB
2:50:07 PM: dist/assets/KaTeX_AMS-Regular.222831ff.woff                 32.72 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Bold.895d6214.ttf             12.05 KiB
2:50:07 PM: dist/assets/KaTeX_Caligraphic-Regular.24cb93b6.ttf          12.03 KiB
2:50:07 PM: dist/assets/KaTeX_Size2-Regular.15df6913.ttf                11.21 KiB
2:50:07 PM: dist/assets/KaTeX_Size1-Regular.8af05c8b.ttf                11.91 KiB
2:50:07 PM: dist/assets/KaTeX_Size3-Regular.569c9046.ttf                7.38 KiB
2:50:07 PM: dist/assets/KaTeX_Size4-Regular.feea5a15.ttf                10.09 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Bold.6e355454.ttf                 19.09 KiB
2:50:07 PM: dist/assets/KaTeX_Fraktur-Regular.3c51f649.ttf              19.09 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Bold.675e3f47.ttf               23.90 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Italic.9e4e756c.ttf             21.81 KiB
2:50:07 PM: dist/assets/KaTeX_SansSerif-Regular.45c5ffa1.ttf            18.95 KiB
2:50:07 PM: dist/assets/KaTeX_Script-Regular.9770e478.ttf               16.23 KiB
2:50:07 PM: dist/assets/KaTeX_Typewriter-Regular.cf805e11.ttf           26.88 KiB
2:50:07 PM: dist/assets/KaTeX_Math-BoldItalic.275f5ffd.ttf              30.44 KiB
2:50:07 PM: dist/assets/KaTeX_Math-Italic.fced106b.ttf                  30.54 KiB
2:50:07 PM: dist/assets/KaTeX_Main-BoldItalic.2241f144.ttf              32.17 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Italic.3b653e89.ttf                  32.76 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Bold.6a6e2a05.ttf                    50.10 KiB
2:50:07 PM: dist/assets/KaTeX_Main-Regular.1a9cbbfd.ttf                 52.30 KiB
2:50:07 PM: dist/assets/KaTeX_AMS-Regular.18191795.ttf                  62.11 KiB
2:50:07 PM: dist/index.html                                             0.72 KiB
2:50:07 PM: dist/assets/index.7df0bd37.js                               0.72 KiB / brotli: 0.34 KiB
2:50:07 PM: dist/assets/FileSaver.min.6ddffa7b.js                       2.62 KiB / brotli: 1.08 KiB
2:50:07 PM: dist/assets/vendor.e218031e.css                             68.50 KiB / brotli: 13.85 KiB
2:50:11 PM: dist/assets/vendor.537e35e9.js                              1135.96 KiB / brotli: 250.61 KiB
2:50:11 PM: browserType.launch: Executable doesn't exist at /opt/buildhome/.cache/ms-playwright/chromium-907428/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
2:50:11 PM: ║ Looks like Playwright Test or Playwright was just installed or updated. ║
2:50:11 PM: ║ Please run the following command to download new browsers:              ║
2:50:11 PM: ║                                                                         ║
2:50:11 PM: ║     npx playwright install                                              ║
2:50:11 PM: ║                                                                         ║
2:50:11 PM: ║ <3 Playwright Team                                                      ║
2:50:11 PM: ╚═════════════════════════════════════════════════════════════════════════╝
2:50:11 PM:     at exportSlides (/opt/build/repo/node_modules/@slidev/cli/dist/export-2N47BSBB.js:66:34)
2:50:11 PM:     at async build (/opt/build/repo/node_modules/@slidev/cli/dist/build-TDF4SOAP.js:382:5)
2:50:11 PM:     at async Object.handler (/opt/build/repo/node_modules/@slidev/cli/dist/cli.js:175:3) {
2:50:11 PM:   name: 'Error'
2:50:11 PM: }
2:50:11 PM: npm ERR! code ELIFECYCLE
2:50:11 PM: npm ERR! errno 1
2:50:11 PM: npm ERR! conf-nuxtnation-2021@ build: `slidev build`
2:50:11 PM: npm ERR! Exit status 1
2:50:11 PM: npm ERR!
2:50:11 PM: npm ERR! Failed at the conf-nuxtnation-2021@ build script.
2:50:11 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2:50:11 PM: npm ERR! A complete log of this run can be found in:
2:50:11 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-09-16T12_50_11_866Z-debug.log
2:50:11 PM: ​
2:50:11 PM: ────────────────────────────────────────────────────────────────
2:50:11 PM:   "build.command" failed                                        
2:50:11 PM: ────────────────────────────────────────────────────────────────
2:50:11 PM: ​
2:50:11 PM:   Error message
2:50:11 PM:   Command failed with exit code 1: npm run build
2:50:11 PM: ​
2:50:11 PM:   Error location
2:50:11 PM:   In build.command from netlify.toml:
2:50:11 PM:   npm run build
2:50:11 PM: ​
2:50:11 PM:   Resolved config
2:50:11 PM:   build:
2:50:11 PM:     command: npm run build
2:50:11 PM:     commandOrigin: config
2:50:11 PM:     environment:
2:50:11 PM:       - NODE_VERSION
2:50:11 PM:     publish: /opt/build/repo/dist
2:50:11 PM:     publishOrigin: config
2:50:11 PM:   redirects:
2:50:12 PM:     - from: /*
      status: 200
      to: /index.html
  redirectsOrigin: config
Caching artifacts
2:50:12 PM: Started saving node modules
2:50:12 PM: Finished saving node modules
2:50:12 PM: Started saving build plugins
2:50:12 PM: Finished saving build plugins
2:50:12 PM: Started saving yarn cache
2:50:14 PM: Finished saving yarn cache
2:50:14 PM: Started saving pip cache
2:50:14 PM: Finished saving pip cache
2:50:14 PM: Started saving emacs cask dependencies
2:50:14 PM: Finished saving emacs cask dependencies
2:50:14 PM: Started saving maven dependencies
2:50:14 PM: Finished saving maven dependencies
2:50:14 PM: Started saving boot dependencies
2:50:14 PM: Finished saving boot dependencies
2:50:14 PM: Started saving rust rustup cache
2:50:14 PM: Finished saving rust rustup cache
2:50:14 PM: Started saving go dependencies
2:50:14 PM: Finished saving go dependencies
2:50:14 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:50:15 PM: Creating deploy upload records
2:50:15 PM: Failing build: Failed to build site
2:50:15 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
2:50:15 PM: Finished processing build request in 1m22.498145276s
</details>

<details>
  <summary>Here is the whole stacktrace of the whole command, obvious I cannot run sudo there</summary>

3:04:36 PM: Build ready to start
3:04:50 PM: build-image version: fa439ad1ab9393b2c0d449d8d7c033927683f4b0
3:04:50 PM: build-image tag: v4.3.0
3:04:50 PM: buildbot version: d34b57a8e2866c6521420792f076bdf372efc56f
3:04:50 PM: Fetching cached dependencies
3:04:50 PM: Starting to download cache of 354.8MB
3:04:52 PM: Finished downloading cache in 2.090938937s
3:04:52 PM: Starting to extract cache
3:05:02 PM: Finished extracting cache in 10.080822837s
3:05:02 PM: Finished fetching cache in 12.255887498s
3:05:02 PM: Starting to prepare the repo for build
3:05:03 PM: Preparing Git Reference refs/heads/master
3:05:05 PM: Parsing package.json dependencies
3:05:05 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npx playwright install && yarn build' versus 'yarn build' in the Netlify UI
3:05:05 PM: Starting build script
3:05:05 PM: Installing dependencies
3:05:05 PM: Python version set to 2.7
3:05:06 PM: Started restoring cached node version
3:05:08 PM: Finished restoring cached node version
3:05:08 PM: v14.17.6 is already installed.
3:05:09 PM: Now using node v14.17.6 (npm v6.14.15)
3:05:09 PM: Started restoring cached build plugins
3:05:09 PM: Finished restoring cached build plugins
3:05:09 PM: Attempting ruby version 2.7.2, read from environment
3:05:10 PM: Using ruby version 2.7.2
3:05:10 PM: Using PHP version 8.0
3:05:10 PM: Started restoring cached yarn cache
3:05:13 PM: Finished restoring cached yarn cache
3:05:13 PM: No yarn workspaces detected
3:05:13 PM: Started restoring cached node modules
3:05:13 PM: Finished restoring cached node modules
3:05:13 PM: Installing NPM modules using Yarn version 1.22.10
3:05:14 PM: yarn install v1.22.10
3:05:14 PM: [1/4] Resolving packages...
3:05:14 PM: [2/4] Fetching packages...
3:05:15 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
3:05:15 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
3:05:15 PM: warning @slidev/theme-default@0.21.0: The engine "slidev" appears to be invalid.
3:05:15 PM: warning theme-vitesse@0.1.12: The engine "vscode" appears to be invalid.
3:05:15 PM: warning @slidev/theme-seriph@0.21.0: The engine "slidev" appears to be invalid.
3:05:15 PM: [3/4] Linking dependencies...
3:05:15 PM: warning "@slidev/cli > @slidev/client > drauu > @drauu/core > perfect-freehand > @tldraw/core@0.0.53" has unmet peer dependency "react@^17.0.2".
3:05:15 PM: warning "@slidev/cli > @slidev/client > drauu > @drauu/core > perfect-freehand > @tldraw/core@0.0.53" has unmet peer dependency "react-dom@^17.0.2".
3:05:15 PM: warning "@slidev/cli > @slidev/client > drauu > @drauu/core > perfect-freehand > rko@0.5.25" has unmet peer dependency "react@^17.0.2".
3:05:15 PM: warning "@slidev/cli > @slidev/client > drauu > @drauu/core > perfect-freehand > rko@0.5.25" has unmet peer dependency "react-dom@^17.0.2".
3:05:15 PM: warning "@slidev/cli > @slidev/client > drauu > @drauu/core > perfect-freehand > @tldraw/core > react-use-gesture@9.1.3" has unmet peer dependency "react@>= 16.8.0".
3:05:16 PM: [4/4] Building fresh packages...
3:05:16 PM: Done in 2.43s.
3:05:16 PM: NPM modules installed using Yarn
3:05:17 PM: Started restoring cached go cache
3:05:17 PM: Finished restoring cached go cache
3:05:17 PM: go version go1.16.5 linux/amd64
3:05:17 PM: go version go1.16.5 linux/amd64
3:05:17 PM: Installing missing commands
3:05:17 PM: Verify run directory
3:05:18 PM: ​
3:05:18 PM: ────────────────────────────────────────────────────────────────
3:05:18 PM:   Netlify Build                                                 
3:05:18 PM: ────────────────────────────────────────────────────────────────
3:05:18 PM: ​
3:05:18 PM: ❯ Version
3:05:18 PM:   @netlify/build 18.10.0
3:05:18 PM: ​
3:05:18 PM: ❯ Flags
3:05:18 PM:   baseRelDir: true
3:05:18 PM:   buildId: 614340e4e860ef0008898fbf
3:05:18 PM:   deployId: 614340e4e860ef0008898fc1
3:05:18 PM: ​
3:05:18 PM: ❯ Current directory
3:05:18 PM:   /opt/build/repo
3:05:18 PM: ​
3:05:18 PM: ❯ Config file
3:05:18 PM:   /opt/build/repo/netlify.toml
3:05:18 PM: ​
3:05:18 PM: ❯ Context
3:05:18 PM:   production
3:05:18 PM: ​
3:05:18 PM: ────────────────────────────────────────────────────────────────
3:05:18 PM:   1. build.command from netlify.toml                            
3:05:18 PM: ────────────────────────────────────────────────────────────────
3:05:18 PM: ​
3:05:18 PM: $ npx playwright install && yarn build
3:05:25 PM: Playwright build of chromium v907428 downloaded to /opt/buildhome/.cache/ms-playwright/chromium-907428
3:05:25 PM: Playwright build of ffmpeg v1005 downloaded to /opt/buildhome/.cache/ms-playwright/ffmpeg-1005
3:05:25 PM: yarn run v1.22.10
3:05:25 PM: $ slidev build
3:05:26 PM:   ●■▲
3:05:26 PM:   Slidev  v0.23.0
3:05:26 PM:   theme   @slidev/theme-seriph
3:05:26 PM:   entry   /opt/build/repo/slides.md
3:05:27 PM: vite v2.5.7 building for production...
3:05:27 PM: transforming...
3:05:37 PM: ✓ 255 modules transformed.
3:05:38 PM: rendering chunks...
3:06:01 PM: dist/assets/8b9eb19119592679c97707c257d88026.a02f38e2.png   59.08 KiB
3:06:01 PM: dist/assets/nuxt_logo.6a7ff90d.svg                          0.60 KiB
3:06:01 PM: dist/assets/poor_effort.6cc30f81.png                        59.93 KiB
3:06:01 PM: dist/assets/e58260c608c6b561fe83014c7cea6b0e.02ca51aa.png   72.94 KiB
3:06:01 PM: dist/assets/logo-title-horizontal.96c3c915.png              119.68 KiB
3:06:01 PM: dist/assets/2088e2bbdbe2490545f19ad7736380a1.fbb3b07c.png   267.53 KiB
3:06:01 PM: dist/assets/63efc529c06aba10c5e1cb302edadb0a.2496976c.png   310.00 KiB
3:06:01 PM: dist/assets/logo.b72bde5d.png                               92.11 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Bold.acee258c.woff2           6.77 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Regular.ada73fb2.woff2        6.75 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Regular.79bb8158.woff2            11.04 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Bold.5ed7c1a3.woff2               11.08 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Bold.eecd8e98.woff2             11.89 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Italic.fba87080.woff2           11.68 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Regular.9729a729.woff2          10.13 KiB
3:06:01 PM: dist/assets/KaTeX_Script-Regular.15c00a11.woff2             9.39 KiB
3:06:01 PM: dist/assets/KaTeX_Size1-Regular.c77c185d.woff2              5.29 KiB
3:06:01 PM: dist/assets/KaTeX_Size2-Regular.5e2769eb.woff2              5.07 KiB
3:06:01 PM: dist/assets/KaTeX_Size4-Regular.80aca689.woff2              4.77 KiB
3:06:01 PM: dist/assets/KaTeX_Typewriter-Regular.e96429b2.woff2         13.23 KiB
3:06:01 PM: dist/assets/KaTeX_AMS-Regular.34c2ce38.woff2                27.43 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Bold.0bc8b973.woff2                  24.74 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Italic.d98644df.woff2                16.58 KiB
3:06:01 PM: dist/assets/KaTeX_Main-BoldItalic.20912b1a.woff2            16.36 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Regular.0b23765e.woff2               25.64 KiB
3:06:01 PM: dist/assets/KaTeX_Math-BoldItalic.6e612a33.woff2            16.08 KiB
3:06:01 PM: dist/assets/KaTeX_Math-Italic.23099f26.woff2                16.06 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Regular.70a90ebd.woff         7.47 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Bold.0ec62f03.woff            7.52 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Regular.25359a5c.woff             12.89 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Bold.00eb32ff.woff                12.97 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Bold.85b2801f.woff              14.06 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Italic.2f4e4b91.woff            13.77 KiB
3:06:01 PM: dist/assets/KaTeX_Script-Regular.ac656332.woff              10.33 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Regular.658e9a9b.woff           12.01 KiB
3:06:01 PM: dist/assets/KaTeX_Size1-Regular.5a63009d.woff               6.33 KiB
3:06:01 PM: dist/assets/KaTeX_Size2-Regular.cf3ac857.woff               6.04 KiB
3:06:01 PM: dist/assets/KaTeX_Size4-Regular.6660bc95.woff               5.83 KiB
3:06:01 PM: dist/assets/KaTeX_Size3-Regular.8f82ae40.woff               4.31 KiB
3:06:01 PM: dist/assets/KaTeX_Typewriter-Regular.19971701.woff          15.64 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Bold.da61b0be.woff                   29.20 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Italic.912e161e.woff                 19.20 KiB
3:06:01 PM: dist/assets/KaTeX_Main-BoldItalic.e0e34b8b.woff             18.95 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Regular.ac0d2690.woff                30.04 KiB
3:06:01 PM: dist/assets/KaTeX_Math-BoldItalic.585a5c0b.woff             18.22 KiB
3:06:01 PM: dist/assets/KaTeX_Math-Italic.44f6b52f.woff                 18.30 KiB
3:06:01 PM: dist/assets/KaTeX_AMS-Regular.222831ff.woff                 32.72 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Bold.895d6214.ttf             12.05 KiB
3:06:01 PM: dist/assets/KaTeX_Caligraphic-Regular.24cb93b6.ttf          12.03 KiB
3:06:01 PM: dist/assets/KaTeX_Size1-Regular.8af05c8b.ttf                11.91 KiB
3:06:01 PM: dist/assets/KaTeX_Size2-Regular.15df6913.ttf                11.21 KiB
3:06:01 PM: dist/assets/KaTeX_Size3-Regular.569c9046.ttf                7.38 KiB
3:06:01 PM: dist/assets/KaTeX_Size4-Regular.feea5a15.ttf                10.09 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Regular.3c51f649.ttf              19.09 KiB
3:06:01 PM: dist/assets/KaTeX_Fraktur-Bold.6e355454.ttf                 19.09 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Bold.675e3f47.ttf               23.90 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Italic.9e4e756c.ttf             21.81 KiB
3:06:01 PM: dist/assets/KaTeX_Script-Regular.9770e478.ttf               16.23 KiB
3:06:01 PM: dist/assets/KaTeX_SansSerif-Regular.45c5ffa1.ttf            18.95 KiB
3:06:01 PM: dist/assets/KaTeX_Typewriter-Regular.cf805e11.ttf           26.88 KiB
3:06:01 PM: dist/assets/KaTeX_Math-BoldItalic.275f5ffd.ttf              30.44 KiB
3:06:01 PM: dist/assets/KaTeX_Math-Italic.fced106b.ttf                  30.54 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Italic.3b653e89.ttf                  32.76 KiB
3:06:01 PM: dist/assets/KaTeX_Main-BoldItalic.2241f144.ttf              32.17 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Bold.6a6e2a05.ttf                    50.10 KiB
3:06:01 PM: dist/assets/KaTeX_Main-Regular.1a9cbbfd.ttf                 52.30 KiB
3:06:01 PM: dist/assets/KaTeX_AMS-Regular.18191795.ttf                  62.11 KiB
3:06:01 PM: dist/index.html                                             0.72 KiB
3:06:01 PM: dist/assets/index.7df0bd37.js                               0.72 KiB / brotli: 0.34 KiB
3:06:01 PM: dist/assets/FileSaver.min.6ddffa7b.js                       2.62 KiB / brotli: 1.08 KiB
3:06:02 PM: dist/assets/vendor.e218031e.css                             68.50 KiB / brotli: 13.85 KiB
3:06:05 PM: dist/assets/vendor.537e35e9.js                              1135.96 KiB / brotli: 250.61 KiB
3:06:06 PM: browserType.launch:
3:06:06 PM: ╔════════════════════════════════════════════════════════════╗
3:06:06 PM: ║ Host system is missing a few dependencies to run browsers. ║
3:06:06 PM: ║ Please install them with the following command:            ║
3:06:06 PM: ║                                                            ║
3:06:06 PM: ║     sudo npx playwright install-deps                       ║
3:06:06 PM: ║                                                            ║
3:06:06 PM: ║ <3 Playwright Team                                         ║
3:06:06 PM: ╚════════════════════════════════════════════════════════════╝
3:06:06 PM:     at exportSlides (/opt/build/repo/node_modules/@slidev/cli/dist/export-2N47BSBB.js:66:34)
3:06:06 PM:     at async build (/opt/build/repo/node_modules/@slidev/cli/dist/build-TDF4SOAP.js:382:5)
3:06:06 PM:     at async Object.handler (/opt/build/repo/node_modules/@slidev/cli/dist/cli.js:175:3) {
3:06:06 PM:   name: 'Error'
3:06:06 PM: }
3:06:06 PM: error Command failed with exit code 1.
3:06:06 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
3:06:06 PM: ​
3:06:06 PM: ────────────────────────────────────────────────────────────────
3:06:06 PM:   "build.command" failed                                        
3:06:06 PM: ────────────────────────────────────────────────────────────────
3:06:06 PM: ​
3:06:06 PM:   Error message
3:06:06 PM:   Command failed with exit code 1: npx playwright install && yarn build
3:06:06 PM: ​
3:06:06 PM:   Error location
3:06:06 PM:   In build.command from netlify.toml:
3:06:06 PM:   npx playwright install && yarn build
3:06:06 PM: ​
3:06:06 PM:   Resolved config
3:06:06 PM:   build:
3:06:06 PM:     command: npx playwright install && yarn build
3:06:06 PM:     commandOrigin: config
3:06:06 PM:     environment:
3:06:06 PM:       - NODE_VERSION
3:06:06 PM:     publish: /opt/build/repo/dist
3:06:06 PM:     publishOrigin: config
3:06:06 PM:   redirects:
3:06:07 PM:     - from: /*
      status: 200
      to: /index.html
  redirectsOrigin: config
Caching artifacts
3:06:07 PM: Started saving node modules
3:06:07 PM: Finished saving node modules
3:06:07 PM: Started saving build plugins
3:06:07 PM: Finished saving build plugins
3:06:07 PM: Started saving yarn cache
3:06:09 PM: Finished saving yarn cache
3:06:09 PM: Started saving pip cache
3:06:09 PM: Finished saving pip cache
3:06:09 PM: Started saving emacs cask dependencies
3:06:09 PM: Finished saving emacs cask dependencies
3:06:09 PM: Started saving maven dependencies
3:06:09 PM: Finished saving maven dependencies
3:06:09 PM: Started saving boot dependencies
3:06:09 PM: Finished saving boot dependencies
3:06:09 PM: Started saving rust rustup cache
3:06:09 PM: Finished saving rust rustup cache
3:06:09 PM: Started saving go dependencies
3:06:09 PM: Finished saving go dependencies
3:06:09 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
3:06:09 PM: Creating deploy upload records
3:06:09 PM: Failing build: Failed to build site
3:06:09 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
3:06:10 PM: Finished processing build request in 1m20.013115169s
</details>

I've dumped it to `https://app.netlify.com/drop` as a built version and it works fine there!

PS: not sure if I'd be better to post this to their [Github issues](https://github.com/microsoft/playwright/issues). Sorry if it was more appropriate.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 91
 - Slidev version: 0.23.0

**Comment by antfu** [comment]
Do you see is there anything we can do to solve this?

**Comment by kissu** [comment]
Upgrading `playwright-chromium` to the [latest `1.15.0` version](https://github.com/microsoft/playwright/releases/tag/v1.15.0), fixed it! 🎉
