### ISSUE TITLE
Add option to give .md file as command line argument

### ISSUE THREAD

**Issue by groma84** [slidevjs/slidev#346]
I have a growing number of multiple small presentations (in the double digits already) - educational stuff, usually 5-10 slides. And I want to share the node_modules to avoid massive amounts of "lost" disk drive space.

It would be great if slidev would take the .md file it should use as an argument and default back to `slides.md` if none is given.

At the moment I'm thinking about writing a nodejs script for each presentation to copy the corresponding markdown files around - but that always carry the risk of losing changes in the slides.md if I forget to copy it somewhere else first manually before overwriting it via script...

**Comment by antfu** [comment]
I think you can already do that. Tried `slidev -h`? Meanwhile you can also install slidev globally to save the disk usage.

**Comment by groma84** [comment]
How embarrassing - I should have read the documentation more closely! Sorry for bothering you and thanks for the information. 

P. S. This project is awesome!
