### ISSUE TITLE
Slidev syncs drawing even without using the presenter

### ISSUE THREAD

**Issue by fabiankachlock** [slidevjs/slidev#348]
Drawing on slides get synced regardless of being in the presenter mode or not. 

For example when presenting a slide, a 'normal' viewer could draw something and everyone would see this drawing.

1. run `yarn slidev --remote`
2. open the presentation
3. draw stuff and watch it sync regardless of being in presenter mode or not.

 - OS: macOS 11.5.2
 - Browser: Firefox 37.0 (on ipad) / Chrome 93.0.4577.82
 - Slidev version: 0.25.0

**Comment by antfu** [comment]
This is actually a feature. Can you share more context here? maybe we could offer an option to disable it.

**Comment by fabiankachlock** [comment]
Oh, i didn't know that. It would be great, if you could turn it off then.

For example: 
You are presenting something to your colleagues. In this situation it could be annoying or disturbing if everybody could see the drawings everyone.

**Comment by fabiankachlock** [comment]
Thanks for your fast support, that's exactly what I meant.
