### ISSUE TITLE
Command failed with exit code 1: npm install

### ISSUE THREAD

**Issue by Yohager** [slidevjs/slidev#35]
I meet an issues about: Command failed with exit code 1: npm install
but I do not know why Error: Command failed with exit code 1: npm install
    at makeError (C:\Users\Yohager\AppData\Local\npm-cache\_npx\c00c242a51a5200e\node_modules\execa\lib\error.js:59:11)
![1](https://user-images.githubusercontent.com/38237744/117533908-c0ccf900-b021-11eb-844c-6be42f315cb5.png)

**Comment by antfu** [comment]
Can you provide more context? Thanks

**Comment by Yohager** [comment]
> Can you provide more context? Thanks

Initially my node version was 12.18 and at that time actually i can build the slides by 'npm init slidev', although it reports some warnings for node's version. 

However, I just updated my node version to 14.16.1 and tried 'npm init slidev'  again but it ran into error. So I do not know why? The error shows I need to install VS but I wonder why it did not fail when node version is 12.18. 

Report errors here.
![2](https://user-images.githubusercontent.com/38237744/117538469-e9acb880-b038-11eb-9740-11782ba7ad19.png)

**Comment by antfu** [comment]
Looks like it's your node-gyp's problem and does not related to this project I think. Maybe try use [nvm](https://github.com/nvm-sh/nvm) to install the node.

**Comment by antfu** [comment]
Close for now.
