### ISSUE TITLE
How to set the font size?

### ISSUE THREAD

**Issue by zheng-hai-peng** [slidevjs/slidev#353]
I checked the [slide/config](https://github.com/slidevjs/slidev/blob/main/packages/types/src/config.ts) file, but I still don't know how to set the font size.

**Comment by antfu** [comment]
Use CSS, or Windi CSS

`<div class="text-lg">Hi</div>`

```css
h1 {
  font-size: 20px;
}
```

**Comment by butla** [comment]
To increase the font size of "standard" text in the presentation, put a `style.css` file in the root directory of the project, and make it look like so:

```
.slidev-layout {
  p {
    font-size: 20px
  }

  ul {
    font-size: 20px
  }
}
```

[The relevant doc](https://sli.dev/custom/directory-structure.html#style).

This might be a nice hint for other non-front-end people (that includes me) that want to use this project.
