### ISSUE TITLE
Safari: camera view square

### ISSUE THREAD

**Issue by sbrugman** [slidevjs/slidev#356]
**Describe the bug**
When showing the camera view in safari, the video is shown as a square (as opposed to the circle in other browsers).  

In the documentation I could not find details on which browsers are supported. Did I overlook that or should we add it?

**To Reproduce**
1. Start the presentation in Safara
2. Click on 'Show camera view'

**Desktop (please complete the following information):**
 - OS: macOS big sur 11.6
 - Browser: Safarin 15.0
 - Slidev version: 0.25.8 (latest)

**Comment by antfu** [comment]
Nice catch. I think we could document it. If it's an easy fix, I am also happy to receive a PR for it. Otherwise, I don't really have the bandwidth to fix Safari issues (you know, the new IE) atm. Thanks
