### ISSUE TITLE
Google Chrome: recording audio/video out of sync

### ISSUE THREAD

**Issue by sbrugman** [slidevjs/slidev#357]
**Describe the bug**
When recording in Google Chrome with camera view, the audio and video are out of sync. (Tested with Safari, this didn't happen).  Tested that it isn't just the playback by converting using `ffmpeg` and viewing with other video player.

**To Reproduce**
1. Start the presentation in Google Chrome
2. Click on 'Show camera vieew'
3. Click on 'Recording'
4. Fill out a recording name
5. Click 'start'
6. Chrome Tab > Select the slidev tab
7. Click "share"
8. (Record)
9. Click on "Recording"
10. Open the recorded screen file

**Desktop (please complete the following information):**
 - OS:  macOS big sur 11.6 (latest)
 - Browser: Google Chrome Version 94.0.4606.61 (latest)
 - Slidev version:  0.25.8 (latest)

**Comment by antfu** [comment]
I can't reproduce on my side. Might need to help on this.
