### ISSUE TITLE
Present the project without localHost

### ISSUE THREAD

**Issue by hesitorremitos** [slidevjs/slidev#365]
Hello good
## My query
I would like to know if there is some way to be able to export html, that I can open without opening it with ```localhost```, not local either.
To be precise, open it in a browser and that's it.
To be able to make your presentations on another computer (That does not have any of the tools such as ```NPM``` installed).

Seria Genial poder portarlo a la unversidad y presentarlo sin mas complicaciones, tambien para trabajos y otros.
eso Reempazaria completamente a ```pptx```

I did not find a solution in this regard (I am starting out in programming).

Thank you for such a wonderful project.

**Comment by antfu** [comment]
https://sli.dev/guide/hosting.html
https://sli.dev/guide/exporting.html
