### ISSUE TITLE
feat: The ability to author slides with something other than vue

### ISSUE THREAD

**Issue by dominikg** [slidevjs/slidev#372]
**Is your feature request related to a problem? Please describe.**

svelte/mdsvex or react/mdx would also make a great base for authoring slides and these are just the 2 i can think of right now. There are and will be more combinations. 

Allowing users to select which frameworks/library to use would broaden the potential userbase as they can stick with their familiar tools.
 
**Describe the solution you'd like**
An abstraction layer allowing to use other languages/libraries to build slides, powered by vite plugins.

**Describe alternatives you've considered**
1) some kind of plugin that wraps the others into vue components
2) accept that sli.dev chose vue an keep using as is

**Comment by AleCandido** [comment]
@dominikg I considered myself to make a tool to author slides with Svelte components. The main motivation was not being aware of Slidev in the first place, so I was using Reveal.js with quite poor DX.
I thought a while about basing it on SvelteKit, and made [just a few attemps](https://github.com/AleCandido/show), but never spent enough time to make anything valuable.
By now, another option I would consider it would be to try to use something like [Astro](https://github.com/withastro/astro), such that it will compile on its own components from different frameworks.

At present time, I have not enough experience nor resources to resume the project on my own. But if someone else were interested in leading the effort, I'd be interest in taking part.

However, Slidev works so well that I'm really satisfied with the present status. I'm just left with the faint desire of being able to use Svelte, that is more intuitive to me. But I can also keep going with Vue, and trying to get used to it.

**Comment by dominikg** [comment]
For a svelte oriented solution, sveltekit+mdsvex are a great starting point, i used a hacky solution for my last talk on svelte summit:  https://github.com/dominikg/summit-2022

For a cross-framework solution i agree that astro is worth a look or two. A slideshow is basically static, so astro being an ssg and supporting multiple component formats makes it instantly tick off multiple boxes. Their extra work around markdown and frontmatter typings in the upcoming astro 2.0 might make it even petter for this an opinionated static ~~site~~ slide generator.

My resources are limited though so while I very much like the idea and would gladly be a beta user/early adoptor, i'm not able to help build one right now.
