### ISSUE TITLE
Internal server error: The request url "/home/node/node_modules/@slidev/client/main.ts" is outside of Vite serving allow list

### ISSUE THREAD

**Issue by nahsi** [slidevjs/slidev#386]
Sorry, I'm not familiar with node or npm, maybe I'm doing things very wrong. I'm following [best practices](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md)

**Describe the bug**
I'm running slidev in docker container, when I try to access http://localhost:3030 I get the error:
```
9:11:53 AM [vite] Internal server error: The request url "/home/node/node_modules/@slidev/client/main.ts" is outside of Vite serving allow list:

- /slides
- /home/node/node_modules/@slidev/cli
- /home/node/node_modules/vite/dist/client

Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.
      at ensureServingAccess (/home/node/node_modules/vite/dist/node/chunks/dep-92cbd8f1.js:56663:15)
      at viteServeRawFsMiddleware (/home/node/node_modules/vite/dist/node/chunks/dep-92cbd8f1.js:56630:13)
      at call (/home/node/node_modules/vite/dist/node/chunks/dep-92cbd8f1.js:45584:7)
      at next (/home/node/node_modules/vite/dist/node/chunks/dep-92cbd8f1.js:45528:5)
      at viteTransformMiddleware (/home/node/node_modules/vite/dist/node/chunks/dep-92cbd8f1.js:56925:9)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1. Create Dockerfile with content:
```dockerfile
FROM node:17-alpine as build
ARG SLIDEV_VERSION=0.27.9
USER node
WORKDIR /home/node
RUN npm install --quiet --no-progress \
        @slidev/cli@v$SLIDEV_VERSION \
        @slidev/theme-default \
        @slidev/theme-seriph

FROM node:17-alpine
ENV NODE_PATH=/home/node/node_modules/
ENV PATH=$PATH:/home/node/node_modules/.bin
USER node
COPY --from=build /home/node/node_modules/ /home/node/node_modules/
WORKDIR "/slides"
ENTRYPOINT ["slidev"]
CMD ["--remote"]
```
2. Build it with `docker build -t slidev:latest .`
3. Run it with `docker run --rm -p 3030:3030 --init -v ${PWD}:/slides slidev:latest`
4. Try to access http://localhost:3030
5. See the error

**Desktop (please complete the following information):**
 - OS: docker alpine
 - Slidev version: 0.27.9

**Comment by crutchcorn** [comment]
I'm experiencing the same error on Windows 11 with the latest Slidev release from a freshly generated `yarn create slidev`

However, `npx` doesn't solve the problem for me

**Comment by pluveto** [comment]
Same error

**Comment by nahsi** [comment]
I think it is better to create a separate issue @antfu please close this one if you
