### ISSUE TITLE
background image is not published for static hosting/SPA

### ISSUE THREAD

**Issue by fastzhong** [slidevjs/slidev#391]
**Describe the bug**
(npm run build) does not copy the background image to dist assets folder 

**To Reproduce**
1. Save a cover image to /images/cover.jpg
2. use the default slides.md and specify the background: /images/cover.jpg 
3. run $ npx slidev to publish locally and can see new cover on 1st slide
4. run $ npm run build to publish as SPA for static hosting
5. check assets folder inside dist and cover.jpg is missing 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Slidev version: 0.27.9

**Comment by antfu** [comment]
You will need to put them under `public/`
