### ISSUE TITLE
Exported SPA slides undisplayable due to CORS

### ISSUE THREAD

**Issue by yheuhtozr** [slidevjs/slidev#395]
**Describe the bug**
I exported a presentation using `yarn slidev build` and put it on GitLab Pages, but when I access the URL it displays a blank page with CORS error in console.

I did add the base path option: in my case, `yarn slidev build --base /iwcc-211107/`.

**To Reproduce**
1. Go to https://yheuhtozr.gitlab.io/iwcc-211007/  
(the source files are: https://gitlab.com/yheuhtozr/iwcc-211007/-/tree/slides)

**Desktop (please complete the following information):**
 - OS: Win10 21H1
 - Browser: Firefox 94.0.1, Chrome 95
 - Slidev version: 0.27.10

**Comment by tonai** [comment]
I don't really know why it's not working in your case, but I don't have any problem publishing to Gitlab pages on my side:
* The repo: https://gitlab.com/tonai/slidev-page
* The published page: https://tonai.gitlab.io/slidev-page
