### ISSUE TITLE
Build fails when using local custom theme.

### ISSUE THREAD

**Issue by Kurogoma4D** [slidevjs/slidev#405]
**Describe the bug**
When deploy some project using custom theme (in monorepo) to Netlify, I found an error like this:

```
3:34:18 PM: Error: Cannot find module '@slidev/types'
3:34:18 PM: Require stack:
3:34:18 PM: - /opt/build/repo/example_theme/setup/shiki.ts
3:34:18 PM:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
3:34:18 PM:     at Function.resolve (node:internal/modules/cjs/helpers:98:19)
3:34:18 PM:     at p (/opt/build/repo/slidev_example/node_modules/jiti/dist/jiti.js:1:52925)
3:34:18 PM:     at g (/opt/build/repo/slidev_example/node_modules/jiti/dist/jiti.js:1:54200)
3:34:18 PM:     at /opt/build/repo/example_theme/setup/shiki.ts:1:176
3:34:18 PM:     at g (/opt/build/repo/slidev_example/node_modules/jiti/dist/jiti.js:1:55111)
3:34:18 PM:     at loadSetups (/opt/build/repo/slidev_example/node_modules/@slidev/cli/dist/chunk-MJ3BO472.js:124:73)
3:34:18 PM:     at createMarkdownPlugin (/opt/build/repo/slidev_example/node_modules/@slidev/cli/dist/chunk-MJ3BO472.js:1135:32)
3:34:18 PM:     at async ViteSlidevPlugin (/opt/build/repo/slidev_example/node_modules/@slidev/cli/dist/chunk-MJ3BO472.js:1349:26)
3:34:18 PM:     at async build (/opt/build/repo/slidev_example/node_modules/@slidev/cli/dist/build-63UO2WKL.js:332:9) {
3:34:18 PM:   code: 'MODULE_NOT_FOUND',
3:34:18 PM:   requireStack: [ '/opt/build/repo/example_theme/setup/shiki.ts' ]
3:34:18 PM: }
```

Changing to not use shiki did not change the error that `@slidev/types` was not found.

And local build is works fine at all time.

**To Reproduce**
An reproducable repository is here: https://github.com/Kurogoma4D/slidev_custom_theme_test,
and here is build log that attempting to deploy it: https://app.netlify.com/sites/adoring-shaw-a7e05b/deploys/618f5c505f1fa67294f98703

1. Create a project and custom theme project to be a monorepo.
2. Make it dependent on that project to use a custom theme.
3. Setup Netlify build to deploy that project.

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser: Chrome 95.0.4638.69
 - Slidev version: 0.27.13

**Comment by Kurogoma4D** [comment]
Okay, I temporary resolved this...
A local custom theme doesn't make node_modules when build automatically, then the main project cannot find module.

So I changed build command to `sh -c 'cd ../custom_theme && npm install'; slidev build` and works it.
However, I think it would be better if slidev had a built-in way to build even a local custom theme (because slidev supports local theme).

**Comment by Kurogoma4D** [comment]
And sadly, the above solution caused a new problem by creating multiple node_modules ( https://github.com/vuejs/vue-next/issues/4344 ).

In the end, I decided to separate the custom theme for each repository in my project and `npm install` it on the user side.

**Comment by yjl9903** [comment]
Maybe you can use something like pnpm workspace to manage your monorepo at the root level?

**Comment by antfu** [comment]
I think you might want to either

- Put the theme under Slidev root
- Have a package.json under your theme and install the necessary packages
- Use monorepo workspace setup

I believe this is more like a Node.js dependency management question rather than a bug of Slidev.
