### ISSUE TITLE
Directory structure may not work with nested user path globally

### ISSUE THREAD

**Issue by yjl9903** [slidevjs/slidev#406]
**Describe the bug**
When bootstrapping slidev at the parent folder of `slides.md` (or absolute path), it still uses the current directory to resolve directory structure (like `public`, `setup` and so on). I think it should use the dirname of `slides.md` to resolve directory structure.

https://github.com/slidevjs/slidev/blob/2acab57e93b069a35541a4598df37a6c576b1d28/packages/slidev/node/options.ts#L92-L101

A possible solution (I am not sure whether it will bring some break changes):

```ts
function getUserRoot(options: SlidevEntryOptions) {
  const { entry: rawEntry = 'slides.md', userRoot = process.cwd() } = options
  const fullEntry = path.resolve(userRoot, rawEntry)
  return { entry: path.basename(fullEntry), userRoot: path.dirname(fullEntry) }
}
```

**To Reproduce**
1. Create `./nest/slides.md`
2. Create some client config `./nest/setup/xxx.ts`
3. Run `slidev ./nest/slides.md`
4. Check that setup does not work

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser: Edge
 - Slidev version: 0.27.13

**Comment by antfu** [comment]
Make sense, do you mind to send a PR? Thanks
