### ISSUE TITLE
Foot note for a list item shows up before it is supposed to

### ISSUE THREAD

**Issue by SathyaBhat** [slidevjs/slidev#408]
**Is your feature request related to a problem? Please describe.**

I've a list and a footnote on a list item, and I can't see to figure out a way to hide the footnote till the actual item comes up. 

The slide content looks like:

```
<v-clicks>

- Cloud Development Kit
- Define cloud resources using code
- Not a DSL, same language that you might be familiar with
- CDK Supports:
  - TypeScript
  - JavaScript
  - Python
  - .net
  - Go [^dev]

</v-clicks>

[^dev]: in developer preview
```

This is what I see:

![image](https://user-images.githubusercontent.com/25424/155025858-aab060df-d03e-49e9-86b3-851e8b53d495.png)

In this case, the "in developer preview should not have been shown.

**Describe the solution you'd like**

The footnote should be shown till the corresponding list item is shown. 

**Describe alternatives you've considered**

I tried applying `v-after` but doesn't seem to work.

**Comment by antfu** [comment]
IIRC you can do:

```ts
---
clicks: 7
---

<v-clicks at="3">

...

</v-clicks>
```

the list will start showing after you click 3 times.

You can refer to my slides: https://github.com/antfu/talks/tree/master/2021-10-20

**Comment by SathyaBhat** [comment]
Yeah, the problem is that the footbote is shown immediately on slide load and using `<v-clicks at="3">` doesn't show the specific list item till click 3 but the footnote is shown all times

**Comment by SathyaBhat** [comment]
I updated the issue to highlight the problem, sorry to have gotten it wrong.
