### ISSUE TITLE
When install @slidev/cli globally, we are forced to globally install @slidev/client and katex 

### ISSUE THREAD

**Issue by aeudes** [slidevjs/slidev#409]
**Describe the bug**
https://github.com/slidevjs/slidev/blob/2acab57e93b069a35541a4598df37a6c576b1d28/packages/slidev/node/plugins/extendConfig.ts#L57-L60
The L58 code resolves to extenal dependancy of slidev/cli and not internal ones, running slidev trigger the following error :
```
Error: Cannot find module '/home/alex/.local/lib/node_modules/@slidev/client/package.json'
```
But client is already install as internal dependancy in :
```
/home/alex/.local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/
```

This force us to install @slidev/client and katex globally to get rid of the module error (but i think is not the intended behavior).

**To Reproduce**
1. npm install -g @slidev/cli
2. create slides.md
3. slidev
4. answer yes to install default theme globally

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: firefox
 - Slidev version: 0.27.13

**Comment by yjl9903** [comment]
I think we should rewrite a new `resolveGlobal` function (another issue #403)?

And when global installed, resolve the `@slidev/client` from `__dirname`.
