### ISSUE TITLE
[Integrations] Plugin for obsidian.md

### ISSUE THREAD

**Issue by cocoonkid** [slidevjs/slidev#41]
[Feature request] obsidian.md plugin.

That would be so cool.

Thank you for your consideration.

**Comment by antfu** [comment]
I don't use Obsidian myself, so I am not sure if I can do anything on this. But if someone what to build the ecosystem and connect between Slidev and Obsidian, I am more than happy to share it. Thanks!

**Comment by BingoKingo** [comment]
How about creating an vscode extension (vsix) that integrate with vscode directly and make it more easily?

**Comment by universvm** [comment]
I'm interested in this as well! 

Not sure if it can help but there's this plugin that integrates with reveal js (https://revealjs.com):  https://github.com/MSzturc/obsidian-advanced-slides 

Maybe it can be of help

**Comment by nirtamir2** [comment]
I've created a plugin for it
See https://github.com/nirtamir2/obsidian-slidev
I need some help creating the server internally if someone wants to help see #1061
