### ISSUE TITLE
Invalid custom component

### ISSUE THREAD

**Issue by peterroe** [slidevjs/slidev#414]
I create a project, and I intercepted a paragraph from the example, so I should see the count component in browser
```
<!-- ./components/Counter.vue -->
<Counter :count="10" m="t-4" />

Check out [the guides](https://sli.dev/builtin/components.html) for more.

</div>
<div>
```
but I cant's see Count component in browser
Count component Not rendered

**Comment by antfu** [comment]
What's the version you are on? Can you upgrade to the lastest if you are not?

**Comment by peterroe** [comment]
I use the version of 0.27.15, and it is the lastest. I just use `yarn dev`, without change any code of example.
The results are as follows：
[https://img-blog.csdnimg.cn/5a3c01b736274709afa27e2e7111ccb5.png](https://img-blog.csdnimg.cn/5a3c01b736274709afa27e2e7111ccb5.png)
I cant's find the Count component

**Comment by peterroe** [comment]
and I try to toggle a few browsers, Includes Edge,FireFox and Chrome, and the results were the same for all these browsers

Development tools config: 
VScode : 1.61.1
git : 2.31.1
node: 14.17.6

My system conifg:
OS: window10
CPU: i5-9400f
GPU: Nvadia 1660

**Comment by peterroe** [comment]
Hey, antfu, I find this happens when I use vscode. I try to use hbuilderx, and everything works normally!!!
