### ISSUE TITLE
Theme using Vite plugins needs workaround

### ISSUE THREAD

**Issue by alvarosabu** [slidevjs/slidev#415]
**Is your feature request related to a problem? Please describe.**
I'm using SVG with `vite-svg-loader` on my theme https://github.com/alvarosaburido/slidev-theme-penguin to add graphics to slides, however, when a user installs my theme, they need to manually add the same plugin on a local `vite.config.ts`  to work.

**Describe the solution you'd like**
Would be possible to avoid this workaround somehow that I can add on the theme itself? Thanks in advance.

**Comment by antfu** [comment]
I think indeed it's possible to merge multiple vite config sources. I think we could introduce a new `setup/vite` entry as the others. PR welcome.

**Comment by tonai** [comment]
@antfu just a little question regarding this issue.
Setup files are processed by this plugin https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/plugins/setupClient.ts using the `transform` fonction.
But at this point, the vite configuration is already loaded, so I'm not sure we can handle the `vite.config.ts` files the same way.
Or maybe we can update the config afterwards ?

We can use the vite `config` hook to extends the configuration but not sure we can import the `vite.config.ts` files using dynamic imports like this: `const config = await import(file)`
In fact I give it a try but I have an error:
```js
const setups = uniq([
  ...options.themeRoots,
  ...options.addonRoots,
]).map(i => join(i, 'vite.config.ts'))
setups.forEach(async (file) => {
  if (!existsSync(file))
    return
  const data = await import(file) // SyntaxError: Cannot use import statement outside a module
})
```

Error I don't have when I import the file using a string:
```js
const data = await import('slidev-theme-penguin/vite.config')
console.log(data.default) // OK
```

Do you know a way to handle this case ?
