### ISSUE TITLE
Proper way to change favicon

### ISSUE THREAD

**Issue by iwgx** [slidevjs/slidev#420]
**Is your feature request related to a problem? Please describe.**
For now if we want to change favicon we should inject `<link rel="icon" ... ` to `index.html`.

Although this is work in some cases (for example it works for me in Google Chrome icon tab) but it's didn't work in another case (for example Slack preview card).

I'm using my own slide here https://wasm-intro.iwgx.io
And this is the repo https://github.com/iwgx/wasm-intro

### **It showed correctly in Chrome tab**

![Screenshot 2021-11-17 132709](https://user-images.githubusercontent.com/20817629/142146436-8a02688f-f391-49a8-a356-f671cd53093e.png)

### **Showed differently in Slack**

![image](https://user-images.githubusercontent.com/20817629/142146409-2088ed03-a708-4c91-a07c-30fb3ad40af6.png)

From [what I got](https://stackoverflow.com/a/35937365): although we think we already "override" the tag, it will be interpreted differently by different services so the icon that showed will be different and of course we don't want that.

I think it's also not a best practice to doing something like "override".

**Describe the solution you'd like**
Adding another property that `slides.md` can accept, something like

```md
icon: /images/favicon.png
```

**Describe alternatives you've considered**
I'm not sure about this. But how about not having a default favicon for the first place?

Thank you for your work in Slidev.

**Comment by antfu** [comment]
Sounds like a good proposal. I am open for PR. Thanks!

**Comment by yjl9903** [comment]
I create a PR to support this feature https://github.com/slidevjs/slidev/pull/421

And there is an issue that I am not sure whether it is necessary to add favicon type.

```html
<link rel="icon" type="image/png" href="https://cdn.jsdelivr.net/gh/slidevjs/slidev/assets/favicon.png">
```

Or just

```html
<link rel="icon" href="https://cdn.jsdelivr.net/gh/slidevjs/slidev/assets/favicon.png">
```

**Comment by iwgx** [comment]
Thanks for the PR, I already try it and looks amazing now 😀
