### ISSUE TITLE
Problems using local images

### ISSUE THREAD

**Issue by tutods** [slidevjs/slidev#423]
Hi
When I try use a local images (on public folder) my presentation not working and receive this error on my browser console:

![image](https://user-images.githubusercontent.com/18479474/142741189-8adcbf4d-2973-4e1b-bf90-ffa41458215b.png)

Anyone can help me?
I only create the project with the yarn command

**Comment by Ahacad** [comment]
Did the whole project crashed? Could you give the essential part of code that you wrote in your file?

**Comment by rayfoss** [comment]
I'm also seeing this in Stackblitz web containers... What operating system are you on? was your connection choppy? do small images have the same problem? How are you uploading the images?

```
Node 16
ChromeOS 99
Connected to github
Uploaded via github
```

**Comment by tonai** [comment]
Can you share an reproduction repo ?

**Comment by rayfoss** [comment]
Stackblitz has a ton of issues with local images, specially ones imported from a Github repository. This is not a slideEv problem. There is also an issue where if your image URL cannot be loaded you have to wait for a 10-20 second timeout before SlideEV will render... that's not clear to the user and it just looks like SlideEV is poorly optimized.
