### ISSUE TITLE
Notes not showing if the only content

### ISSUE THREAD

**Issue by mathieutu** [slidevjs/slidev#424]
**Describe the bug**
Hi,
I've slides with no content : it's just a layout with some props (in my case some images paths).

If I try to add a comment in the content, it will not be shown as a note (despite the fact that it is the last thing in slide because the only)

**To Reproduce**
Add a slide like this one: 
```
---
layout: image
image: /photos/maps/france-map.jpg
dim: true
---
<!-- fooooo -->
```

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Firefox
 - Slidev version: v0.27.13

Thanks for your amazing work!
Mathieu.

**Comment by bambalamm** [comment]
Yep, I noticed this as well. As a workaround adding a dummy comment above the note works:

```
---
layout: image
image: /photos/maps/france-map.jpg
dim: true
---

<!-- dummy comment - not shown as note -->

<!-- note - now shows in notes -->
```
