### ISSUE TITLE
[vite]: Rollup failed to resolve import "~icons/mdi/web"

### ISSUE THREAD

**Issue by spences10** [slidevjs/slidev#426]
**Describe the bug**

I've been getting this error message since I started using an icon in the deck and now, even after removing the dependency still get the same error:

```
9:01:56 PM: [vite]: Rollup failed to resolve import "~icons/mdi/web" from "../../../@slidev/slides/47.md".
9:01:56 PM: This is most likely unintended because it can break your application at runtime.
9:01:56 PM: If you do want to externalize this module explicitly add it to
9:01:56 PM: `build.rollupOptions.external`
9:01:56 PM: Error: [vite]: Rollup failed to resolve import "~icons/mdi/web" from "../../../@slidev/slides/47.md".
9:01:56 PM: This is most likely unintended because it can break your application at runtime.
```

I've tried building on Vercel and Netlify and it the same error, it build locally no issues (using pnpm)

**To Reproduce**
1. Go to 'https://github.com/spences10/sveltekit-and-the-content-layer'
2. Clone
3. Deploy to Vercel
4. See the error

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu 20.04
 - Browser: Edge
 - Slidev version: latest `"@slidev/cli": "^0.27.17"`

**Comment by antfu** [comment]
Might because of this https://github.com/antfu/unplugin-icons/issues/123 Please upgrade your lock and try again
