### ISSUE TITLE
Selecting the "cover" layout for the first slide instead of "intro" when a layout is not explicitly specified

### ISSUE THREAD

**Issue by radiantshaw** [slidevjs/slidev#429]
**Describe the bug**
Currently, Slidev auto-selects the "cover" layout for the first slide and "default" for the rest. I feel it should select the "intro" layout for the first slide instead.

**To Reproduce**
1. `npm init slidev-theme` or `yarn create slidev-theme`
2. `npm run dev` or `yarn dev`
3. Open the first slide in the browser
4. Inspect the slide content, and notice that it has the `cover` class added to it (also has the "cover" layout selected implicitly)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6
 - Browser: Chrome 96.0.4664.55
 - Slidev version: >= 0.19.3

**Comment by radiantshaw** [comment]
@antfu Any updates on this?

**Comment by antfu** [comment]
I don't understand the reason behind this
