### ISSUE TITLE
Images not loaded in presenter mode.

### ISSUE THREAD

**Issue by kxxt** [slidevjs/slidev#433]
**Describe the bug**
I have a monorepo where there are several slidev projects inside it. Everything goes well except presenter mode.
When I open the presenter mode, my local images doesn't load.
**To Reproduce**
1. Create a  monorepo using yarn.
2. Add a slidev project to it using slidev-cli.
3. Add a local picture to `slides.md`, for example `![Image title](slides.assets/image.jpg)`.
4. Run `yarn install` in the monorepo
5. Run `yarn workspace xxx dev`.
6. Go to presenter mode. Local images doesn't load.

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview Build 22509
 - Browser: Edge Dev  98.0.1089.1 
 - Slidev version: 0.27.18

I found that the presenter mode is trying to load the image from `http://localhost:3030/presenter/slides.assets/image-20211207200935516.png`, which results in a 404 error.
But the image can be loaded with this url `http://localhost:3030/slides.assets/image-20211207200935516.png`.
Maybe this issue is not related to monorepo, because when I tried without monorepo, the issue persists.

**Comment by Ahacad** [comment]
Try `<img src="/slides.assets/image-20211206220732601.png" />`

**Comment by kxxt** [comment]
> Try `<img src="/slides.assets/image-20211206220732601.png" />`

Hi @Ahacad , thanks for your reply.
I think this could be considered a temporary workaround. But it would be better if this issue will be solved completely.

By the way, using markdown syntax like `![image-20211206220732601](/slides.assets/image-20211206220732601.png)` works in presenter mode as well.

**Comment by kxxt** [comment]
Hi. As I saw that this is a documented behavior in  https://sli.dev/guide/syntax.html#static-assets , I'm going to close this issue.
However, It would be more convenient if we can reference images without the leading slash character.

Anyway, thank you for this awesome application👋! Now I love to create slides with **slidev** insted of PowerPoint.
