### ISSUE TITLE
Shareable demo link not loaded properly

### ISSUE THREAD

**Issue by noook** [slidevjs/slidev#44]
I can't tell if this is a router misconfiguration or server misconfiguration, but when sharing the link on a specific slide / clicks, the page remains black.

Willing to contribute if this is code related

<https://sli.dev/demo/composable-vue/7.html>

**Comment by antfu** [comment]
It's just me been a bad typewriter 😅

**Comment by noook** [comment]
It's not possible to resume the slides from a specific point ? (yet ?)

**Comment by antfu** [comment]
Should not have the `.html` suffix, sli.dev/demo/composable-vue/7.

Where did you get the url tho?

**Comment by noook** [comment]
Probably copy pasted from the URL bar when the issue was still present. My bad then !
