### ISSUE TITLE
When the code block contains process.env.NODE_ENV, run error

### ISSUE THREAD

**Issue by mlzzen** [slidevjs/slidev#440]
**Describe the bug**

**To Reproduce**
just 
1. 
![image](https://user-images.githubusercontent.com/11664505/146641657-9a6c8797-85d5-49d1-9168-49a2cacb17bc.png)

then it work error
![image](https://user-images.githubusercontent.com/11664505/146641700-6ab4ae36-eb50-4517-8657-80c246ae121a.png)

**Desktop (please complete the following information):**
 - OS: win10 
 - Browser: Edge 95
 - Slidev version: v0.27.20

**Comment by GuillaumeAmat** [comment]
Just ran into this, can we reopen the issue?
