### ISSUE TITLE
Page number of multiple window are not synchronized in presenter mode

### ISSUE THREAD

**Issue by yunying1** [slidevjs/slidev#442]
**Describe the bug**
i'm run slidev project and open presenter mode in local, project normal operation in multiple window, but other window stay at the original page number when i switch page number in current window, i'm not sure if this is a bug but i'm very puzzled.
i like slidev very much, hope to have the opportunity to contribute to slidev.

**Desktop (please complete the following information):**
 - OS: Macos monterey
 - Browser: Google Chrome v96.0.4664.110 (x86_64)
 - Slidev version: ^0.27.20

**Comment by yunying1** [comment]
draw and dark mode is synchronization in multiple window

**Comment by tonai** [comment]
Page synchronization is only available from the presenter view.
