### ISSUE TITLE
Expose slides metadata through global context

### ISSUE THREAD

**Issue by Mojeer0** [slidevjs/slidev#446]
**Is your feature request related to a problem? Please describe.**
I would like to be able to build a summary slide dynamically.
Let's say all my section titles slides use `layout: section`. I have 3 slides that use this layout with the following titles `first` `second` `third`
I would like to be able to build this summary slide automatically:

```
1. first (slide n°8)
2. second (slide n°13)
3. thrid (slide n°19)
```

**Describe the solution you'd like**
Expose slides metadata through vue global context. $slidev could have a new key `slides`. `slides` would be an array of objects with the following keys: `title` (or `h1`?), `number`, `layout`, `url`, `configs`.
With such an object the above summary could be built as a vue component that iterate over $slidev.slides

`configs` would be similar to `$slidev.configs`, updated for each slide. It is not needed for this summary example, but I figured it could enable other use cases. For instance one might not want to add an entry to the summary simply by looking at the layout, but through a custom `showInSummary` setting.

**Describe alternatives you've considered**
Manually build that summary slide, and update it when inserting a new slide or section

If that make sense I'm willing to work on this.

**Comment by aeudes** [comment]
I start playing with that sort of thing for a personal project. My finding at the moment is that those data are not accessible via the global context. But you can recover most of the info by importing the route metadata generated by the server in your component/layout:
``` import {rawRoutes} from "@slidev/client/routes" ```
IMHO, you will be able to access slide layout and config and necessary info to build summary.


The only thing, i was not able to discover at client side at the moment without inject it is : the slide number where my component is embedded...

**Comment by tonai** [comment]
@Mojeer0 You can have a look at the built-in `<toc>` component for that: https://sli.dev/builtin/components.html#toc

If this does not answer your needs you can still create your own component and, as @aeudes suggests use the `rawRoutes` variable, or check again the `$slidev` variable that contains new data like `tree` properties that is used by the `<toc>` component.

**Comment by Mojeer0** [comment]
@tonai Thanks, that's exactly what I was looking for.
