### ISSUE TITLE
When I save my slides.md the front-matter of my slide is converted on ## markdown

### ISSUE THREAD

**Issue by messenjer** [slidevjs/slidev#447]
Hello, I think there is a regression with the last modification on [packages/parser](https://github.com/slidevjs/slidev/commit/6fd57a3e7c86152f4b4ae2352f6971f47fec7aa1)

When I save my slides.md, prettier transforms the [front-matter](https://sli.dev/guide/syntax.html#front-matter-layouts) of my slide, like this: 

Before: 

```
---
layout: section
---
```

After: 

```diff
 ---
-layout: section
----
+
+## layout: section
```

Like this issue https://github.com/slidevjs/slidev/pull/202

**To Reproduce**
- Install the latest version of slidev `npm init slidev@latest` (here version 0.27.20) 
- Open the slides.md with vscode and the prettier extension
- Save the file

```
---
layout: image-right
image: https://source.unsplash.com/collection/94734566/1920x1080
---
```
```diff
---
+
layout: image-right
image: https://source.unsplash.com/collection/94734566/1920x1080
+
---
```

Thanks for your amazing work!

Mathieu

**Comment by maiertech** [comment]
@messenjer What was the solution?

**Comment by messenjer** [comment]
Disable prettier extension in vscode

**Comment by wycats** [comment]
This doesn't seem like a great solution, since it also means that code examples can't get formatted.

Maybe we need a slidev-specific formatter? Or a different way to do front matter (maybe something with code fences) that would be more compatible with markdown tooling?

**Comment by Evertras** [comment]
Just ran into this as well, was wondering why my slides had the layout printed at the top each time...

It looks like [prettier's 3.0 release](https://prettier.io/blog/2023/07/05/3.0.0.html) just updated their plugin interface.  I wonder if there's a way to basically patch [the existing markdown](https://github.com/prettier/prettier/tree/main/src/language-markdown) code as a plugin.

**Comment by leggomuhgreggo** [comment]
Here's what I did, using [this extension](https://marketplace.visualstudio.com/items?itemName=mervin.markdown-formatter)
```
  "[markdown]": {
    "editor.defaultFormatter": "mervin.markdown-formatter",
    "editor.renderWhitespace": "all",
    "editor.quickSuggestions": {
      "other": true,
      "comments": true,
      "strings": true
    }
  },
  ```

**Comment by zkriszti** [comment]
> Here's what I did, using [this extension](https://marketplace.visualstudio.com/items?itemName=mervin.markdown-formatter)
> 
> ```
>   "[markdown]": {
>     "editor.defaultFormatter": "mervin.markdown-formatter",
>     "editor.renderWhitespace": "all",
>     "editor.quickSuggestions": {
>       "other": true,
>       "comments": true,
>       "strings": true
>     }
>   },
> ```

Though it would be nice to find the root cause (which might not be in slidev at all), god bless you for this comment, this did the trick for me! ❤️
