### ISSUE TITLE
Installation problem with 'const execa = require('execa')'

### ISSUE THREAD

**Issue by MarcAntoineAlex** [slidevjs/slidev#455]
**Describe the bug**

**Describe the bug**
When I try to install slidev with "npm init slidev", I've encounterd the following error:

/Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/index.js:10
const execa = require('execa')
              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/node_modules/execa/index.js from /Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/index.js not supported.
Instead change the require of /Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/node_modules/execa/index.js in /Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/marc-antoine/.config/yarn/global/node_modules/create-slidev/index.js:10:15) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code 1
npm ERR! path /Users/marc-antoine/.config/yarn/global/node_modules/create-slidev
npm ERR! command failed
npm ERR! command sh -c create-slidev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marc-antoine/.npm/_logs/2022-01-14T09_05_41_836Z-debug-0.log

I've googled this error and got 2 advises:
1. Downgrade node-fetch version to 2.6.1
2. add "type": "module" in the package.json file and change "const execa = require('execa')" to "import execa from 'execa'"
But none of them work. 

**To Reproduce**
1. Type  'npm init slidev'
2. See the error

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1
 - Slidev version: latest

**Comment by antfu** [comment]
Should already be fixed in v0.28.1
