### ISSUE TITLE
Error when building with Tweet-component

### ISSUE THREAD

**Issue by jolo-dev** [slidevjs/slidev#471]
**Describe the bug**
When adding the `Tweet` component to the slides and run `pnpm build`, it failes.

Here is the output

```sh
(!) "base" option should start with a slash.
(!) "base" option should end with a slash.
vite v2.7.12 building for production...
<script src="https://platform.twitter.com/widgets.js"> in "/index.html" can't be bundled without type="module" attribute
```

**To Reproduce**

Add a `Tweet` component to your slides; e.g.

```md
---
preload: true

---

<div v-motion-roll-visible-top>

<Tweet id="1449138460615315458" />

</div>
```

Then run `pnpm build`. 

When I remove it, it works.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey (Version 12.1)
 - Browser: No Browser needed
 - Slidev version: 0.28.2

**Comment by hisamafahri** [comment]
Can't reproduce the problem

**Comment by jolo-dev** [comment]
Seems to be on my end.
Apparently, it works now
