### ISSUE TITLE
Unwanted opacity for picture

### ISSUE THREAD

**Issue by mephistorine** [slidevjs/slidev#472]
Unwanted opacity for picture, when the picture goes right after the title, a transparency effect is superimposed on it

Steps to reproduce the behavior, use next markup for slide:

```md
# Hello there

![](https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png)
```

<img width="1371" alt="Screenshot 2022-02-04 at 00 38 57" src="https://user-images.githubusercontent.com/17084223/152433396-70c2b073-1dbb-4540-bd78-e7428d21c374.png">

 - OS: MacOS 12.1
 - Browser: Google Chrome 97
 - Slidev version: 0.28.2

**Comment by hisamafahri** [comment]
I guess it is a bug that assuming the image as a `p`. If you try to add a `p` below the `h1`, you'll see that the image opacity is normal and the `p` is the one that have the opacity:

```md
# Hello there

Hello, world!

![](https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png)
```

---

Currently, the workaround is to make the `opacity: 1` inside the markdown itself:

```md
# Hello there

<style>
h1 + p { opacity: 1 }
</style>

![](https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png)
```

OR, make the title as an `H2` or below:

```md
## Hello there

![](https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png)
```

**Comment by antfu** [comment]
Sorry for the inconvenience but this is how the style of the default theme is. If you see a way to only selector the plain text `p` after `h1` but not the images, feel free to send a PR to fix it. Otherwise, I think you can either have a stylesheet to override it, or creating your own theme.
