### ISSUE TITLE
Error on slidev --open

### ISSUE THREAD

**Issue by bobstrange** [slidevjs/slidev#474]
**Describe the bug**
`npm run dev` throws error after I update @slidev/cli@0.28.3.

**To Reproduce**

1. init a new project `npm init slidev` or update @slidev/cli@0.28.3 for existing project.
2. run `npm run dev` then get error.

```bash
npm run dev

> dev
> slidev --open

 > node_modules/@slidev/parser/dist/chunk-YMAA333D.mjs:79:9: error: No matching export in "browser-external:url" for import "fileURLToPath"
    79 │ import { fileURLToPath } from "url";
       ╵          ~~~~~~~~~~~~~

(node:24816) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
node_modules/@slidev/parser/dist/chunk-YMAA333D.mjs:79:9: error: No matching export in "browser-external:url" for import "fileURLToPath"
...
```

I downgraded slidev to 0.28.2 then run `npm run dev`, it works.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4
 - Browser: Chorome
 - Slidev version: 0.28.3
 - Node.js version: 14.17.0 and 16.10.0

**Comment by marob** [comment]
@antfu f4142dd0d550ca042536ee07e18f9e4d115a04ec seems to have introduced a regression.

**Comment by marob** [comment]
@antfu It looks like it doesn't solve the issue.

**Comment by tonai** [comment]
I confirm, I still have an issue running slidev in 0.28.3 or 0.28.4

**Comment by tonai** [comment]
Last 0.28.5 version fixes the issue :)
