### ISSUE TITLE
Add mp4 or mov exports to the recording

### ISSUE THREAD

**Issue by kissu** [slidevjs/slidev#475]
When recording and sending the `.webm` to a conference after a record, they usually me for a `.mp4` or a `.mov` because it's probably a more common extension for video montage softwares.

Having the possibility to choose an extension before the recording would be perfect!

I could transcode it to another format but it will probably bring some quality loss during the conversion. It's still the only available solution right now, but the quality suffers out of this.

**Comment by antfu** [comment]
AFAIK, most browsers only support recording to webm format, and I don't know how to convert them efficiently with JS

**Comment by MarvinXu** [comment]
[RecordRTC](https://github.com/muaz-khan/RecordRTC) support sevaral Codecs and can be configured by `mimeType`.
So we can pass in a custome config into `packages\client\logic\recording.ts`

I'm not sure how to design this feature. Maybe adding a selection list in the recording dialog?
