### ISSUE TITLE
Dependency Security Issue

### ISSUE THREAD

**Issue by Penguinlay** [slidevjs/slidev#476]
Is it necessary to freeze mermaid version to `8.13.0`? If not, it should be updated due to security issue.

https://github.com/slidevjs/slidev/blob/b7c145997d4a63e660177935f371c5b4c4128965/package.json#L64

<img width="1010" alt="CleanShot 2022-02-08 at 13 38 29@2x" src="https://user-images.githubusercontent.com/13214144/153080080-4590a5bc-cf6f-43c4-8253-6e4907099b13.png">

**Comment by antfu** [comment]
At the time I make the fixed version, the newer version of mermaid is fails to be built. You can try to upgrade it, if it works fine, I am happy to receive a PR. Thanks.
