### ISSUE TITLE
How to create multiple MD files?

### ISSUE THREAD

**Issue by he57207494** [slidevjs/slidev#479]
I want to create multiple slides and ensure that each can be accessed separately

**Comment by gabriel-del** [comment]
I made an implementation that is working
You can access at: https://github.com/gabriel-del/slidev
All feedbacks are welcome

**Comment by CondensedMilk7** [comment]
I made a similar thing as @gabriel-del but in Node.
Just throwing it out there in case someone might find it useful: https://github.com/CondensedMilk7/pluraslides

This one is best suited for netlify (which is my use case).
