### ISSUE TITLE
PDF links to slides are broken

### ISSUE THREAD

**Issue by tonai** [slidevjs/slidev#483]
**Describe the bug**
When creating a link in the slides with the `RouterLink` component (example `<RouterLink to="10">go to slide 10</RouterLink>`), the link does not work when exporting the slides into pdf. 

**To Reproduce**
1. Create a slidev project
2. Add `<RouterLink to="10">go to slide 10</RouterLink>` into one of the slide
3. It should work in dev and build mode (if you have at least 10 pages in your slides)
4. run `npm run export` and click the same link inside the PDF and it does not work

**Desktop (please complete the following information):**
- OS: ubuntu 20.04.3 LTS (Focal Fossa)
- Browser: chrome 96.0.4664.110
- Slidev version: main branch (v0.28.1)
- node: 16.13.1
- pnpm: 6.25.1

**Additionnal comments**
This is most likely due to the fact that the export creates each page independently and then concat them all to have the full pdf file.
Maybe we should consider having a custom `/print` URL that will format all the slides (using the `@media print`), so we can print the whole presentation using the browser print pdf feature.
It should also considerably increase the export time.

**Comment by twitwi** [comment]
@tonai can this be closed?

**Comment by tonai** [comment]
Sure
