### ISSUE TITLE
Local server extremely slow since 0.27

### ISSUE THREAD

**Issue by derkoe** [slidevjs/slidev#484]
**Describe the bug**
Since version 0.27 slidev hangs (or is very slow) when running from a project with multiple slides. 

**To Reproduce**
1. Clone https://github.com/fguisso/talks.git
2. Update the dependency of `@slidev/cli` to the current version (0.28.5)
3. run `npm i`
4. run `npm run dev -- slides/top-10.md `
5. See the process hanging/running at 100% cpu. It will finish after 1-2 minutes building

**Desktop (please complete the following information):**
 - OS: Linux fedora 5.16.8-200.fc35.x86_64
 - Browser: any
 - Slidev version: 0.28.5

**Comment by chartinger** [comment]
On windows the server will not even start if the markdown files are in a subdirectory with error:
`[vite] Internal server error: EMFILE: too many open files`

Last known working version was `0.27.13`. It may be the same error: Does it start normally if you put `top-10.md` in the project root directory?

**Comment by YeautyYE** [comment]
I run macOS and have the same problem

**Comment by derkoe** [comment]
This is still a problem - bump.

**Comment by derkoe** [comment]
Just tried it with 0.36.11 - still the same behaviour

**Comment by jonarriza96** [comment]
Hi! First and foremost, thanks for the awesome tool :fire: . For anyone bumping into this issue, opening a exclusive window (with a single tab) solved this for me (using firefox).
