### ISSUE TITLE
Could not resolve entry module (index.html).

### ISSUE THREAD

**Issue by derkoe** [slidevjs/slidev#485]
**Describe the bug**
When running the build with multiple slides repository it fails with the error

```
Could not resolve entry module (index.html).
Error: Could not resolve entry module (index.html).
    at error (/tmp/talks/node_modules/rollup/dist/shared/rollup.js:160:30)
    at ModuleLoader.loadEntryModule (/tmp/talks/node_modules/rollup/dist/shared/rollup.js:22421:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
```

**To Reproduce**
1. Clone https://github.com/fguisso/talks.git
2. Update the dependency of `@slidev/cli` to the current version (0.28.5)
3. run `npm i`
4. run `npm run build -- ./slides/top-10.md --base /talks/top-10/`
5. See the error above

**Desktop (please complete the following information):**
 - OS: Linux fedora 5.16.8-200.fc35.x86_64
 - Browser: -
 - Slidev version: 0.28.5

**Comment by spawnrider** [comment]
Hi,

Same issue on my machine : 
`vite v2.8.4 building for production...
✓ 0 modules transformed.
Could not resolve entry module (../../../../.nvm/versions/node/v14.18.1/lib/node_modules/@slidev/cli/index.html).
Error: Could not resolve entry module (../../../../.nvm/versions/node/v14.18.1/lib/node_modules/@slidev/cli/index.html).
    at error (/Users/yciurlik/.nvm/versions/node/v14.18.1/lib/node_modules/@slidev/cli/node_modules/rollup/dist/shared/rollup.js:159:30)
    at ModuleLoader.loadEntryModule (/Users/yciurlik/.nvm/versions/node/v14.18.1/lib/node_modules/@slidev/cli/node_modules/rollup/dist/shared/rollup.js:22409:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'`

Seems to be a duplicate from https://github.com/slidevjs/slidev/issues/497

**Comment by derkoe** [comment]
The issue is not resolved with v0.28.9 - repeating the steps in the bug description with this version leads to the exact same error.

**Comment by derkoe** [comment]
When I create and index.html at the repository root the error goes away but index.html in the dist folder does not include Slidev (it is just copied there)

**Comment by derkoe** [comment]
@antfu  should i open a new issue?

**Comment by snice** [comment]
install globally，same issue

**Comment by Andrej-Marsic** [comment]
Same issue, how come this is closed?
