### ISSUE TITLE
Not an issue: How to publish to the web?

### ISSUE THREAD

**Issue by brucou** [slidevjs/slidev#49]
First of all congrats for the amazing work that you did. It is inspiring. I just got to know about it, I would interested actually in using it for my own presentations, I was just wondering how to publish to the web? I only find exporting to pdf. I understand `slidev build` produces a SPA? So I would only need a web server post build to run it right? Well I guess it is just about trying it out but I thought you could quickly dispell the doubts in my mind.

**Comment by antfu** [comment]
You can use services like GitHub Pages, Netlify, Vercel for hosting

https://sli.dev/guide/exporting.html#single-page-application-spa

Do you faced any obstacle on this?

**Comment by brucou** [comment]
Nope, went like a charm. Many thanks!
