### ISSUE TITLE
Sync presenter and play mode 

### ISSUE THREAD

**Issue by arnoson** [slidevjs/slidev#492]
I'm not sure if I'm missing something, but the presenter and play mode are not in sync. For example: when using the starter presentation and increasing the counter in the `Components` slide, the counter value doesn't update in the play mode window. 
The same problem occurs when using `layout: iframe`. If I scroll the website, the scroll position isn't in sync.

Would be awesome if all mouse/keyboard events from the presenter mode are synced with the play mode. Otherwise I can't really see the usecase for presenter mode when working with interactive slides.

**Comment by tonai** [comment]
This can be quite complicated to create a universal solution.

Currently there are multiple synchronized states between the view mode and the presenter mode:

* a shared state containing:
  * the page
  * the click (of `v-click`/`v-clicks`/`v-after` elements)
  * the mouse position
* a drawing state for the drawings

You can create a custom button component that will used the shared state if you want to save the state of the counter.
Here is an example of an external component that adds some data in that state: https://github.com/Smile-SA/slidev-component-spotlight/blob/main/src/slidev-spotlight.vue

It's more simple to share a state than to share an event.
If we try to synchronize events, there still be some cases where it would not work.
For exemple some actions in the browser requires that a real user is at the origin of the event and it will not work if the event is triggered programmatically.
And want event should we synchronize ? Only clicks ? But what about hover effects...etc.
