### ISSUE TITLE
unable to build use default template

### ISSUE THREAD

**Issue by zyfyy** [slidevjs/slidev#497]
**Describe the bug**
`npm run build` and
`[!] Error: unfinished hook action(s) on exit:`

**To Reproduce**
1. `npm init slidev`
2. `npm run build`
3.  See the error

**Desktop (please complete the following information):**
 - OS: Linux and OSX
 - Browser: null
 - Slidev version: `0.28.8`

**Comment by zyfyy** [comment]
old version such as `0.27.0` is good.

**Comment by Penguinlay** [comment]
It is due to mermaid minified file. You can run prettier on `mermaid.min.js` in `node_modules/mermaid/dist` and the build should be fine.

**Comment by Penguinlay** [comment]
It is probably what @antfu mentioned in #476.

**Comment by Penguinlay** [comment]
My guess is something is corrupted syntactically during the minification of mermaid which failed vite build of slidev.
