### ISSUE TITLE
Image is dimmed when there's a title. 

### ISSUE THREAD

**Issue by myknbani** [slidevjs/slidev#503]
**Describe the bug**
Image is dimmed when there's a title. I tried a slide with `layout: image` and it retains its brightness.

**To Reproduce**

Create a slide with a title and image.
```md
---
layout: center
---

# Artificial Neural Networks

![neuron](images/neuron.png)
```

![Screenshot from 2022-03-02 18-21-47](https://user-images.githubusercontent.com/5841268/156345416-fdaf4b0a-e3b6-4a42-8b60-87c5b4472d8c.png)

**Desktop (please complete the following information):**
 - OS: `Linux 5.15 (Manjaro)`
 - Browser: `Opera`
 - Slidev version:` 0.28.9`

**Comment by myknbani** [comment]
![Screenshot from 2022-03-02 18-48-25](https://user-images.githubusercontent.com/5841268/156348217-4ca76b14-0b31-431d-9a74-ba4b8eb9b073.png)

As a workaround, I discovered that adding an element after the title fixes it.

```md
---
layout: center
---

# Artificial Neural Networks

<p></p>

![neuron](images/neuron.png)
```

**Comment by myknbani** [comment]
Not a bug if image is inside `public/images`, without  Only used `slidev` today 😅, sorry for the trouble.

**Comment by myknbani** [comment]
@a-h yeah I should have dug deeper into the underlying code, it's Sli**dev** after all :sweat_smile: At least that's something we can easily override.

**Comment by a-h** [comment]
I think it's a genuine bug. I can't believe that it's right that the images are dimmed in this case.

This appears to be the culprit: https://github.com/slidevjs/themes/blob/main/packages/theme-default/styles/layouts.css#L3

**Comment by goekce** [comment]
I had the same problem today. I believe dimming applies to the title slides, i.e., you use first-level heading.

If you use a second-level heading (`## heading`) then the content is not dimmed.
