### ISSUE TITLE
Favicon in index.html not working

### ISSUE THREAD

**Issue by seonglae** [slidevjs/slidev#51]
I added this `index.html` to my project root like [guide page](https://sli.dev/custom/directory-structure.html#style) (tested in `public/index.html` either)

```html
<!-- ./index.html -->
<head>
  <link rel="icon" type="image/png" href="/favicon.png" />
</head>
````

But favicon still not changing
I think this is overwrited by slidev favicon. Is there correct way to change favicon by changing `index.html` or `vite.config.js`?

**Comment by TutoDS** [comment]
You find any solution to change favicon?

**Comment by seonglae** [comment]
Current version is working v21.0.0

you can check favicon in my [slidev page](https://seonglae-slides.vercel.app)
