### ISSUE TITLE
Component mounted twice

### ISSUE THREAD

**Issue by haoyun** [slidevjs/slidev#510]
**Describe the bug**
components being mounted twice.

**To Reproduce**

1. create a new project with
```
$ npm init slidev 
```

2. create a new component `MountTwice.vue`
```
<template>
    <div>Hello World</div>
</template>

<script setup>
import {onMounted} from 'vue'
onMounted(()=>{console.log('mounted')})
</script>
```
3. edit the `slides.md` to 
```
---
theme: seriph
---

<MountTwice/>
```

4. `mounted` is printed twice in the console.

---
probably https://github.com/slidevjs/slidev/issues/396 is the same issue (not verified)

**Comment by antfu** [comment]
Yes, this is by design.

**Comment by haoyun** [comment]
> Yes, this is by design.

However, that might have some problem. Let's take my use case as an example. I would like to create an [`asciinema-player`](https://github.com/asciinema/asciinema-player#use-the-player-in-your-own-application-bundle) component. As `slidev` is advertised as *Presentation Slides for Developers*, I think it's a proper example. I did the following

```typescript
<template>
<div id="player" />
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import * as AsciinemaPlayer from 'asciinema-player'

onMounted(()=>{
  AsciinemaPlayer.create('/demo.cast', document.getElementById('player'))
})
</script>
```
(`slides.md` omitted)

Then the player is mounted to the same `<div>` twice. My current hack is to remove the `id` at the end of `onMounted` hook. Might not be a good solution, though. Do you have any suggestion? 

BTW, there is also another small bug (off topic from the current issue) which I think it's also on the `slidev` side. The above player will not show unless the page that the player is in is refreshed once manually. I have not found the cause of that.

**Comment by antfu** [comment]
I think "components" as component should be reusable. You can use ref to get the dom instead of relying on id.

**Comment by ManUtopiK** [comment]
How to deal with component displayed only specific slide?
I want to focus an input when I navigate to the slide. Here is the code of the component:

```ts
<script setup lang="ts">
import { ref, onMounted } from "vue";

const el = ref();

onMounted(() => {
  el.value.focus();
});
</script>

<template>
  <div>
    <textarea
      ref="el"
      v-model="input"
      class="border focus:outline-none rounded p-2 w-full h-50"
    />
  </div>
</template>
```
