### ISSUE TITLE
[Bug] In the production environment, under different browser resolutions, there are issues with displaying and hiding the function menu at the bottom.

### ISSUE THREAD

**Issue by songjianet** [slidevjs/slidev#522]
**Describe the bug**
In the production environment, under different browser resolutions, there are issues with displaying and hiding the function menu at the bottom.

1689*1312
![image](https://user-images.githubusercontent.com/19239641/159271936-9a3526a8-d0cb-4bee-99c7-2ec3f6fd42fc.png)

1689*548
![image](https://user-images.githubusercontent.com/19239641/159272066-d0961996-d6f8-47ae-a397-0b43619a55d4.png)

2560*1369
![image](https://user-images.githubusercontent.com/19239641/159271864-afebae31-7c95-4b8b-818b-e8fa4fd84c79.png)

**To Reproduce**
4. See the error

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome 99
 - Slidev version: 0.28.10

**Comment by tonai** [comment]
There is a feature that hides the toolbox if it it is on top of the slides.
So if the viewport is matching an 16/9 aspect ratio or wider, the slides will touch the bottom and the top of the viewport and the toolbox should be hidden.  In that case you have to hover your mouse in the bottom right corner to make the toolbox appear.
If you have spaces below the slides, then the toolbox should be visible.
It is related to that ?

**Comment by songjianet** [comment]
> There is a feature that hides the toolbox if it it is on top of the slides. So if the viewport is matching an 16/9 aspect ratio or wider, the slides will touch the bottom and the top of the viewport and the toolbox should be hidden. In that case you have to hover your mouse in the bottom right corner to make the toolbox appear. If you have spaces below the slides, then the toolbox should be visible. It is related to that ?

I've tried hovering over it, but it still doesn't show up.
