### ISSUE TITLE
about slidev export

### ISSUE THREAD

**Issue by Qm-jmz** [slidevjs/slidev#532]
first, i install the playwright into the '../@slidev/cli' path by using 'npm i -D playwright-chromium' 
and then, this is what i can see in powershell 7 when i type in 'slidev export' from another path:

  ●■▲
  Slidev  v0.29.2 (global)

  theme   @slidev/theme-seriph
  entry   D:\File\ResourceCode\Python\slide\slides.md

Error: The exporting for Slidev is powered by Playwright, please installed it via `npm i -D playwright-chromium`
    at exportSlides (D:\Software\ProgrammingAndEnvironment\nodejs\node_global\node_modules\@slidev\cli\dist\export-XA3FQNS5.js:66:11)
    at Object.handler (D:\Software\ProgrammingAndEnvironment\nodejs\node_global\node_modules\@slidev\cli\dist\cli.js:274:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS D:\File\ResourceCode\Python\slide>

**Desktop (please complete the following information):**
 - OS: win11 21H2 22000.556
 - Browser: chrome 100.0.4896.75（正式版本） （64 位）
 - Slidev version: v0.29.2 (global)

**Comment by tonai** [comment]
I think you have to install playwright in the directory of you slide project that seems to be `D:\File\ResourceCode\Python\slide\`

**Comment by Qm-jmz** [comment]
> I think you have to install playwright in the directory of you slide project that seems to be `D:\File\ResourceCode\Python\slide\`

thx! But it's a pity for me that i have to install something into the project's directory, what i think goes against the  goal of global installation.

**Comment by antfu** [comment]
Do you have `playwright-chromium` installed globally?

**Comment by immorBen** [comment]
> 

@Qm-jmz I  think we had the same problem. As @antfu pointed out, installing `playwright-chromium` globally can fix it. Tweaking the command provided in the documentation as : `npm i -g -D playwright-chromium`
