### ISSUE TITLE
Custom name for exported pdf file

### ISSUE THREAD

**Issue by AlessandroAnnini** [slidevjs/slidev#533]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify a custom name for the exported pdf file and not always have `slidev-exported.pdf`.

**Describe the solution you'd like**
I would like to be able to specify the pdf file name on the front matter, where `download: true` is.

**Comment by Bustuk** [comment]
You can do it already with the --output flag

`npx slidev export --output my-custom-name`

**Comment by twitwi** [comment]
Fixed by #547 , you can now (since 0.30.2), e.g. to export as `amazing.pdf`, you can add the following frontmatter 

```
exportFilename: amazing
```
