### ISSUE TITLE
Drawing with my stylus pen does not work correctly

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [slidevjs/slidev#534]
**Describe the bug**

When I try to draw with my stylus pen I only get a small dot drawn similar to what I would get with a single click and very small move. It does not keep drawing the stroke as I'm holding and moving the pen on my tablet.

Please note that I have no issue drawing with my stylus pen on https://drauu.netlify.app/, all pen strokes work perfectly fine. So I guess it is probably a configuration issue of drauu from the slidev side.

**To Reproduce**
1. Enable the drawing toolbar
2. Try to draw with stylus pen
3. See the error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave 1.37.111
 - Slidev version: 0.29.2
 - Tablet model: Huion 610 PRO

**Comment by twitwi** [comment]
Hi @Celeborn2BeAlive,
can you confirm that it corresponds to the following issue?
https://github.com/slidevjs/slidev/issues/504

**Comment by Celeborn2BeAlive** [comment]
@twitwi Yes I confirm !
