### ISSUE TITLE
Hide on click 0, show on click 1 and hide on click 2

### ISSUE THREAD

**Issue by robiot** [slidevjs/slidev#538]
Is it possible?

Now when setting v-click-hide, the v-click doesn't work and it is shown at click 0.

**Comment by Leone25** [comment]
Wouldn't `v-if="$slidev.nav.clicks === 2"` be what you need?
Just remember to add `clicks: 3` in the slide proprieties.

**Comment by robiot** [comment]
Seems like it could work. Thanks! But having the ability to use both v-click and v-click-hide on the same element would still be a great feature.

**Comment by Leone25** [comment]
you are right, tho I'm defensively not the person that should implement it lol

I'm happy that i could help you tho
