### ISSUE TITLE
Script runs twice rather than one

### ISSUE THREAD

**Issue by gudh** [slidevjs/slidev#539]
First of all, thanks for the amazing library, the output slides are gorgeous ❤️

## To Reproduce

1. create a new project with `npm init slidev `
2. Add following code to `slides.md` file

```html
<script setup lang="ts">
console.log('should run once')
</script>
```

3. Run it, and you'll find the message is printed twice rather than one

## Related issues

* https://github.com/slidevjs/slidev/issues/510
* https://github.com/slidevjs/slidev/issues/396

## Why this matters

The reason it matters to me is that I try to autoplay the slides every 3 seconds with following code

```html
<script setup lang="ts">
import { next } from '@slidev/client/logic/nav'

const autoplay = () => {
  console.log('go next')
  next()
}

const interval = setInterval(autoplay, 3000)
</script>
```

Now that it runs twice, it jumps two pages rather than one, that is page 1, 3, 5, 7....

**Comment by antfu** [comment]
For singleton patterns, you can use setups, https://sli.dev/custom/config-vue.html

Components are aimed to be reused.
