### ISSUE TITLE
Feature request: support mermaid.js

### ISSUE THREAD

**Issue by WingLim** [slidevjs/slidev#54]
Hey there, thanks a lot for creating this program.

Is there has any plan to support [mermaid.js](https://github.com/mermaid-js/mermaid)?

Is great to write code to gernate diagram with mermaid rather than paste a image to slide.

**Comment by antfu** [comment]
Alright, let's go with mermaid. Basic functionality are implemented on https://github.com/slidevjs/slidev/tree/feat/mermaid
