### ISSUE TITLE
[Bug]: Image style in exported PDF differ from dev mode

### ISSUE THREAD

**Issue by Woodykaixa** [slidevjs/slidev#540]
**Describe the bug**

Markdown: 
```markdown
# 毕设进度

支持附加 Windows 进程

![attach process](/assets/bedbg-index-process.png)

---
```

Start in dev mode:
![image](https://user-images.githubusercontent.com/22990333/162775684-1a089377-7e17-45c4-9d38-80c595888876.png)

Export as PDF:
![image](https://user-images.githubusercontent.com/22990333/162776064-a93f52cd-1d7c-4e81-972c-57a306e46d37.png)

**To Reproduce**
1. Package.json
```json
{
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --open",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.29.2",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*",
    "slidev-theme-vuetiful": "^0.1.0"
  },
  "devDependencies": {
    "playwright-chromium": "^1.20.1"
  }
}
```

Install using pnpm
2. Start slides using `pnpm dev`
3. Export slides usint `pnpm export`

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser: Microsoft Edge 100.0.1185.36
 - Slidev version:  @slidev/cli: 0.29.2

**Comment by tonai** [comment]
Same as https://github.com/slidevjs/slidev/issues/333
See my response in the post.

Solutions are:
* make sure that the image does not overflow the slide
* or use a absolutely positionned image
* or add a parent element with display that is flex or grid
