### ISSUE TITLE
[Custom Shortcuts] `nav.toggleOverview()` does only toggle once

### ISSUE THREAD

**Issue by manniL** [slidevjs/slidev#555]
**Describe the bug**

When mapping a key to use `nav.toggleOverview()`, the overview is only toggled once.

Shortcut file:
```ts
import { defineShortcutsSetup, NavOperations } from '@slidev/types'

export default defineShortcutsSetup((nav: NavOperations) => {
  return [
    {
      key: 'Escape',
      fn: () => nav.toggleOverview(),
    }
  ]
})
```

**To Reproduce**
1. Create a new slidev project
2. Setup your `setup/shortcuts.ts` file as shown above.
3. Start slidev
4. Push ESC. You see the open overview now.
5. Push ESC again. It is still open.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome and FF, both show the issue
 - Slidev version: v.0.30.2

**Comment by WingLim** [comment]
Because there is a conflict with `Escape`.

## Principle

https://github.com/slidevjs/slidev/blob/8d0ae82274b3528cf3bc122b0ad90110c19a0eb9/packages/client/logic/shortcuts.ts#L65

When you press the `Escape`, it is executed in the following order:
1. overview is **NOT** opened (`showOverview` is `false`).

    - Execute your custom shortcut to open it (Make `showOverview` to `true`)

2. overview is opened (`showOverview` is `true`).

    - Execute the method posted above, it will **close overview** (Make `showOverview` to `false`)
    - Then execute your custom shortcut to open it (Make `showOverview` to `true`)

This is why situations like yours happen.

## Conclusion

You can't use `Escape` as overview open/close shortcut right now.

**Comment by manniL** [comment]
Oh! I somehow overread that part of the built-in shortcuts 😲 
Thanks for the detailed info @WingLim  👍 

An "easy" workaround regarding this issue could be the alteration of the built-in shortcut so it toggles instead of just closing the overview, right? 🤔

**Comment by WingLim** [comment]
Yep, but I think slidev will not change the `Escape` shortcut for overview.
`Escape` for closing something is consistent with human intuition。

**Comment by manniL** [comment]
> Yep, but I think slidev will not change the `Escape` shortcut for overview. `Escape` for closing something is consistent with human intuition.

Absolutely! But on the other hand, [reveal.js](https://revealjs.com/demo/) is also using `ESC` for opening/closing the overview.
I'm fine with either of the possible behaviors though ☺️
