### ISSUE TITLE
[v-clicks] `depth` parameter

### ISSUE THREAD

**Issue by manniL** [slidevjs/slidev#557]
**Is your feature request related to a problem? Please describe.**
When using the `<VClicks>` component or the corresponding directive with nested lists (see example for one below), then only the top-level elements will be "keyed" for clicks.

---
**Example list**

* Entry 1
* Entry 2
  * Entry 2a
  * Entry 2b
    * Entry 2bA
* Entry 3
---

It'd lead to three clicks and the reveal order would be Entry 1, Entry 2 and all sublists, Entry 3.
There is no way to "key" sublists individually or make them open one-by-one as well.

**Describe the solution you'd like**
Instead of adding the directive manually there, a `depth` attribute for the component (or value/attribute for the directive) would be desirable IMO. The value would be 1 by default to keep the current behavior. 

* `depth=2` would have the following order: Entry 1, Entry 2, Entry 2a, Entry2b with sublist (Entry 2bA), Entry 3
* `depth=3` would have the following order: Entry 1, Entry 2, Entry 2a, Entry2b, Entry 2bA, Entry 3

**Describe alternatives you've considered**
A suitable option would be applying `v-click` manually (what I tend to do at the moment). This is fine but a `depth` param would add more convenience 😋 

Another alternative to the `depth` parameter would be adding `v-click` to each subitem (of lists). But this is less configurable and also changes the standard behavior

**Comment by manniL** [comment]
Not stale ☺️

**Comment by ChiMaoShuPhy** [comment]
Strongly second this!

**Comment by manniL** [comment]
> Would this be a duplicate of #362?

Yes and no. Definitely related but not strictly a duplicate I'd say

**Comment by manniL** [comment]
not stale 👀

**Comment by manniL** [comment]
Noo stale bot. Why 🙈

**Comment by BretFisher** [comment]
@manniL it works in v0.40.5! Thanks @tonai I needed this today and saw it just released.

**Comment by manniL** [comment]
Indeed, resolved by https://github.com/slidevjs/slidev/pull/893 👏🏻
