### ISSUE TITLE
`$slidev.nav.go` not working ...

### ISSUE THREAD

**Issue by Wxh16144** [slidevjs/slidev#560]
**Describe the bug**

![image](https://user-images.githubusercontent.com/32004925/165458806-ecf815ea-1482-4a86-ab8c-3c60d6aaa837.png)

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: macOS 12.3
 - Browser: Chrome: 100.0.4896.127
 - Slidev version: 0.30.3

**Comment by twitwi** [comment]
Some note, probably the nav that we get here is https://github.com/slidevjs/slidev/blob/main/packages/client/composables/useNav.ts

**Comment by Wxh16144** [comment]
Thanks, the problem has been solved.
