### ISSUE TITLE
Parsing slide metadata with line break

### ISSUE THREAD

**Issue by naptestdev** [slidevjs/slidev#563]
**Describe the bug**
Prettier formats my markdown like this
![image](https://user-images.githubusercontent.com/88878684/165741389-be120b45-1460-49fb-9c10-bd8358e68926.png)

And slidev just make this a new slide?
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/88878684/165741502-c778c469-e83c-4d9e-8ebf-880166fa09cc.png">

**To Reproduce**
Try to make some slide with metadata and then format it with prettier

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser: Chrome v100
 - Slidev version: 0.30.3

**Comment by schickling** [comment]
Still an issue 👀

**Comment by brody715** [comment]
There is a workaround, see https://github.com/slidevjs/slidev/pull/202

**Comment by schickling** [comment]
> There is a workaround, see https://github.com/slidevjs/slidev/pull/202

Unfortunately this doesn't work well together with using a formatter like Prettier.

**Comment by ekil1100** [comment]
@naptestdev Any updates on this issue?

**Comment by leggomuhgreggo** [comment]
Here's what I did, using [this extension](https://marketplace.visualstudio.com/items?itemName=mervin.markdown-formatter)
```
  "[markdown]": {
    "editor.defaultFormatter": "mervin.markdown-formatter",
    "editor.renderWhitespace": "all",
    "editor.quickSuggestions": {
      "other": true,
      "comments": true,
      "strings": true
    }
  },
  ```

**Comment by eai04191** [comment]
To anyone who found this issue by searching for prettier:
The prettier plugin will solve this problem.
https://sli.dev/features/prettier-plugin#prettier-plugin
