### ISSUE TITLE
Dev mode does not work with files in the sub-directory

### ISSUE THREAD

**Issue by ansidev** [slidevjs/slidev#575]
**Describe the bug**

**To Reproduce**
1. Init the default project.
2. Move `slides.md` to `slides/slides.md`.
3. Update package.json dev command to `slidev --open ./slides/slides.md`
4. Run `yarn dev`
5. The slide was not rendered and cannot stop the dev server by pressing `Ctrl+C`, must use `kill -9`.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser: Chrome 101.0.4951.54 (Official Build) (x86_64)
 - Slidev version: 0.31.2

**Comment by yjl9903** [comment]
slidev can render the content correctly, but it costs very long time to setup.

It is caused by vite-plugin-windicss trying to scan too much files in the node_modules of the current dir.
