### ISSUE TITLE
Image element error when space in name

### ISSUE THREAD

**Issue by Leone25** [slidevjs/slidev#587]
**Describe the bug**
When trying to include images with discrete img elements I found an issue with the src attribute. If a space is present in the name it will work in dev and export, but will error out in build.

**To Reproduce**
`<img src="/My image.png">`--> error
`<img src="/My_image.png">`--> no error

(supposed both `My image.png` and `My_image.png` are real images in the public folder)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Slidev version: 31.3

**Comment by EnixCoda** [comment]
This still happens in the latest version.

```
[vite]: Rollup failed to resolve import "/images/my%20image.svg" from "../../../../@slidev/slides/3.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

I felt quite confused because the file does exist and works in dev mode.

Perhaps a more user-friendly warning would be helpful? Thank you!
