### ISSUE TITLE
bug: export to PDF does not render final state of slides

### ISSUE THREAD

**Issue by bguiz** [slidevjs/slidev#596]
**Describe the bug**
- PDF export on slides with multiline code blocks which have progressive highlighting does not work as expected
- Only the first highlight is highlighted instead of showing all lines
- When exporting it makes much more sense to show the final state of the slide, not the initial one

**To Reproduce**

1\. create a `slides.md` file and run in slidev
2.\ create a slide with the following markdown content:

```markdown
---
layout: default
---

## `require`

- defines conditions that, if not met, reverts transaction

\`\`\`solidity {1,4|2|3|all}
        require(
            catsInAMap[id].isFriendly,
            "scratched!"
        );

\`\`\`
```

(note that \\\`\\\`\\\` is actually just a triple backtick but github can't render nested markdown code blocks properly)

3\. export to PDF

4\. Slide renders like this, with lines 1 & 4 full visibility, and lines 2 & 3 greyed out:
![image](https://user-images.githubusercontent.com/1773785/169623493-0273f55a-5dd3-4161-8cb9-fdeb6e99e718.png)

5\. Expected behaviour:
Slide renders with all lines full visibility, none greyed out.
Alternatively, allow this to be specified as an option in the export command.

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser: Chrome
 - Slidev version: 
 
```
    "@slidev/cli": "^0.31.3",
    "@slidev/theme-default": "^0.21.2",
    "slidev-theme-purplin": "1.1.0",
```

**Comment by tonai** [comment]
Maybe use `{all|1,4|2|3|all}` ?

**Comment by bguiz** [comment]
:wave: Any word on this - is this something which can be fixed?
