### ISSUE TITLE
Shortcut to toggle drawing / annotation mode

### ISSUE THREAD

**Issue by IanVS** [slidevjs/slidev#597]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to have a shortcut key to start the drawing mode, to be able to quickly pull it up. 

**Describe the solution you'd like**
`d` has already been taken, so maybe `a` could be used, for `annotation`.

**Describe alternatives you've considered**
I can use the mouse/trackpad, not a huge deal, just a nice-to-have.

**Comment by WingLim** [comment]
Add `a` to start the drawing mode is easy, but you need another shortcut to close it.
Because `a` is binded to arrow drawingMode when drawing is enabled.

https://github.com/slidevjs/slidev/blob/8d0ae82274b3528cf3bc122b0ad90110c19a0eb9/packages/client/logic/drawings.ts#L129-L131

**Comment by IanVS** [comment]
`Add a to start the drawing mode is easy`

Could you explain how I would do this?  Sorry if it should be easy, I can't tell from the documentation.

**Comment by WingLim** [comment]
The documentation is in here: https://sli.dev/custom/config-shortcuts.html#configure-shortcuts

Add below code in `./setup/shortcuts.ts`:
```
import { defineShortcutsSetup, NavOperations } from '@slidev/types'

export default defineShortcutsSetup((nav: NavOperations) => {
  return [
    {
      key: 'a',
      fn: () => nav.toggleDrawing(),
    },
  ]
})
```

But as I said, this `a` shortcut will have a conflict with drawing's mode arrow(`a`) shortcut.

**Comment by IanVS** [comment]
Thanks, it wasn't listed in https://sli.dev/guide/navigation.html#navigation-bar, so I thought it wasn't possible.  I'll make a PR to update the docs if I have a chance.

Sounds like I just need to use a key that's not conflicting with anything else in the drawing mode.  :+1:
