### ISSUE TITLE
i18n support and previewable outline for viewer

### ISSUE THREAD

**Issue by DavidRicardoWilde** [slidevjs/slidev#600]
I'm making a slide, and I'm listening from multiple countries, and I want them to review the slide in a language they're familiar with. And it would be better if the audience could scan an outline. But this means that there needs to be some additional output that is accessible to the user.

**Comment by d-koppenhagen** [comment]
Hey, I would be interested in such a feature. Is it possible to re-open it? Are there already Ideas how such a feature could be implemented?

**Comment by d-koppenhagen** [comment]
I think there are three different levels of i18n to consider:

1. inline text translation
2. paragraph translation
3. whole slides
