### ISSUE TITLE
v0.32.3 fails to create new presentation on MacOS

### ISSUE THREAD

**Issue by adamjanovsky** [slidevjs/slidev#608]
**Describe the bug**

After fresh global install of slidev `0.32.3` on MacOS, the package fails to create new presentation with the following trace:

```
~/phd/talks/2022/test  $ slidev
✔ Entry file "slides.md" does not exist, do you want to create it? … yes
/usr/local/lib/node_modules/@slidev/cli/dist/chunk-JWGORJY6.js:121
    throw new Error(`Failed to resolve package "${importName}"`);
          ^

Error: Failed to resolve package "/Users/adam/phd/talks/2022/gg/package.json"
    at resolveImportPath (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-JWGORJY6.js:121:11)
    at getPackageJson (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9515:72)
    at getAddons (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9518:33)
    at resolveOptions (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9600:24)
    at async initServer (/usr/local/lib/node_modules/@slidev/cli/dist/cli.js:82:21)
```

After downgrading to 0.31.4 the commands works as expected. I'm not certain whether this affects also other patches of 0.32.x, didn't test. I can test with other versions if necessary.

Possibly related : #606 

**To Reproduce**

1. Install slidev globally `$ npm i -g @slidev/cli@0.32.3`
2. `$ mkdir test && cd test`
3. `$ slidev`

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.3.1
 - Browser: irrelevant
 - Slidev version: 0.32.3

Let this also be an opportunity to thank you for this awesome project ❤️.

**Comment by kaaass** [comment]
As a workaround (or intentionally maybe?), `npm init` in the same directory would fix this.

**Comment by isaaccaa** [comment]
This seems to have something to do with the new version of slidev, which I encountered when installing the latest version on macOS and Windows.
A temporary solution is to install the older version. Version `0.29.2` works fine on my computer.
```
yarn global add @slidev/cli@0.29.2
```
