### ISSUE TITLE
[Slide Overview] Auto scroll to open slide

### ISSUE THREAD

**Issue by manniL** [slidevjs/slidev#619]
**Is your feature request related to a problem? Please describe.**
When moving into the "slide overview" mode, it would be convenient to see the opened slide directly in the middle of the page.
This is especially helpful when having tons of slides (e.g. for a workshop)

**Describe the solution you'd like**
When opening the overview, scroll to the current slide

**Describe alternatives you've considered**
Live with the current behavior 😛

**Comment by sunny7dusk** [comment]
![image](https://user-images.githubusercontent.com/71191616/181396583-7d3024ea-140a-4602-8509-6a6fce71b8a6.png)
Something like this? @manniL

**Comment by sunny7dusk** [comment]
@manniL Like this?
![slidev](https://user-images.githubusercontent.com/71191616/181403742-31565dbd-c2ea-4306-8aa1-3328a90a2ed1.gif)
