### ISSUE TITLE
[mermaid] scaling is broken

### ISSUE THREAD

**Issue by TheAlexLichter** [slidevjs/slidev#625]
**Describe the bug**
The `scale` property is ignored since #570 has been in place. I guess because the SVG is now in the shadow root, height is not applied "correctly"?

**To Reproduce**

1. Check https://stackblitz.com/edit/slidev-xf3l8y?file=package.json,slides.md - it works fine 
2. Check https://stackblitz.com/edit/slidev-z9jj6c?file=package.json,slides.md,README.md where scaling is broken

cc @twitwi - any idea how to solve this in a elegant manner?

**Comment by twitwi** [comment]
I'll have a look.

**Comment by twitwi** [comment]
@manniL if it is easy for you to check that the branch solves the issue on your side, that would be amazing (it works with my local tests).

**Comment by twitwi** [comment]
(unfortunately it might not be so easy to actually depend on the branch without rebuilding it manually)

**Comment by manniL** [comment]
Yes, this fixes the issue! Thanks a lot 🙏 

(I monkeypatched the code to try out 🙈)

**Comment by twitwi** [comment]
Amazing :) . Thank you.
