### ISSUE TITLE
Ability to install Slidev globally

### ISSUE THREAD

**Issue by SaekiRaku** [slidevjs/slidev#63]
First of all, great project. For further, I hope it can be used like this:

```
npm i -g @slidev/cli
vim index.md
slidev index.md
# Then, start to performance.
```

Didn't know if this was already done, but currently, if I use @slidev/cli like this, it will report lack of dependencies.

In this way, it can make user more focus on the content (only a single markdown file) than now (vscode, node_modules, package.json, etc).

Thanks.

**Comment by sbibauw** [comment]
I also want to second this: a way to use Slidev without needing a 500MB standalone project for each presentation.
I am a teacher, currently using [Marp](https://github.com/marp-team/marp), and I have hundreds of presentations. While it's possible to have all the presentations for a course as one single slide, it's not practical (~200-400 slides per presentation), and even that would still require dozens of very heavy projects containing redundant slidev dependencies.
Having a way to generate a `slides.md` presentation without needing to add anyother file or `node_modules` next to it would be great!

**Comment by antfu** [comment]
This was tough 😅

![image](https://user-images.githubusercontent.com/11247099/119768852-f3b13100-beeb-11eb-972d-ccfa944ae8e2.png)

But hey! We get it supported in v0.14.0 🎉
