### ISSUE TITLE
pnpm - Missing peer on install

### ISSUE THREAD

**Issue by pi43r** [slidevjs/slidev#630]
**Describe the bug**
pnpm fails installation

**To Reproduce**
 `pnpm create slidev`

Error message:
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @slidev/cli
  └─┬ @slidev/client
    └─┬ @vueuse/motion
      └── ✕ missing peer @nuxt/kit@npm:@nuxt/kit-edge@latest
Peer dependencies that should be installed:
  @nuxt/kit@npm:@nuxt/kit-edge@latest  
```

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Slidev version: 0.33.0

**Comment by gunters63** [comment]
This problem still exists in version 0.35.4. Exactly the same error message.
pnpm version used: 7.9.0
