### ISSUE TITLE
Can't run after global install 

### ISSUE THREAD

**Issue by SkyTeamWater** [slidevjs/slidev#635]
**Describe the bug**
Can't run after global install 

err:
```
/usr/local/lib/node_modules/@slidev/cli/dist/chunk-IP7ZGKHI.js:121
    throw new Error(`Failed to resolve package "${importName}"`);
          ^

Error: Failed to resolve package "/home/bradford/workspace/slidev/package.json"
    at resolveImportPath (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-IP7ZGKHI.js:121:11)
    at getPackageJson (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-LIMOCTLS.js:9516:51)
    at getAddons (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-LIMOCTLS.js:9522:33)
    at resolveOptions (/usr/local/lib/node_modules/@slidev/cli/dist/chunk-LIMOCTLS.js:9604:24)
    at async initServer (/usr/local/lib/node_modules/@slidev/cli/dist/cli.js:82:21)

Node.js v18.4.0
```

Appreciate for help

**To Reproduce**
1. `sudo npm i -g @slidev/cli`
2. `sudo slidev test.md`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Microsoft Edge 104.0.1287.1 dev (64)
 - Slidev version: 0.33.1

![image](https://user-images.githubusercontent.com/51621873/175527129-0cf32d33-e247-4b6e-8ac5-16fd11b6c9e3.png)

**Comment by Liguobing00** [comment]
Try to copy the file named "package.json" to your directory, which is needed and has contents like the following:

```json
{
  "name": "slidev",
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --open",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.33.0",
    "@slidev/theme-apple-basic": "^0.20.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*",
    "slidev-theme-academic": "^1.1.0"
  },
  "devDependencies": {
    "playwright-chromium": "^1.22.2"
  }
}

```

**Comment by SkyTeamWater** [comment]
copy that. Thanks for help. I'll try!------------------------------------------------------------------
***@***.***>
日　期：2022年06月28日 03:52:20
***@***.***>
抄　送：Bradford ***@***.***>; ***@***.***>
主　题：Re: [slidevjs/slidev] Can't run after global install (Issue #635)

Try to copy the file named "package.json" to your directory, which is needed and has contents like the following:
{
  "name": "slidev",
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --open",
    "export": "slidev export"
  },
  "dependencies": {
    ***@***.***/cli": "^0.33.0",
    ***@***.***/theme-apple-basic": "^0.20.0",
    ***@***.***/theme-default": "*",
    ***@***.***/theme-seriph": "*",
    "slidev-theme-academic": "^1.1.0"
  },
  "devDependencies": {
    "playwright-chromium": "^1.22.2"
  }
}
