### ISSUE TITLE
How to run terminal commands

### ISSUE THREAD

**Issue by lyzhang1999** [slidevjs/slidev#639]
How do I run the `terminal` command and return the results in real time? 
For example, run `git status` on a slide and return the results.

**Comment by yjl9903** [comment]
Maybe you can:

1. Write a simple http server to run terminal command;
2. Use https://github.com/antfu/vite-plugin-vue-server-ref (slidev also uses it to share states in draw and prensentor mode);
3. Create Vite [virtual module](https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention).
