### ISSUE TITLE
Support for katex macros

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [slidevjs/slidev#644]
I try to use custrom marco definitions in katex, but did not find a way to make it work

I tried define marco flowing instructions on [https://katex.org/docs/supported.html#macros](https://katex.org/docs/supported.html#macros) but failed.

Is there any way to use marco definitions in slidev? Either define them globally in some katex elements or instructions (an example would be more helphul) on how config katex.

**Comment by ChiMaoShuPhy** [comment]
```ts
import { defineKatexSetup } from '@slidev/types'

export default defineKatexSetup(() => {
  return {
    /* ... */
    macros:{
        "\\dst": "\\displaystyle"
    }
  }
})
```

**Comment by erlebach** [comment]
Where are the statements above located? What file? What folder? Thanks.

**Comment by ChiMaoShuPhy** [comment]
> Where are the statements above located? What file? What folder? Thanks.

I placed a `setup` directory in the root directory of the slide project and create a `katex.ts` file under `setup`. The definitions are placed in `katex.ts`.
