### ISSUE TITLE
the bug of export with option '--with-clicks'

### ISSUE THREAD

**Issue by zqhexor** [slidevjs/slidev#654]
**Describe the bug**
when we export our slidev with option '--with-clicks', the number of page is not according to the frontmatter's clicks.

**To Reproduce**
1. for example: a page

```md
---
clicks: 2
---
<div v-click-hide="1">
item1
</div>
<div v-click-hide="2" v-click="1">
item2
</div>
<div v-click="2">
item3
</div>
```
2. when we export our slidev with option '--with-clicks', the number of page is 3, but in fact we need 2 pages

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: chrome
 - Slidev version: 0.34.3

**Comment by yunying1** [comment]
Hi, I don't think animation works in PDF, so you need 3 pages to show it.
