### ISSUE TITLE
Toc rendering is broken in Firefox

### ISSUE THREAD

**Issue by kolaente** [slidevjs/slidev#655]
**Describe the bug**

Using the `<Toc/>` component with a few slides results in this table of contents being generated:

![image](https://user-images.githubusercontent.com/13721712/178955641-a7a86c86-7c98-4aa4-8884-9d8a028fbdc0.png)

It looks like the html generated by slidev is something like this:

```
<ol class="slidev-toc-list slidev-toc-list-level-1">
  <li class="slidev-toc-item">
    <a href="/1" class="">
      <div>Welcome to Slidev</div>
    </a>
    <!--v-if-->
  </li>
  <li class="slidev-toc-item">
    <a href="/3" class="">
      <div>What is Slidev?</div>
    </a>
    <!--v-if-->
  </li>

...

</ol>

```

Notice the `<div>` tag inside the `<a>`.

**To Reproduce**

Here's a reproduction repo: https://github.com/kolaente/slidev-toc-repro

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: Firefox 101.0.1
 - Slidev version: 0.34.3

**Comment by kolaente** [comment]
This is still relevant.

**Comment by FossPrime** [comment]
@kolaente How did you get **playwright** to work on NixOS? I can't get it running on Replit's NixOS 22.05 or on my Laptop's baremetal NixOS 22.11

**Comment by kolaente** [comment]
@FossPrime I passed the path to chromium into it (chromium needs to be installed or available in your shell).

Like this:

```
slidev export --executable-path `which chromium`
```

Sadly, the `--executable-path` option is not available for exporting notes.
