### ISSUE TITLE
Request url is outside of Vite serving allow list.

### ISSUE THREAD

**Issue by lomirus** [slidevjs/slidev#657]
I installed `@slidev/cli` and `@slidev/theme-default` globally by yarn 1.22, and then run slidev:
```
slidev framework/frameworks.md
```
It printed the error information:
```
  ●■▲
  Slidev  v0.34.3 

  theme   @slidev/theme-default
  entry   /home/lomirus/classware/framework/frameworks.md

  public slide show   > http://localhost:3030/
  presenter mode      > http://localhost:3030/presenter/
  remote control      > pass --remote to enable

  shortcuts           > restart | open | edit


Failed to resolve force included dependency: @slidev/parser
```
After I opened the http://localhost:3030, it gave such output:
```
The request url "/usr/local/share/.config/yarn/global/node_modules/@slidev/client/main.ts" is outside of Vite serving allow list.

- /home/lomirus/classware/framework
- /usr/local/share/.config/yarn/global/node_modules/@slidev/cli
- /usr/local/share/.config/yarn/global/node_modules/vite/dist/client

Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.
```

**Desktop (please complete the following information):**
 - OS: Linux x86_64
 - Browser: Firefox & Chrome both have the problem
 - Slidev version: 0.34.3

**Comment by manniL** [comment]
Hey 👋🏻

Try creating a `vite.config.ts` in your slidev project root folder and add:

```ts
import { defineConfig } from 'vite'

export default defineConfig({
  server: {
    fs: {
      strict: false
    }
  }
})
```

**Comment by lomirus** [comment]
Thanks! It seems that I misunderstood the usage of Slidev. I used to think I can run `slidev any_path.md` straightly without creating a single complete project every time. Though it's not like that actually :)
