### ISSUE TITLE
[Regression] Markdown with Vue components in list does not render links

### ISSUE THREAD

**Issue by manniL** [slidevjs/slidev#658]
**Describe the bug**
Some markdown that was rendered correctly before does not render anymore since switching to `vite-plugin-vue-markdown`.
For example: `* <mdi-github /> [Example link](https://github.com/)`. #655 could be related too.

Related commit: https://github.com/slidevjs/slidev/commit/a2e35696687b711bb1981fd5a6d496f0894e059a

**To Reproduce**

1. Check out https://stackblitz.com/edit/slidev-nxyjmy?file=slides.md

---

Manually:

1. Create a new project
2. Add the line `* <mdi-github /> [Example link](https://github.com/)` to it
3. See that it fails to render correctly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: FF Dev Edition
 - Slidev version: 0.33.1 and above (works fine in 0.33.0)

**Comment by antfu** [comment]
https://github.com/mdit-vue/vite-plugin-vue-markdown/issues/7

**Comment by manniL** [comment]
@antuf Could we upgrade [vite-plugin-vue-markdown](https://github.com/mdit-vue/vite-plugin-vue-markdown) to 0.21.x?
