### ISSUE TITLE
feature request: Export PDF to generate TOC(outline, bookmarks)

### ISSUE THREAD

**Issue by condorheroblog** [slidevjs/slidev#662]
**Problems encountered**

When there are many PDF pages, I want to quickly locate the specified page, because there is no directory and I need to scroll many times to find the page I need

**Describe the solution you'd like**

Choose to generate a Table of Contents (or bookmark) when exporting PDF from Slidev. can solve the problem of finding too many pages

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/47056890/180923641-968975e3-d15f-4641-acfb-01543b2745cf.png">

**Comment by Shinyaigeek** [comment]
https://github.com/puppeteer/puppeteer/issues/1778#issuecomment-1198240981 This comment in the issue of puppeteer may help. I try to work on this.
