### ISSUE TITLE
Github pages deployment: blocked because of a disallowed MIME type (“text/html”)

### ISSUE THREAD

**Issue by klieret** [slidevjs/slidev#667]
**Describe the bug**

Using the official demo repository and adding the GH action script from [the docs](https://sli.dev/guide/hosting.html#github-pages), no page is shown. The console shows 

> Loading module from “https://klieret.github.io/assets/index.6e08241d.js” was blocked because of a disallowed MIME type (“text/html”). slidev-deploy-gh-pages-bug-demo
Loading failed for the module with source “https://klieret.github.io/assets/index.6e08241d.js”. slidev-deploy-gh-pages-bug-demo:8:1

**To Reproduce**

I've prepared a [demo repository](https://github.com/klieret/slidev-deploy-gh-pages-bug-demo), which uses the `init slidev` example with no further customization.

The site should be live [here](https://klieret.github.io/slidev-deploy-gh-pages-bug-demo/); you should be able to observe the above error.

**Desktop (please complete the following information):**

Not on desktop

**Comment by antfu** [comment]
The assets are 404. The case is actually because you are deploying to a sub directory without config. Try `slidev build --base /slidev-deploy-gh-pages-bug-demo/`
https://sli.dev/guide/hosting.html#base-path

**Comment by klieret** [comment]
Thanks a lot, this solved it after a bit of trying! I really support https://github.com/slidevjs/docs/pull/88 because I imagine a lot of beginners will run into something similar (as the sub-route deployment is the default when you use github pages without a custom domain).
