### ISSUE TITLE
Using Component `SlideCurrentNo` in Layout Causing Error

### ISSUE THREAD

**Issue by Xusine1131** [slidevjs/slidev#675]
**Describe the bug**
After upgrading to 0.35.4, using component `slideCurrentNo` in customized layouts causes error. Here is the error message:

![image](https://user-images.githubusercontent.com/8319391/183051755-c72368f9-70b6-445a-a230-9abdb09502e5.png)

However, this problem does not occur when using slidev 0.34.3. 

**To Reproduce**
1. Create a new project, and insert `<SlideCurrentNo />`  to any slide. 
2. yarn dev 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Slidev version: 0.35.4
 - Package manager: `yarn`
 
Thanks for time and effort.

**Comment by inody** [comment]
Same for me. Any solution?

**Comment by Xusine1131** [comment]
Upgrading to the latest version 0.35.5 solves this problem.
