### ISSUE TITLE
The web page can't show any content

### ISSUE THREAD

**Issue by Smangic** [slidevjs/slidev#678]
**Describe the bug**
The Web page can't show any content

**To Reproduce**
I use the command `slidev` it can run properly.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/83532013/183584615-b7d12911-b0cd-4656-8d95-b53a832c6707.png">
But when I open the web page, there is actually nothing.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/83532013/183584940-14202db3-7ba6-4822-b050-8f44acf8a83c.png">
And there is no any other information.
(Remote can't open either)
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Slidev version: 0.35.4

**Comment by Smangic** [comment]
I use the command `slidev` it can run properly.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/83532013/183584615-b7d12911-b0cd-4656-8d95-b53a832c6707.png">
But when I open the web page, there is actually nothing.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/83532013/183584940-14202db3-7ba6-4822-b050-8f44acf8a83c.png">
And there is no any other information.
(Remote can't open either)

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
