### ISSUE TITLE
`$slidev` context fail to inject

### ISSUE THREAD

**Issue by JackLiR8** [slidevjs/slidev#679]
**Describe the bug**
After Running the demo on StackBlitz, I got some warns from vue: `[Vue warn]: injection "Symbol(slidev-slidev-context)" not found.`. And then click the 'Press Space for next page' button on Page 1, I got an error: `Uncaught TypeError: Cannot read properties of undefined (reading 'nav')`. It turn out that `$slidev` is `undefined`;

**To Reproduce**
1. Go to  StackBlitz and run then demo
2. Click on 'Press Space for next page`
3.  See the error `Uncaught TypeError: Cannot read properties of undefined (reading 'nav')`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Slidev version: lastest

**Comment by justindasilva** [comment]
I have similar issue. From the demo:
```
<span @click="$slidev.nav.next" class="px-2 py-1 rounded cursor-pointer" hover="bg-white bg-opacity-10">
    Start Presentation <carbon:arrow-right class="inline"/>
  </span>
```

But clicking "Start Presentation" does not work. I see this error.
<img width="737" alt="Screen Shot 2022-08-15 at 11 56 35 AM" src="https://user-images.githubusercontent.com/882534/184670658-3b5cbb1b-4a47-4a15-81e4-8328d33ca45c.png">
