### ISSUE TITLE
The Slidev service starts successfully, but the browser has a blank page.

### ISSUE THREAD

**Issue by liweiook** [slidevjs/slidev#681]
**To Reproduce**
1. slidev is installed globally
2. type "slidev" in cmd,it successful
3. open it in the Google, it's blank 
4. open in Edge,it's blank

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser:  Google
 - Slidev version:  v0.35.4 (global)

Here are some screenshots
![image](https://user-images.githubusercontent.com/42706756/184480598-7c298134-025c-4911-bf19-8e0c07e25fd0.png)
![image](https://user-images.githubusercontent.com/42706756/184480616-b6bd15fb-b3aa-4e2b-a9c5-fd46f46433bc.png)
![image](https://user-images.githubusercontent.com/42706756/184480620-9e2bcb16-5665-4c6a-9830-9656de0831ed.png)

**Comment by liweiook** [comment]
node version: 16.16.0
npm version: 8.11.0

**Comment by liweiook** [comment]
I succeeded in a different way, which is  `npm init slidev@latest.`.And then I realized that I could reproduce the problem.
This is my directory structure
![image](https://user-images.githubusercontent.com/42706756/184494510-f48b6dd1-673d-4a6a-a191-436d97c62344.png)
if i do this,it has a blank page
![image](https://user-images.githubusercontent.com/42706756/184494540-32f6491b-5e41-4ec7-b674-921f65f00eb8.png)
if i do this,it has a error.
![image](https://user-images.githubusercontent.com/42706756/184494670-bfb95e2e-0e90-414c-9f04-e46a0c1fbdcc.png)
if  I go from the Markdown folder to the Slidev folder,it also has a error by this
![image](https://user-images.githubusercontent.com/42706756/184494857-39d6294d-3a3d-44a9-8f97-cfc3af91cf51.png)

only do this,it's successful
![image](https://user-images.githubusercontent.com/42706756/184494917-6c515257-b810-455c-9f6e-49349bcba8e9.png)

**Comment by liweiook** [comment]
Do markdown files have to be in the root directory?

**Comment by Shinyaigeek** [comment]
This issue seems to be dup of #652 👀
