### ISSUE TITLE
Using monorepo to develop a theme locally, writing the theme path in md can render normally, but writing the theme name will not work

### ISSUE THREAD

**Issue by htharoldht** [slidevjs/slidev#682]
**Describe the bug**
Using monorepo to develop a theme locally, writing the theme path in md can render normally, but writing the theme name will not work

**To Reproduce**
Build monorepo with pnpm, there are demo, themeslidev-theme-xx under packages, the former is slidev manuscript, the latter is self-developed theme
![image](https://user-images.githubusercontent.com/31093493/184496290-4ca003ce-939b-47d9-b420-c661f7a1f80e.png)

If it is specified with `"dependencies": { "slidev-theme-xx": "workspace:*" }` under the demo, it will prompt 
```
The theme "slidev-theme-xx" was not found in after running the `slidev demo` your project, do you want to install it now?
```
And if the theme is published and the dependencies are installed outside the monorepo to rebuild the slidev document, it can be rendered normally

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: edge
 - Slidev version: 0.35.4

Is this issue caused by pnpm? Maybe [this function](https://github.com/slidevjs/slidev/blob/734665a604934e7f4cde0c20fdf17ed882199a59/packages/slidev/node/utils.ts#L15) can't resolve the workspace dependencies, but I can't be sure and fix it.

**Comment by toimc** [comment]
same here

**Comment by cnguyen-de** [comment]
same, am also working on a monorepo which contain multiple presentations which share a theme and although 

`slidev-theme-custom: "workspace:*"` 

is already set, it doesn't recognize it.

**Comment by mudssky** [comment]
same bug happened in v0.46.3
my theme in pnpm monorepo can’t be recognized 
```json
@mudssky/slidev-theme-default": "workspace:*"
```
I can only choose to publish my thme to npm,and use `pnpm add @mudssky/slidev-theme-default@latest --link-workspace-packages=false` to install,
