### ISSUE TITLE
Persisted drawings aren't exported to PDF nor hosted site

### ISSUE THREAD

**Issue by adrianbienias** [slidevjs/slidev#692]
**Describe the bug**
Despite the following setting
```
drawings: 
  persist: true
```
Drawings aren't exported to PDF nor static site.

From the docs, I understand that it should be possible

> The following frontmatter configuration allows you to persist your drawings as SVGs under .slidev/drawings directory and have them inside your exported pdf or hosted site.

https://sli.dev/guide/drawing.html#persist-drawings

**To Reproduce**
1. Create a project `$ npm init slidev`
2. Change drawings config in slides.md to
```
drawings:
  persist: true
```
3. Run the `$ slidev`
4. Draw something on slides
5. Confirm that drawings were saved in `.slidev/drawings`
6. Install `playwright-chromium` https://sli.dev/guide/exporting.html#exporting
7. Export slides to PDF `$ slidev export`
8. See that there are no drawings on exported slides

**Desktop (please complete the following information):**
 - Slidev version: `0.35.5`

**Comment by lpil** [comment]
I am also having this problem when running `npm run build` to compile the presentation to host on my website. When I do this the drawings are absent. There are no errors or warnings in the browser console.

**Comment by lpil** [comment]
Hi robot! Please keep this open.

**Comment by lpil** [comment]
Hi robot, please keep this open.
