### ISSUE TITLE
Add support for changed delimiters of Vue

### ISSUE THREAD

**Issue by welcoMattic** [slidevjs/slidev#693]
Hi,

I had to change the Vue default delimiters (I use `$[ ]`) in my slidev slides,(because I use Twig code which have `{{ }}` as delimiters too). But it breaks the slidev UI as above:

![2022-08-24_12-04](https://user-images.githubusercontent.com/773875/186391972-805b9211-973f-44a6-a8be-fe47fc48b2ac.png)

Make slidev understanding the user config set in vite.config.ts (where I changed the Vue delimiters).

**Comment by antfu** [comment]
I am not sure if it's possible as the `{{ }}` in UI and theme are shipped as code and not dynamic.

**Comment by welcoMattic** [comment]
Another solution is to ignore `{{ }}` embraced in backticks

```markdown

Some Twig code
\```twig
{{ 'now'|date }}
\```

```

(I've try to escaped backtick, for GitHub proper display)

**Comment by twitwi** [comment]
@welcoMattic I tried to put some `{{` inside some backticks and in my case it renders without vue interpretation.

![image](https://user-images.githubusercontent.com/244649/189192161-444daadb-2308-4c2f-84ad-dbf86ad1b41d.png)

I'm not sure what we are doing differently though.

**Comment by twitwi** [comment]
Thanks for the feedback and sorry that you spent some time on this.
