### ISSUE TITLE
Monaco cannot display the written code and its theme is not controlled by Slidev based on the light/dark mode.

### ISSUE THREAD

**Issue by XuekaiShi** [slidevjs/slidev#701]
**Describe the bug**
1. Monaco cannot display the written code. The code block is blank:
![blank](https://user-images.githubusercontent.com/88176333/188254827-d90bbd5f-7433-4647-ac25-2352a203a8b3.jpg)
2. Its theme is not controlled by Slidev based on the light/dark mode:
dark mode:
![darkmode](https://user-images.githubusercontent.com/88176333/188254628-d61e0a99-6125-4b69-92e3-ff3e2eed059a.jpg)
light mode:
![lightmode](https://user-images.githubusercontent.com/88176333/188254640-db57432b-0081-4fd8-8391-2c38207a684d.jpg)
(The code in Monaco editor was writen after `npm run dev`)
When downgrading the Slidev version (such as v0.31.4), these bugs were fixed.

**To Reproduce**
1. Create a new Slidev project
2. Add `{monaco}` after the language id
3. `npm run dev`
4. Toggle light/dark mode

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Slidev version: 0.35.5

**Comment by antfu** [comment]
Yeah, I found that too. PR welcome if you find any clue on how to fix it
