### ISSUE TITLE
Navigation bar disappear and Code highlight doesn't work

### ISSUE THREAD

**Issue by Crowds21** [slidevjs/slidev#704]
**Describe the bug**
The button still works, but the navigation bar doest not display.
Highlighting a specific line of a code block does not work.
These functions can be used normally in `v0.34.2`

**To Reproduce**
`npm init slidev@latest`  
`npm run dev `

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Edge and Safari
 - Slidev version: v0.35.6

**Comment by Bruce-Ming** [comment]
me too 

{
  "name": "share",
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --open",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.35.6",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
  }
}

Possible dependency issues？
 Issues with peer dependencies found
.
└─┬ @slidev/cli
  └─┬ @slidev/client
    └─┬ @vueuse/motion
      └── ✕ unmet peer @nuxt/kit@npm:@nuxt/kit-edge@latest: found 3.0.0-rc.10-27708028.1ca294e

**Comment by LAWTED** [comment]
me too, but 0.35.4 works well

**Comment by twitwi** [comment]
I can reproduce the issue (linux, firefox) for the bar, the code highlighting seems to work.

- if I remove `css: unocss` in the frontmatter, the bar is displayed but with no icons

**Comment by twitwi** [comment]
The first console warnings that are abnormal are about __DEV__, __SLIDEV_FEATURE_DRAWINGS__ etc not found

![image](https://user-images.githubusercontent.com/244649/189347468-0a4ea773-2438-48d0-9433-eb63bacc526a.png)

@tonai As you worked on the build part, maybe you're familiar with these kind of errors?

**Comment by tonai** [comment]
Hum environment variables should be replaced by the build tool.
The plugin responsible for this is defined in that file: https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/plugins/patchTransform.ts
And the environment variables are defined in the `getDefine` method located in that file: https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/plugins/extendConfig.ts
It only transforms file with the `.vue` extension.
I don't really know why this is broken...

**Comment by twitwi** [comment]
I confirm it break by switching from 0.34.3 to 0.35.0, which seems to be only made of an upgrade to vite3.

**Comment by twitwi** [comment]
But no issue when running the demo presentation with a clone and build of v0.35.6 (or any version probably).

**Comment by Crowds21** [comment]
> I can reproduce the issue (linux, firefox) for the bar, the code highlighting seems to work.

Now I am using  v0.36.4. The navigation bar works well. But Line Highlighting still can't work.
Sorry, I didn't express the issue accurately.

This is the picture for `http://127.0.0.1:3030/4`
<img width="381" alt="image" src="https://user-images.githubusercontent.com/48215334/189632142-44a688f4-0df3-489a-b468-6a3e2ab78fff.png">
And it is  the same result for `http://127.0.0.1:3030/4?clicks=1`

The Line Highlighting doesn't work for `ts {all|2|1-6|9|all}`. It highlights all lines all the time .
