### ISSUE TITLE
Navigation's controls panel disappeared 

### ISSUE THREAD

**Issue by wxxb789** [slidevjs/slidev#705]
**Describe the bug**
Navigation's controls panel disappeared. Click is work. But show nothing.

**To Reproduce**
Local dev with slidev@v0.35.6 and online version https://stackblitz.com/edit/slidev-h3h8qm?file=slides.md both could repro this issue.

**Desktop (please complete the following information):**
 - OS: latest windows 11
 - Browser: latest edge and firefox
 - Slidev version: v0.35.6

screenshot:
![image](https://user-images.githubusercontent.com/49564443/188585496-8c906d7d-768f-42e1-a3f0-ed96e2c3649d.png)

**Comment by wxxb789** [comment]
looks same with #704

**Comment by antfu** [comment]
...it's here

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/11247099/188711660-d243eab2-dc7a-40cf-a1c9-3fb8af9f0f7b.png">
