### ISSUE TITLE
global-top.vue does not display header

### ISSUE THREAD

**Issue by ajmoralesa** [slidevjs/slidev#707]
**Describe the bug**
While trying to include a common header for all slides `global-top.vue` does not work when a `<header></header>` tag is used.

 The [slidev-theme-unicorn](https://github.com/Dawntraoz/slidev-theme-unicorn) comprises a logo in the header using a component approach (see [LayoutHeader.vue](https://github.com/Dawntraoz/slidev-theme-unicorn/blob/master/components/LayoutHeader.vue)), however this implies  specifying the logoHeader prop in all slides. A less verbose approach may be achieved using `global-top.vue`?

**To Reproduce**
https://stackblitz.com/edit/slidev-1xd2ou?embed=1&file=global-top.vue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 105.0.5195.102 (Build officiel) (64 bits)
 - slidev version: 
      "dependencies": {
        "@slidev/cli": "latest",
        "@slidev/theme-default": "latest",
        "@slidev/theme-seriph": "latest"
      }

**Comment by cnguyen-de** [comment]
can not reproduce, the example in stackblitz works, you just had bottom-0 also for global-top.vue, if you change to top-0 it should work properly.

<img width="1055" alt="Screenshot 2022-10-21 at 18 41 34" src="https://user-images.githubusercontent.com/6671583/197246747-1eebf748-fff2-4f32-8197-9bd6f1b5152d.png">
