### ISSUE TITLE
Custom client setup (e.g. for shortcuts, mermaid) fail when not on demo:dev

### ISSUE THREAD

**Issue by twitwi** [slidevjs/slidev#708]
**Describe the bug**
Custom setup/ that run on the client are not run. (But they are run in demo:dev).
Looks somewhat (as it works in demo:dev) similar to the issue that was fixed by https://github.com/slidevjs/slidev/commit/596f2ce8b52788752112649ad3cfc3ee12af3936 by @antfu 

**To Reproduce**
- Create a presentation, tested with the latest 0.36.4, and add a `setup/shortcuts.ts`.
- It is ignored.
- The same added to "demo:dev" works.

Digging a little it seems that here https://github.com/slidevjs/slidev/blob/a067890aae4b1c77f351b84706a7bc223b46c7c5/packages/slidev/node/plugins/setupClient.ts#L27 , the path has a `?v=41b2b615` suffix when run from a presentation and no suffix when run in "demo:dev".

**NB**: I tried to remove the suffix in the setupClient.ts and **it then works,** but I'm wondering if there are **other places than would need fixing**?

**Comment by antfu** [comment]
> remove the suffix in the setupClient.ts

Sounds like a good solution. PR welcome
