### ISSUE TITLE
How to use echarts or plotly in slidev?

### ISSUE THREAD

**Issue by crazyn2** [slidevjs/slidev#711]
Does slidev support echarts or any way to show chart?

**Comment by twitwi** [comment]
@crazyn2 

It is possible, but I think you have to force the size (to go against the auto-sizing of vue-echarts).
Here is a mashup from the vue echars examples.

1) install vue-echarts with `npm install echarts vue-echarts` (or pnpm ...)

2) create a `setup/main.ts`
```ts
import { defineAppSetup } from '@slidev/types'

/* echarts */
import { use } from "echarts/core";
import { CanvasRenderer } from "echarts/renderers";
import { PieChart } from "echarts/charts";
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent
} from "echarts/components";
import VChart, { THEME_KEY } from "vue-echarts";
import { ref, defineComponent } from "vue";

use([
  CanvasRenderer,
  PieChart,
  TitleComponent,
  TooltipComponent,
  LegendComponent
]);


export default defineAppSetup(({ app, router }) => {
  window.console.log(app)
  app.component('v-chart', VChart)
})
```

3) use it in your slides
```html

# Hello

<v-chart style="width: 800px !important; height: 400px !important" :option='{
      title: {
        text: "Traffic Sources",
        left: "center"
      },
      tooltip: {
        trigger: "item",
        formatter: "{a} <br/>{b} : {c} ({d}%)"
      },
      legend: {
        orient: "vertical",
        left: "left",
        data: ["Direct", "Email", "Ad Networks", "Video Ads", "Search Engines"]
      },
      series: [
        {
          name: "Traffic Sources",
          type: "pie",
          radius: "55%",
          center: ["50%", "60%"],
          data: [
            { value: 335, name: "Direct" },
            { value: 310, name: "Email" },
            { value: 234, name: "Ad Networks" },
            { value: 135, name: "Video Ads" },
            { value: 1548, name: "Search Engines" }
          ],
          emphasis: {
            itemStyle: {
              shadowBlur: 10,
              shadowOffsetX: 0,
              shadowColor: "rgba(0, 0, 0, 0.5)"
            }
          }
        }
      ]
    }' />
```

(tested just now)

**Comment by twitwi** [comment]
For the record, for plotly:
1) install vue3-plotly with `npm install vue3-plotly plotly.js uuid` (or pnpm ...)

2) create a `setup/main.ts`
```ts
import { defineAppSetup } from '@slidev/types'

/* plotly */
import { VuePlotly } from 'vue3-plotly'

export default defineAppSetup(({ app, router }) => {
  app.component('v-plotly', VuePlotly  )
})
```
3) use it in your slides
```html
# hello

<v-plotly :data="[{ x: [1, 3], y: [2, 4] }]" :layout="{}" :options="{}"/>

```

**Comment by crazyn2** [comment]
> @crazyn2
> 
> It is possible, but I think you have to force the size (to go against the auto-sizing of vue-echarts). Here is a mashup from the vue echars examples.
> 
>     1. install vue-echarts with `npm install echarts vue-echarts` (or pnpm ...)
> 
>     2. create a `setup/main.ts`
> 
> 
> ```ts
> import { defineAppSetup } from '@slidev/types'
> 
> /* echarts */
> import { use } from "echarts/core";
> import { CanvasRenderer } from "echarts/renderers";
> import { PieChart } from "echarts/charts";
> import {
>   TitleComponent,
>   TooltipComponent,
>   LegendComponent
> } from "echarts/components";
> import VChart, { THEME_KEY } from "vue-echarts";
> import { ref, defineComponent } from "vue";
> 
> use([
>   CanvasRenderer,
>   PieChart,
>   TitleComponent,
>   TooltipComponent,
>   LegendComponent
> ]);
> 
> 
> export default defineAppSetup(({ app, router }) => {
>   window.console.log(app)
>   app.component('v-chart', VChart)
> })
> ```
> 
>     3. use it in your slides
> 
> 
> ```
> # Hello
> 
> <v-chart style="width: 800px !important; height: 400px !important" :option='{
>       title: {
>         text: "Traffic Sources",
>         left: "center"
>       },
>       tooltip: {
>         trigger: "item",
>         formatter: "{a} <br/>{b} : {c} ({d}%)"
>       },
>       legend: {
>         orient: "vertical",
>         left: "left",
>         data: ["Direct", "Email", "Ad Networks", "Video Ads", "Search Engines"]
>       },
>       series: [
>         {
>           name: "Traffic Sources",
>           type: "pie",
>           radius: "55%",
>           center: ["50%", "60%"],
>           data: [
>             { value: 335, name: "Direct" },
>             { value: 310, name: "Email" },
>             { value: 234, name: "Ad Networks" },
>             { value: 135, name: "Video Ads" },
>             { value: 1548, name: "Search Engines" }
>           ],
>           emphasis: {
>             itemStyle: {
>               shadowBlur: 10,
>               shadowOffsetX: 0,
>               shadowColor: "rgba(0, 0, 0, 0.5)"
>             }
>           }
>         }
>       ]
>     }' />
> ```
> 
> (tested just now)

Couldn't it upgrades to vue-echarts-v3?

**Comment by twitwi** [comment]
I haven't tried, I just took the first that came (I forgot about versions etc...) but maybe there is also https://www.npmjs.com/package/vue3-echarts , I don't know and cannot check in the short term.

**Comment by crazyn2** [comment]
in any case, your advice is helpful to me. Thank you.
