### ISSUE TITLE
Easily access to slidev context from a custom component

### ISSUE THREAD

**Issue by welcoMattic** [slidevjs/slidev#712]
I would like to create a global progress bar component for my deck, but in my Progress.vue component, I can't access to `$slidev` context to get current slide and total slide number.

Did I miss something?

**Comment by twitwi** [comment]
You should be able to access it from templates, and use imports in the script part, e.g. `import { currentPage } from '@slidev/client/logic/nav'`

**Comment by welcoMattic** [comment]
```<template>
  <div class="absolute bottom-0 -left-40px h-10 progress" 
       style="width: {{ Math.floor(100 * ($slidev.nav.currentPage / $slidev.nav.total)) }}%;"></div>
</template>```

I tried this code to achieve it, but it doesn't work properly: I see no `style` attribute in the rendered HTML.

I guess I definitely miss something :sweat_smile:

**Comment by twitwi** [comment]
good, indeed the top syntax was kind of mustach-y
