### ISSUE TITLE
To much space below the text in mermaid charts, only with windicss

### ISSUE THREAD

**Issue by legousk** [slidevjs/slidev#713]
**Describe the bug**
When creating mermaid charts the text is not centered in the middle of the nodes. This seems to be the case for all different node shapes (tested it for the first 7 nodes on the mermaid documentation). The space increases with more lines of text in the node.

**To Reproduce**
```
graph LR
  A(text) --> C(text)
  C       --> D(text)
```
```mermaid
graph LR
  A(text) --> C(text)
  C --> D(text)
```
 becomes 
![chart](https://user-images.githubusercontent.com/65074333/191903449-7acb6cd7-db9b-4f61-b9a8-35c85c9e867d.png)

and 
```
flowchart LR
  A(text) --> C(text\ntext\ntext\ntext\ntext)
  C       --> E(text)
```
```mermaid
flowchart LR
  A(text) --> C(text\ntext\ntext\ntext\ntext)
  C --> E(text)
```
becomes 
![chart2](https://user-images.githubusercontent.com/65074333/191903714-7b7adf7d-47c8-4173-83b5-75e58d329bc8.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Tested on Firefox, Brave and Chrome
 - Slidev version: v.0.32.2

**Comment by twitwi** [comment]
@legousk I cannot reproduce it (I couldn't have a running 0.32.2 presentation ! and starting from the latest 0.36.5 gives the proper layout).
Do you have any custom style in your presentation?

**Comment by legousk** [comment]
Hello @twitwi, so I kinda cornered the problem I think. 

When I create a new project the mermaid charts are indeed shown normally, but when I put my slides in the .md file the problem came back, apparently it has to do with the setting ```css: unocss``` in the example.  With that setting the charts show normally, but without they don't. However a second problem came up which was that in the layout.css file there is ```// default theme color```, where defaults was an 'unknown word'. I removed this setting and added the ```css: unocss``` and now everything seems to work as expected. 

However I don't know if the ```// default theme color``` setting is/was important? 

**To reproduce**: In a project without anything (layouts, styles) and only this in the slides.md:

```
---
# css: unocss
---

# Welcome to Slidev

---

# Hello

(```)mermaid

flowchart LR;
  A(A) ---> B(B)
  B    ---> C(C)

class A,B,C blocks;

(```)

---
```

the charts do not show correctly, when uncommenting the ```css: unocss``` part they do. 

It might be me as I am still quite new to this, but I couldn't make it work otherwise. If there is something that I did/do wrong let me know :-).

This was all done on an updated version of Slidev btw (v0.36.5)

**Comment by twitwi** [comment]
@antfu any idea why there could be a difference between windi and unocss
It boils down to the following line-height style that gets applied with windicss (and thus breaks the layout) and not with unocss
![image](https://user-images.githubusercontent.com/244649/192606552-bb384851-1439-406e-a70d-d359376e83bd.png)
