### ISSUE TITLE
Operation not permitted by Node.js on MacOS

### ISSUE THREAD

**Issue by GzrDavidRicardo** [slidevjs/slidev#714]
I ran the following command:

> slidev slides.md

The error in Terminal can be viewed as follows:

> node:internal/process/promises:279
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> [Error: EPERM: operation not permitted, scandir '/Users/david/Library/VoiceTrigger/SAT'] {
>   errno: -1,
>   code: 'EPERM',
>   syscall: 'scandir',
>   path: '/Users/david/Library/VoiceTrigger/SAT'
> }

It will be great if anyone can help me out. Thanks!

**Comment by arjungecon** [comment]
Same issue on my MacOS too! Used the global slidev installation. Nothing more.
