### ISSUE TITLE
Don't use external resources

### ISSUE THREAD

**Issue by MarcelCoding** [slidevjs/slidev#717]
**Is your feature request related to a problem? Please describe.**
In some countries, it is not really "allowed" (by law) to open connections to other websites. (without consent of users)
e.g.:
````html
  <link rel="icon" href="https://cdn.jsdelivr.net/gh/slidevjs/slidev/assets/favicon.png">

````

**Describe the solution you'd like**
So it would be more beneficial to just export these resources as well when building using `slidev build`.

**Describe alternatives you've considered**
Download these resources manually and upload them manually to my web space.

**Comment by MarcelCoding** [comment]
I think this is still relevant

**Comment by tonai** [comment]
@MarcelCoding what country and what law are you referring to ?
Thanks

**Comment by MarcelCoding** [comment]
I am in Germany and currently is there like a thing where website providers that are using Google fonts are being fined for sending their user ips to other countries outside the US. So it would be helpful if all assets would be localized and served from the own web server.

**Comment by tonai** [comment]
Ok thanks for your response.
What assets are you referring to ?
Is this only for the favicon ?
You can set up a custom favicon using the frontmatter part of the first slide, and if you want to use a local icon just put it inside the public folder and set:
```md
---
favicon: /my-favicon.png
---
```
See https://sli.dev/custom/#frontmatter-configures

**Comment by MarcelCoding** [comment]
Ok, I did not know this, until now, I just replaced the URL myself in the resulting HTML. But I hope I made you aware of this problem, to that it isn't going to lead to more external (non-configurable) assets.
