### ISSUE TITLE
export presenter notes only

### ISSUE THREAD

**Issue by pieterjd** [slidevjs/slidev#718]
I'm preparing a talk and would like to print my notes as the room setup does not allow to have a separate window in presenter mode.

Is it possible to add an export of the print notes only, with for instance some information of the slide the notes applies to (eg slide nr, maybe title?)

Thanks!
Pieter-Jan

**Comment by antfu** [comment]
Sounds reasonable, open to pr.

**Comment by lomby92** [comment]
@antfu I will open a PR asap, have you think about the content to print?

I think we should print info about the page number the comment refers to, since not all pages could have presenter notes

**Comment by pieterjd** [comment]
That is just perfect 👍 Indeed pages without notes should not be included. 

THanks for taking this up. I started looking into it, I have an idea what's going on but I don't really feel comfortable making changes as my main focus is Java dev 😉

**Comment by lomby92** [comment]
@pieterjd this is how it looks like for now:
![Screenshot_20221022_100836](https://user-images.githubusercontent.com/5825081/197328388-44833504-8b04-4fdb-b092-34ca0701fcb7.png)

I'm looking for testing the new CLI command and I will open the PR
