### ISSUE TITLE
MacOS Cannot Edit

### ISSUE THREAD

**Issue by dougalg-tw** [slidevjs/slidev#719]
**Describe the bug**

When attempting to edit slides I am presented with an error:

```sh
> $ npm run dev                                                                                                                                                                    ⬡ 18.10.0

> dev
> slidev --open


  ●■▲
  Slidev  v0.36.5

  theme   @slidev/theme-seriph
  entry   /Users/dougal.graham/Documents/Presentations/vue-react-hooks/slides.md

  public slide show   > http://localhost:3030/
  presenter mode      > http://localhost:3030/presenter/
  remote control      > pass --remote to enable

  shortcuts           > restart | open | edit

Could not open slides.md in the editor.
The editor process exited with an error: spawn code ENOENT.
```

**To Reproduce**
1. `npm run dev` in a fresh project
2. Click the "edit" button
3. Nothing happens, there is an error in the JS console in the CLI

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser: Chrome or Firefox
 - Slidev version: v0.36.5

**Comment by PkuCuipy** [comment]
got the same issue, any solution?

**Comment by PkuCuipy** [comment]
I think I've resolved it:
1. Start slidev backend server in CLI;
2. Manually open `VS Code` with `slidev` extension installed;
3. Then my `VS Code` can automatically detect and connect to that backend, and display the `edit` UI layout.
