### ISSUE TITLE
Allow bundling assets in themes that can be used in slides

### ISSUE THREAD

**Issue by DonDebonair** [slidevjs/slidev#727]
**Is your feature request related to a problem? Please describe.**
Slidev makes it quite easy to create custom themes. But in corporate settings, there is often a specific set of stock images that can be used in presentations within that company. Currently, it seems Slidev doesn't support bundling images with a theme, to be used in presentations that use that theme

**Describe the solution you'd like**
I'd like to be able to bundle images with a theme which users of that theme can than easily use within their slides. Like this:

```markdown
---
layout: image-right
image: 'theme/assets/stock-image-1.png'
---

# Slide Title
## Slide Subtitle

* Slide bullet text
* 
```

**Describe alternatives you've considered**
Alternatively, images could be wrapped in components that are provided with the theme. But that would be cumbersome and these images wouldn't be able to be used in frontmatter

**Comment by DonDebonair** [comment]
Bumping this, because I don't consider this to be stale :)

**Comment by ecuriotto** [comment]
I'm buming it as well, I think this would be an interesting feature!

**Comment by DonDebonair** [comment]
@antfu is this something you'd like to see? Would you accept a PR for this?

**Comment by antfu** [comment]
For sure, PR welcome. Thanks!

**Comment by DonDebonair** [comment]
Apologies for the huge delay @antfu , I had to find some time to learn how slidev works and how the code base is structured. I have opened [a PR](https://github.com/slidevjs/slidev/pull/951). Let me know what you think!
