### ISSUE TITLE
Blank screen post recording.

### ISSUE THREAD

**Issue by hemanth** [slidevjs/slidev#73]
On chrome stable and canary wasn't able to see the screen or the camera recording :

https://user-images.githubusercontent.com/18315/117896110-ad659c00-b274-11eb-94d9-d194f6a547d5.mov

On FF, it was better and but the audio wasn't recorded.

P.S: Browser dev console has not errors.

**Comment by antfu** [comment]
Have you tried with `localhost` instead of `127.0.0.1` maybe? I can't reproduce it on my side.

**Comment by antfu** [comment]
Close due to inactive
