### ISSUE TITLE
Column highlighting

### ISSUE THREAD

**Issue by JohnnyJayJay** [slidevjs/slidev#730]
**Is your feature request related to a problem? Please describe.**
While it is possible to highlight certain lines in a code block, it does not seem to be possible to highlight certain columns. This would be a nice feature to have, allowing you to highlight different sections of a single line.

**Describe the solution you'd like**
The solution could be implemented as an optional extension to the current format for specifying lines, i.e. for each line specification, an optional column specification could follow. The format for specifying columns could be the same as the format for specifying lines. 

A couple examples of what that might look like:
<pre>
```ts {2(1-20),3}
function add(
  a: Ref<number> | number,
  b: Ref<number> | number
) {
  return computed(() => unref(a) + unref(b))
}
```
</pre>
This would highlight line 2, columns 1-20 and line 3. The column specification is in parentheses behind the line specification here. This shows that something like this would preserve backward compatibility: omitting the column specification simply highlights all columns.

An example with a single line, but multiple steps:

<pre>
```js {1(1-7|9-11|13-19)}
console.log("Hello")
```
</pre>

This would highlight `console`, then `log`, then `"Hello"`.

How about combining "line highlighting steps" *and* "column highlighting steps"?
Since columns are the "secondary" dimension, it would walk through the column steps for a given line step first, and when the column steps are exhausted, move on to the next line step. Example to illustrate:

<pre>
```js {1-2(1-3|1)|2(5-7)}
foo quz
bar baz
```
</pre>

This would induce the following order:
1. `foo` and `bar` are highlighted
2. `f` and `b` (first column) are highlighted
3. `baz` is highlighted

**Describe alternatives you've considered**
This syntax suggestion is just that: a suggestion. I came up with this on the spot without giving it a lot more thought, there may be better solutions. Another alternative could be to separate line and column highlighting - this would make the syntax simpler, but would make it impossible to highlight specific line and column combinations like above.

**Comment by CarsonSlovoka** [comment]
see also: https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences
