### ISSUE TITLE
Slidev logo in presenter mode became huge

### ISSUE THREAD

**Issue by Envek** [slidevjs/slidev#733]
**Describe the bug**
Most of the time header logo in presenter view is HUGE:
![image](https://user-images.githubusercontent.com/264400/195845493-d8ed7adb-76ec-4186-bd23-3825487d08aa.png)

For some reason `lg:h-14` class applied to slidev `img` element doesn't exist so height isn't limited.

This issue is flaky, but present most of the time in my slides.

I didn't touched windicss config, just put some custom styles to `styles/index.css`.

**To Reproduce**
1. Go to presenter mode (either directly or from public slide show)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Google Chrome 106.0.5249.119 (Official Build) (64-bit) and Firefox 105.0.3 (64-bit)
 - Slidev version: 0.36.5 and 0.36.6

**Comment by cnguyen-de** [comment]
can confirm I've seen this exact issue, sometimes restarting the dev server the problem goes away.

**Comment by Envek** [comment]
For me, deleting the whole `node_modules` folder sometimes helps :sweat_smile: 

---

I published slides where it occurs here: https://github.com/Envek/kaigionrails-postgresql-as-seen-by-rubyists/

It occurs not only my machine, but also on others. However it may require to restart dev server several times before it happens.

**Comment by antfu** [comment]
Can you verify if it's still present in 0.36.11? Thanks

**Comment by Envek** [comment]
No, still reproducible after `npm update @slidev/cli` (it became 0.36.11 in `package-lock.json`). But it seems to became less frequent.

Reproduction steps:
 1. Run `npm run dev`, browser window will open
 2. Go to presenter mode (most probably logo will be fine)
 3. Stop dev server and run `npm run dev` again
 4. Already opened window will reload and logo will became huge (not always)

Steps 3 and 4 may be needed to repeat 1-2 times, but after several dev server restarts logo will become huge.

Also logo may become normal size after a few seconds (but often won't).

Closing all browser tabs and restarting dev server once again rarely helps.

**Comment by jimbobbennett** [comment]
Seeing the same. It didn't happen with 0.31.2, but happens with 0.36.11.

**Comment by jimbobbennett** [comment]
Looks like it is related to #624. If I manually revert the classes for the image to what was before this PR, then the image shrinks back down to the right size.

**Comment by twitwi** [comment]
Switching to windicss seems to be a workaround (removing `css: unocss` from the headmatter).

**Comment by Envek** [comment]
Confirming: can't reproduce after removing `css: unocss`

**Comment by jimbobbennett** [comment]
This is still an issue. Please don't mark as stale. Tested with 0.38.4

**Comment by MMMikeM** [comment]
Still an issue in 0.40.3

**Comment by 117503445** [comment]
Still an issue in 0.40.3

can fixed by

> Confirming: can't reproduce after removing `css: unocss`

**Comment by elrinor** [comment]
Still an issue.

**Comment by TechWatching** [comment]
We can reproduce it easily just by adding a long text as a comment of a slide. If the text is too long, it breaks something making the logo becoming huge.

**Comment by 0phoff** [comment]
I'm not sure whether this is the same issue, but I had this once and then noticed it is because I was zoomed in on my browser. Because slidev automatically rescales your slides to fit in the viewport, you don't really notice your zoomed in, except for this extra elements such as the slidev logo.

On google chrome, pressing `ctrl+0` resets your zoom level to 100%.

It seems silly to post this, but I put it here anyway in case it can help some people :innocent:

**Comment by antfu** [comment]
This should be fixed in the latest version. Can anyway still reproduce it?

**Comment by TechWatching** [comment]
I did not succeed in reproducing it. I don't know if someone else can confirm it's good now.

**Comment by Envek** [comment]
Couldn't reproduce it on 0.42.4 :tada: 

@antfu thank you for creating and maintaining such an amazing tool!
