### ISSUE TITLE
player component and auto-play

### ISSUE THREAD

**Issue by PhE** [slidevjs/slidev#735]
**Is your feature request related to a problem? Please describe.**
I would like to embed slidev presentations in web pages in auto-play mode.

**Describe the solution you'd like**
Let's have a vue component that can embed a slidev presentation in any page.
A prop, or a frontmatter setting, would allow an auto-play feature (setting the default period in seconds).

**Describe alternatives you've considered**
I currently use a multi-page SVG file rendered and animated in the target page.

**Comment by twitwi** [comment]
@PhE it does not provide a component (I think slidev is designed to be on its own in the page so in the end it would rather be an iframe) but you might be interested in the AutoPlay example I had done:
- it is instantiated here https://github.com/twitwi/slidev-addon-ultracharger/blob/main/global-top.vue#L14
- the code is part of my set of addons, but you can as well copy it directly https://github.com/twitwi/slidev-addon-ultracharger/blob/main/components/AutoPlay.vue
