### ISSUE TITLE
problem after install 

### ISSUE THREAD

**Issue by ropoko** [slidevjs/slidev#75]
## Screenshot
![image](https://user-images.githubusercontent.com/49417432/117900305-4b6e5c00-b29f-11eb-835d-fc3fe8f12b07.png)

## Explanation
After following the steps on start guide in official website: ` yarn create slidev ` and then ` yarn dev `, the url - http:localhost:3030/1 open in browser and the above message immediately appear. BTW, this is just an annoying bug, since it can be hidden.

## Possible solution 
On [Vite documentation](https://vitejs.dev/config/#publicdir), they say to add a folder "public" to add static files, after testing it, the message doesn't show up, apparently fixing the bug. If this is a right approach, I'll be glad to open a pull request. ;)

:heart: Great project, I really loved this.

**Comment by antfu** [comment]
We will try to find a solution on the Vite side. Thanks

**Comment by Arcadianer** [comment]
I just encountered the same issue. 
But also ... GREAT project 👍

**Comment by shenshaojun1993** [comment]
same with me, using npm init slidev.
I found it will appear the second time I run npm run dev.
