### ISSUE TITLE
Combining code block highlighting and v-click results in empty clicks

### ISSUE THREAD

**Issue by AustinGil** [slidevjs/slidev#752]
**Describe the bug**
Combining code blocks with line highlighting along with v-click directive results in more registered clicks than should be on the slide. Depending on the order, if the code block is before the v-click, it will add a bunch of empty clicks to the end of the list. If the code block comes after the v-click, it will add a bunch of empty clicks at the beginning of the list.

**To Reproduce**
Create a slide that includes a code block with line highlighting. Add some content that uses v-click. Count the number of times it takes to click through the slide. Example code below.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Slidev version: 0.36.9

**Example code**
This block was taken from my presentation. I had to modify the closing code block fence so that it would actually show up properly here.

```html
<div class="grid gap-4 grid-cols-2">

```yml {all|all|4|6|8|10|12}
# ci.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm run build

      - run: npm run deploy

` ` `
<div>
<div v-click="1" class="mt-6">A machine that lives on GitHub's servers</div>
<div v-click="2" class="mt-15">running Ubuntu OS (with NPM installed)</div>
<div v-click="3" class="mt-9">checks out your repo's code,</div>
<div v-click="4" class="mt-9">installs NPM dependencies,</div>
<div v-click="5" class="mt-9">then runs the "build" command from your package.json file,</div>
<div v-click="6" class="mt-5">then runs the "deploy" command from your package.json file.</div>
</div>
</div>
```

Should have 6 clicks, but registers 12 before moving on to next slide.

**Comment by edimitchel** [comment]
I have the same issue, @AustinGil we could work together to find out a solution to this issue, are you ok?

**Comment by AustinGil** [comment]
I am ok. So far I've just been clicking extra times whenever I run into this issue.

**Comment by edimitchel** [comment]
Let's try to create a reproduction using stackblitz

**Comment by edimitchel** [comment]
I just found a solution to that issue by using the option `at` on the code block:

```vue {all|11-13|15-20|1-9} {at: 2}
<script>
export default {
  data() {
    return {
      greeting: 'Hello World!'
    }
  }
}
</script>

<template>
  <p class="greeting">{{ greeting }}</p>
</template>

<style>
.greeting {
  color: red;
  font-weight: bold;
}
</style>
```

Within a v-click (the second one in the slide), putting `at` to 2 will make it work as expected.

**Comment by edimitchel** [comment]
Actually, testing your markdown won't be solved by my suggestion..

Just to be clear: what do you want? having lines highlighted shown in same time that v-clicks steps ?

**Comment by flolbr** [comment]
I think I made it work here: https://github.com/slidevjs/slidev/issues/860#issuecomment-1633057289

**Comment by AustinGil** [comment]
Thank you so much for updating here. Sounds like a good option. I'll give it a go :)
