### ISSUE TITLE
Relative Imports with `src:`

### ISSUE THREAD

**Issue by rawkode** [slidevjs/slidev#753]
**Describe the bug**
I'm composing my slide decks with markdown files from across my repository. Some of my markdown files contain:

```
---
src: ./LAB.md
---
```

Where `LAB.md` is a relative markdown file with a lab associated with that topic.

However, relative links do not work. This means that even while I'm 3/4 levels deeps within my repository, I need to use `src: /topics/kubernetes/pods/LAB.md`

**To Reproduce**
1. Create `slides.md` with `src: ./topics/TOPIC.md`
2. Try to link these docs together with `src: ./LAB.md` in `./topics/TOPIC.md`
3. Errror

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Slidev version: v0.36.10

**Comment by twitwi** [comment]
@rawkode it should be shipped in 0.38.2
