### ISSUE TITLE
A document about how to use axios in slidev

### ISSUE THREAD

**Issue by WYX-K** [slidevjs/slidev#758]
When I use slidev to develop an academic ppt, I want to connect with my  backend. I choose to use axios, but there are some problems about cross-domain. It isn't similar with pure vue3 and vite. I can't insert settings in vite.config.ts. Thus, please give a document about it. Thanks

**Comment by twitwi** [comment]
If you still need it, please note that there is an entry in the documentation here https://sli.dev/custom/config-vite.html

**Comment by tonai** [comment]
Just used axios in a custom component in slidev without any issue.
If you have CORS errors it is most probably to your API configuration and not to Slidev.
