### ISSUE TITLE
Slidev manager

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [slidevjs/slidev#760]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you'd like**

Slidev is a frontend system. I want a backend system designed for Slidev that can manage all my slides. Is there anything like that?

**Describe alternatives you've considered**
If there is no products ready, I can make one myself.

**Comment by Gorgeous-Patrick** [comment]
I want to be able to access to my slides with any computer.

**Comment by antfu** [comment]
We don't have the plan to do that officially for now. Free free to experiments :)
