### ISSUE TITLE
How to forbid public slide show mode

### ISSUE THREAD

**Issue by zhou-jianwen** [slidevjs/slidev#761]
Although the remote parameter can set a password for the presenter mode. The  public slide show mode still can be access directly when deploying the application on a cloud server that exposes port 3030.

![image](https://user-images.githubusercontent.com/118164769/202358512-e0ff68ff-e5cb-41a9-9849-32cfc46f2e20.png)

**Comment by Krue1** [comment]
Why my remote setting didn't work?
![image](https://user-images.githubusercontent.com/44221403/210819445-fd21a90a-b4ff-49a5-941f-4c7ca1137c66.png)

**Comment by tonai** [comment]
Can you clarify your request ?
You want to forbid all access ? (the presenter and slides ?)
