### ISSUE TITLE
Monaco cannot display code in md & style when using unocss

### ISSUE THREAD

**Issue by YinDongFang** [slidevjs/slidev#762]
**Describe the bug**
When using `unocss`, the code in `md` cannot be send to monaco editor.

**To Reproduce**
[![](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/slidev-bk6ko6?file=slides.md)
1. Open in stackblitz
2. You can see the monaco editor without code
3. Remove `css: unocss` and refresh. It's be expected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome:107.0.5304.107
 - Slidev version: 0.36.11

**Comment by YinDongFang** [comment]
### Possible reason:

It seems to be caused by: https://vscode.dev/github.com/unocss/unocss/blob/9710504f571e204cd2edc9c2a59024abcf2d0586/packages/vite/src/modes/global/dev.ts#L177

It should be the `await` causes the subsequent code to be executed asynchronously. Which delays the execution of `addEventListener('message')` later than the trigger of the `load` event. So the iframe cannot recieve data when the `load` event fires and executing `postCode`.

###  Possible solution:

`window.parent.postMessage` after `addEventListener('message')` and handle the message in `Monaco.vue` by `postCode` and `postStyle`


> Glad to make new PR!     : )

**Comment by YinDongFang** [comment]
Seems same as https://github.com/slidevjs/slidev/issues/701 . But the issue closed without fixed?

**Comment by edimitchel** [comment]
I get the same issue here:

<details>
<summary>Error stack</summary>
> Uncaught Error: Unexpected usage

loadForeignModule@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:35495:27
_getForeignProxy/this._foreignProxy<@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:35976:22
promise callback*_getForeignProxy@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:35974:45
getProxy@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:35998:17
_getClient@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:84:28
getLanguageServiceWorker@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:99:17
worker@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:1070:19
_doValidate@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:351:31
maybeValidate@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:288:16
onModelAdd@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:313:7
DiagnosticsAdapter/<@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:344:80
DiagnosticsAdapter@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:344:51
setupMode@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:1085:3
setupTypeScript@http://localhost:3030/node_modules/.vite/deps/tsMode-SH4JQRSA.js?v=22f65a64:1046:22
@http://localhost:3030/node_modules/.vite/deps/chunk-O3ZP4UQR.js?v=22f65a64:235:40
promise callback*@http://localhost:3030/node_modules/.vite/deps/chunk-O3ZP4UQR.js?v=22f65a64:235:20
onLanguage/disposable<@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:89161:7
invoke@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:1813:23
fire@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:1913:24
_createAndGetLanguageIdentifier@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:70479:36
createById/<@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:70463:19
LanguageSelection@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:70491:28
createById@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:70462:12
createTextModel@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:88484:61
createModel@http://localhost:3030/node_modules/.vite/deps/chunk-TUOEDPXQ.js?v=22f65a64:88513:10
start@http://localhost:3030/@fs/Users/micheledighoffer/CAP/formation-vue3-vitest-cypress/node_modules/.pnpm/@slidev+client@0.36.11_vite@3.2.4/node_modules/@slidev/client/iframes/monaco/index.ts:42:31
async*@http://localhost:3030/@fs/Users/micheledighoffer/CAP/formation-vue3-vitest-cypress/node_modules/.pnpm/@slidev+client@0.36.11_vite@3.2.4/node_modules/@slidev/client/iframes/monaco/index.ts:127:1
setTimeout handler*@http://localhost:3030/__uno.css:12:44
@http://localhost:3030/__uno.css:12:11
    editor chunk-TUOEDPXQ.js:873
    setTimeout handler*node_modules/.pnpm/monaco-editor chunk-TUOEDPXQ.js:871
    onUnexpectedExternalError errors.js:29
    onUnexpectedExternalError errors.js:43
    promises inlayHints.js:115
    rejected inlayHints.js:9
    promise callback*step inlayHints.js:10
    __awaiter33 inlayHints.js:11
    __awaiter33 inlayHints.js:7
    promises inlayHints.js:107
    promises inlayHints.js:107
    create inlayHints.js:107
    __awaiter33 inlayHints.js:11
    __awaiter33 inlayHints.js:7
    create inlayHints.js:105
    scheduler inlayHintsController.js:152
    __awaiter35 inlayHintsController.js:20
    __awaiter35 inlayHintsController.js:16
    scheduler inlayHintsController.js:145
    doRun async.js:406
    onTimeout async.js:401
    setTimeout handler*schedule async.js:384
    _update inlayHintsController.js:183
    InlayHintsController2 inlayHintsController.js:103
    invoke event.js:407
    fire event.js:551
    register languageFeatureRegistry.js:37
    registerInlayHintsProvider standaloneLanguages.js:484
    setupMode tsMode.js:1092
    setupTypeScript tsMode.js:1054
    <anonymous> monaco.contribution.js:242
    promise callback* monaco.contribution.js:242
    disposable standaloneLanguages.js:56
    invoke event.js:407
    fire event.js:551
    _createAndGetLanguageIdentifier languageService.js:62
    createById languageService.js:43
    LanguageSelection languageService.js:74
    createById languageService.js:42
    createTextModel standaloneCodeEditor.js:316
    createModel standaloneEditor.js:66
    start index.ts:50
    async* index.ts:149
    setTimeout handler* __uno.css:12
    <anonymous> __uno.css:12
errors.js:12:26
    unexpectedErrorHandler errors.js:12
    (Async: setTimeout handler)
    unexpectedErrorHandler errors.js:10
    onUnexpectedExternalError errors.js:29
    onUnexpectedExternalError errors.js:43
    promises inlayHints.js:115
    throw self-hosted:1766
    rejected inlayHints.js:9
    (Async: promise callback)
    step inlayHints.js:10
    __awaiter33 inlayHints.js:11
    __awaiter33 inlayHints.js:7
    promises inlayHints.js:107
    map self-hosted:221
    promises inlayHints.js:107
    map self-hosted:221
    create inlayHints.js:107
    InterpretGeneratorResume self-hosted:1819
    next self-hosted:1740
    __awaiter33 inlayHints.js:11
    __awaiter33 inlayHints.js:7
    create inlayHints.js:105
    scheduler inlayHintsController.js:152
    InterpretGeneratorResume self-hosted:1819
    next self-hosted:1740
    __awaiter35 inlayHintsController.js:20
    __awaiter35 inlayHintsController.js:16
    scheduler inlayHintsController.js:145
    doRun async.js:406
    onTimeout async.js:401
    onTimeout self-hosted:1356
    (Async: setTimeout handler)
    schedule async.js:384
    _update inlayHintsController.js:183
    InlayHintsController2 inlayHintsController.js:103
    invoke event.js:407
    fire event.js:551
    register languageFeatureRegistry.js:37
    registerInlayHintsProvider standaloneLanguages.js:484
    setupMode tsMode.js:1092
    setupTypeScript tsMode.js:1054
    <anonymous> monaco.contribution.js:242
    (Async: promise callback)
    <anonymous> monaco.contribution.js:242
    disposable standaloneLanguages.js:56
    invoke event.js:407
    fire event.js:551
    _createAndGetLanguageIdentifier languageService.js:62
    createById languageService.js:43
    LanguageSelection languageService.js:74
    createById languageService.js:42
    createTextModel standaloneCodeEditor.js:316
    createModel standaloneEditor.js:66
    start index.ts:50
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    (Async: async)
    <anonymous> index.ts:149
    (Async: setTimeout handler)
    <anonymous> __uno.css:12
    <anonymous> __uno.css:12
    AsyncFunctionNext self-hosted:807
</details>

With TS code:
> SyntaxError: import declarations may only appear at top level of a module ts.worker.js:1
