### ISSUE TITLE
$setup.$slidev.nav.go is not a function

### ISSUE THREAD

**Issue by jadestarzuo** [slidevjs/slidev#763]
**Describe the bug**
Vue Global Context
$slidev.nav.go can not work

[stackblitz](https://stackblitz.com/edit/slidev-xh49kh?file=slides.md)

1. Open in stackblitz
2. You can click the second page  'XXX2'
3.  is not work becourse  the error  "$setup.$slidev.nav.go is not a function "

**Desktop (please complete the following information):**
 - OS: Mac Pro
 - Browser: chrome 107.0.5304.110
 - Slidev version: 0.36.11

**Comment by kuro7766** [comment]
I tried using `<a href="/page">`. But when it jumps, it will break full screen view, which is anoying.

**Comment by twitwi** [comment]
@jadestarzuo there is a component to make links (that behave well from different perspectives, including focus and pdf export) in slidev https://sli.dev/builtin/components.html#link

**Comment by jadestarzuo** [comment]
> @jadestarzuo there is a component to make links (that behave well from different perspectives, including focus and pdf export) in slidev https://sli.dev/builtin/components.html#link (but I don't know why go() is not found)

yes, you are right ,use Link is ok
