### ISSUE TITLE
Is it possible to capture slide navigation events?

### ISSUE THREAD

**Issue by mpenna** [slidevjs/slidev#767]
I'm not sure if this is the best forum, but I've been trying to figure out how to capture the slide navigation events, something along the lines of "slide enter/leave" events. Is this possible?

**Comment by tonai** [comment]
What are you trying to achieve ?

**Comment by mpenna** [comment]
Trigger some custom logic upon slide navigation.

**Comment by antfu** [comment]
Use https://sli.dev/custom/config-vue.html :

```ts
import { useRouter } from 'vue-router'

const router = useRouter()

router.beforeEach(() => {

})

router.afterEach(() => {

})
```

**Comment by yogabonito** [comment]
I tried your approach and it allows me to run some code on each click 👍 I can also see that, for example, `router.afterEach` is provided with information on the current and previous state (e.g., a path such as `"/2?clicks=1"`). It would be super-useful, if there was a way to find out the `id` of the element that is being shown as the result of a click. Is this possible?
