### ISSUE TITLE
Can't use Vue component in my custom layout 

### ISSUE THREAD

**Issue by SpookyJelly** [slidevjs/slidev#773]
**Describe the bug**

When Import Vue Component on ` layouts/my-cool-theme.vue `, pages don't moves, (I think it's `display:none` won't applied on key pressed)

**To Reproduce**

1. Make vue component on `root/layout ` as layout
```ts
// my-cool-theme.vue

<script setup lang="ts">

</script>
<template>
  <div class="slidev-layout default">
    <slot />
  </div>
</template>
<style>

```
2. import other SFC from other
```ts
// Lorem.vue

<template>
  <p>Lorem</p>
</template>

```

```ts
// my-cool-theme.vue
<script setup lang="ts">
import Lorem from  './Lorem.vue' // I also tried `root/component` too
</script>
<template>
  <div class="slidev-layout default">
    <slot />
  </div>
<Lorem/>
</template>
<style>


```
3. use it on `slides.md`

```md
~~~

---

layout: my-cool-theme
---

~~
```

4. unexpected results

![Nov-28-2022 17-45-23](https://user-images.githubusercontent.com/74237436/204233600-066f2a5d-7f34-462c-a243-ab0cfae13ef1.gif)

- before 

![Nov-28-2022 17-47-14](https://user-images.githubusercontent.com/74237436/204233486-be0b46b2-1546-437f-b095-d8f58a8b0c15.gif)

- after I applied custom layout with vue component on second page

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser: Chrome
 - Slidev version: 0.37.0

**Comment by tonai** [comment]
Just created a slidev project.
Created `components/Lorem.vue` with:
```html
<template>
  <p>Lorem</p>
</template>
```

Then created `layouts/my-cool-theme.vue` with:
```html
<template>
  <div class="slidev-layout default">
    <slot />
    <Lorem />
  </div>
</template>
```

And in the slides:
```md
---
layout: my-cool-theme
---

Some content

---
```
And it works fine.

You can check the doc here: https://sli.dev/custom/directory-structure.html#components

**Comment by tonai** [comment]
Closing this issue, please reopen if this is not fixed for you.
Also if you need support you may post questions on the Discord channel: https://chat.sli.dev/
