### ISSUE TITLE
"npx slidev build" only produce a blank html in Version 0.37.0

### ISSUE THREAD

**Issue by Fanisting** [slidevjs/slidev#775]
**Describe the bug**
I cannot use the static host function by "npx slidev build" to produce HTML files. 
The "index.html" file in "dist" folder is a blank html. 
I tried to build the default project and my project(use theme academic), and both of them failed to function well.

**To Reproduce**
1. initialize a new default project by "npm init slidev"
2. Type "y" to proceed and start a project.
3. In the new project's folder, run "npx slidev build" 
4. Find the newly-emerging "dist" folder and open the index.html
5. it is blank

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Slidev version: 0.37.0

I would appreciate any feedback and comment, and let me know if any further information is needed.

**Comment by FerroEduardo** [comment]
Have you opened the index.html directly from the browser? If yes, it won't work properly.  
You could try opening using Vite built-in preview server by running `npx vite preview` after `npm run build`

**Comment by anoreg** [comment]
> 

Thx. It works. Why can't we preview it by opening it in the browser directly?

**Comment by FerroEduardo** [comment]
> > > Have you opened the index.html directly from the browser? If yes, it won't work properly. You could try opening using Vite built-in preview server by running `npx vite preview` after `npm run build`
> 
> Thx. It works. Why can't we preview it by opening it in the browser directly?

Because when the file is opened directly, the path of the linked files (css/js) may be interpreted wrongly

Explanation: https://stackoverflow.com/a/74739994

**Comment by tonai** [comment]
Yes you need a HTTP server to serve the static build.
