### ISSUE TITLE
Question: size of layout: iframe

### ISSUE THREAD

**Issue by AlexisRenchon** [slidevjs/slidev#777]
Hi, 
I am not sure if GitHub issues is the right place to ask questions... 
I am using 
```
layout: iframe-right
url: myurl
```
It works great, but in my case, the url appear really big (big font, etc). I tried zooming out with ctrl - , but it doesn't help. 
Is there a way to style / resize the url content to make it smaller? 

My presentation is available on GitHub [here](https://github.com/AlexisRenchon/Slides_CliMA_soilCO2), and the problem is in slide 6

**Comment by antfu** [comment]
We could do https://github.com/slidevjs/slidev/commit/fcdd4da5b51bcde9969d63d51009577ff2e73937 for `iframe-right.vue` and `iframe-left.vue`. PR welcome :)

**Comment by AlexisRenchon** [comment]
Hi @antfu, I fixed the issue in PR #783. Let me know if it looks good to be merged! Then issue can be closed.

**Comment by AlexisRenchon** [comment]
#783
