### ISSUE TITLE
Some of `slʌɪdɪv` characters are not correctly displayed

### ISSUE THREAD

**Issue by jdbruxelles** [slidevjs/slidev#778]
**Describe the bug**
Some `slʌɪdɪv` characters are not correctly displayed on Chrome Android. Maybe you can do something that can fix it :).

![image](https://user-images.githubusercontent.com/18559798/204641158-0d0489a6-0874-4dfa-a000-e44357d16bba.png)

**To Reproduce**
1. Go to the [Getting Started](https://sli.dev/guide/#overview) page
2. Scroll down to the first paragraph, first line.
3. See the error

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Chrome latest
 - Slidev version: Online website v0.37.1

**Comment by jdbruxelles** [comment]
I found the problem. It's because "/slʌɪdɪv/" is in a `code` tag. I made a test where I remove the surrounding `code` tag and I can see that It's displayed correctly on both mobile and laptop.

Maybe just use */slʌɪdɪv/* intead of `/slʌɪdɪv/`?

**Comment by antfu** [comment]
Sounds reasonable, pr welcome :)
