### ISSUE TITLE
Search modal visible by default on page load

### ISSUE THREAD

**Issue by jdbruxelles** [slidevjs/slidev#779]
**Describe the bug**
Search modal visible by default once the page loaded. When going to another page, the search modal doesn't appear.

**To Reproduce**
1. Go to any page in [sli.dev](https://sli.dev/)
2. And see the modal first

**Desktop (please complete the following information):**
 - OS: Windows and Android
 - Browser: Chrome, Firefox, etc.
 - Slidev version: Online website v0.37.1

**Comment by antfu** [comment]
Fixed, thanks
