### ISSUE TITLE
Support of xterm

### ISSUE THREAD

**Issue by Roger-luo** [slidevjs/slidev#785]
**Is your feature request related to a problem? Please describe.**
I tried to put a terminal using `xterm.js` but the example at xterm front page does not work because it mutates a `<div>` obj.

**Describe the solution you'd like**
I think it's pretty standard for one who wants to demo some live coding
in the terminal while giving the presentation. I wonder if we can have a built-in component `<terminal></terminal>` that creates a terminal at the location.

**Describe alternatives you've considered**
alternatively, I'd like to know what would be the right way to implement this myself as I'm not super familiar with vue.

**Comment by tonai** [comment]
It's clearly not perfect but you can create a custom component (cf https://sli.dev/custom/directory-structure.html#components) like this one:
```html
<script setup>
import { onMounted, ref } from 'vue'
import { Terminal } from 'xterm'
import 'xterm/css/xterm.css'

const terminalRef = ref()

onMounted(() => {
  const term = new Terminal()
  term.open(terminalRef.value)
  term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
})
</script>

<template>
  <div ref="terminalRef" />
</template>
```
If you want to propose the `Terminal` component to everybody you can create an addon.
(you can check this addon for the example : https://github.com/Smile-SA/slidev-component-pager)

**Comment by Roger-luo** [comment]
Thanks you!
