### ISSUE TITLE
feat: theming support for mermaid

### ISSUE THREAD

**Issue by wheatjs** [slidevjs/slidev#79]
Don't see it anywhere in the docs, but maybe we could have support for theming mermaid via https://mermaid-js.github.io/mermaid/#/theming in slidev custom themes.

I haven't looked to much into how difficult it would be to add support, but I think visually the diagrams would benefit a lot from being able to theme them

**Comment by antfu** [comment]
Do you mean the `%%{init: {'theme':'base'}}%%` syntax, or custom themes?

**Comment by wheatjs** [comment]
My knowledge of it is pretty surface level as I've only briefly looked into it, but I guess what I mean is a way to customize the themes of the diagrams via `create-theme`. But if this is already possible maybe some documentation for it

**Comment by antfu** [comment]
Got it. This is currently missing, will do that later

**Comment by antfu** [comment]
See https://sli.dev/custom/config-mermaid.html
