### ISSUE TITLE
The generated PDF from vercel is wrong.

### ISSUE THREAD

**Issue by cp3hnu** [slidevjs/slidev#791]
**Describe the bug**
Generate PDF in local is correct, but generate PDF from vercel is wrong.

**To Reproduce**
1. Go to https://web-frontend-mock-29td8q1xq-cp3hnu.vercel.app/1
2. Click on 'download'
3. Save PDF
4. The generated PDF is wrong.

**Desktop (please complete the following information):**
 - OS: mac os 12.1
 - Browser: chrome
 - Slidev version: 0.37.1

**Comment by tonai** [comment]
Hello @cp3hnu ,
do you have a reproduction repository or something I can test locally ?

**Comment by cp3hnu** [comment]
repository: https://github.com/cp3hnu/web-frontend-mock
