### ISSUE TITLE
Chapter Selection (Named Goto)

### ISSUE THREAD

**Issue by rawkode** [slidevjs/slidev#794]
**Is your feature request related to a problem? Please describe.**

The `g` key, `goto` feature is fantastic - but only if you know the slide number you need to visit.

I'd like to see this extended to offer chapter selection.

**Describe the solution you'd like**

In the frontmatter, we can add `chapter: XYZ` or `name: XYZ` and this gives us a name `XYZ` that we can use to jump around.

`g` input box should then support auto-completing `X` into `XYZ` if there's no ambiguity and go straight to that slide.

**Describe alternatives you've considered**

NA

**Comment by tonai** [comment]
@rawkode here is a draft of a solution for this case.
Can you have a look and tell me what you think ?

**Comment by rawkode** [comment]
@tonai Sorry for the delay. That draft looks awesome.

1. `routeAlias` I think is fine while you gather some feedback from adopters
2. I agree that headers would lead to an overly complicated chapter selection, so let's avoid that.
3. I think a new parameter is a good route forward, but letting people adopt with the routeAlias approach and understanding the vocab people use for chapters could mean less hassle later.
