### ISSUE TITLE
Ability to change image's backgroundSize on `image` layout different than `cover`

### ISSUE THREAD

**Issue by alpcoker** [slidevjs/slidev#798]
While using screenshots in presentation, images with a different proportion (for example a vertical image) than the slide ratio are cropped. It is the side effect of using `backgroundSize: cover` in the [handleBackground function](https://github.com/slidevjs/slidev/blob/main/packages/client/layoutHelper.ts#L31).

**To Reproduce**

1. Go to https://stackblitz.com/edit/slidev-image-custom-size
2. The first slide is a default image layout. You can see the image is cropped compared to the latter slide.
3. The second slide is my custom solution with a custom layout. You can see all of the image.

I think some people will need to show their images without any cropping. Three options come to my mind that I would love to be involved in. 

1. Adding another layout with strict naming `image-contain`
2. Customizable layout, with a prop `image-custom-size` 
3. Adding an optional property to the existing image layout. By preserving default `cover` behavior. 

I have solved this requirement in this environment: https://stackblitz.com/edit/slidev-image-custom-size by following these;

1. Created a clone of the image layout
2. Add `backgroundSize` prop to the layout and in my slide set this as `contain`
3. Send this prop value clone of the [`handleBackground`](https://github.com/slidevjs/slidev/blob/main/packages/client/layoutHelper.ts#L12) function with an existing default parameter `cover`

If any of my proposals are suitable, I would love to open a PR.

**Comment by asm0dey** [comment]
Yes please, I need it!

**Comment by tonai** [comment]
Yes please propose a PR.

**Comment by asm0dey** [comment]
up

**Comment by alpcoker** [comment]
Hey @antfu you left an initial comment on PR: https://github.com/slidevjs/slidev/pull/862, we can discuss continuing here. I [commented](https://github.com/slidevjs/slidev/pull/862#issuecomment-1418249626) on PR but you may miss it. As it has been a long time, I wanted to make this topic reactive. 

Before discussing proposes. The first question will be; 

Do we need that feature? Seems like two other people in this issue also want that feature. If not, we can close.

**Proposes**

1. Adding `backround-size` as a prop to [`image`](https://github.com/slidevjs/slidev/blob/d240c927fed92a26dc4d37dec74feabc0ff39435/packages/client/layouts/image.vue), [`image-left`](https://github.com/slidevjs/slidev/blob/d240c927fed92a26dc4d37dec74feabc0ff39435/packages/client/layouts/image-left.vue), and [`image-right`](https://github.com/slidevjs/slidev/blob/d240c927fed92a26dc4d37dec74feabc0ff39435/packages/client/layouts/image-right.vue). 


2. Adding [`image-custom`](https://github.com/slidevjs/slidev/blob/d240c927fed92a26dc4d37dec74feabc0ff39435/packages/client/layouts/image-custom.vue) to be able to set all other image styles as well. The idea as you [commented](https://github.com/slidevjs/slidev/pull/862#issuecomment-1415261696).


3. The statically set `background-size` as `contain` with a new layout: [`image-contain`](https://github.com/slidevjs/slidev/blob/d240c927fed92a26dc4d37dec74feabc0ff39435/packages/client/layouts/image-contain.vue). Probably also, need to create new layouts as `image-contain-left`, and `image-contain-right`.

**Comment by Kehrlann** [comment]
I'd be glad to have this!

For the moment, I hack it with a CSS customization:

```css
.slidev-layout[layout="image"] {
  background-size: contain !important;
}
```

**Comment by asm0dey** [comment]
Still actual
