### ISSUE TITLE
code highlighting seems broken on slidev default example

### ISSUE THREAD

**Issue by pierreroth64** [slidevjs/slidev#799]
**Describe the bug**

When running the slidev default example, code highlighting seems broken.

**To Reproduce**

1. Run `npm init slidev`
2. Go to `http://localhost:3030/4`
3. Use Right Arrow
4. Result: broken layout (code duplicated) and no code highlighting

<img width="769" alt="Capture d’écran 2022-12-22 à 11 19 20" src="https://user-images.githubusercontent.com/4201248/209112789-e4c76ad5-2f32-476c-9317-b763fbd8747a.png">

**Desktop**

 - OS: macOS - Monterey `12.6.2`
 - Node: `v18.12.1`
 - Browser: Firefox `108.0.1` (same issue with Chrome `108.0.5359.124`)
 - Slidev version: `v0.38.2`

⚠️ **IMPORTANT**: works with version `v0.37.1` !

**Comment by twitwi** [comment]
`v0.38.1` works too.
So my best guess for the cause would be the shiki update
https://github.com/slidevjs/slidev/commit/3b79d4765310751e6e04308f79223fb74d0ea4eb#diff-4fc037dd5180dae1af9ac637aa57f5e164f0dd6119ba0da6681646cee8a1afa6R87

**Comment by twitwi** [comment]
Actually shiki has no version `v0.12.1` (the latest being `v0.12.0`)

**Comment by twitwi** [comment]
shiki has no 0.12.1 on github https://github.com/shikijs/shiki/tags
but has a 0.12.1 on npm https://www.npmjs.com/package/shiki

In anycase, both 0.12.0 and 0.12.1 are causing the problem (reverting to 0.11.1 on the latest slidev works).

**Comment by lili21** [comment]
same issue here
