### ISSUE TITLE
Export has empty final slide

### ISSUE THREAD

**Issue by alexanderdavide** [slidevjs/slidev#800]
**Describe the bug**
From [v0.36.7](https://github.com/slidevjs/slidev/releases/tag/v0.36.7) the export has an empty final slide.

**To Reproduce**
1. Install [v0.36.7](https://github.com/slidevjs/slidev/releases/tag/v0.36.7) or later
2. `npm run export` exemplary slides.md 
```md
---
theme: seriph
---

See empty final slide.
```
3. See empty final slide in pdf

**Desktop:**
 - OS: Ubuntu 22.04.1
 - Browser: Chromium Version 108.0.5359.124
 - Slidev version: v0.36.7 - v0.38.2

**Comment by anoreg** [comment]
Same issue

**Comment by tonai** [comment]
I tried to reproduce with slidev version `0.36.7` or `0.38.2` but I don't have any empty final slide in the pdf.
By using the exact same markdown you used I only have one slide in the export (I'm also on ubuntu 22.04.1).
Do you have a reproduction repository ?

**Comment by alexanderdavide** [comment]
> I tried to reproduce with slidev version `0.36.7` or `0.38.2` but I don't have any empty final slide in the pdf. By using the exact same markdown you used I only have one slide in the export (I'm also on ubuntu 22.04.1). Do you have a reproduction repository ?

Here's the [reproduction repository](https://github.com/alexanderdavide/slidev-repro-export-empty-final-slide). I've also added the PDF as slidev exports it on my system.

**Comment by tonai** [comment]
Your repository doesn't contain a `package.json` file.
That's strange.
Do you have all dependencies installed globally ?

**Comment by tonai** [comment]
Thanks for the update.
But I still can't reproduce.
I used `npm ci` to install exactly the same packages you have.
Then ran `npm run export` and got a pdf with only one page.

Maybe it can be related to some playwright browser version.
Playwright browsers are installed in `~/.cache/ms-playwright/` (for linux).
Can you check the installed version of chromium ?
(you can start the browser by launching `~/.cache/ms-playwright/chromium-1041/chrome-linux/chrome`)

**Comment by alexanderdavide** [comment]
> Maybe it can be related to some playwright browser version. Playwright browsers are installed in `~/.cache/ms-playwright/` (for linux).

This is the content of this directory on my system:

```bash
$ ls ~/.cache/ms-playwright/
chromium-1033  chromium-1041    chromium-965416  ffmpeg-1007  firefox-1304
chromium-1040  chromium-939194  ffmpeg-1006      ffmpeg-1008  webkit-1578
```

> Can you check the installed version of chromium ? (you can start the browser by launching `~/.cache/ms-playwright/chromium-1041/chrome-linux/chrome`)

It's version 109.0.5414.46 (Developer Build) (64-bit). The version stated along the issue template is my system's chromium, just to be clear.

I've assumed it could be linked to the playwright-chromium package and fiddled with its version but wasn't successful.

**Comment by tonai** [comment]
Ok that's the version associated to folder `chromium-1041`.
But I also see strange folders `chromium-939194`  and `chromium-965416`.
I was not sure the version you provided was your browser or the playwright version.
Are you sure version `109.*` is the version of chromium used by playwright durgin the export ?

**Comment by alexanderdavide** [comment]
> Ok that's the version associated to folder `chromium-1041`. But I also see strange folders `chromium-939194` and `chromium-965416`. I was not sure the version you provided was your browser or the vesion used by playwright. Are you sure version 109 is the version of chromium used by playwright durgin the export ? (My chromium is also 109)

I mean the chromium version used during the export is dependent on the playwright-chromium package, isn't it? In view of that, the version is in line with the release notes of playwright-chromium [v1.29.2](https://github.com/microsoft/playwright/releases/tag/v1.29.2) that is used in my reproduction repository (see package-lock.json).

**Comment by tonai** [comment]
Just to be sure, can you create a file `test.mjs` in your slidev project with:
```js
import { chromium } from 'playwright-chromium'
const browser = await chromium.launch({
  headless: false
})
const context = await browser.newContext()
const page = await context.newPage()
```
You can then run `node test.mjs`, it will open a chromium not in headless mode.
You can then direcly check the chromium version inside the launched browser.

**Comment by alexanderdavide** [comment]
> Just to be sure, can you create a file `test.mjs` in your slidev project with:
> 
> ```js
> import { chromium } from 'playwright-chromium'
> const browser = await chromium.launch({
>   headless: false
> })
> const context = await browser.newContext()
> const page = await context.newPage()
> ```
> 
> You can then run `node test.mjs`, it will open a chromium not in headless mode. You can then direcly check the chromium version inside the launched browser.

Thanks! I was able to confirm that it's the expected version 109.0.5414.46 (Developer Build) (64-bit).

**Comment by tonai** [comment]
I recently reproduced the case of having an empty final blank slide.
I created a PR for that: https://github.com/slidevjs/slidev/pull/879
It should be available in the next release.
Hope it will fix your issu.
