### ISSUE TITLE
How can I use "slidev" as a component to display markdown?

### ISSUE THREAD

**Issue by fjun99** [slidevjs/slidev#802]
Slidev is great. Thank you @antfu.

In the homepage of  slidev docs site, you use components of slidev components to display a dynamic demo.  And in the docs you explained how to export Single Page Applications(SPA) and self-host a slideshow.

Is there a way to use slidev as an imported component in a vue-based site to display several markdown files?

Thank you again!

**Comment by jd-solanki** [comment]
https://github.com/slidevjs/docs/blob/c32272eee9133102e2913c79e771691761502cce/.vitepress/theme/components/demo/Demo.vue

**Comment by twitwi** [comment]
@fjun99 the answer depends on what you are looking for. If it is the markdown rendering side of slidev that you are interested in, slidev uses markdown-it (there are probably vue component to directly embed markdown-it).

**Comment by fjun99** [comment]
> @fjun99 the answer depends on what you are looking for. If it is the markdown rendering side of slidev that you are interested in, I think slidev uses [markdown-it](https://github.com/markdown-it/markdown-it/) (there are probably vue component to directly embed markdown-it).

Thank you. I want to find out whether there is a way to use slidev as a component in a website to display slidev markdown slides. SPV hosting is ok but it is not enough for me.

**Comment by fjun99** [comment]
> https://github.com/slidevjs/docs/blob/c32272eee9133102e2913c79e771691761502cce/.vitepress/theme/components/demo/Demo.vue

Thanks. This code snippet in the docs is the very beginning for me  to wonder whether we can use slidev as a website component.

**Comment by tonai** [comment]
In dev mode, slidev relies on a custom vite server.
In build mode, slides are packaged into a bunch of files (html, css, js, images...).
So there no simple way to add slides using a component in an existing website.
If you want to display the slides inside a website maybe the easiest way is to use an iframe using the endpoint of your slides ?

**Comment by antfu** [comment]
I consider this not possible, as Slidev relies a lot on the build pipeline with a dev server. As @tonai mentioned, using iframe might be the best solution.

**Comment by fjun99** [comment]
> I consider this not possible, as Slidev relies a lot on the build pipeline with a dev server. As @tonai mentioned, using iframe might be the best solution.

thanks @antfu @tonai !
