### ISSUE TITLE
Home key to go to first slide

### ISSUE THREAD

**Issue by schneiderfelipe** [slidevjs/slidev#804]
**Is your feature request related to a problem? Please describe.**

I would like an easy way to go to the beginning of a presentation.

**Describe the solution you'd like**

Use the `Home` key to go to the first slide.

**Describe alternatives you've considered**

Maybe `PgUp` and `PgDn` to jump over 5 or 10 slides at a time.

**Comment by twitwi** [comment]
Hi, I use `g` then `1` and `enter`.

**Comment by schneiderfelipe** [comment]
> Hi, I use `g` then `1` and `enter`.

Great, I didn't know that! I guess the issue has been settled. Closing.
