### ISSUE TITLE
File not found in Github Pages

### ISSUE THREAD

**Issue by clong365** [slidevjs/slidev#807]
When I publish statics to Github Pages.
The file [_commonjsHelpers-725317a4.js](https://github.com/clong365/year2022/blob/gh-pages/assets/_commonjsHelpers-725317a4.js) is 404.

![image](https://user-images.githubusercontent.com/150419/210761590-4a74a0d9-1af4-4ebf-a316-e29b8b7f185e.png)

But the js file is in the repository indeed.
https://github.com/clong365/year2022/tree/gh-pages/assets

![image](https://user-images.githubusercontent.com/150419/210761664-fa372dfb-d040-4a5b-8ad3-28057df0610e.png)

**Comment by tonai** [comment]
Everything looks fine to me now
![Capture d’écran du 2023-01-09 14-40-46](https://user-images.githubusercontent.com/5246045/211321421-38bd4570-e51f-4127-b258-018a65d17a56.png)

**Comment by tonai** [comment]
I close the issue, please reopen it if this is not fixed.

**Comment by FrankieLv** [comment]
@tonai  Could you tell how to fix that?

**Comment by tonai** [comment]
@FrankieLv I didn't do anything.
I just went to the Github page URL of @clong365 repo: https://clong365.github.io/year2022/
Currently I see it is not working.
