### ISSUE TITLE
Block code are broken

### ISSUE THREAD

**Issue by tonai** [slidevjs/slidev#810]
**Describe the bug**
Block code are broken.
See picture:
![blockcode](https://user-images.githubusercontent.com/5246045/211346846-44f84e47-6712-4aab-b58f-1f70afb61863.png)
* Dark mode and light mode are both displayed
* font size is much bigger (compared to previous versions)

**To Reproduce**
Reproducible with the demo slides embedded in the repo:
1. `npm run build`
2. `npm run demo:dev`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: chrome 108.0.5359.94
 - Slidev version: 38.2

**Comment by tonai** [comment]
Introduced by the recent upgrade of `shiki` from `0.11.1` to `0.12.1`

**Comment by twitwi** [comment]
see https://github.com/slidevjs/slidev/issues/799
