### ISSUE TITLE
Hidden slide support

### ISSUE THREAD

**Issue by oripka** [slidevjs/slidev#816]
Powerpoint has the ability to hide slides. These slides are shown in the overview but not during the presentation. It is a nice feature for slide development and showing content as necessary.

I found that I can implement a layout that just doesn't render the slide but this is not exactly the same feature.

**Comment by tonai** [comment]
This can be interesting but maybe we need to define where the slide will be visible or not:
- in the presentation
- in the overview
- in presenter mode
- in the export
- anything else ?

So do we need to only have a `hidden: true` frontmatter option or maybe a more flexible solution ?

**Comment by oripka** [comment]
As a user my desired default behavior would be. If `hidden: true` is set:

in the presentation (hidden, unless explicitly opened from overview)
in the overview (visible)
in presenter mode (hidden, unless explicitly opened from overview)
in the export (hidden, with option to export them, too)

In essence i want to be able to show just the slides without `hidden: true` but I also want to be able to exlicitly open them from the overview, modify them or show them in presentation or presenter mode. Basically what powerpoint does.

My main purpose for hidden slides is to provide extra information or have some slides in there that are not yet finished. So in this case I don't want to export them. But I can totally image also cases where people might want to export the hidden slides, too.

**Comment by fjun99** [comment]
I also need this feature badly. 

There is a hide for subpages. 

`hide: true`. 

But it doesn't work for a general slide.

**Comment by fjun99** [comment]
well, I found hide feature is supported by:

`disabled: true`

**Comment by tonai** [comment]
Yes in fact the `disabled` is not taken into account by the `<Toc>` component.
This should be not be complex to fix, @fjun99 do you want to take the point ?

But it does not respond to @oripka original request, as `disabled` also remove the slide from the overview.
But maybe we can support both `disabled` for completely disabling a slide, and `hide` that will work like the powerpoint feature.
We should also document those features.

**Comment by Mokkapps** [comment]
Just a comment to stop this issue from being closed by the stale bot 😇

**Comment by oripka** [comment]
Another issue linked to this. I think it is not possible to hide entire slides from printing either. 

I currently have this component to deal with this:

```
<template>
  <div v-if="isPrintMode">
    <slot />
  </div>
</template>
<script setup>
import { isPrintMode } from "@slidev/client/logic/nav";
</script>
```

But this only allows me to show content depending on the mode but not to hide the slide entirely. My use case is that I have a slide layout for breaks that should not be in the PDF hand-out.

**Comment by yogabonito** [comment]
Is there any news on this? I'd also like to show some slides in the presentation which are excluded from the PDF export.

**Comment by oripka** [comment]
I did it using a `setup/preparser.ts` file

```
import { definePreparserSetup } from "@slidev/types";
import { red } from "kolorist";

function removeSlidesWithHidePrint(lines) {
  let markers = []; // To store indices of '---' that mark the beginning/end of slides
  let slidesToRemove = []; // To store start and end indices of slides to remove

  // Step 1: Identify all '---' markers
  lines.forEach((line, index) => {
    if (line.trim() === "---") markers.push(index);
  });

  // Step 2: Determine which slides to remove based on front matter
  for (let i = 0; i < markers.length; i += 2) {
    // Check if there's a next marker to form a front matter block
    if (i + 1 < markers.length) {
      let start = markers[i];
      let end = markers[i + 1];
      let frontMatter = lines.slice(start + 1, end);
      let hidePrintFound = frontMatter.some((line) =>
        line.replace(/\s+/g, "").toLowerCase().includes("hideprint:true")
      );
      if (hidePrintFound) {
        // If hidePrint is found, plan to remove this slide
        slidesToRemove.push({
          start: start,
          end: i + 2 < markers.length ? markers[i + 2] - 1 : lines.length - 1,
        });
      }
    }
  }

  // Step 3: Remove identified slides in reverse order to avoid index shifting
  for (let i = slidesToRemove.length - 1; i >= 0; i--) {
    const { start, end } = slidesToRemove[i];
    lines.splice(start, end - start + 1);
  }
}

export default definePreparserSetup((ar) => {
  return [
    {
      transformRawLines(lines) {
        if(ar?.mode == 'export'){
          removeSlidesWithHidePrint(lines);
        }
      },
    },
  ];
});
```

**Comment by yogabonito** [comment]
> I did it using a `setup/preparser.ts` file

That's a great idea 😃 Thank you!

**Comment by sjrothfuss** [comment]
Just a +1 to say I'd like this feature too. Similar to https://github.com/slidevjs/slidev/issues/816#issuecomment-1401905678, I'd like to hide slides in the presentation but have the show in overview and presenter view. I don't really care if they show up in printing/exporting.

My imagined use case is to create extra slides that may be useful to answer audience questions but I won't show every time.
