### ISSUE TITLE
Can't start dev server when `.md` is in a folder 

### ISSUE THREAD

**Issue by Barbapapazes** [slidevjs/slidev#817]
**Describe the bug**

When I try to start the dev server, I've got this issue.

```sh
2:35:33 PM [vite] Internal server error: EMFILE: too many open files, open 'C:\Users\***\dev\Formations\node_modules\prismjs\components\prism-pug.js'
```

**To Reproduce**
1. Create a new slidev project `npm init slidev@latest`
2. Move `slides.md` into a folder
3. Start the dev server using `slidev <folder>/slides.md`

**Desktop (please complete the following information):**
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 822.30 MB / 15.69 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.39.0.
  IDEs:
    VSCode: 1.74.3 - C:\Users\esoubiran\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\windows\system32\bash.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.76), ChromiumDev (110.0.1587.1)
    Internet Explorer: 11.0.22000.120

    "@slidev/cli": "^0.38.3",
    "@slidev/theme-default": "^0.21.2",

**Comment by tonai** [comment]
I followed your reproduction instructions and the error I got is:
```
Error: ENOENT: no such file or directory, open '[...]/pages/multiple-entries.md'
```
That's because of the file import in the `slides.md` file:
```yaml
---
src: ./pages/multiple-entries.md
hide: false
---
```
That should be updated with `../pages/multiple-entries.md`.
Then everything works as expected.

Note that I'm not on windows.
