### ISSUE TITLE
Inline code elements have extra backticks in generated slides

### ISSUE THREAD

**Issue by neilmispelaar** [slidevjs/slidev#818]
**Describe the bug**

When denoting inline code in markdown, or the `<code>` elements, Sli.dev is adding in backticks to the generated slide content. 

**To Reproduce**
1. Create a presentation
2. Add the following content to a slide (including the backticks) as if you were marking up inline code:  \`some inline code content\`
3. Alternatively you can also use the `<code>` element: Here is some `<code>inline code</code>` content
4. Run `npm run dev` to run your slide show 
5. View the page and you'll notice something like the following. Note the backticks in the code block.

<img width="815" alt="Screenshot 2023-01-11 at 3 57 14 PM" src="https://user-images.githubusercontent.com/9325038/211916208-32770642-7f3d-4966-9660-e3a0259bb442.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox 
 - Slidev version: v0.38.3

**Comment by twitwi** [comment]
I think it is part of the theme, you can disable this behavior by adding the following in a file named `style.css`

```css
:not(pre) > code::before, :not(pre) > code::after {
	content: "";
}
```

**Comment by neilmispelaar** [comment]
@twitwi Thank you kindly for the reply. Much appreciate the fix. 

I'm wondering - is that the intended behaviour (to have the backticks)? If it's not I can try to put together a PR for the default theme to remove them.

**Comment by tonai** [comment]
This is an intended behaviour of the seriph theme you probably use: https://github.com/slidevjs/themes/blob/main/packages/theme-seriph/styles/prism.css

You can use another theme (some are listed here https://sli.dev/themes/gallery.html) or just use the fix @twitwi gave to you

**Comment by neilmispelaar** [comment]
Thank you so much everyone for the comments and feedback - I realize that this issue is in the wrong place (it would better be logged in the theme documentation). 

I'm going to close this and recreate an issue or PR in the actual repo that is housing the themes.

In my opinion, I don't believe the backticks should be there. If we look at GitHub / GitLab and a bunch of other sites that use markdown, no one puts the backticks in when displaying the in-line code blocks.

## Example 

`this is a inline code block with no ticks`
