### ISSUE TITLE
mchem katex plugin

### ISSUE THREAD

**Issue by 0187773933** [slidevjs/slidev#82]
https://mhchem.github.io/MathJax-mhchem/

https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/README.md

**Comment by antfu** [comment]
Probably will not make it built-in, but will expose the setup to make it configurable on user-side

**Comment by antfu** [comment]
See https://sli.dev/custom/config-katex.html

**Comment by schneiderfelipe** [comment]
Old topic, but it took me a while to figure this out, so other people might have the same issue.

It worked for me by creating a dummy `./setup/katex.ts` that loads `katex/contrib/mhchem`:

```typescript
import "katex/contrib/mhchem";
import { defineKatexSetup } from "@slidev/types";

export default defineKatexSetup(() => {});
```
