### ISSUE TITLE
How to create first webpage (documentation enhancement)

### ISSUE THREAD

**Issue by epogrebnyak** [slidevjs/slidev#823]
**Is your feature request related to a problem? Please describe.**

No clear path to first page creation. The Getting started section ends with project init.

Consider a specific command stated in  marp documentation:

```
# Convert slide deck into HTML
npx @marp-team/marp-cli@latest slide-deck.md
npx @marp-team/marp-cli@latest slide-deck.md -o output.html
```

What is the similar command for slidev? No clue in starter page of docs, unfortunately.

**Describe the solution you'd like**

In https://sli.dev/guide/#command-line-interface describe specific commands needed to render a markdown file.

**Describe alternatives you've considered**

- Looking at [SPA part of documentation](https://sli.dev/guide/hosting.html).
- Playing which combinations of `npm` / `npx` work.
- Finding out why `slidev` not on path.
- Looking how other similar packages work (eg marp, fusuma)

**Comment by tonai** [comment]
Mayeb are you looking for this: https://sli.dev/guide/install.html#command-line-interface-cli ?
