### ISSUE TITLE
Background in center layout not shown

### ISSUE THREAD

**Issue by AckslD** [slidevjs/slidev#828]
**Describe the bug**
I'm starting to learn how to use `slidev` and am following the [guide](https://sli.dev/guide/syntax.html#front-matter-layouts). For some reason the background image is not show using the `center` layout as the example shows, ie if I do:
```markdown
---
layout: center
background: '/background.png'
class: 'text-white'
---
```

However both:
```markdown
---
layout: image
image: '/background.png'
class: 'text-white'
---
```
and
```markdown
---
layout: cover
background: '/background.png'
class: 'text-white'
---
```
work.

**To Reproduce**
See above.

**Desktop (please complete the following information):**
 - OS: arch-linux
 - Browser: Firefox
 - Slidev version: 0.38.3

**Comment by tonai** [comment]
In fact the `center` layout does not accept an image as parameter.

**Comment by AckslD** [comment]
@tonai, does it accept a `background`?

**Comment by AckslD** [comment]
I see, thank you for explaining!
