### ISSUE TITLE
Layout is broken when using Monaco Editor

### ISSUE THREAD

**Issue by watagit** [slidevjs/slidev#83]
Hi 👋 
Layout is broken when I use Monaco Editor.
Is this bug?

![Kapture 2021-05-12 at 17 49 57](https://user-images.githubusercontent.com/44804976/117947709-6e564a00-b34b-11eb-91c1-2744c2e655ea.gif)

### Environment
- OS: macOS Catalina ver. 10.15.7
- Browser: Chrome

**Comment by antfu** [comment]
As noted https://sli.dev/custom/config-monaco.html, Monaco does not aware of the scale at this moment, will need to find a solution for that later.
