### ISSUE TITLE
Nested lists on right-to-left languages are broken

### ISSUE THREAD

**Issue by aligit** [slidevjs/slidev#834]
**Nesting in lists does not work when dir is right-to-left**
As I speak in Arabic I need to change the direction of the text. The exact same markdown snippet is correctly rendered on [github](https://github.com/aligit/testrtlinmd).

**To Reproduce**
1. Add the following to presentation 
```markdown
<div dir="rtl">
```
3. Create an unordered list of elements as follow:
```markdown
* مقدمه
* معرفی
  * معرفی ۱
  * معفرفی ۲
* نتیجه‌گيری
```
4. You will see that elements 3 and 4 are not nested and they all appear in the same level as other elements.
![56e26bf8-8865-4527-8908-7c1ddee894ac](https://user-images.githubusercontent.com/342484/213261251-1c46fdfe-1bf7-419c-b288-561b6cd744f0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome, Firefox
 - Slidev version: v0.38.3

**Comment by tonai** [comment]
Fixed here https://github.com/slidevjs/slidev/pull/835

For info you can also put the `dir` attribute in the frontmatter (instead of creating a new div):

```md
---
dir: rtl
---
```
