### ISSUE TITLE
Relative reference in Link component

### ISSUE THREAD

**Issue by AleCandido** [slidevjs/slidev#848]
**Is your feature request related to a problem? Please describe.**
While editing the presentation, it is frequent to add slides in the middle, breaking all the links pointing after the inserted slide.

**Describe the solution you'd like**
Just add an alternative syntax with `+x`/`-y` - it won't solve completely the problem, but it might alleviate it  (only links *traversing* the inserted slide would be broken, not all those after the slide).

**Describe alternatives you've considered**
An ideal solution would be to have cross-reference markers, such that I can set the link to point to a certain slide, irrespective of its marker (but I expect the proposed solution to be much simpler to implement).

**Comment by sosensible** [comment]
Could we create slide anchors? Similar to the idea of HTML anchor tags. Then we could target an anchor location in the slide show, and changes to the number and location of pages would not break the links.

**Comment by AleCandido** [comment]
> Could we create slide anchors? Similar to the idea of HTML anchor tags.

This is exactly what I called *cross-reference markers* above (I guess because I have Latex in mind, rather than HTML, but the concept is that one)

**Comment by tonai** [comment]
Maybe this can be related to this PR: https://github.com/slidevjs/slidev/pull/833
By giving a route an alias it would be easy to create a link to that alias.
In fact you can probably already try to use the `routeAlias` parameter because it is already implemented in the routing.

**Comment by tonai** [comment]
I just try and I confirm that you can create a `routeAlias` for a slide in the frontMatter and then use that alias with the `Link` component:
```jsx
<Link to="myAlias">Go to slide with "routeAlias: myAlias"</Link>
```
Maybe this can answer to your need ?

**Comment by AleCandido** [comment]
> Maybe this can answer to your need ?

I believe so! Thank you very much :D

I haven't tried myself, but in case there will be any problem, I will reopen the issue, or open another more specific one.
