### ISSUE TITLE
VSCode - format slides.md - break the build

### ISSUE THREAD

**Issue by deleonio** [slidevjs/slidev#854]
**Describe the bug**
If I format the markdown file - the build break.

**before**
```md
---
layout: center-layout
---
```

**after** formatting
```md
---

## layout: center-layout
```

**To Reproduce**
1. Run the `dev`
1. Go to `slides.md`
2. Make some slides with different layouts
3. Format the Markdown file `slides.md`
4. See the error

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Slidev version: 0.39

**Comment by joe733** [comment]
This happens if you're using either [`Markdownlint`](https://github.com/DavidAnson/vscode-markdownlint) or [`Prettier`](https://github.com/prettier/prettier-vscode) as formatter. If you use [`MarkdownAllInOne`](https://github.com/yzhang-gh/vscode-markdown) instead, that particular change does not happen.

Not so cool suggestion: Adding a formatter to [`slidev-vscode`](https://github.com/slidevjs/slidev-vscode)

**Comment by maxandron** [comment]
A cool suggestion would be to add a prettier parser :D

**Comment by emersonbottero** [comment]
I just add an the prettier config file in the root disabling it for .md

**Comment by wycats** [comment]
I think this should be reopened. It's probably my biggest pain point with slidev atm.

**Comment by jakebailey** [comment]
I've so far gotten through this with `<!-- prettier-ignore-start -->` or `<!-- dprint-ignore-start -->`, like:

```
<!-- prettier-ignore-start -->

---
layout: fact
---

<!-- prettier-ignore-end -->
```

But, another way to do this would be great.

**Comment by maxandron** [comment]
@jakebailey this is very cool! I didn't know this option existed. Thanks!

Now creating a workaround is quite simple: <https://gist.github.com/maxandron/ce7ca54f2e808dadd209e34ebe751f92>

**Comment by jakebailey** [comment]
That works for those who only run prettier separately; I format in my editor, so, I think an alternative way to write these blocks would be still great.

Maybe:

```md

---
title: the first one is okay
---

# Blah

---

<v-config>
layout: fact
</v-config>

# This is a fact!

```

Or something. Unfortunate that this repo uses the stale bot, though; this is the second filing of this 😢

**Comment by CodyBontecou** [comment]
> This happens if you're using either [`Markdownlint`](https://github.com/DavidAnson/vscode-markdownlint) or [`Prettier`](https://github.com/prettier/prettier-vscode) as formatter. If you use [`MarkdownAllInOne`](https://github.com/yzhang-gh/vscode-markdown) instead, that particular change does not happen.
> 
> Not so cool suggestion: Adding a formatter to [`slidev-vscode`](https://github.com/slidevjs/slidev-vscode)

@joe733 I switched over to MarkdownAllInOne but am not getting any formatting on save.

**Comment by joe733** [comment]
@CodyBontecou `Format-on-save` is a VSCode feature. https://code.visualstudio.com/updates/v1_6#_format-on-save

**Comment by naramdash** [comment]
my suggestion is using `.prettierignore` that content below

```
**/*.md
```

**Comment by antfu** [comment]
I think it might be worth having a custom, prettier plugin/parser. As I don't have much knowledge about Prettier (nor really using it), I might not have enough incentive to work on it very soon. Would appreciate if someone is interested in giving it a try

**Comment by antfu** [comment]
Meanwhile https://github.com/slidevjs/slidev/pull/1186 might be a good solution that works today

**Comment by jakebailey** [comment]
I'm an idiot; I ran `pnpm update` and thought it updated, but since it was in a `0.x` bump it didn't automatically do it. Now on the latest version it works great!

(So, IMO this can be closed; sorry I didn't notice that PR.)

**Comment by antfu** [comment]
Created https://github.com/slidevjs/slidev/issues/1261 to track on Prettier
