### ISSUE TITLE
Changing the theme in defineMermaidSetup doesn't apply anything

### ISSUE THREAD

**Issue by estruyf** [slidevjs/slidev#857]
**Describe the bug**

Following the steps on the Mermaid configuration (https://sli.dev/custom/config-mermaid.html) to define the default settings doesn't change anything to my output.

My diagram looks as follows:

![image](https://user-images.githubusercontent.com/2900833/216049984-1bb9ad19-bfa7-4660-b449-2727661b42c7.png)

It contains the following contents:

~~~md
//```mermaid
sequenceDiagram
  participant A as Extension Host
  participant B as Webview

  A->>B: Send message to webview

  Note over A,B: Webview listens and reacts to messages

  B->>A: Send message to extension host

  Note over A,B: Extension Host listens and reacts to messages
//```
~~~

I wanted to use another theme, but no matter what I define in my `.setup/mermaid.ts` file, it doesn't get applied.

> Also tried to create a custom theme, but this was the same experience.

Is there anything I do wrong?

**To Reproduce**

1. Go to [mermaid config doc](https://sli.dev/custom/config-mermaid.html)
2. Create the `mermaid.ts` file
3. Add the contents from the doc
4. Start `npm run dev`
5. Check the diagram, the outcome is still the same as before

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: Microsoft Edge / Chrome
 - Slidev version: `0.39.0`

**Comment by estruyf** [comment]
Got it to work for custom theming:

![image](https://user-images.githubusercontent.com/2900833/216058448-e82dcf97-2494-4954-8a91-77941f48121a.png)

For applying default mermaid themes, the `theme` property seems to be ignored.

**Comment by MetRonnie** [comment]
I have this problem on Chromium (but not Firefox interestingly). The config is not applied, unless you hit save on the `./setup/mermaid.ts` file _after_ starting the slidev server.

I was able to get around it by specifying the config for each mermaid chart:
````md
```mermaid
---
config:
  theme: 'base'
  fontFamily: 'JetBrains Mono'
---
gitGraph
  commit
  commit
```
````
