### ISSUE TITLE
local images don't render in presenter mode

### ISSUE THREAD

**Issue by dlleigh** [slidevjs/slidev#859]
**Describe the bug**
When using presenter mode, local images appear as broken links

**To Reproduce**
1. Put an image file (e.g. "image.png") in the same directory as slides.md
2. Include the image in a slide (e.g. `<img src="image.png">`)
3. In a browser, go to the slide in presentation mode
4. The image will appear as "unavailable".  
5. The url for the broken image will be:  `http://localhost:3030/presenter/image.png`

Note that `http://localhost:3030/image.png` will display the image but `http://localhost:3030/presenter/image.png` displays the alt text *The image “http://localhost:3030/presenter/image.png” cannot be displayed because it contains errors.*

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser:  firefox, safari, and chrome
 - Slidev version: 0.38.8

**Comment by antfu** [comment]
You have to use absolute path for your assets unfortunately: https://sli.dev/guide/syntax.html#static-assets

**Comment by poqudrof** [comment]
Hello,  sorry to bump into a closed comment.  

Here is the fix I did : 

``` bash 
$ cd public 
$ mkdir presenter 
$ cd presenter/
$ln -s ../../images/ . 
``` 

You can do more or less the same for public assets. 
Cheers, 
Jeremy.
