### ISSUE TITLE
Make an element present only at some clicks

### ISSUE THREAD

**Issue by yannham** [slidevjs/slidev#860]
Hi!

I'm trying Slidev for my next talks, and first of all, it's working quite well, so thank to the team for their contribution.

**Is your feature request related to a problem? Please describe.**
I usually use beamer, and something that I found myself doing a lot, was to make an element appear _only_ at some clicks. For example, between frames 2 and 4.

It's very useful when most of your slide layout doesn't change (a column with an image on the left, the title, some bottom notes), and you want that to be fix, but you just need to change the examples inside. In some sense, this feature allows to define a "local" layout for your slide and just change parts of it at each click.

Another usage is when you want an element to have a specific style or the like only for some clicks, although I suspect you can achieve that in CSS using the class `.slidev-vclick-target` and cos.

**Describe the solution you'd like**
Something like `v-click`, `v-click-hide`, or `v-after`, but to specify a range (or even a set, but usually a range is what I need in practice) of frames at which I want the element to be present. For example, `<div v-click-only-between="2-3"> content </div>`. The element should be _removed_ from the DOM after, not just hidden (or at least provide an option to customize that).

**Describe alternatives you've considered**

The first alternative is simply to copy the whole page and just change part of it.  But it leads to a lot of duplication, which its lot of issues (If I made a typo in the non-moving parts, I need to substitute in like 5 places instead of one, things can be inconsistent, etc.).

In simple cases, we can use `v-click` in conjunction with `v-hide` to achieve something that looks like it could work, but it doesn't, because `v-hide` doesn't remove the element, it just hides it, meaning that it still taking up space.

Or is there a way to achieve this currently? I couldn't find any through the manual or examples.

**Comment by antfu** [comment]
You can use:

```md
---
clicks: 6 // total clicks on this page
---

<div v-show="$slidev.nav.clicks < 4">
  Content show before 4 clicks
</div>
```

**Comment by yannham** [comment]
I'll try that solution, thanks @antfu ! That being said, it only covers the pattern hide after a number of clicks. If I want to do it for a specific range, I guess I have to do something like:

```html
<div v-if="$slidev.nav.clicks > 1 && $slidev.nav.clicks < 4">
  Content show before 4 clicks
</div>
```

Though if this workaround works, it's a bit cumbersome (have to write lower-level vuejs code, specify the number of clicks by hand, etc.). I feel like this issue can stay open, until there is a proposal to provide a better integrated way, or if maintainers declare won't fix/not interested :slightly_smiling_face:.

**Comment by sosensible** [comment]
A simple solution. This isn't in there yet, but seems approachable within the current syntax.

`
<div v-click="2" v-click-hide="4">
  Content shown on click 2, hidden on click 4.
</div>
`

**Comment by flolbr** [comment]
I made a custom component, which I named `ShowHide` to solve this issue, to be added in the `/components`directory of your slide:

```vue
<script setup lang="ts">
import {inject, ref, onMounted} from "vue";
import { injectionClicks, injectionClicksElements } from '@slidev/client/constants.ts'
import { parseRangeString } from '@slidev/parser/core'

const props = defineProps<{
  on: string
}>()

const clicks = inject(injectionClicks)
const elements = inject(injectionClicksElements)
const totalClicks = ref(elements.value.length)
const ranges = ref(parseRangeString(totalClicks, props.on))

onMounted(() => {
  console.log('mounted')
  totalClicks.value = elements.value.length
  ranges.value = parseRangeString(totalClicks.value, props.on)
})
const show = () => (ranges.value.indexOf(clicks.value) !== -1)

// Add this to the template for debugging: {{ clicks }} / {{ totalClicks }} in {{ ranges }} => {{ show() }}

</script>

<template>
  <div v-if="show()">
    <slot/>
  </div>
</template>

```

Usage example:
```vue
<ShowHide on="2-3,5">
test
</ShowHide>
```
So far it seems to work well

**Comment by yannham** [comment]
Thanks a lot @flolbr! I'll try that out :slightly_smiling_face:

**Comment by flolbr** [comment]
I just made some changes that allow for more flexibility by using the `slidev-vclick-***` classes instead:

```vuejs
```
