### ISSUE TITLE
Hot relading breaks `v-clicks` CSS classes

### ISSUE THREAD

**Issue by TimJentzsch** [slidevjs/slidev#863]
**Describe the bug**

When hot-reloading a slide with a `<v-clicks>` component, the `.slidev-vclick-current` class breaks, instead `.slidev-vclick-prior` is used until you reload the page manually.

For some slides I am setting `display: none` for `.slidev-vclick-prior` to switch between different animation states (useful for LaTeX animations until #266 is implemented), so this bug means that I can't see the changes after hot reloading, because everything inside `v-clicks` is invisible until I reload the page manually. Especially when debugging errors in LaTeX formulas this can limit productivity.

**To Reproduce**

1. Create a slide with this content:

```html
<style>
  .slidev-vclick-prior {
    color: lightblue;
  }

  .slidev-vclick-current {
    color: lightgreen;
  }
</style>

<v-clicks>

1. One
2. Two
3. Three

</v-clicks>
```

3. Launch it with `npx slidev` and navigate to <http://localhost:3030/1?clicks=2> (i.e. 2 clicks in).
4. Observe that item 1 is blue, item 2 is green and item 3 is hidden.
5. Using the inspect tools of your browser, observe that item 1 has class `slidev-vclick-prior` and item 2 has class `slidev-vclick-current`.
6. Apply a change to the slide, e.g. changing "Three" to "Thre" to trigger hot reloading.
7. Observe that both item 1 and 2 are blue.
8. Using the inspect tools of your browser, observe that item 1 and 2 have class `slidev-vclick-prior`.
9. Refresh the page.
10. Observe that the intended result (step 4 and 5) is visible again.
11. Change the style of `.slidev-vclick-prior` to `visibility: hidden;`.
12. Trigger hot reloading again.
13. Observe that you can't see anything anymore, because of the incorrectly applied CSS class.

**Desktop (please complete the following information):**

 - OS: Linux (Pop!_OS)
 - Browser: Firefox 109.0 (64-bit)
 - Slidev version: `@slidev/cli": "^0.39"`

**Comment by MountNoperest** [comment]
Even if this is a bug, your code helped me make slidev do what I wanted for the most part. Thank you very much!

**Comment by TimJentzsch** [comment]
I can still reproduce the issue with `slidev@0.40`.

**Comment by TimJentzsch** [comment]
To my knowledge, this issue still exists.
