### ISSUE TITLE
Licensing of files generated by `npm init slidev` is unclear

### ISSUE THREAD

**Issue by pbrkr** [slidevjs/slidev#864]
**Describe the bug**
Running `npm init slidev` as described in the [Getting Started](https://sli.dev/guide/#scaffolding-your-first-presentation) documentation page results in a directory of files. Some of these ppear to be autogenerated based on the project name I gave (e.g. `package.json`) whereas others seem to have been copied in without modification (`components/Counter.vue` and the initial contents of `slides.dev`). However, none of these files contain any licensing information.

Taking a look around I can see the template in https://github.com/slidevjs/slidev/blob/main/packages/create-app/template/ so I would assume that the copyright notice and license are equal to those for slidev itself (i.e. https://github.com/slidevjs/slidev/blob/main/LICENSE). If so, this should be clearly specified and a copy of the MIT license should be included in the generated output when I run `npm init slidev`.

A good way to resolve this issue would be to bring slidev in line with the [REUSE specification](https://reuse.software/) so that every file in the repository has the copyright notice and license clearly identified.

**To Reproduce**
1. Run `npm init slidev`

**Comment by antfu** [comment]
Sorry I lost it in the sea of notifications.

Actually, I don't know how to say it's public code that is unlicensed (should I put a LICENSE to say you are free to use any license you want? But that feels weird as well). But anyway if it's not some strictly legal concern, hereby you have my word that you can do whatever you want with the code generated by `npm init slidev`.

**Comment by neo-franklin-tina** [comment]
> Sorry I lost it in the sea of notifications.
> 
> Actually, I don't know how to say it's unlicensed (should I put a LICENSE to say you are free to use any license you want? But that feels weird as well). But anyway if it's not some strictly legal concern, hereby you have my word that you can do whatever you want with the code generated by `npm init slidev`.

You're too kind, Anthony ☺️
