### ISSUE TITLE
Multi-line html/xml markdown code block does not syntax highlight (PrismJS)

### ISSUE THREAD

**Issue by duckness** [slidevjs/slidev#866]
**Describe the bug**
Using the default Prism code highlighter, making a code block with multi-line html/xml does not syntax highlight correctly even though it appears to be supported on Prism's website.

![chrome_w3ZPdOi6HX](https://user-images.githubusercontent.com/6380270/217146408-630ec614-31dc-47d4-9dff-3c99ceb4bb26.png)

**To Reproduce**
1. create any slide with the following code:
````md
# test

```html
<p class="hey">Type some code here</p>
<p 
class="hey">Type some code here</p>
```
````
2. notice that the class attribute and opening tag isn't highlighted in line 2 & 3.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Slidev version: 0.40.2

**Comment by AlbertBrand** [comment]
I've created a fix for this: https://github.com/slidevjs/slidev/pull/1029
