### ISSUE TITLE
Empty presentation after build

### ISSUE THREAD

**Issue by Guray00** [slidevjs/slidev#869]
**Describe the bug**
I'm on slidev 0.40.2 on Windows11, when i run `npm run build` with any project (even the default one) it successfully creates the dist folder but the index.html file doesn't contain any slide. If i open the index with a web browser (or xxamp) it only shows a blank page.

**To Reproduce**
1. Run `npm run build`
2. open `index.html`
3. now you see a blank  presentation

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave, Chrome
 - Slidev version: 0.40.2

**Comment by Marienkos** [comment]
I have the same error, I'm on slidev 0.40.2 on Enveavour OS.

**Comment by tonai** [comment]
Also confirmed on Ubuntu 22.04

**Comment by Guray00** [comment]
You are right, sorry for the stupid question, but how can we self host it? Is apache2 not enough?

**Comment by tonai** [comment]
Apache will work but you probably need to configure it for a single page application.

**Comment by tonai** [comment]
Doc updated: https://sli.dev/guide/hosting.html#build-single-page-applications-spa
