### ISSUE TITLE
root dark mode class only shows in dark mode

### ISSUE THREAD

**Issue by nico-bachner** [slidevjs/slidev#87]
In the base <html> element, there is a class that should be toggled: `class="light"` | `class="dark"`. 

However, what currently happens is: `class` | `class="dark"`. Essentially, the "light" class is not assigned.

I looked through the source code and it may be possible that this is a Vue issue, not a Slidev one, but I wanted to put this out there just in case.

**Comment by antfu** [comment]
What are you trying to achieve? This is the expected behavior for Tailwind/WinidCSS.

**Comment by nico-bachner** [comment]
Oh I see.

What I was doing was to define variables under `.light{}` and `.dark{}`, respectively.

Right now I'm using a workaround that I declare the variables in the `:root{}` and then overwrite them in `.dark{}`, which works, but is less elegant and could more easily lead to missing a variable.
