### ISSUE TITLE
Auto slide transition after timeout

### ISSUE THREAD

**Issue by jiaxincao** [slidevjs/slidev#888]
**Is your feature request related to a problem? Please describe.**
I'd like to convert slidev slides into videos, and I don't prefer to manually switch each pages.

**Describe the solution you'd like**
Support a timeout for v-click, e.g., `<div v-click timeout="5s">Hello</div>`

**Describe alternatives you've considered**
An alternative solution that I could think of is to use a js timer and whenever the timer times out, send a click to the page.

**Comment by tonai** [comment]
Adding `timeout` to `v-click` can be a solution to trigger the display of an hidden item inside a slide.
But it won't work for navigation between slides.

**Comment by jiaxincao** [comment]
Right. Could there be a solution that can apply to all cases?

**Comment by tonai** [comment]
For slide transition we could maybe have a `timeout` settings in the frontmatter of the slide:
```yaml
---
timeout: 5000
---
The next slide will automatically be displayed in 5s
```

**Comment by sosensible** [comment]
I would like to have audio that played in the background. Pre-recorded presentation.
