### ISSUE TITLE
documentation: how to extend slidev with addons and add custom transformers

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [slidevjs/slidev#892]
**Describe the bug**

It is unclear to me, how and if slidev can be extendend and add custom transformers. Looking at the example addons I can see that I can add custom components via addons.
What I want is add a custom transformer, so that I can add another block type (like mermaid, plantuml etc.,).

**To Reproduce**
Looking through the documentation, I find the addon section. It tells me, what addons can do. Transformers are not part of it, so I am unsure if there is any way of doing this.

**Desktop (please complete the following information):**
 - OS: Linux (Pop-OS)
 - Browser: brave
 - Slidev version: 0.40.3

**Comment by tonai** [comment]
You are right, this not stated in the documentation but you should provide a `vite.config.ts` file in an addon you can use to extend the vite configuration and add transformers.
Check how to customize vite here: https://sli.dev/custom/config-vite.html
