### ISSUE TITLE
Background image in style might not be loaded in dev mode

### ISSUE THREAD

**Issue by jgosmann** [slidevjs/slidev#894]
**Describe the bug**
When importing an image in a Vue component and setting it as background image in CSS via a `style` attribute, it might not be loaded in dev mode.

**To Reproduce**
The bug seems to be somewhat timing dependent and might not always be reliably reproducible. But I did manage to put together a quite minimal repository that allows me to reproduce the bug reliably: jgosmann/slidev-img-load-bug-reproducer

You should be able to observe the bug if you follow these steps:

1. Checkout the repository
2. Run `npm install`
3. Run `npm run dev`
4. Flip through the slides quickly until you reach the last slide before the "END" slide. For me it shows a blank slide instead of loading the "B" image.

Note that the intermediate slides are somehow relevant. If I remove them, I cannot reproduce the bug. If I use less, the bug becomes less reliable to reproduce. In fact, it seems to be related to timing: if I flip quickly through the slides, it still reproduces, but if I do it more slowly, the bug disappear.

Also note, that reloading the "B" slide will load the image. But then flipping back to the "A" slide that image will be missing. 

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browsers:
   - Firefox 110.0
   - Chrome 110.0.5481.100
 - Slidev version:
    - Earliest Slidev version reproducing the bug: **0.40.1**
    - Also reproduces with the latest Slidev version which is **0.40.3** at time of writing
    - Does **not** seem to reproduce with Slidev version 0.40.1
    - Only occurs in dev mode. Building a static version and using that is fine.
    - Only occurs with windicss (does not occur with unocss)

**Some further comments**
I looked through the changes between Slide 0.40.0 and 0.40.1 which aren't very many. I can only imagine ee634caabbe36fc9e2fc44419c933f3a0717806d being the cause, though it is not clear to me how. (Neither, it is clear why those plugins where moved to the end to me.) Or maybe it is some weird timing issue that already existed before, but was surfaced through the other change?

It is also somewhat weird that the style is properly applied, when checking in the dev tools. But the browser says it couldn't load the image. However, when clicking the URL it just loads fine. In the network tab, one can see the request (among others) as "pending".

![image](https://user-images.githubusercontent.com/850157/221254471-97932573-8a47-4698-84b3-a6b1730a44a7.png)

**Comment by jgosmann** [comment]
I also made a screen recording:
https://user-images.githubusercontent.com/850157/221255371-33f3117e-9b8a-4c86-841f-780a4a7a47e7.mov

**Comment by christian-nils** [comment]
I experience the same issue with my custom theme. For now, I am using v0.40.0 where I do not encounter this issue.

**Comment by jgosmann** [comment]
I can confirm that this seems to be fixed for me in the latest version (v0.40.16). :)
