### ISSUE TITLE
Presenter Mode not Syncing with Play Mode Instances

### ISSUE THREAD

**Issue by samkasbawala** [slidevjs/slidev#897]
**Describe the bug**
The presenter view seems to not be updating the other instances of the same presentation. I have also had some occurrences where the presenter mode version of the slides is not displaying the correct UI. In that I still have the option to record my screen and that there is no option to witch back to play mode. For what ever reason, when I test the demo slidev slides, everything seems to work, but I highly doubt it's user error since the slide content should not be affecting the UI.

**To Reproduce**

I created a really basic `slides.md` document:
```markdown
---
theme: default
---

# This is a test

---

# This is a second slide

Here is some content

---

# Here is a third slide

Here is some more content on the third slide
```

When I start the slidev server and open the slides in presenter view and have play mode next to it. Navigating through the slides in presenter mode doesn't sync with what's on play mode.

![image](https://user-images.githubusercontent.com/65199913/222921025-17bf44ba-77ec-463b-868f-bdc2dc0fabd3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Slidev version: 0.40.3

**Comment by samkasbawala** [comment]
Here is an example of being in presenter mode in another project. You can see that the option to enter presenter mode is still there, despite already being in presenter mode, with no option to return to play mode.

![image](https://user-images.githubusercontent.com/65199913/222921632-f9c29680-3c11-4f6a-8cab-d9eaab4993f7.png)

**Comment by MMMikeM** [comment]
I'm experiencing the same thing. Remote presenter works a little better but still dies

**Comment by tonai** [comment]
Does it work when you switch to unocss ?
You can switch from windi to unocss by adding in the frontmatter block of the first slide:
```
---
css: unocss
---
```

**Comment by samkasbawala** [comment]
yeah, seems like presenter mode worked when I switched to unocss.

**Comment by Raniz85** [comment]
I've got the same issue and I'm using unocss already.

The cursor shows up in both windows but navigation and drawings doesn't transfer.


https://user-images.githubusercontent.com/4972103/223632604-45a3e5eb-2531-4f30-9d9f-593988431915.mp4

**Comment by Raniz85** [comment]
Here's another video showing the console displaying incoming  cursor movements but nothing when I change slides.


https://user-images.githubusercontent.com/4972103/223633270-e81ef8ec-7d98-4194-8f97-3c9c95512930.mp4

**Comment by tonai** [comment]
@Raniz85 is it possible you share your project for reproduction ?

**Comment by oliver-sanders** [comment]
> is it possible you share your project for reproduction ?

I can replicate the issue with this example:

```md
foo

---

bar

---

baz

---

pub

---

qux
```

It's an intermittent problem, it usually breaks within a few slides but can sometimes last longer. Here are some screenshots showing an example communication breakdown.

**Presenter Tab**

(the outgoing messages continue, but the incoming messages stop)

<img width="725" alt="Screenshot 2023-03-14 at 09 54 21" src="https://user-images.githubusercontent.com/16705946/224964081-4bcb321d-c389-439c-b0a2-58394dc79089.png">

<img width="858" alt="Screenshot 2023-03-14 at 09 55 03" src="https://user-images.githubusercontent.com/16705946/224964105-dd024e16-db5a-4280-a8dc-7f9393a4fa96.png">

**Live Slides Tab**

(the incoming messages stop)

<img width="725" alt="Screenshot 2023-03-14 at 09 54 10" src="https://user-images.githubusercontent.com/16705946/224964156-78b5c4f9-8caa-495c-a20c-c840265070da.png">

<img width="858" alt="Screenshot 2023-03-14 at 09 54 49" src="https://user-images.githubusercontent.com/16705946/224964179-692714a6-090f-4d33-b9e2-69d6f8c21090.png">

**Comment by tonai** [comment]
@oliver-sanders That's also what I have when using Windi CSS (the default), but I do not have the problem anymore when switching to unocss.

I think you shouldn't have the problem anymore whyen adding at the top of your `slides.md` file:
```yaml
---
css: unocss
---
```

But @Raniz85 seems to still have the problem with unocss and I can't reproduce that specific scenario.

**Comment by oliver-sanders** [comment]
I tried the unocss suggestion, however, it didn't make any difference.

Note, this issue only occurs in development mode (i.e. `slidev`), it works fine for me for static builds (i.e. `slidev build`). From poking through GitHub it looks like different methods are used for synchronisation between these modes.

Is there any debugging I can perform on the server to help identify the problem? I've tried running the server with `--log=info`.

**Comment by tonai** [comment]
Ok it's strange that I can't reproduce the behavior with unocss.
In fact the source of the problem comes from vite-plugin-vue-server-ref and I already made a PR that has been merged: https://github.com/antfu/vite-plugin-vue-server-ref/pull/3
I propose we wait the next slidev release and check if this problem is solved for both windicss and unocss.

**Comment by Raniz85** [comment]
I've upgraded to 0.40.3 and haven't had any issues since.
