### ISSUE TITLE
SVG text size out of order

### ISSUE THREAD

**Issue by AnnyTerfect** [slidevjs/slidev#906]
**Describe the bug**
When I use SVG text in the slide, the text size is out of order.

**To Reproduce**
1. Insert an SVG with text in one page.
2. Refresh the page.
3. The text is extremely large.
4. After switching to another page and then back, the text size is normal.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome
 - Slidev version: 0.40.3

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by AnnyTerfect** [comment]
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Apologies for the inconvenience. Here are the detailed steps to reproduce the issue:

1. Create a new slidev project using the command:
```
slidev
```
2.  Edit <code>slides.md</code> file as shown below:
```markdown
---

# Cover

---

# Page

<svg style="background: black">
        <text dominant-baseline="hanging" fill="white">Text</text>
</svg>
```
3. Open the second slide directly in Chrome (i.e., without going from the first slide to the second) by visiting http://localhost:3030/2. You will notice that the text size is extremely large.
4. If you go back to the first slide and then switch to the second slide again, the text size returns to normal.

This bug appears to occur in Chrome, but Safari appears to work correctly.

Please let me know if you need any further assistance.

**Comment by AnnyTerfect** [comment]
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

It seems that I do not have permission to reopen the issue. May I ask if you can see my reply?

**Comment by tonai** [comment]
@AnnyTerfect  what do you mean with "the text size is out of order" ?
I try to reproduce using MDN example of `dominant-baseline`: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline

Slide:
```html

# SVG

<svg viewBox="0 0 200 120" width="500">
  <path d="M20,20 L180,20 M20,50 L180,50 M20,80 L180,80" stroke="grey" />
  <text dominant-baseline="auto" x="30" y="20">Auto</text>
  <text dominant-baseline="middle" x="30" y="50">Middle</text>
  <text dominant-baseline="hanging" x="30" y="80">Hanging</text>
</svg>
```

Result:
![svg](https://user-images.githubusercontent.com/5246045/224651276-d64c4083-f235-4516-8038-ff8f49e47900.png)

Can you share a screenshot of what's wrong ?

**Comment by AnnyTerfect** [comment]
@tonai  I apologize for not being clear in my previous message. Here are the screenshots that illustrate the issue:

1. In the first screenshot, you can see that when I visit http://localhost:3030/2 directly, the text size is disorderly much larger than normal.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/22359580/224652754-c7418ebf-e711-4e41-9c13-2a476dff2b20.png">
2. In the second screenshot, I switched from the first page and then went back, and the text size returned to normal.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/22359580/224653111-31a4f20b-ad48-49de-9dfb-ddcecb6968fd.png">

The code I used is as follows:
```
---

# Cover

---

# Page

<svg style="background: black">
        <text dominant-baseline="hanging" fill="white">Text</text>
</svg>
```

I hope that helps clarify the issue.

**Comment by tonai** [comment]
Ok, I didn't understand the problem because I am not able to reproduce it in fact.
The font size is always correct whether I refresh or change the page.
I am on Ubuntu 22.04 with Chrome 109.
