### ISSUE TITLE
run slidev export get a blank white pdf.

### ISSUE THREAD

**Issue by ramwin** [slidevjs/slidev#912]
**Describe the bug**
I'm using 
```
[#15#wangx@windows:ppt] $ node -v
v16.15.1
[#16#wangx@windows:ppt] $ npm -v
n8.11.0
[#17#wangx@windows:ppt] $ npm list @slidev/cli
ppt@ /mnt/s/github/html-reference/ppt
└── @slidev/cli@0.40.3
```

I init the slidev and try to export it as pdf. After exporting, the pdf file only contains one blank page.

**To Reproduce**
1. `npm init slidev@latest`
2. `cd slidev@latest`
3. slidev export
4. open `slides-export.pdf`

**Desktop (please complete the following information):**
 - OS: WSL on windows
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
 - Browser:  111.0.5563.64
 - Slidev version: 0.40.3

**Comment by tonai** [comment]
It seems related to WSL because I can't reproduce on Ubuntu 22.04 (tested with slidev 0.40.3 and 0.40.5)
