### ISSUE TITLE
请问slidev有计划支持导出双击直接打开的html格式吗

### ISSUE THREAD

**Issue by Alex-coder251** [slidevjs/slidev#916]
导出pdf后没有动画效果了，导出spa需要部署到网上才能用不够便携。

请问大佬有计划支持导出可以双击直接打开的html之类的便携形式吗？

大佬们辛苦了，感谢你们的贡献

**Comment by antfu** [comment]
没有，Vite 本身也不支持，也许一些插件可以做到但这 out-of-scope of Slidev
