### ISSUE TITLE
locally installed themes + globally installed slidev

### ISSUE THREAD

**Issue by dlleigh** [slidevjs/slidev#918]
**Is your feature request related to a problem? Please describe.**
It appears that if slidev is installed globally, then (based on my interpretation of [this code](https://github.com/slidevjs/slidev/blob/734665a604934e7f4cde0c20fdf17ed882199a59/packages/slidev/node/utils.ts#L23)) it only looks for themes that are installed globally.

**Describe the solution you'd like**
slidev should look for locally installed themes as well as globally installed themes.  Locally installed themes should take precedence if there are naming conflicts.

I'm happy to try creating a PR for this.

**Comment by dlleigh** [comment]
I should have added some context:  The use case I'm after is to run slidev in a docker image, however I do not want to install the theme in the image, nor do I want the container to download the theme at runtime.

**Comment by tonai** [comment]
PR is welcome.
To solve your docker image problem you can maybe try to install slidev locally

**Comment by dlleigh** [comment]
> I mean you can for example use a package.json in the docker image that will install slidev + themes...etc.

There's a couple issues I am trying to avoid by not installing the theme in the image:

1. The theme is in our instance of GitHub Enterprise and referenced using a git repo url in package.json.  Installing the theme requires an SSH key which makes it problematic to do in the image or in the container.
1. The theme is rapidly evolving and we typically "pin" the commit hash of the theme in package.json to avoid backward compatibility issues with older presentations created with the theme. Ideally, the docker image would be reusable independent of the theme version.

Your suggestion made me realize that it might be possible to install slidev locally in the image and mount only the theme directory into node_modules on the container.  I managed to get that working, and I'll describe the method here in case anyone is interested:

In the presentation repo, the only dependency is the theme:

package.json:
```
{
  "dependencies": {
    "my-slidev-theme": "<my_git_repo_url>"
  }
}
```
Dockerfile:
```
FROM node:19
RUN npx playwright install-deps 
WORKDIR /slidev
RUN npm init -y
RUN npm install @slidev/cli @slidev/theme-default
RUN npm install playwright-chromium
```
Makefile:
```
current_dir = $(shell pwd)

docker-build:
	docker build -t docker-slidev .

docker-presentation:
	docker run \
		--rm \
		-it \
		-p 3030:3030 \
		--mount type=bind,src=${current_dir},dst=/slidev \
		--mount type=volume,dst=/slidev/node_modules \
		--mount type=bind,src=${current_dir}/node_modules/my_slidev_theme/,dst=/slidev/node_modules/my_slidev_theme \
		docker-slidev make presentation 

docker-export-slides: 
	docker run \
		--rm \
		--mount type=bind,src=${current_dir},dst=/slidev \
		--mount type=volume,dst=/slidev/node_modules \
		--mount type=bind,src=${current_dir}/node_modules/my_slidev_theme/,dst=/slidev/node_modules/my_slidev_theme \
		docker-slidev make export-slides

presentation:
	npm exec -c 'slidev slides.md --remote'

export-slides: 
	npm exec -c 'slidev export slides.md'
```
The tricky bit is the 3 mounts in the `docker run` command which (in sequence):
1. Makes the current directory available in the container
2. Uses `node_modules` from the image (ignoring `node modules` in the current directory)
3. Adds the theme module from the current directory into the `node_modules` on the container.

Thanks for inspiring this solution to my problem!  I think we can close this issue.
