### ISSUE TITLE
Error when doing a `slidev build`

### ISSUE THREAD

**Issue by notthetup** [slidevjs/slidev#921]
**Describe the bug**
When using `@slidev/cli` to do a build, an `Error [RollupError]: Could not resolve entry module` is seen and the slides don't get built.

**To Reproduce**

- Install slidev cli globally using `npm i -g @slidev/cli`
- Download example slides from https://github.com/slidevjs/themes/blob/main/packages/theme-default/example.md and rename as `slides.md`
- Remove the  line 2 : `theme: ./`
- On the cli in the directory with this `slides.md` file, run `slidev build`
- Note the error `Error [RollupError]: Could not resolve entry module`

```
❯ head slides.md
---
layout: cover
background: https://images.unsplash.com/photo-1502189562704-87e622a34c85?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2100&q=80
---

# Presentation title

Presentation subtitle

---
[9:28] ❯ slidev build


  ●■▲
  Slidev  v0.40.5 (global)

  theme   @slidev/theme-default
  entry   /Users/chinmay/Desktop/test/slides.md


vite v4.2.1 building for production...
✓ 0 modules transformed.
✓ built in 44ms
Could not resolve entry module "../../.nvm/versions/node/v16.17.0/lib/node_modules/@slidev/cli/index.html".
Error [RollupError]: Could not resolve entry module "../../.nvm/versions/node/v16.17.0/lib/node_modules/@slidev/cli/index.html".
    at error (file:///Users/chinmay/.nvm/versions/node/v16.17.0/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at ModuleLoader.loadEntryModule (file:///Users/chinmay/.nvm/versions/node/v16.17.0/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:23797:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
```

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser: Chrome 111.0.5563.64
 - Slidev version: 0.40.5
 - Nodejs version : v16.17.0

**Comment by NeumoNeumo** [comment]
I have the same issue. It seems that it is caused by *global installation*. A workaround is installing it locally and run `slidev build` under the directory.

**Comment by CarsonSlovoka** [comment]
I have the same issue. global installation and then `slidev build` doesn't work.
