### ISSUE TITLE
Automatically resize / arrange text overflow

### ISSUE THREAD

**Issue by axiomtutor** [slidevjs/slidev#923]
**Is your feature request related to a problem? Please describe.**
I intend to use slidev to make lecture notes, and therefore I will have a lot of text.  Sometimes that text overflows the slide's boundaries.  Because I often refer to earlier parts of what I was talking about, I can't always just move to a next slide -- I need it all to fit on a single screen.  So then I have to manually adjust the sizing and arrangement of the text.

**Describe the solution you'd like**
I would love a feature where the current text that I'm speaking about is large, and at the bottom of the slide.  Then as I click "next" it would shrink that text, move that text to the upper-left corner, and a new block of large text would appear at the bottom.  When I click "next" it shrinks the new large text, which then goes below the text that's already stored in the upper-left.  And so on.  

**Describe alternatives you've considered**
Manually adjusting all the sizes and locations with transformations -- but this takes a lot of time fidgeting.  I don't know how to work with the backend well enough to write a script that would make this automatic.

**Comment by antfu** [comment]
FYI, I wrote an experimental component a while ago that you can try: 
https://github.com/slidevjs/slidev/blob/main/packages/client/builtin/AutoFitText.vue

I think solving this perfectly is quite tricky, maybe deserve to be a standalone lib.
