### ISSUE TITLE
v-click regression

### ISSUE THREAD

**Issue by tonai** [slidevjs/slidev#924]
**Describe the bug**
If multiple items are wrapped inside a `<v-click>`, only the first one will be hidden.

**To Reproduce**
Add inside a slide somthing like:
```md
<v-click>

Paragraph 1

Paragraph 2

</v-click>
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome 111.0.5563.64
 - Slidev version: 0.40.5

**Comment by antfu** [comment]
Do you want to revert the last PR and do a hotfix before figuring out a better solution, or?
