### ISSUE TITLE
Chemical equation

### ISSUE THREAD

**Issue by ganfeng1964** [slidevjs/slidev#928]
Who can tell me how to type chemical equations.

**Comment by twitwi** [comment]
slidev uses katex and it seems to have an extension for chemical equations

- https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem
- https://mhchem.github.io/MathJax-mhchem/

I'm not sure how difficult it is to install/use but that seems a good candidate.

**Comment by ganfeng1964** [comment]
Dear Emonet


Thank you very much for your email. I know KaTeX can render chemical equation in markdown. But I don’t know why it does not work in SliDev. SliDev is a very good tool for slide and I hope to use it in my class of chemistry.


Feng


| |
甘峰
|
|
***@***.***
|


---- Replied Message ----
| From | Rémi ***@***.***> |
| Date | 04/3/2023 02:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [slidevjs/slidev] Chemical equation (Issue #928) |

slidev uses katex and it seems to have an extension for chemical equations

https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem
https://mhchem.github.io/MathJax-mhchem/

I'm not sure how difficult it is to install/use but that seems a good candidate.

**Comment by bru02** [comment]
you can create a `katex.ts` file in the project root with the following content:

```js
import 'katex/contrib/mhchem'

export default {}
```

you could also use `vite.config.ts`, but the important part is to import `katex/contrib/mhchem` before markdown parsing begins.
