### ISSUE TITLE
Failure on running the "getting started" instructions

### ISSUE THREAD

**Issue by jamesmortensen** [slidevjs/slidev#930]
**Describe the bug**

When running `npm init slidev` I get this error message in both Node.js 16 and Node.js 18 on macOS M2 13.2.1

```
$ npm init slidev
sh: create-slidev: command not found
npm ERR! code 127
npm ERR! path /Users/james/proj/slidev
npm ERR! command failed
npm ERR! command sh -c -- create-slidev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2023-03-30T05_51_36_455Z-debug-0.log
```

**To Reproduce**
1.  Run `npm init slidev
2.  Observe the failure to install

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 M2
 - Browser:  N/A
 - Slidev version:  latest

**Comment by antfu** [comment]
I am not able to reproduce it:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/11247099/228793184-5964003d-c38f-45a4-a0c8-5c5d384659e2.png">
