### ISSUE TITLE
Integrate a charting library like plotly or echarts.

### ISSUE THREAD

**Issue by rafo** [slidevjs/slidev#931]
**Is your feature request related to a problem? Please describe.**
I almost always need the possibility to display diagrams.

**Describe the solution you'd like**
Instead of importing an image from Exel, it would be much better to use plotly or the echarts for this like https://sli.dev/custom/config-mermaid.html. This would also have the advantage that you can format the chart via the stylesheet. Just like with Mermaid.

**Comment by twitwi** [comment]
I've been making first experiments with Vega recently. I'm attaching a simple component I used.

[Vega.vue.txt](https://github.com/slidevjs/slidev/files/11133023/Vega.vue.txt)

I then use it in `slides.md` to load and plot a file from the public folder:

```vue
<Vega :spec='{
  width: 355,
  height: 150,
  data: {url: "/data.csv"},
  ... all vega code
  title: "...",
}
'/>
```

**Comment by rafo** [comment]
Thanx for your solution. I will try it.
