### ISSUE TITLE
Custom grid columns with Arbitrary Values

### ISSUE THREAD

**Issue by matttrice** [slidevjs/slidev#938]
Specifying column widths with [Arbitrary Values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values) such as this 3 column example of `grid-cols-[200px,1fr,10%]`  from the the Slidev [FAQ](https://sli.dev/guide/faq.html#grids) doesn't set `grid-template-columns` as expected.  I only see `display: grid` in chrome dev-tools and no columns. 

**To Reproduce**
1. Copy the second grid example from [slidev faq](https://sli.dev/guide/faq.html#grids)
2.  Install to slidev and run
3. Observe grid columns are not horizontal and no width applied.

OR

1. Clone my barebones example: https://github.com/matttrice/grid-cols-nt
2.  Install and run
3. Observe slide 1 is not a grid 

I also tried adding a custom windi configuration via https://sli.dev/custom/config-windicss.html
and then extending the theme with `gridTemplateColumns` using the same pattern but still couldn't get custom grid widths. 
 
**Desktop**
 - OS: Apple M2 Max
 - Browser: Chrome Version 111.0.5563.14
 - Slidev version: 0.40.6

**Comment by matttrice** [comment]
I see, using underscores instead of commas works: `grid-cols-[200px_1fr_10%]`
Maybe [windicss test](https://github.com/windicss/windicss/blob/cf3067b9272704adab30d568bdaa5f64bd44b7b5/test/processor/interpret.test.ts#L81) needs a look but I haven't dug in yet. 

I'll add a pr to the docs section for this.
https://sli.dev/guide/faq.html#grids

Thanks!

**Comment by misogihagi** [comment]
This  issue seems to be caused by uno css.
I was stuck because I assumed that slidev was using wind css
