### ISSUE TITLE
[Integration] Plugin for Visual Studio Code 

### ISSUE THREAD

**Issue by Alesnim** [slidevjs/slidev#94]
**[Integration]** Plugin for Visual Studio Code with live preview.
There is a similar plugin for Marp with a preview right inside Visual Studio Code and command integration.
[Marp for VS Code](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode)

**Comment by nico-bachner** [comment]
Are you perhaps looking for this: https://marketplace.visualstudio.com/items?itemName=antfu.slidev?

Source code here: https://github.com/slidevjs/slidev-vscode

**Comment by antfu** [comment]
For live preview, you can try https://github.com/antfu/vscode-browse-lite
