### ISSUE TITLE
Iframe don't connect on every website

### ISSUE THREAD

**Issue by gabriel-del** [slidevjs/slidev#945]
Iframe layout don't work on every websites

**To Reproduce**
1. On slides.md add the content:
```
---
layout: iframe-right
url: https://wiki.gentoo.org/wiki/Main_Page
---

# Wiki 

## Gentoo

[https://wiki.gentoo.org/wiki/Main_Page](https://wiki.gentoo.org/wiki/Main_Page "Gentoo Wiki")
```
2. See the error on browser: wiki.gentoo.org refused to connect.

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave 
 - Slidev version: 0.40.6

**Comment by antfu** [comment]
It's the website's policy to disallow being inside of an iframe, I think there is, unfortunately, nothing we can do about it.
