### ISSUE TITLE
feat: allow to export presenter notes in text format

### ISSUE THREAD

**Issue by mitsuo0114** [slidevjs/slidev#953]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/slidevjs/slidev/issues/718
but I want to have text format of presenters notes.

**Describe the solution you'd like**
I want to use the presenters note for input of Text-to-Speech API.
That enable me to build movie file from voice + slides.

For the API integration, current PDF format is not easy to parse. so I want to have text data from each slides.
Any machine readable text format is good (raw text / json / xml / yaml etc)  as long as we can find slide number to build movie later

**Describe alternatives you've considered**
I have considered to extract data from PDF or .md file directly but it is little bit hard to develop by myself.

**Comment by ekohilas** [comment]
I am also interested in this feature!
For me, this would be to capture a diff to verify whether notes were updated on changes.

Would the owners be against this?
