### ISSUE TITLE
question about windicss sunsetting

### ISSUE THREAD

**Issue by fjun99** [slidevjs/slidev#957]
Windicss is sunsetting. 

Which css framework will slidev choose to use?

Thanks.

**Comment by huyhoang160593** [comment]
There is already [unocss](https://unocss.dev/) preconfigured as it was mentioned [here](https://sli.dev/custom/config-vite.html). You can check this out and figuring out what you want to do with it

**Comment by fjun99** [comment]
> There is already [unocss](https://unocss.dev/) preconfigured as it was mentioned [here](https://sli.dev/custom/config-vite.html). You can check this out and figuring out what you want to do with it

thanks a lot.

**Comment by devxan** [comment]
But will sli.dev use UnoCSS by default in the future?

**Comment by antfu** [comment]
UnoCSS is already a "soft" default in the starter template for a long while. In the next minor, we will flip the default to UnoCSS, while the windicss mode will still be supported.

**Comment by antfu** [comment]
```md
---
css: unocss
---
```

This, btw, if you didn't have it enabled
