### ISSUE TITLE
"resolvePackageData" is not supported in CJS build of Vite 3. Please use ESM or dynamic imports `const { resolvePackageData } = await import('vite')`.

### ISSUE THREAD

**Issue by a1ooha** [slidevjs/slidev#959]
**Describe the bug**
import react in monaco, it's broken.

**To Reproduce**

```
//```ts {monaco}
import { useRef } from 'react'

interface User {
  id: number
  firstName: string
  lastName: string
  role: string
}

function updateUser(id: number, update: User) {
  const user = getUser(id)
  const newUser = { ...user, ...update }
  saveUser(id, newUser)
}
//```
```

https://stackblitz.com/edit/slidev-e2drac?file=slides.md

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Slidev version: latest

**Comment by antfu** [comment]
PR welcome :)

**Comment by a1ooha** [comment]
> PR welcome :)

The demo of https://sli.dev/custom/config-monaco.html#types-auto-installing also broken.

```
//```ts {monaco}
import { ref } from 'vue'
import { useMouse } from '@vueuse/core'

const counter = ref(0)
//```
```

https://stackblitz.com/edit/slidev-ntdqy8?file=slides.md
