### ISSUE TITLE
[Feature] Grid layout support

### ISSUE THREAD

**Issue by ycjcl868** [slidevjs/slidev#96]
```md
---
title: Hello
layout: grid
gap: 4
---

<section>

# One

</section>


<section>

# Two

</section>

<section>

# Three

</section>
```

I found `layouts/*.vue` couldn't support multiple slots, so how to implement it?

**Comment by Ahacad** [comment]
Maybe you could use `grid` in tailwindcss (windicss)?  Check `packages/create-app/template/slides.md` the `Component` section for example, and refer to [tailwindcss doc](https://tailwindcss.com/docs).

```
# Components

<div grid="~ cols-2 gap-4">
<div>

You can use Vue components directly inside your slides.

We have provided a few built-in components like `<Tweet/>` and `<Youtube/>` that you can use directly use. And add your custom components are also super easy.

```html
<Counter :count="10" />
```


<Counter :count="10" m="t-4" />

Check out [the guides](https://sli.dev/custom/#components) for more.

</div>
<div>

```html
<Tweet id="1390115482657726468" />
```

<Tweet id="1390115482657726468" scale="0.65" />

</div>
</div>
```

**Comment by antfu** [comment]
We already provided the flexible gird system powered by windicss, as @Ahacad mentioned. And custom layout can be easily created on the user side or with in the theme. Currently, we do not have the plan to include a built-in grid layout (as can't cover any cases you want anyway, but you can with HTML+CSS). Thanks for bringing this up, close now.

**Comment by ycjcl868** [comment]
If I'm not a front-end developer, I'd like to use `layout: grid` rather than `<div grid="~ cols-2 gap-4">`.

**Comment by Ahacad** [comment]
That's a valid point. If I were not a frontend developer I would also think `layout: grid` is more intuitive. But we always need some syntax to denote the different parts in the grid, so it's actually only about putting the `grid` properties in the front matter or inside the page body. 

For now, I think the current practices are good enough, maybe this feature can be added later.

P.S. You could also use tailwindcss syntax, i.e. `<div class="grid grid-cols-3 gap-4">`.

**Comment by ycjcl868** [comment]
> That's a valid point. If I were not a frontend developer I would also think `layout: grid` is more intuitive. But we always need some syntax to denote the different parts in the grid, so it's actually only about putting the `grid` properties in the front matter or inside the page body.
> 
> For now, I think the current practices are good enough, maybe this feature can be added later.
> 
> P.S. You could also use tailwindcss syntax, i.e. `<div class="grid grid-cols-3 gap-4">`, ref [tailwindcss Grid Template Columns](https://tailwindcss.com/docs/grid-template-columns)

Right, slidev should make developers focused on **content** not `<div>` html tags,  the reality is that I wrote to much `html` tags, now writing a slide is like writing a html project.
