### ISSUE TITLE
How can I load extra Google fonts?

### ISSUE THREAD

**Issue by tdd** [slidevjs/slidev#972]
Hi all! Thanks for Slidev, it's awesome! 👏 

I wish to use a custom font for my `<strong>` tags, using a font loaded from Google.  This falls outside the `fonts` setup, which is only about Sans/Serif/Mono.

All it would take is adding the relevant `<link/>` element in the `<head>`, but nowhere in Slidev do I see any way of augmenting that element of the page. Short of JS injection that link in the page dynamically, is there a "clean" way of doing it?

Thanks!

**Comment by bru02** [comment]
you can do it like so:
```md
---
fonts:
  custom: Libre Barcode 39
---

# Welcome to Slidev

<strong>barcode</strong>


<style>
strong {
  font-family: 'Libre Barcode 39'
}
</style>
