### ISSUE TITLE
Disable default last page

### ISSUE THREAD

**Issue by HenriqueAurelio** [slidevjs/slidev#974]
**Is your feature request related to a problem? Please describe.**
I'm trying to build an slide for apresentation but I'm not able to avoid the default end page.

**Describe the solution you'd like**
Is there a config to disable the default template or disable the last page?

**Describe alternatives you've considered**
Trying to use layout:end and build my last slide into it.

**Comment by rightaway** [comment]
I also would like a setting to disable the end page. I already have created my own which is better than a blank slide with END.

@antfu Is there a workaround to remove it?
