### ISSUE TITLE
SlideCurrentNo not exported correctly as PDF when in global-bottom.vue

### ISSUE THREAD

**Issue by eric-burel** [slidevjs/slidev#976]
**Describe the bug**
Exporting slides as PDF using `global-bottom.vue` with `SlideCurrentNo` will render incorrectly:
![image](https://user-images.githubusercontent.com/7983005/234356629-3591367d-dd2b-4cdd-85cc-3ea7fed9284b.png)

Maybe all the page numbers are rendered together? This issue doesn't happen during development.

**To Reproduce**
1. Create `global-bottom.vue`
```
<!-- global-bottom.vue -->
<style>
#pageno {
  position: fixed;
  bottom: 4px;
  right: 8px;
}
</style>
<template>
  <div id="pageno">
    <SlideCurrentNo />
  </div>
</template>
```
2.  `slidev export ./your-slides.md`
**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser: Not relevant
 - Slidev version: v0.40.14

**Comment by bru02** [comment]
use `position: absolute;` instead of `fixed`

or export using the `per-slide` option:
```sh
slidev export --per-slide ./your-slides.md
```

**Comment by eric-burel** [comment]
Closing as position absolute works fine

**Comment by MuTsunTsai** [comment]
I was having the same issue; in my case I need `--per-slide` option to make it work.
