### ISSUE TITLE
How to view the presentation?

### ISSUE THREAD

**Issue by philippludwig** [slidevjs/slidev#98]
So I followed the [guide](https://sli.dev/guide/install.html?) and ran `npm init slidev`. npm asks a bunch of questions and creates a package.json file.

And then what? How do I view a presentation?

**Comment by philippludwig** [comment]
So I tried the steps from "Install Manually" and I get:
```
$ npx slidev
Cannot find module 'worker_threads'
```

**Comment by Ahacad** [comment]
If you use `npm init slidev` and successfully installed the dependencies by default the browser should pop out the webpage at `http://localhost:3030/1`, if not you may try `npm run dev` (refer to `package.json` `scripts` section) and open the page manually.

Regarding the `worker_threads`, you may want to check that your `NodeJS` version is v11+, try to update it to a LTS version like 12, 14 or 16. For your reference this is another discussion thread about [this similar problem](https://github.com/microsoft/pyright/issues/769)

This is actually a more general frontend question related to npm, check out its documentation for information.
