### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by erlebach** [slidevjs/slidev#980]
Has anybody linked D3.js into slidev?

**Comment by CarsonSlovoka** [comment]
Hi @erlebach, You can create a component and then write the d3 syntax you want. Here's an example using [markMap](https://markmap.js.org/) (which requires the use of d3.js)

https://gist.github.com/CarsonSlovoka/34478f75a9f0a27b06d7cf92d6427ade#file-markmap-vue-L185
