### ISSUE TITLE
Creating an umlaut

### ISSUE THREAD

**Issue by erlebach** [slidevjs/slidev#981]
An umlaut is usually created in latex as: \"{o}, which will put two dot over the letter `o`. This does not work in `slidev`. What are the features of latex that are known not to work in `slidev`? I find no information on diacritic marks using Slidev. Given the generality of the package, this is hard to understand. More generally, how does one write in unicode? For example, since there is documentation in Chinese, I assume that one can write in Chinese? How is that done? Thanks.

**Comment by twitwi** [comment]
If you can type it with you keyboard or copy it somewhere, just using the unicode character in the source file should work, both in normal and math mode,

.e.g. `öβ𓆉 and $öβ𓆉$` 
gives ![image](https://github.com/slidevjs/slidev/assets/244649/2de6c383-848a-4ae6-8423-b4b0e019bcad)

you can copy from wikipedia or from https://copychar.cc/letters/ for example.
