### ISSUE TITLE
Mermaid within slide

### ISSUE THREAD

**Issue by erlebach** [slidevjs/slidev#982]
I started to use slides and was testing Mermaid. The `scale` parameter does not work. Many other people have reported this. So far, I have not seen a single example that demonstrates using Mermaid with a scaling factor that functions correctly. I am using the Chrome Browser. 

Could somebody please post an example of a pie chart created within slides with the triple backquotes, and demonstrate scaling of 20%, 100%, and 200%? I have investigated css files, html, and other measures, all unsuccessfully. Any help would be appreciated. I really don't know why this has not been reported given that Mermaid has been integrated into `slides`. This could be deal breaker for me. Thanks.  Gordon.

**Comment by kraegpoeth** [comment]
+1
