### ISSUE TITLE
Merge public directory from themes

### ISSUE THREAD

**Issue by oripka** [slidevjs/slidev#983]
**Is your feature request related to a problem? Please describe.**

I want to provide some assets (images and videos) in a theme within the `public` directory and share them between slide decks.

**Describe the solution you'd like**

Currently the public directory seems not to be merged into the slide deck

**Describe alternatives you've considered**

Copy static assets into each slide deck.

**Comment by antfu** [comment]
I think we already supported in the recent version, or can you provide a minimal reproduction? Thanks.

**Comment by oripka** [comment]
Ok, sorry for opening the issue. I just looked at the source and found that the static assets get copied to the `theme` folder in the `public` directory. So to reference an asset of the them `slidev-theme-mine/public/example.jpg`, on needs to reference via `/theme/example.jpg`.
