### ISSUE TITLE
Windi CSS sunsetting/deprecated 

### ISSUE THREAD

**Issue by Markvandersteen** [slidevjs/slidev#989]
**Is your feature request related to a problem? Please describe.**

Not a problem yet but WindiCSS is going to get deprecated sooner than later. 
They call it sunsetting but they are already encouraging people to look for alternatives.  

https://windicss.org/posts/sunsetting.html

**Describe the solution you'd like**

Tailwind would probably be the most obvious solution since it's so close in its implementation.

**Describe alternatives you've considered**

UnoCSS, seems also very close in it's implementation, maybe even closer.

**Comment by antfu** [comment]
https://github.com/slidevjs/slidev/issues/957#issuecomment-1519123619
