### ISSUE TITLE
Double brackets cannot be displayed correctly

### ISSUE THREAD

**Issue by Ahacad** [slidevjs/slidev#99]
Ref: #95 

This actually cannot be easily fixed by `\{`, the backslash will be displayed, see the picture below, I wrote the lines in markdown.

```
function updateUser(id: number, update: Partial<User>) {
  const user = getUser(id)
  const newUser = {...user, ...update}  
  saveUser(id, newUser)
}
{{}}
```

![20210513-19:48:06](https://user-images.githubusercontent.com/51874356/118121746-7f26be80-b424-11eb-89e5-0fd04824d745.png)

https://github.com/slidevjs/slidev/blob/103da55c4e7382d76a72b5d2a368525e9538f0ab/packages/slidev/node/plugins/markdown.ts#L143

Seems that character references are still needed, i.e. `&lbrace; &rbrace;` for &lbrace; and &rbrace;.

**Comment by antfu** [comment]
> `&lbrace; &rbrace;`

Ah, i was looking for this! Thanks, mind create a PR for it? Thanks
