### ISSUE TITLE
Alternative syntax for presenters notes

### ISSUE THREAD

**Issue by marshallfWCCI** [slidevjs/slidev#991]
I'd like the option for presenter notes to be visible outside of slidev, e.g. when GitHub does its default presentation of `.md` files. But HTML comments are hidden by GitHub.

This could be accomplished by creating a new type of code block, perhaps ````presenter`, which would understood by slidev as a presenter note, but which GitHub would simply treat as a code block.

That way, my entire presentation (including notes) could be reviewed on GitHub without any additional work.

I'd be happy to code this if this proposal is considered acceptable.

**Comment by antfu** [comment]
I think we provide enough configuration/api (or even vite plugin) to allow you to extend the syntax with a custom transformation. I would like to align with the Markdown spec more and have HTML "just work", and also avoid introducing too many different ways of doing one thing. Thanks for bringing this up but I think it's better to provide as a custom integration or so.

**Comment by antfu** [comment]
Because I consider notes are less likely "codeblocks". Backquote (it's not a new syntax) is a better fit for me as you can even embed code snippets inside 

> **Notes**
> Here is the code
> ```js
> const a = 1 + 1
> ```
> And some text

**Comment by marshallfWCCI** [comment]
I just realized that this feature isn't needed at all...

```
<RenderWhen context="presenter">
```

suffices.

**Comment by marshallfWCCI** [comment]
For my purposes, yes.  Thanks!
