### ISSUE TITLE
"resolvePackageData" is not supported in CJS build of Vite 4.

### ISSUE THREAD

**Issue by mrLuisFer** [slidevjs/slidev#999]
**Describe the bug**
I started a new project, made some basic changes to learn more about slidevjs, but when I cancel the server and start it again, this error appears

![Captura de pantalla 2023-05-15 a la(s) 13 00 22](https://github.com/slidevjs/slidev/assets/65029792/9ee69dce-abfc-44ac-81af-3164ce66a77b)

I did the same with a project from scratch, without changing any configuration or content and the same error appears

**To Reproduce**
1. init a project with `npm init slidev`
2. select **npm** for run the project
3. down the server and run it again
4. see the error

**Desktop (please complete the following information):**
 - OS: MacOs 13.3.1 (Ventura)
 - Browser: Chrome 113
 - Slidev version: `^0.40.16`
 - Node version: `v18.16.0`

**Comment by AriPerkkio** [comment]
This is fixed in `main` and will be included in the next release. https://github.com/slidevjs/slidev/pull/984
